### ISSUE TITLE
{Enhancement} Support for more IP Camera features

### ISSUE THREAD

**Issue by felixekman** [KhaosT/homebridge-camera-ffmpeg#1]
Support for more IP Camera features such as:

Pan & Tilt Control - Current & Target Angle
Night Vision Toggle - On/Off (Possible HTML request call)
Optical & Digital Zoom

**Comment by KhaosT** [comment]
Those features (except digital zoom) are highly hardware dependent. Different IP camera may offer different APIs to do those. As a general purpose FFMPEG based plugin, I'm trying to avoid adding features that only works on specific hardware.

You're welcomed to fork and publish new plugins that supports specific IP Camera ^^

**Comment by felixekman** [comment]
Very reasonable choice, is there support in HAP-NodeJS for the features, calls to build upon?

**Comment by KhaosT** [comment]
HomeKit defines those as characteristics under CameraControl service. Please check HomeKitTypes under HAP-NodeJS for more details.

**Comment by KhaosT** [comment]
PS: If the camera you are trying to support can do direct RTP video streaming (rtsp probably), you should try to have the camera stream directly to iOS device instead of going through ffmpeg.

**Comment by felixekman** [comment]
I'm trying to have this work: https://github.com/fritz-smh/yi-hack
But sadly my skills are lacking to write a plugin

**Comment by basvdploeg** [comment]
@KhaosT So it should be possible to directly stream my rtsp camera to iOS without ffmpeg? How can I try this?

**Comment by KhaosT** [comment]
@basvdploeg there is no direct support for this... It's possible to developer a plugin that negotiates the stream and forward it directly to iOS device but right now there isn't a general purpose one doing this.
