### ISSUE TITLE
only first image is shown, using v4l2rtspserver and a pi camera

### ISSUE THREAD

**Issue by kevinfoerster** [KhaosT/homebridge-camera-ffmpeg#10]
hi,

i see the stream "working" as the camera displays the first image (including a counter when this was taken) but no video.

![fullsizeoutput_2e06](https://cloud.githubusercontent.com/assets/163305/19037367/2771ad86-8976-11e6-96ce-7331cea93b50.jpeg)

i run homebridge on a pi, my ffmpeg version ist:
`
ffmpeg version 0.8.17-6:0.8.17-2+rpi1+deb7u2, Copyright (c) 2000-2014 the Libav developers
  built on Jun 18 2016 00:05:51 with gcc 4.6.3
`

a secondary pi is providing the stream using [v4l2rtspserver](https://github.com/mpromonet/v4l2rtspserver) which works in vlc, except some grey picture at the beginning of the stream.

i run `v4l2rtspserver -F 30 -W 640 -H 480 -c /dev/video0` and my homebridge config basically looks like the example provided:

`
{
        "platform": "Camera-ffmpeg",
          "cameras": [
    {
      "name": "Basement Cam",
      "videoConfig": {
        "source": "-re -i rtsp://192.168.178.47:8554/unicast",
        "maxStreams": 2,
        "maxWidth": 640,
        "maxHeight": 480,
        "maxFPS": 30
      }
    }
`

any idea how to get to video output working? is it a problem with my ffmpeg version? 

do you have any other recommendations to stream video from /dev/video0 device using v4l2 drivers on a pi?

**Comment by cmh716** [comment]
I have the same issue with a completely different setup.  I'm using a full blown PC (ubuntu) and a vivotek network camera.  First (stil) image is shown but streaming does not work.

**Comment by kevinfoerster** [comment]
similar issue when running homebridge on a mac with the [homebridge-camera-isight](https://github.com/KhaosT/homebridge-camera-isight) plugin, it shows a single image (reloads from time to time) but the stream does not work…

**Comment by KhaosT** [comment]
In these cases, I'd suggest you try to run ffmpeg separately ``ffmpeg your_source -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 300k -bufsize 300k -f rtp rtp://127.0.0.1:51293`` and see if ffmpeg was able to output anything

**Comment by cmh716** [comment]
I don't want to hijack Kevin's post but I just tried it and it seems to be working when issuing ffmpeg manually but I don't see ffmpeg launch at all for streaming when using the homebridge-camera-ffmpeg

ffmpeg -re -i rtsp://192.168.0.35:554/live.sdp -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1600:1200 -b:v 300k -bufsize 300k -f rtp rtp://127.0.0.1:51293


ffmpeg version 2.8.6-1ubuntu2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.1 (Ubuntu 5.3.1-11ubuntu1) 20160311
  configuration: --prefix=/usr --extra-version=1ubuntu2 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Guessed Channel Layout for  Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://192.168.0.35:554/live.sdp':
  Metadata:
    title           : RTSP server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mpeg4 (Simple Profile), yuv420p, 1600x1200 [SAR 1:1 DAR 4:3], 30 fps, 30 tbr, 30k tbn, 30 tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
[libx264 @ 0x1b0cd40] VBV maxrate unspecified, assuming CBR
[libx264 @ 0x1b0cd40] using SAR=1/1
[libx264 @ 0x1b0cd40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0x1b0cd40] profile High, level 4.0
Output #0, rtp, to 'rtp://127.0.0.1:51293':
  Metadata:
    title           : RTSP server
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 (libx264), yuv420p, 1600x1200 [SAR 1:1 DAR 4:3], q=-1--1, 300 kb/s, 30 fps, 90k tbn, 30 tbc
    Metadata:
      encoder         : Lavc56.60.100 libx264
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (libx264))
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=RTSP server
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 56.40.101
m=video 51293 RTP/AVP 96
b=AS:300
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1

Press [q] to stop, [?] for help
[NULL @ 0x197e120] RTP: missed 54 packets
[mpeg4 @ 0x19c8600] ac-tex damaged at 14 24
[mpeg4 @ 0x19c8600] Error at MB: 2438
[mpeg4 @ 0x19c8600] concealing 5135 DC, 5135 AC, 5135 MV errors in I frame
[NULL @ 0x197e120] RTP: missed 43 packetsB time=00:00:00.60 bitrate= 308.3kbits/s dup=14 drop=0    
[mpeg4 @ 0x19c8600] ac-tex damaged at 65 21
[mpeg4 @ 0x19c8600] Error at MB: 2186
[mpeg4 @ 0x19c8600] concealing 5384 DC, 5384 AC, 5384 MV errors in I frame
[NULL @ 0x197e120] RTP: missed 127 packets
[mpeg4 @ 0x19c8600] mcbpc damaged at 4 17
[mpeg4 @ 0x19c8600] Error at MB: 1721
[mpeg4 @ 0x19c8600] concealing 5848 DC, 5848 AC, 5848 MV errors in P frame
[NULL @ 0x197e120] RTP: missed 217 packets time=00:00:01.93 bitrate= 251.3kbits/s dup=51 drop=0    
[mpeg4 @ 0x19c8600] ac-tex damaged at 19 11
[mpeg4 @ 0x19c8600] Error at MB: 1130
[mpeg4 @ 0x19c8600] concealing 6430 DC, 6430 AC, 6430 MV errors in I frame
[NULL @ 0x197e120] RTP: missed 101 packets time=00:00:03.60 bitrate= 246.8kbits/s dup=98 drop=0

**Comment by kevinfoerster** [comment]
@KhaosT i just ran this on the pi running homebridge:
`
ffmpeg rtsp://192.168.178.47:8554/unicast -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 300k -bufsize 300k -f rtp rtp://127.0.0.1:51293
…
Unable to find a suitable output format for 'rtsp://192.168.178.47:8554/unicast'
`

**Comment by cmh716** [comment]
Try this:

ffmpeg -re -i rtsp://192.168.178.47:8554/unicast -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 300k -bufsize 300k -f rtp rtp://127.0.0.1:51293

I'm assuming in your config your device starts with "-re -i" ?

**Comment by kevinfoerster** [comment]
now got some response, 0 fps…

    pi@fhem-pi ~ $ ffmpeg -re -i rtsp://192.168.178.47:8554/unicast -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 300k -bufsize 300k -f rtp rtp://127.0.0
    .1:51293
    ffmpeg version 0.8.17-6:0.8.17-2+rpi1+deb7u2, Copyright (c) 2000-2014 the Libav developers
      built on Jun 18 2016 00:05:51 with gcc 4.6.3
    The ffmpeg program is only provided for script compatibility and will be removed
    in a future release. It has been deprecated in the Libav project to allow for
    incompatible command line syntax improvements in its replacement called avconv
    (see Changelog for details). Please use avconv instead.
    [h264 @ 0x1668460] Missing reference picture
    [h264 @ 0x1668460] decode_slice_header error
    [h264 @ 0x1668460] concealing 1200 DC, 1200 AC, 1200 MV errors
    [rtsp @ 0x1664660] Estimating duration from bitrate, this may be inaccurate

    Seems stream 0 codec frame rate differs from container frame rate: 180000.00 (180000/1) -> 90000.00 (180000/2)
    Input #0, rtsp, from 'rtsp://192.168.178.47:8554/unicast':
      Metadata:
        title           : LIVE555 Streaming Media v2016.09.22
        comment         : LIVE555 Streaming Media v2016.09.22
      Duration: N/A, start: 0.033256, bitrate: N/A
        Stream #0.0: Video: h264 (High), yuv420p, 640x480, 90k tbr, 90k tbn, 180k tbc
    [buffer @ 0x1666540] w:640 h:480 pixfmt:yuv420p
    [scale @ 0x1660920] w:640 h:480 fmt:yuv420p -> w:1280 h:720 fmt:yuv420p flags:0x4
    [libx264 @ 0x1669500] VBV bufsize set but maxrate unspecified, ignored
    [libx264 @ 0x1669500] lookaheadless mb-tree requires intra refresh or infinite keyint
    [libx264 @ 0x1669500] using cpu capabilities: none!
    [libx264 @ 0x1669500] profile Main, level 3.1
    Output #0, rtp, to 'rtp://127.0.0.1:51293':
      Metadata:
        title           : LIVE555 Streaming Media v2016.09.22
        comment         : LIVE555 Streaming Media v2016.09.22
        encoder         : Lavf53.21.1
        Stream #0.0: Video: libx264, yuv420p, 1280x720, q=-1--1, 90k tbn, 30 tbc
    Stream mapping:
      Stream #0.0 -> #0.0
    SDP:
    v=0
    o=- 0 0 IN IP4 127.0.0.1
    s=LIVE555 Streaming Media v2016.09.22
    c=IN IP4 127.0.0.1
    t=0 0
    a=tool:libavformat 53.21.1
    m=video 51293 RTP/AVP 96
    a=rtpmap:96 H264/90000
    a=fmtp:96 packetization-mode=1

    Press ctrl-c to stop encoding
    [h264 @ 0x1668460] Missing reference picture
    [h264 @ 0x1668460] decode_slice_header error
    [h264 @ 0x1668460] concealing 1200 DC, 1200 AC, 1200 MV errors
    frame=    5 fps=  0 q=24.0 size=      49kB time=0.17 bitrate=2402.6kbits/s

**Comment by kevinfoerster** [comment]
i changed the fps (15FPS instead of 30) of the streaming pi to 

`v4l2rtspserver -F 15 -W 640 -H 480 -c /dev/video0` 

just to make sure `Seems stream 0 codec frame rate differs from container frame rate: 180000.00 (180000/1) -> 90000.00 (180000/2)` is not a problem, but it does not change anything, still outputs 0fps in ffmpeg

**Comment by kevinfoerster** [comment]
ok, i just checked with htop, and the ffmpeg process runs at 100% cpu and therefor outputs 0fps… i will check a different machine with more power

**Comment by tmur11** [comment]
I'm having a similar issue and am running on macOS Sierra. I am able to play my streaming with replay but only get a still image on the home overview page.

**Comment by kevinfoerster** [comment]
ok, different hardware(pi3) similar issue… running the ffmpeg command now shows 2fps at 100%

otherwise my issue seems to be similar to what has been described here:
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/12

when checking htop and see if ffmpeg gets invoked, I see that ffmpeg is running for a very short time (i guess to create the still image in the overview) but is not constantly running and therefor I see a spinner and nothing happens.

**Comment by tmur11** [comment]
I am also seeing this @kevinfoerster ffmpeg runs only briefly, but not running while trying to view live stream

**Comment by Be2daErtin** [comment]
Can you please share an example of a complete config file.

Mine looks like this but my camera is not showing:

{
  "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:33",
        "port": 51828,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

  "platform" : "Camera-ffmpeg",

  "cameras": [
    {
      "name": "Camera Name",
      "videoConfig": {
        "source": "-re -i rtsp://192.168.1.20:5554/MyVideo",
        "maxStreams": 2,
        "maxWidth": 1280,
        "maxHeight": 720,
        "maxFPS": 30
      }
    }
  ],
  "accessories": [
    
  ]

}

**Comment by Be2daErtin** [comment]
I am an idiot:

Here is what I did

{
  "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:33",
        "port": 51828,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        {
            "platform" : "Camera-ffmpeg",
            "name" : "Hue",
            "cameras": [
              {
                "name": "Camera Name",
                "videoConfig": {
                  "source": "-re -i rtsp://192.168.1.20:5554/MyVideo",
                  "maxStreams": 2,
                  "maxWidth": 1280,
                  "maxHeight": 720,
                  "maxFPS": 30
                }
              }
            ]
        }
    ]

}

**Comment by Glavin001** [comment]
Hopefully this is resolved with the merge of https://github.com/KhaosT/homebridge-camera-isight/pull/12 😄

**Comment by patricks** [comment]
It looks like the latest update crashed my camera. 😄 

I saw that you changed the fps form 30 to 25. Since this update I only see the first image and now live video.

We have to figure out a way to detect which features are supported by the connected webcam.

I am using a logitech one and this one worked without any problems with the latest version (0.0.2)

**Comment by voleksiienko** [comment]
For raspberry users. Follow this small tutorial - https://www.raspberrypi.org/forums/viewtopic.php?t=125367. 
Instead of compiling the ffmpeg, install **libav-tools** and make a global alias to ffmpeg. Worked for me.

**Comment by tokamac** [comment]
@voleksiienko 
"It worked for you" Fine, how exactly? Do you now have a video streaming of your pi camera in the Home app? If so, is it watchable (i.e. over 10fps in 720p) or even smooth?
