### ISSUE TITLE
Apparently only pulling stills

### ISSUE THREAD

**Issue by DinRigtigeFar** [KhaosT/homebridge-camera-ffmpeg#100]
The livestream of my Maginon IPC-10AC camera works great in the browser, but HomeKit is only pulling the stills. I've tried adjusting the resolution to 320X240 and the FPS to 20 but to no avail.
Does anybody have any idea how to show the stream?
Config.json looks like this:
`"platform": "Camera-ffmpeg-omx",

"cameras": [{
"name": "Hjem",
"videoConfig": {
"source": "-re -i http://correctipandport.asf?user=user&pwd=pass&resolution=640X480",
"stillImageSource": "-re -i http://correctipandport/snapshot.cgi?user=user&pwd=pass",
"maxStreams": 2,
"maxWidth": 640,
"maxHeight": 480,
"maxFPS": 30
}
}]
}]
}`

When I dump the "source" into the terminal I get this:
`ffmpeg -re -i http://IPandPort.asf?user=user&pwd=pass&resolution=640X480
[1] 5099
[2] 5100

~ $ ffmpeg version N-81800-gf013ba4 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.9.2 (Raspbian 4.9.2-10)
configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-omx --enable-omx-rpi
libavutil 55. 30.100 / 55. 30.100
libavcodec 57. 58.103 / 57. 58.103
libavformat 57. 51.100 / 57. 51.100
libavdevice 57. 0.102 / 57. 0.102
libavfilter 6. 63.100 / 6. 63.100
libswscale 4. 1.100 / 4. 1.100
libswresample 2. 2.100 / 2. 2.100
libpostproc 54. 0.100 / 54. 0.100`

**Comment by distressedsk** [comment]
I've had a similar issue when trying to setup the "Fang" camera through my Mac where the still image would update every 10 seconds, but the live video would never "go live"

Today I moved the MacBook, disconnecting its ethernet connection, falling back to WiFi... Behold, live streaming... plug ethernet back in... no dice!

Props an issue with my machine, but random never the less... Hopefully this helps you?

**Comment by DinRigtigeFar** [comment]
Thanks. I'll have to try that with my Raspberry Pi.
