### ISSUE TITLE
Where does the bitrate & fps from?

### ISSUE THREAD

**Issue by iJaffa** [KhaosT/homebridge-camera-ffmpeg#101]
The _ffmpeg.json_ file has the bitrate coded to 300, but the ffmpeg command which homebridge runs is always `-b:v 299k -bufsize 299k` for me.

Even if I change the bitrate to something higher like `var bitrate = 600`, it still only outputs 299. Where is it getting the 299 bitrate from?

Similarly, when I am setting `"maxFPS": 25` in the _config.json_ file with a resolution of 720p, it's still putting `-r 30` in the ffmpeg command.

**Comment by steveatinfincia** [comment]
I've only looked at the code briefly, but it *seems* like HomeKit might actually include parameters like resolution and bitrate when it requests to start the stream, and the plugin passes them to the ffmpeg command.

If that is the case, the hardcoded bitrate found in the file would only be used if HomeKit didn't include one in the stream request. I'm not sure when (or if) that happens in practice.
