### ISSUE TITLE
Hardware FFMPEG Raspberry Pi

### ISSUE THREAD

**Issue by simonrb2000** [KhaosT/homebridge-camera-ffmpeg#104]
Has anyone got this to work? I have it all running on a raspberry pi 3. I have compiled https://github.com/legotheboss/YouTube-files/wiki/(RPi)-Compile-FFmpeg-with-the-OpenMAX-H.264-GPU-acceleration

All that appears to by running and I added the "vcodec": "h264_omx" to the bottom of camera info inside the config like the example on the readme and I get the screen show and when I connect to camera it waits 30 secs then fails to connect.

Anyone have this working?

**Comment by simonrb2000** [comment]
Update:-
I have since followed these instructions and can confirm ffmpeg with omx is installed yet still can't get the stream working

https://www.reddit.com/r/raspberry_pi/comments/5677qw/hardware_accelerated_x264_encoding_with_ffmpeg/

Homebridge shows this
-re -i rtsp://user:password@ipaddress/videoMain -threads 0 -vcodec h264_omx -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ky55zXbHGGg+fr5hitkYpOGedPluvhiv9vG/uNfm srtp://192.168.1.139:62394?rtcpport=62394&localrtcpport=62394&pkt_size=1378

Cheers for any help you can provide

**Comment by simonrb2000** [comment]
Got this working for a while but now on iOS 11 Beta is has stopped working. I did work in previous beta's. Anyone else with issue?

**Comment by allistoncarlos** [comment]
I'm having the same issue, but it occurs on both iOS 10 and 11 Beta 9. The funny thing is that when I try to access the streaming through VLC app on Macbook, it goes great! Oh, and I'm running on RaspberryPi Zero W...

Here's my raspivid command:
`raspivid -o - -t 0 -w 640 -h 360 -fps 30 -rot 270 | tee /home/pi/video.h264 | cvlc stream:///dev/stdin --sout '#standard{access=http,mux=ts,dst=:8090}' :demux=h264`

And here's my config.json
`"videoConfig":
            {
                "source": "-re -i http://192.168.1.24:8090",
                "maxStreams": 2,
                "maxWidth": 640,
                "maxHeight": 480,
                "maxFPS": 30,
                "vcodec": "h264_omx"
            }`

**Comment by Willian-Zhang** [comment]
> Got this working for a while but now on iOS 11 Beta is has stopped working. I did work in previous beta's. Anyone else with issue?

Only tested on iOS 11 and not working as well.
The stream came for a couple of seconds, and "not responding"

Tried to fetch process via `htop` the `ffmpeg` process stoped after a couple of second also, from call of `node`.

**Comment by Willian-Zhang** [comment]
I think the problem might more dues to iOS11 rather than `ffmpeg`.
I'll test on an iOS10 later.

**Comment by moritzmhmk** [comment]
I had problems with this as well - wrote my findings down in a [gist](https://gist.github.com/moritzmhmk/48e5ed9c4baa5557422f16983900ca95).

results: iOS 10 and 11 tested, CPU usage of ffmpeg ~5%, video delay ~1s

**Comment by Willian-Zhang** [comment]
> I had problems with this as well - wrote my findings down in a gist.
> results: iOS 10 and 11 tested, CPU usage of ffmpeg ~5%, video delay ~1s
- @moritzmhmk 

great I'd like to test it out

**Comment by simonrb2000** [comment]
Mine seems to work now, had to play about with the streams. Then I have to do a whole restart of HomeKit and Homebridge. I am using the beta of tvOS also for Apple TV 4

**Comment by Willian-Zhang** [comment]
@simonrb2000 
> Mine seems to work now, had to play about with the streams. Then I have to do a whole restart of HomeKit and Homebridge. I am using the beta of tvOS also for Apple TV 4

I'm using beta tvOS as well, haven't yet try to restart it yet.

So let me confirm what you've done:

You are using ffmpeg with omex.
You restarted homebridge and your Apple TV.

And it no longer fail-to-connect-after-30-s?

**Comment by moritzmhmk** [comment]
@Willian-Zhang you can now install [homebridge-camera-rpi](https://github.com/moritzmhmk/homebridge-camera-rpi) to test it 😉

**Comment by Willian-Zhang** [comment]
> @Willian-Zhang you can now install homebridge-camera-rpi to test it 😉

I'm not using video0 from within the raspberry, I'm using outside rtsp courses, I couldn't make it work, Am I missing something?

**Comment by moritzmhmk** [comment]
@Wi

**Comment by morilm** [comment]
I have only been able to make it work by using an special version of ffmpeg 

sudo wget goo.gl/gMGA81 -O ffmpeg.deb
sudo dpkg -i ffmpeg.deb

The information is taken from homebridge-camera-ffmpeg-omx pakage.

**Comment by moritzmhmk** [comment]
@morilm using the omx enabled version of ffmpeg seems to be the only sane way of dealing with anything that is **not** a pi camera

**Comment by jeylites** [comment]
@morilm 

I tried running the following but to joy...

sudo wget goo.gl/gMGA81 -O ffmpeg.deb
sudo dpkg -i ffmpeg.deb


Hardware: Raspberry pi 3 model B Jessie
Is there a good link to install ffmpeg?
