### ISSUE TITLE
Failed while trying to pull stream from octopi

### ISSUE THREAD

**Issue by teja235** [KhaosT/homebridge-camera-ffmpeg#111]
Hey Guys!
I have a raspi 3 connected to my 3D printer running Octopi for control and video streaming. It outputs what I believe is an mjpg stream to http://192.168.86.97/webcam/?action=stream&1505110798734, and I'm able to access the stream through VLC and through my browser, but Home just says no response. I set that as my source and removed the still image source line.
Any advice? 
Thanks in advance!

**Comment by Fienberber** [comment]
same problem ... did you manage to find the correct setup ?

**Comment by vinjegaard** [comment]
I also want to get the webcam stream from octoprint as a camera in homekit. Has anyone managed to get this to work?

**Comment by reiterbene** [comment]
This worked for me. Replace `localhost` with the IP of your Octopi if your Homekit-Instance is on another device.

``` 
{
        "platform": "Camera-ffmpeg",
        "cameras": [
            {"name": "3D Printer",
                "videoConfig": {
                    "source": "-re -f mjpeg -i http://localhost:8080/?action=stream",
                    "stillImageSource": "-f mjpeg -i http://localhost:8080/?action=snapshot",
                    "maxStreams": 2,
                    "maxWidth": 1280,
                    "maxHeight": 800,
                    "maxFPS": 10
                 }
            }
        ]
    } 
```

**Comment by makealeft** [comment]
I needed /webcam/ before the action
{
        "platform": "Camera-ffmpeg",
        "cameras": [
            {"name": "3D Printer",
                "videoConfig": {
                    "source": "-re -f mjpeg -i http://localhost:8080/webcam/?action=stream",
                    "stillImageSource": "-f mjpeg -i http://localhost:8080/webcam/?action=snapshot",
                    "maxStreams": 2,
                    "maxWidth": 1280,
                    "maxHeight": 800,
                    "maxFPS": 10
                 }
            }
        ]
    }

**Comment by reboot81** [comment]
You might want to examine if changing to the H.246 stream instead of reencoding from MJPEG improves CPU load/latency.
I got much better response by removing **-re -f mjpeg** and using the following:
"name": "OctoPi Camera",
            "videoConfig": {
                **"source": "-i http://192.168.0.141:8080/video",**
                "stillImageSource": "-i http://192.168.0.141:8080/snapshot",
                "vcodec": "copy",
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 25,
                "audio": false,
                "debug": true
