### ISSUE TITLE
Stream and picture does not work

### ISSUE THREAD

**Issue by Patrykos9114** [KhaosT/homebridge-camera-ffmpeg#115]
Hi,
I have a D-link camera DCS-5020L, everything in the config I have set up as in the attachment below. In apple home I see the camera but the picture and video unfortunately do not appear. Any solution?

[homebridge.docx](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/1340628/homebridge.docx)
![img_0105](https://user-images.githubusercontent.com/32360107/30964185-9728de9c-a450-11e7-922f-746e454c20cb.png)
![img_0104](https://user-images.githubusercontent.com/32360107/30964186-97593bdc-a450-11e7-9173-08d2a424cda3.png)

**Comment by jannnfe** [comment]
Adding
"source": "-re -i http://login:password@192.168.8.116/video.cgi",
"stillImageSource": "-i http://login:password@192.168.8.116/image/jpg",
should fix it. Make sure ports are open
