### ISSUE TITLE
Supported ffmpeg version

### ISSUE THREAD

**Issue by vswee** [KhaosT/homebridge-camera-ffmpeg#119]
On mac ffmpeg v3.4 fails for live streaming for this plugin and homebridge-camera-isight plugin.

Is there any version of ffmpeg that is known to work for live streams with D'link basic IPCams on mac with the latest versions of macOS and iOS?

**Comment by hjdhjd** [comment]
Any update on this one? I noticed this stopped working with recent ffmpeg versions and recent updates to this plugin. Previously everything was working fine. It seems that ffmpeg isn't launched or dies immediately after being spawned by the plugin. Any insight?

**Comment by vswee** [comment]
What's the last working version you can recall?
Have you tried rolling back?

**Comment by hjdhjd** [comment]
Can't recall. The current relevant versions are:

node 8.9.1
homebridge 0.4.33
FFmpeg 3.4

I'm noticing there are other issues filed that exhibit similar symptoms like #126 

Thoughts?

**Comment by hjdhjd** [comment]
Got things working again -- did an uninstall / reinstall of homebridge and that seems to have corrected whatever the underlying issue was. Make sure to clean out node_modules as appropriate for those that come across this "fix".

**Comment by vswee** [comment]
Tried your method and got no change to the issue. What does your source parameter for your cameras look like? I've used this: 

`-re -f mjpeg -i http://user:pass@10.0.1.xx:xx/mjpeg.cgi  -i http://user:pass@10.0.1.xx:xx/audio.cgi`

which is straight from the docs and naturally, doesn't work.
