### ISSUE TITLE
Port Issue

### ISSUE THREAD

**Issue by jannnfe** [KhaosT/homebridge-camera-ffmpeg#122]
Hello,
is it possible to add a strict port to the config so i can open this port on my ubuntu firewall?
At the moment every time homebridge is restarting there is a new port for the stream socket.
Thanks!

**Comment by llemtt** [comment]
See also my issue at homebridge:

https://github.com/nfarina/homebridge/issues/927

**Comment by jannnfe** [comment]
Question answered in issue above
