### ISSUE TITLE
Stream freeze after 3 seconds

### ISSUE THREAD

**Issue by jannnfe** [KhaosT/homebridge-camera-ffmpeg#123]
Hello,
with iOS11 and iPhone X the Stream freezes After a couple of seconds opend the live Stream. Does anyone have the same issue? How to fix?

**Comment by desq42** [comment]
Hi,

same here on iPad 4 mini & iOS11.2.1.
3 Seconds and it halts. After 10-20 Seconds it comes back for 3 Seconds...

Suggestions?

**Comment by jannnfe** [comment]
Adding a Apple TV 4 in my System fixed the problem. Maybe the new iOS Update fixed it too.
