### ISSUE TITLE
not working for dlink 932L

### ISSUE THREAD

**Issue by motomd1** [KhaosT/homebridge-camera-ffmpeg#124]
so I have home bridge working on my Mac, cant get the dlink camera to work. Camera shows up fine on the dlink app on local and internet when im signed in not so well if im not not sure if this is a reason for it. I have the IP reserved with my router which is a archer c9 tplink.

here is my config

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [],

    "platforms": [

{

  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name":"D-Link Camera",
   "videoConfig": {
        "source":"-re -f mjpeg -i http://admin:password@192.168.1.105/mjpeg.cgi  -i http://admin:password@192.168.1.105/audio.cgi",
      "stillImageSource":"-f mjpeg -i http://admin:password@192.168.1.105/mjpeg.cgi",
        "maxStreams": 2,
        "maxWidth": 640,
        "maxHeight": 480,
        "maxFPS": 30
      }
    }
  ]
}
]

}

thank you

**Comment by iuliusmaximilian** [comment]
I have a 932L working properly, here my configuration, replace PASSWORD and NAME by your configuration. Also, I setup a port forwarding on my router from external 800 to local IP of the camera on port 80.

{
                                "name": "D-Link",
                                "videoConfig": {
                                        "source": "-re -f mjpeg -i http://admin:PASSWORD@NAME.dlinkddns.com:800/mjpeg.cgi",
                                        "stillImageSource": "-f mjpeg -i http://admin:PASSWORD@NAME.dlinkddns.com:800/mjpeg.cgi",
                                        "maxStreams": 5,
                                        "maxWidth": 640,
                                        "maxHeight": 480,
                                        "maxFPS": 30
                                }

**Comment by acharris76** [comment]
I've also managed to get the 932L working with Homekit via Homebridge, except that the live stream does not work. The still image refreshes every 10 seconds but live stream doesn't work at all. Have you got it to live stream?

**Comment by iuliusmaximilian** [comment]
Yes, live stream is working too, check my config above. 932L firmware 1.12

**Comment by acharris76** [comment]
When you say "NAME", do you mean the name you have given to the camera on the DLink website? Or the name given to it in homebridge/homekit?
