### ISSUE TITLE
camerafeed 'no response' in home app

### ISSUE THREAD

**Issue by xdenneboom** [KhaosT/homebridge-camera-ffmpeg#126]
This has been asked before, but I havent been able to find an answer that resolved it for people, so here goes: 

I have ffmpeg installed, homebridge set up with multiple lights, and now homebridge-camera-ffmpeg also installed. 

My configuration: 
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:33:AA:CC:22",
		"port": 51826,
		"pin": "000-11-333"
	},
	"description": "Hi :)",

	"platforms": [{
			"platform": "Hue",
			"name": "Hue",
			"users": {
				"000": "000"
			},
			"lights": "true"
		},
		{
			"platform": "BroadlinkRM",
			"name": "Broadlink RM",
			"hideScanFrequencyButton": true,
			"hideLearnButton": true,
			"accessories": [{
				"name": "Apple TV",
				"type": "switch",
				"disableAutomaticOff": false,
				"onDuration": 5,
				"data": {
					"on": "0000",
					"off": "0000"
				}
			}]
		},
		{
			"platform": "Camera-ffmpeg-omx",
			"cameras": [{
				"name": "cameraNameThing",
				"videoConfig": {
					"source": "-re -i rtsp://admin:pass@192.168.1.1:10554/tcp/av0_0",
    			    		"stillImageSource": "-i https://cdn-enterprise.discourse.org/helloforos/uploads/default/original/4X/a/8/7/a8747d7f246653a5864c20d22d425656b0c3e4e7.jpg",
					"maxStreams": 2,
					"maxWidth": 960,
					"maxHeight": 960,
					"maxFPS": 24
				}
			}]
		}
	]
}
```
And the output is giving me:

```
[2017-11-30 22:31:28] [Camera-ffmpeg-omx] Initializing Camera-ffmpeg-omx platform...
[2017-11-30 22:31:28] leylacam is running on port 33649.
```

I've tried reinstalling all kinds of versions and sources of ffmpeg, homebridge-camera0-ffmpeg. Oh and I have to remove homebridge from the home app and add it again in order to identify new accessories. So all my accessories load, but the camera is nowhere to find. 

I've also checked the rtsp source via VLC, I'm getting a solid stream there. I really don't want to give up on this :( Does anyone have any other suggestions?

**Comment by xdenneboom** [comment]
So I did a clean install of raspbian, ffmpeg and homebridge. Now the camera is adding as an accessory in the Home app. I believe the load homebridge on boot was causing issues here. 

Now the camera doesn't have a feed and still image. I'm trying all kinds of solutions that were provided to previously answered similar issues, without any luck. I'm not getting an error or anything in the output. The config file is still the same as above. Any help in the right direction? I did set my maxWidth to 640, height to 360 and maxFPS to 30 atm.

**Comment by xdenneboom** [comment]
this is an output I get when the Home app gives me a "No response" from the camera view:

Does anyone know what this means?

> `rtsp_transport tcp -re -i rtsp://user:pass@192.168.178.24:10554/tcp/av0_0 -threads 0 -vcodec h264_omx -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params zWXhsnyHoXSvttMdxGbewoDI6rZwUsAsj6/NSsdj srtp://192.168.178.45:64149?rtcpport=64149&localrtcpport=64149&pkt_size=1378`

**Comment by xdenneboom** [comment]
So I got it working. In case anyone encounters the same issues I had, here are a couple of steps that helped for me. Maybe we want to mention this in the documentation.

**1. When you're not seeing the camera in the Home app.**
 Adding the camera to the Home app is not like other plugins. After adding Homebridge to the Home app, you have to add another accessory, but not scan the QR. Click the link _I don't have a QR_ and the camera will be visible in the next view. If that also doesn't happen. Quit Homebridge, change the homebridge name (mac address) and the camera name). Retry and it will show up.

**2. When you don't have a feed in the camera app.**
The moment you open the camera in the home app, you should see the feed url output in Terminal. If this is not the case, try rebooting Homebridge. This wasn't always the case for me. Once you see the feed url in Homebridge, and you still don't see the feed in the Home app, play with your settings. and try again. This means, change the camera name again and add it to Homebridge again. 

**3. Settings that made my feed not work in the Home app**
- The resolution of my camera had to be the exact resolution of the camera output. Anything other than that made it not work. So for me that was 940 x 940 (because of the fisheye lens camera). 
- Adding rtsp_transport tcp before the -re -i helped for me. 
- Framerate for me is still at 30. Even though my camera doesn't support this. 
- Also keep in mind, that you might have to open the home app several times before the feed finally shows up. After the feed has shown up 1 time, it worked everytime. 
- Immediately after my feed was working, all my lights were disconnected (even the official homekit supported ones, that don't run via Homebridge). This took about an hour, before everything became responsive again. This includes the camera.

**Comment by kebabmane** [comment]
Hi @xdenneboom do you have a snippet/gist of the final config you used? I'm having very similar issues and have tried everything. I have ensured my camera can handle the resolution and fps requested, I'm getting stills but cannot get the live stream working at all - below is a snippet of my config

`        {
            "platform": "Camera-ffmpeg",
            "cameras": [
              {
                "name": "Living Room Camera",
                "videoConfig": {
                    "source": "rtsp_transport tcp -re -i http://192.168.1.121:554/ch0_0.h264",
                    "stillImageSource":"-i rtsp://192.168.1.121:554/ch0_1.h264 -vframes 1 -r 1",
                    "maxStreams": 2,
                    "maxWidth": 1280,
                    "maxHeight": 720,
                    "maxFPS": 30,
                    "vcodec": "h264_omx"
                }
              },
              {
                "name": "Nursery Camera",
                "videoConfig": {
                    "source": "rtsp_transport tcp -re -i rtsp://192.168.1.122:554/ch0_0.h264",
                    "stillImageSource":"-i rtsp://192.168.1.122:554/ch0_0.h264 -vframes 1 -r 1",
                    "maxStreams": 2,
                    "maxWidth": 1280,
                    "maxHeight": 720,
                    "maxFPS": 30,
                    "vcodec": "h264_omx"
                }
              }
            ]
          },`

**Comment by jeylites** [comment]
Hi

I followed the instructions on homebridge-camera-ffmpeg-omx but I can't seem to get the camera show up on Homekit. Previously I got it working on IOS 10, a few months ago but after upgrading to 11 and I had to switch to a different Raspberry Pi 3, I can't seem to get it working.

Homebrige shows up on Homekit app but no camera in the accessories tab. I have also deleted the persist files and added everything again.
Any ideas?

Instruction followed...
https://github.com/legotheboss/homebridge-camera-ffmpeg-omx

Hardware
Phone: IOS 11
Raspberry Pi3
Valid RTSP link, verified using a RTSP player

Config.json
{
"bridge":{
"name":"Homecam",
"username":"7C:77:07:B7:77:EA",
"port":51827,
"pin":"031-45-157"
},
"description":"Configuration file",
"platform": "Camera-ffmpeg-omx",
"cameras": [
{
"name":"Camera Name",
"videoConfig":{
"source":"-re -i rtsp://admin:0162855518@192.168.1.64:554//h264Preview_01_main",
"stillImageSource":"-i http://192.168.1.64/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=abcd123456&user=admin&password=0162855518",
"maxStreams":2,
"maxWidth":1280,
"maxHeight":720,
"maxFPS":30,
"vcodec":"h264_omx"
}
}
]
}

**Comment by jeylites** [comment]
**A follow-up update**

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-1-16 10:47:12] Loaded plugin: homebridge-camera-ffmpeg-omx
[2018-1-16 10:47:13] Registering platform 'homebridge-camera-ffmpeg-omx.Camera-ffmpeg-omx'
[2018-1-16 10:47:13] ---
[2018-1-16 10:47:13] Loaded config.json with 0 accessories and 0 platforms.
[2018-1-16 10:47:13] ---
Load homebridge-camera-ffmpeg-omx.Camera-ffmpeg-omx
Setup Payload:
X-HM://0023ISYWZO7HG
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-155 │     
    └────────────┘     
                       
[2018-1-16 10:47:13] Homebridge is running on port 51821.

**Comment by TerryLansdown** [comment]
I'm getting a No Response in the Home app also. I can see the rtsp stream using VLC fine, but very often the Home app will return No Response from the stream. config is:
```
{
"description": "Homebridge",

"bridge":

        {
        "name": "Homebridge",
        "username": "1A:1A:1A:B6:BC:A9",
        "port": 51447,
        "pin": "000-00-001"
        },

"platforms":

        [
                {
                "platform": "Camera-ffmpeg", "cameras":
                        [
                        {
                        "name": "Camera",
                            "videoConfig":
                                {
                                "source": "rtsp_transport tcp -re -i rtsp://192.168.1.56:554/onvif2",
                                "maxStreams": 3,
                                "maxWidth": 480,
                                "maxHeight": 270,
                                "maxFPS": 30
                                }
                        }
                        ]
                }
        ]
}
```
Any ideas how to debug this. In the log the only thing that seems related is:
```
[Camera-ffmpeg] ERROR: FFmpeg exited with code 1
```
Thanks, Terry

**Comment by llemtt** [comment]
Put

"debug": true

into videoConfig.

FFmpeg exiting with code 1 usually means it doesn't understand parameters and/or it has problems analyzing the input stream.
