### ISSUE TITLE
multiple cameras in config file, shows same camera using two ports when homebridge starts.

### ISSUE THREAD

**Issue by tmur11** [KhaosT/homebridge-camera-ffmpeg#13]
When there's multiple cameras setup in a config file it appears the first camera in the list uses two different ports and it appears the second does get loaded. This can be seen in the output when homebridge first starts.

**Comment by KhaosT** [comment]
Can you post your configuration and logs?

**Comment by tmur11** [comment]
{
	"bridge": {
		"name": "Homebridge-Camera",
		"username": "CE:21:3D:C1:CE:30",
		"port": 51827,
		"pin": "169-69-169"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [],

	"platforms": [{
		  "platform": "Camera-ffmpeg",
		  "cameras": [
		    {
		      "name": "Driveway Camera",
		      "videoConfig": {
		        "source": "-re -i rtsp://user:password2001@17.172.2.32:554/Streaming/Channels/2",
		        "maxStreams": 2,
			"maxWidth": 640,
			"maxHeight": 480,
			"maxFPS": 15
		      	}
			},{
			      "name": "Garage Camera",
			      "videoConfig": {
			        "source": "-re -i rtsp://user:password@17.172.2.80/mpeg4",
				"maxStreams": 2,
			        "maxWidth": 640,
			        "maxHeight": 480,
			        "maxFPS": 15
			      }
					}
		    ]
		 }

	]
}

**Comment by KhaosT** [comment]
I just tried the one you provided and it creates two camera... Are you sure you don't see the second  one?

**Comment by tmur11** [comment]
sorry for the poor posting abilities. I was having hell of a time figuring out how to post my config in a valid code format.

I am seeing the log indicate both cameras on running on the same port. I do in fact get both cameras but terrible frame rate but that's another issue.

**Comment by KhaosT** [comment]
It should not be on the same port, can you post the full log with this problem here?

**Comment by tmur11** [comment]
![image](https://cloud.githubusercontent.com/assets/21132832/19462184/d9b36fbe-94b8-11e6-8dc6-0bec9287694a.png)


now it appears to be showing the garage camera on both ports. I may have initially been mistaken in its behavior.

**Comment by KhaosT** [comment]
The only thing I can think of is the scope issue at [here](https://github.com/nfarina/homebridge/blob/master/lib/server.js#L482). I'll try to fix it in homebridge.

**Comment by TaperCrime** [comment]
Was this actually resolved? I've got two cameras and I'm hitting the exact same issue. Tried the latest build but still had the problem. Please let me know if you need any information.

**Comment by KhaosT** [comment]
The error at here should only affect the log output, it should still be functional. On the Home app side, did you see two same cameras?

**Comment by TaperCrime** [comment]
Derp, I'm an idiot. You're right, it's just in the logs. Thanks again!

**Comment by ZoneMR** [comment]
Do multiple cameras actually work for you, TaperCrime?

I had one camera working. Attempted to add another two. Now none of them work.

**Comment by blysik** [comment]
I have 6 cameras (rebranded Hikvision) setup via this method.  They are on private IPs to my network.  They are assigned across two "rooms" in the Home app.  It works perfectly.  I see the snapshots on the room pages, and I can click through to the live camera feeds.

I have homebridge running on a Mac Mini.

**Comment by gijoecool** [comment]
What version of iOS?

**Comment by blysik** [comment]
iPhone 7 currently running 10.1.1.  I don't know what version the Apple TV 4th gens are running, but they are set to auto-updated.

**Comment by gijoecool** [comment]
Interesting... I'll retry my setup this weekend. I tried with iOS 10.0.2 on iPhone 7 with a Foscam camera hosted by a Debian machine. The preview worked but I couldn't get streaming working.
