### ISSUE TITLE
Accessory sent an invalid response

### ISSUE THREAD

**Issue by kennymc-c** [KhaosT/homebridge-camera-ffmpeg#134]
When I'm trying to load my camera to fullscreen in different homekit apps i get an error that the camera is not responding after 30 seconds. I use MotionEyeOS in Fast Network Camera Mode on a Raspberry Pi Zero W with a camera connected to the CSI interface. The MJPEG Stream seems to be working fine.
Homebridge is running on a Raspberry Pi 1 B+ with Raspbian Wheezy. 

My Config loks like this:

> "platform": "Camera-ffmpeg",
  				"cameras": [				
    				{
      					"name": "Türspion",
      					"videoConfig": {
      						"source": "rtsp_transport tcp -re -f mjpeg -i http://user:pass@192.168.1.110:8081",
      						"maxStreams": 2,
      						"maxWidth": 1280,
      						"maxHeight": 720,
      						"maxFPS": 30,
      						"vcodec": "h264_omx"
      						      		}
    				}

This is what the homebridge log shows when trying to load the camera stream:

> rtsp_transport tcp -re -f mjpeg -i http://user:pass@192.168.1.110:8081 -threads 0 -vcodec h264_omx -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 93yZ26ZLnEp0BQszisr6Tu0KmIwXQsihHPEU7ehj srtp://192.168.1.102:50985?rtcpport=50985&localrtcpport=50985&pkt_size=1378

And the output of that command with ffmpeg

> [1] 7964
[2] 7965
pi@raspberrypi ~ $ ffmpeg version N-81800-gf013ba4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-omx --enable-omx-rpi
  libavutil      55. 30.100 / 55. 30.100
  libavcodec     57. 58.103 / 57. 58.103
  libavformat    57. 51.100 / 57. 51.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 63.100 /  6. 63.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100

iOS Console Log: https://pastebin.com/0cUWvzQT

I noticed in the "Accessory sent an invalid response" error that iOS tries to load the stream with a resolution of 480x270 instead of 1280x720 in my config. Unfortunately i can't set my camera set to this exact resolution in MotionEyeOS. I also tried just setting the config to this resolution and don't change the actual camera resolution.

**Comment by nicholastripp** [comment]
@kennymc-c

Did you ever figure this one out? I'm running into the same thing. Raspberry Pi Zero W with the Pi Camera on the CSI interface. MotionEyeOS in Fast Network Camera mode. Homebridge loads it and I can add it as an accessory in Homekit. However, when Homekit tries to load the camera stream it crashes Homebridge. I see the same 480x270 image request before the crash happens.

**Comment by kennymc-c** [comment]
Unfortunately not, i recently did a clean install on a new Pi 3 B with Raspbian stretch with just homebridge installed and ran into the same problem. Now i think think this is some kind related to MotionEyeOS.
