### ISSUE TITLE
Another question on audio...

### ISSUE THREAD

**Issue by brownad** [KhaosT/homebridge-camera-ffmpeg#135]
Hi,

I'm using a copy of all the great work, and wondering how I can test audio, aware there are some serious limitations here but curious to try out the basics and probably fail.

My plugin has the elements for a video doorbell (intercom), and I've exposed both the speaker and microphone to show the experience.

https://github.com/brownad/homebridge-doorbird

So, the device exposes APIs for both audio (from the device) as an endpoint, and an endpoint to transmit audio:

receive: /bha-api/audio-receive.cgi
transmit: /bha-api/audio-transmit.cgi

Is there a way to test adding the stream(s) in config, and to see what happens or is this not possible with these kind of streams?

The api for this:
https://www.doorbird.com/downloads/api_lan.pdf?rev=0.17

Many thanks 👍

**Comment by brownad** [comment]
@normen can you tell me how the changes to support audio would be configured?  I have a separate stream providing audio would that just be added as another stream (how?) or does this expect a video with audio stream combined?

Thanks

**Comment by normen** [comment]
The latter, yes.
