### ISSUE TITLE
Random ssrc lacks bound checks

### ISSUE THREAD

**Issue by zllovesuki** [KhaosT/homebridge-camera-ffmpeg#142]
4a7c790e4d235bd57bd4f8a5a116c5c7a29a6e5a now generates a random `ssrc` with `crypto.randomBytes(4).readUInt32BE(0, true)`. However, it does not enforce the boundary for 32-bit integer (-2147483647 to 2147483647).

Propose solution:
1) `Math.floor(Math.random() * 2147483647);`
2) `crypto.randomBytes(4).readUInt32BE(0, true) % 2147483647`

Gonna head to bed now.. All nighter. Let me know what you think :)

**Comment by KhaosT** [comment]
v0.1.3 should addressed this. Thanks for bringing this up.
