### ISSUE TITLE
Disconnects after several minutes

### ISSUE THREAD

**Issue by drewcassidy** [KhaosT/homebridge-camera-ffmpeg#143]
The video feed I have is working fine, but after several minutes the connection times out, and I need to hit "done" and open the camera again to view it. This is on a raspberry pi 3 with a USB webcam, and with only a few filters added to the ffmpeg.js file to crop and rotate the video

**Comment by TannerH** [comment]
Can you post your config? Also kind of off topic but I'm interested in how you rotated the image. I would like to mount my camera upside down and wasn't sure how to go about flipping the image so I mounted it right side up.

**Comment by drewcassidy** [comment]
> I'm interested in how you rotated the image

I edited the command that starts ffmpeg to use the transpose filter 

I should note I also reproduced this with an unmodified version of the progran
