### ISSUE TITLE
Question: How to configure a local V4L2 camera

### ISSUE THREAD

**Issue by iDevo** [KhaosT/homebridge-camera-ffmpeg#146]
Hi there!
First of all thank you very much for the great project! I really appreciate your work!

I'm currently about to add a local V4L2 camera (HD webcam), which is connected via USB and already providing a basic http livestream using motion. 
Unfortunately I'm struggling with the `source` property of the config file. I already googled / read the motion documentation days over days and also tried a lot of settings, mentioned in this wiki, but I'm unfortunately not familiar with this topic. 

Does anybody have a guess, what I could try to enter as a value for the `source` field for a local V4L2 camera?

```
{
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "My camera",
      "videoConfig": {
      	"source": " ??? ",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 15
      }
    }
  ]
}
```

**Comment by swgn** [comment]
From the author of this very plugin:

https://mobile.twitter.com/KhaosT/status/960592605808549888

**Comment by iDevo** [comment]
Thank you! That did the trick!
