### ISSUE TITLE
Camera not found after 0.1.4 update

### ISSUE THREAD

**Issue by ryanchucks** [KhaosT/homebridge-camera-ffmpeg#148]
After the the latest 0.1.4 update, the platform no longer finds the camera.

From the console, I can see the Camera-ffmpeg platform is initiated, but no camera is found/loaded as I do not see the line "XXX camera is running on port XXXXX". As the accessory isn't found/started, I can't add it in Home app.

Is there a way to install the previous version of Camera-ffmpeg? Thanks.

**Comment by KhaosT** [comment]
Sorry about that, please try v0.1.5. That should fix the issue.

**Comment by brianerdelyi** [comment]
I'm having same issue :(
