### ISSUE TITLE
Getting error when viewing the camera

### ISSUE THREAD

**Issue by jcbriones** [KhaosT/homebridge-camera-ffmpeg#15]
Oct 12 00:03:32 homekit homebridge[10546]: events.js:141
Oct 12 00:03:32 homekit homebridge[10546]: throw er; // Unhandled 'error' event
Oct 12 00:03:32 homekit homebridge[10546]: ^
Oct 12 00:03:32 homekit homebridge[10546]: Error: spawn ffmpeg ENOENT
Oct 12 00:03:32 homekit homebridge[10546]: at exports._errnoException (util.js:907:11)
Oct 12 00:03:32 homekit homebridge[10546]: at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
Oct 12 00:03:32 homekit homebridge[10546]: at onErrorNT (internal/child_process.js:344:16)
Oct 12 00:03:32 homekit homebridge[10546]: at nextTickCallbackWith2Args (node.js:442:9)
Oct 12 00:03:32 homekit homebridge[10546]: at process._tickCallback (node.js:356:17)

**Comment by jcbriones** [comment]
I am trying to load the rtsp link from my camera using this manual

https://s3.amazonaws.com/amcrest-files/AMCREST_CGI_SDK_API.pdf

I am not sure if the feed is FFMPEG. Probably not.

**Comment by KhaosT** [comment]
ENOENT means there is no ffmpeg installed on the machine. Please try to install ffmpeg and try again.
