### ISSUE TITLE
Framerate VERY low, downgrade to previous version?

### ISSUE THREAD

**Issue by leroyrichjr** [KhaosT/homebridge-camera-ffmpeg#152]
For the past 12 hours or so, my cameras have been virtually unusable.  The framerate dropped to about .2fps (yes, that's one frame every 4-5 seconds).  Nothing changed on the hardware or config and testing the RTSP stream in VLC shows that the camera is working fine, but I did notice the version number of the plugin has increased to 0.1.5.

Is there a way I can run a previous verison to avoid this problem?

**Comment by Yardco** [comment]
Try lowering packetsize if you’ve upgraded to 0.1.5. One of my cameras works fine with a packetsize of just 188 (minimum).

**Comment by normen** [comment]
Also note that it might be something in your network. I had terrible issues until I updated one old RasPis firmware that was also on the network. But yeah, 188 is also working better for me.

**Comment by normen** [comment]
And note the default packet size DID change in this version, you can try 1378 to get the old value, supposedly it's not good to use values that are not multiples of 188 - don't ask me why, I'm not a network expert :)

**Comment by patelhiren** [comment]
I had the same problem after upgrading to the version that added audio support. I narrowed it down to these parameters being removed from the ffmpeg launch command.

`-f rawvideo -tune zerolatency`

I forked the code added those parameters back to the ffmpeg command. With that version I can see the streaming back to what it was with the previous versions. I do not however have a way of testing audio as I have no camera hardware that supports that, so I am reluctant to issue a pull request. If someone wants to take a look here is the commit.

https://github.com/patelhiren/homebridge-camera-ffmpeg/commit/91f8df862f05f8f6dcf8ff2893032a9ac69ff0b0

I also set the packet size to 1378 in my config.

**Comment by normen** [comment]
Well the latest versions of ffmpeg don't support that parameter so maybe try compiling a new ffmpeg, that might improve a lot of things :)

I put instructions in this wiki https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki

**Comment by KhaosT** [comment]
Ah I didn't realize this was removed in that diff... Feel free to send the PR and I'll merge it.

@normen what do you mean "don't support"? 3.4 seems still have that...

**Comment by normen** [comment]
Okay I have a PR going so I can make that parameter optional then, okay? If you compile the latest ffmpeg from github ffmpeg fails with an error, will look it up.

**Comment by normen** [comment]
I mean the zerolatency parameter btw, not rawvideo

**Comment by KhaosT** [comment]
@normen make sure you have correct libx264? It's still here `https://github.com/mirror/x264/blob/7d0ff22e8c96de126be9d3de4952edd6d1b75a8c/common/base.c#L540`

**Comment by patelhiren** [comment]
Sorry guys I do not have too much experience with linux or ffmpeg for that matter. Just using this to view my IPCameras via HomeKit and it was working well right before the upgrade so just looked up the diffs and ruled things out.

I am running this on Debain 9.3 and ffmpeg version shows as 3.2.10-1. So 3.4 may very well not have this option.

**Comment by livefeed** [comment]
Same here, was working now will not load;

Just will not load
18:55:51 - [My Home] refresh error: Error: invalid /1/public/person/... response

**Comment by normen** [comment]
Ah so this is between the RasPI OMX and the libx264 then I guess - I will make it optional and add a hint to the README, okay?

**Comment by KhaosT** [comment]
@normen `h264_omx` also supports this thing... What's the error you are getting?

**Comment by KhaosT** [comment]
@livefeed I'm not sure this log is generated by this plugin.

**Comment by normen** [comment]
I think it might be down to me not including libx264, I thought it wasn't necessary when using omx.. Will try and compile it with that and then update the RasPi compile info in the wiki if thats the case.

**Comment by normen** [comment]
Looks like indeed 70% of all "How to compile ffmpeg for RasPi" guides online are missing this and it is actually the root of the issue.

The libx264 encoder is indeed needed for the tune parameter to work even if you're using the h264_omx encoder - which can compress just fine alone if that parameter isn't needed - go figure.

Updated the wiki RasPi compile infos, sorry for the confusion :)

**Comment by livefeed** [comment]
@KhaosT my camera plugin is the only plugin not working.

**Comment by normen** [comment]
The 0.1.17 update isn't working either?

**Comment by leroyrichjr** [comment]
It's worse with 0.1.7, now the stream never starts.  Debug info in the console shows information about the stream, but the client never actually shows video.

**Comment by patelhiren** [comment]
I suggest you try after restarting your iOS device. I had weird issues with stream not starting which were resolved after a restart of the iOS device.

**Comment by Samfox2** [comment]
If you use the host name of your cam in your config.json file try to use the ip instead.
