### ISSUE TITLE
Hikvision DS-2CD2F22FWD-IWS 1 frame in 10 sec. (

### ISSUE THREAD

**Issue by Skull09rus** [KhaosT/homebridge-camera-ffmpeg#153]
Hello!
Please help me to setup smooth live stream. 
config
	{ "platform": "Camera-ffmpeg",
  	"cameras":
     	[{"name": "FFCAM",
        "videoConfig": {
      	"source": "-rtsp_transport tcp -re -i rtsp://admin:******@192.168.1.99:554/Streaming/Channels/102",
        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 25}
    }
  ]
}
]

homebridge 
Snapshot -i http://faster_still_image_grab_url/this_is_optional.jpg -t 1 -s 480x270 -f image2 -
ffmpeg -rtsp_transport tcp -re -i rtsp://admin:*******@192.168.1.99:554/Streaming/Channels/102 -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 25 -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 8951307 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params kKmdXstnY+hiXp1EILxxhOeC6AKO6uVdOstjLmux srtp://192.168.1.102:58147?rtcpport=58147&localrtcpport=58147&pkt_size=1316

Live stream stops after few minutes 
homebridge
Stopped ffmpeg
In VLC stream nice and smooth.
Thanks in advance! Sorry for my English )

**Comment by ptath** [comment]
Не получилось решить проблему? У меня то же самое )
