### ISSUE TITLE
MaxWidth/MaxHeight not picking up

### ISSUE THREAD

**Issue by normen** [KhaosT/homebridge-camera-ffmpeg#155]
It seems as if the maxWidth and maxHeight parameters don't pick up from the HomeKit side. The ffmpeg process will always create up to 1280x720, depending on the devices display window size.

In code, the HomeKit request contains a width and height that is larger than the given max values in the videoResolutions array.

I am not sure if this is intended behavior on every side. If HomeKit really _requires_ the device to stream a larger video then not much can be done I guess but then at least the config values don't make much sense? Or are they only used for configuring the camera hardware from HomeKit in the future?

Unless that is actually so I see a two options I could make a PR for:
- Force ffmpeg to the user given frame size
  - If its larger than the request value use request
  - use the current "find max size" logic to find a compatible ratio
- Remove the config value

Another option is an issue in HomeBridge/HAP-NodeJS or actually HomeKit? Thats something where I can't do much :)

**Comment by mriksman** [comment]
Odd. No matter what size I set, I always get 640x360. Even though I have my config.json set to 1280x720@300.
`Start streaming video from Camera with 640x360@132kBit`
I can set the bitrate lower, but not higher than 132kBit. 
But I can't even go lower with the resolution. It gets completely ignored, and will always do a 640x360 resolution.

**Comment by mriksman** [comment]
#120 I noticed he pasted his ffmpeg output, he has a Foscam camera, and he is also ignoring his settings and is getting 640x360@132kBits. Is the camera itself ignoring the settings........ ??

**Comment by normen** [comment]
Lower sizes are normal, thats what iOS requests when you only open the video in a small window on your iOS device. If you open full screen on an iPad it will request 720p - but as said also when theres a lower max size given.

**Comment by mriksman** [comment]
Yeah I was starting to get the impression the iPhone was dictating the resolution/bitrate. It looks pretty terrible at that resolution/bitrate; at least for me it does...
But you're right/and as I've found - you can reduce the bitrate, but you can't reduce the resolution.

**Comment by normen** [comment]
Yeah I know, the questions of the main issue text remain :) The thing is its nominally not a "max" size, its apparently just what iOS requests. Hence the question to @KhaosT

**Comment by adrianmihalko** [comment]
I have similar question.

```
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "Kamera kint",
      "videoConfig": {
        "source": "-re -i rtsp://192.168.1.61:9002/Streaming/Channels/102/",
        "stillImageSource": "-i http://192.168.1.61:9000/Streaming/channels/1/picture",
        "debug": true,
        "maxStreams": 2,
        "maxWidth": 1280,
        "maxHeight": 720,
        "maxFPS": 10,
        "maxBitrate": 100,
        "vcodec": "libx264",
        "audio": false
      }
    }
  ]
},
```


Where maxBitrate, maxFPS is not picked up.

In log I see:

` -re -i rtsp://192.168.1.61:9002/Streaming/Channels/102/ -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 8T6puR812ETl0oBYayA6q7z2W4DvdkZHeBsH4zzy srtp://192.168.1.102:60110?rtcpport=60110&localrtcpport=60110&pkt_size=1378`

According to -r 30, fps is set to 30 (maxFPS was set to 10),  -b:v 299k (maxBitrate was set to 100).

**Comment by adrianmihalko** [comment]
My bad. I had older version...
