### ISSUE TITLE
Any suggestion for an iOS app?

### ISSUE THREAD

**Issue by timdeville** [KhaosT/homebridge-camera-ffmpeg#158]
Managed to do this to my camera now which is great, but now im after a good iPhone app that can do PTZ and is modern with widgets and notification of movement etc.  Is there such an app?

**Comment by swgn** [comment]
I'm using a combination of the iOS Home app and [Homecam](http://homecamapp.com/).

**Comment by timdeville** [comment]
Thanks, that’s what I’m thinking of doing. It needs homebridge though which I’m never tried before so I guess I need to give that a go on.
Shane there is no pan and tilt in homecam or the iOS home app

Thanks,

Tim
________________________________
