### ISSUE TITLE
can't add camera to homekit / can't stream

### ISSUE THREAD

**Issue by iShift** [KhaosT/homebridge-camera-ffmpeg#159]
Hi, i have in log:
[2018-3-17 11:58:36] Camera Name1 is running on port 37623.

but i can't see my camera in home kit app on iphone, what can i do?

**Comment by iShift** [comment]
update - i try add accessory --> i haven't code -->  then i see my camera but app requesting camera code, all zero don't help me

**Comment by iShift** [comment]
ok, i go to next step - default code for camera add - my home kit code from config...

**Comment by Samfox2** [comment]
If your cam is running it should appear after adding it as new accessory and using your homebridge code defined at the top of your config.json file.

**Comment by iShift** [comment]
@Samfox2 ok, i add my camera to home app, with home kit code, after that - i get still image but no video stream, can i get video?

**Comment by iShift** [comment]
@Samfox2 i try limit fps to 15 and set low packet size, but i don't get video stream, also i don't see any ffmpeg in homebridge logs after i start stream (when it take screenshot - i see line)

**Comment by iShift** [comment]
how i can get ffmpeg line for streaming?

**Comment by iShift** [comment]
ohh, ffmpeg starts but i don't get any image (but i get logs!)
i use that settings:
"maxStreams": 2,
"maxWidth": 1280,
"maxHeight": 720,
"maxFPS": 2,
"maxBitrate": 200,
"debug": true

play with width/height/bitrate/fps don't help me...

in logs  have 
_[h264 @ 0x1f28a50] concealing 6379 DC, 6379 AC, 6379 MV errors in I frame
frame=   31 fps=2.0 q=19.0 size=     483kB time=00:00:15.00 bitrate= 263.5kbits/s dup=4 drop=78 speed=0.975x
frame=   33 fps=2.0 q=14.0 size=     509kB time=00:00:16.00 bitrate= 260.4kbits/s dup=4 drop=79 speed=0.992x
frame=   35 fps=2.1 q=18.0 size=     547kB time=00:00:17.00 bitrate= 263.4kbits/s dup=4 drop=79 speed=1.02x
frame=   36 fps=2.1 q=19.0 size=     562kB time=00:00:17.50 bitrate= 262.9kbits/s dup=4 drop=80 speed=1.01x
frame=   36 fps=2.0 q=19.0 size=     562kB time=00:00:17.50 bitrate= 262.9kbits/s dup=4 drop=85 speed=0.976x_

and another question - why i need ffmpeg if camera make h264 stream that can be native handle by ios?

**Comment by iShift** [comment]
hmm i solve all my problems with that fork https://github.com/legotheboss/homebridge-camera-ffmpeg-omx
