### ISSUE TITLE
Help flipping stream

### ISSUE THREAD

**Issue by MattCheetham** [KhaosT/homebridge-camera-ffmpeg#16]
Hey,

I have this all setup and working (thank you!) but my camera is actually mounted on the roof upside down. I have added `-vf "transpose=2,transpose=2` to the source URL in the config and that has flipped the image in the capture preview but when i actually view the stream it goes back to being upside down.

Is there a way to get this to flip properly?

Thanks

**Comment by KhaosT** [comment]
Currently there isn't. I'll think about adding this.

**Comment by durosity** [comment]
It'd be awesome if it could also rotate xº as i have some cameras that are mounted at a 90º angle!
