### ISSUE TITLE
Error: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by henkied** [KhaosT/homebridge-camera-ffmpeg#160]
Please can someone help me,

I have homebridge installed with docker in Synology works great but only error with ffmpeg:

[2018-3-17 13:38:12] [Camera-ffmpeg] Snapshot from TEST at 480x270
Error: spawn ffmpeg ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-3-17 13:38:17] Loaded plugin: homebridge-camera-ffmpeg
[2018-3-17 13:38:17] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'

**Comment by senadman** [comment]
excuse my noobness, i have exactly the same problem, how is this fix implemented??

**Comment by TURSTY** [comment]
Hey I am having this issue as well and cant make sense of the above answer. Any idea how we can find some instructions on how to implement this?

**Comment by Caribsky** [comment]
@TURSTY, 
You need install ffmpeg package via docker's terminal.
Example for Debian based docker: 

echo 'deb http://ftp.uk.debian.org/debian jessie-backports main' >> /etc/apt/sources.list

apt-get update

apt-get -y install ffmpeg

**Comment by senadman** [comment]
I think its more than just having ffmpeg on your system and a correct url, I'm thinking its a plugin issue. Im running windows and can get ffplay to play the stream no problem, but as soon as I have the plugin try and play the same stream it fails with this fault when creating a snapshot.

When I have the camera accessory open (click on the accessory)  and try and run the plugin, the command line tells me the stream begins and then boom it fails ENOENT.

**Comment by Caribsky** [comment]
@senadman 
Error: spawn ffmpeg ENOENT - it's mean plugin **homebridge-camera-ffmpeg** does not have access to ffmpeg. 
Need to insert a path to own video processor into config:

> 

{
  "platform": "Camera-ffmpeg",
  "videoProcessor": "/my/own/compiled/ffmpeg",
  "cameras": [
    ...
  ]
}

> 

**Or**

Need to install ffmpeg under docker if we use it.

**Comment by senadman** [comment]
@Caribsky 
I have already tried this with full path to ffmpeg.exe. Still fails.

**Comment by senadman** [comment]
@Caribsky

Wall of text, i have both outputs. 

for path_to_ffmpeg.exe -re -i camera_stream_url test.mp4

PS C:\Users\Administrator> ffmpeg -rtsp_transport tcp -re -i rtsp://xxxx:xxx@192.168.1.194/live/ch00_0.h264 test.mp4
ffmpeg version N-90649-g9825f77ac7 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enabl
e-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-
libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-l
ibtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --en
able-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-l
ibvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enabl
e-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 13.100 / 56. 13.100
  libavcodec     58. 17.100 / 58. 17.100
  libavformat    58. 11.101 / 58. 11.101
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 14.100 /  7. 14.100
  libswscale      5.  0.102 /  5.  0.102
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, rtsp, from 'rtsp://xxxx:xxxx@192.168.1.194/live/ch00_0.h264':
  Metadata:
    title           : Easy Rtsp 1.0
    comment         : Easy
  Duration: N/A, start: 0.201000, bitrate: N/A
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 1920x1080, 25 fps, 24.83 tbr, 90k tbn, 50 tbc
File 'test.mp4' already exists. Overwrite ? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 000002594598c100] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000002594598c100] profile High, level 4.0
[libx264 @ 000002594598c100] 264 - core 155 r2901 7d0ff22 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.vid
eolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed
_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookah
ead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_
adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc_lookahe
ad=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'test.mp4':
  Metadata:
    title           : Easy Rtsp 1.0
    comment         : Easy
    encoder         : Lavf58.11.101
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1920x1080, q=-1--1, 24.83 fps, 19072 tbn, 24.83 tbc
    Metadata:
      encoder         : Lavc58.17.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=  535 fps= 21 q=-1.0 Lsize=    1721kB time=00:00:21.42 bitrate= 658.1kbits/s dup=417 drop=5 speed=0.843x
video:1714kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.417623%
[libx264 @ 000002594598c100] frame I:3     Avg QP:14.64  size: 87054
[libx264 @ 000002594598c100] frame P:135   Avg QP:13.92  size:  6881
[libx264 @ 000002594598c100] frame B:397   Avg QP:20.88  size:  1421
[libx264 @ 000002594598c100] consecutive B-frames:  0.6%  1.1%  1.1% 97.2%
[libx264 @ 000002594598c100] mb I  I16..4: 33.8% 59.0%  7.2%
[libx264 @ 000002594598c100] mb P  I16..4:  2.0%  3.1%  0.1%  P16..4: 14.1%  1.1%  1.4%  0.0%  0.0%    skip:78.1%
[libx264 @ 000002594598c100] mb B  I16..4:  0.1%  0.0%  0.0%  B16..8:  7.4%  0.1%  0.0%  direct: 1.1%  skip:91.3%  L0:47
.2% L1:52.3% BI: 0.4%
[libx264 @ 000002594598c100] 8x8 transform intra:57.5% inter:91.8%
[libx264 @ 000002594598c100] coded y,uvDC,uvAC intra: 26.9% 54.7% 24.0% inter: 1.7% 5.1% 0.1%
[libx264 @ 000002594598c100] i16 v,h,dc,p: 54% 18% 14% 14%
[libx264 @ 000002594598c100] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 35% 10% 46%  2%  2%  2%  1%  2%  1%
[libx264 @ 000002594598c100] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 17% 24%  5%  5%  5%  7%  3%  3%
[libx264 @ 000002594598c100] i8c dc,h,v,p: 58% 21% 20%  2%
[libx264 @ 000002594598c100] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 000002594598c100] ref P L0: 69.4%  1.5% 20.0%  9.1%
[libx264 @ 000002594598c100] ref B L0: 76.0% 20.2%  3.8%
[libx264 @ 000002594598c100] ref B L1: 91.1%  8.9%
[libx264 @ 000002594598c100] kb/s:651.42
Exiting normally, received signal 2.

and for path_to_ffmpeg.exe -i camera_stream_url test.jpg

PS C:\Users\Administrator> ffmpeg -rtsp_transport tcp -i rtsp://xxxx:xxxx@192.168.1.194/live/ch00_0.h264 test.jpg
ffmpeg version N-90649-g9825f77ac7 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enabl
e-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-
libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-l
ibtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --en
able-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-l
ibvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enabl
e-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 13.100 / 56. 13.100
  libavcodec     58. 17.100 / 58. 17.100
  libavformat    58. 11.101 / 58. 11.101
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 14.100 /  7. 14.100
  libswscale      5.  0.102 /  5.  0.102
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, rtsp, from 'rtsp://xxxx:xxxx@192.168.1.194/live/ch00_0.h264':
  Metadata:
    title           : Easy Rtsp 1.0
    comment         : Easy
  Duration: N/A, start: 0.201000, bitrate: N/A
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 1920x1080, 25 fps, 24.83 tbr, 90k tbn, 50 tbc
File 'test.jpg' already exists. Overwrite ? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0000021b1f3cb4c0] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'test.jpg':
  Metadata:
    title           : Easy Rtsp 1.0
    comment         : Easy
    encoder         : Lavf58.11.101
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 1920x1080, q=2-31, 200 kb/s, 24.83 fps, 24.83 tbn, 24.83 tbc
    Metadata:
      encoder         : Lavc58.17.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
[image2 @ 0000021b1d388980] Could not get frame filename number 2 from pattern 'test.jpg' (either set update or use a pa
ttern like %03d within the filename pattern)
av_interleaved_write_frame(): Invalid argument
frame=    2 fps=0.0 q=3.2 Lsize=N/A time=00:00:00.08 bitrate=N/A dup=0 drop=4 speed=0.286x
video:79kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

**Comment by Caribsky** [comment]
@senadman 
ffmpeg working, it's a fact. 

Do you run homebridge  as Administrator?
I can only guess that homebridge has no access to C:\Users\Administrator>ffmpeg.exe

ps.  I don't use Windows, so I can explain how to check this issue on macOS, linux or Synology (like TS)

**Comment by senadman** [comment]
Yes ffmpeg does work, and yes homebridge is used and installed as administrator.  This has baffled me for weeks now.

**Comment by Caribsky** [comment]
@senadman 
Try to define PATH to ffmpeg.exe into Environment Variables in System Settings of Windows
Then remove "videoProcessor" from config.json

**Comment by senadman** [comment]
@Caribsky

Path was set during the ffmpeg install process and it works. If it didn’t work then I wouldn’t be able to call ffmpeg in command line and get those outputs earlier. 

I’m wondering if there is an explicit entry that has to defined in one of the homebridge config files or the plugin itself. Maybe they are expecting ffmpeg to be in a certain location???

**Comment by Caribsky** [comment]
@senadman 
Just idea …
Copy ffmpeg.exe to root dir, for example C:\ffmpeg.exe
Add in config.json videoProcessor with '/' only

{
"platform": "Camera-ffmpeg",
"videoProcessor": "/ffmpeg",
"cameras": [
...
]
}

**Comment by senadman** [comment]
@Caribsky 

That works!! 

I have since discovered that there is a permissions issue with the ffmpeg folders, once users were granted full control it worked, but ONLY if "videoProcessor": "/ffmpeg", is included in config.json, just having the path in system variables doesnt resolve it to ffmpeg.exe. 

So,  in my case my path to ffmpeg is  C:\ffmpeg\bin\ffmpeg.exe and my config.json entry is "videoProcessor": "/ffmpeg/bin/ffmpeg".

Thankyou very much @Caribsky and i hope this helps others out as well.

Now, to get the snapshots to refresh and audio??

**Comment by Caribsky** [comment]
@senadman 
Good! You did it! :) 
Regarding snapshot.. if you can see a stream from cam and can't see snapshot, then try to reboot iOS device or do hard reset (Hold down the home and on/off buttons at the same time until you see logo). I saw this bug a few times. 

Ffmpeg must be compiled with support for the necessary audio codecs.  If yes, then needs to play with params.

**Comment by schmoofdie** [comment]
Hi guys,

I seem to be having the same issue but can't make sense of it. Forgive me for being quite the NOOB so I'm hoping one of you can help. I have installed ffmpeg and it resides inside the /usr/bin where I believe it should.

pi@raspberrypi:~ $ ffmpeg
ffmpeg version 3.2.10-1~deb9u1+rpt1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
pi@raspberrypi:~ $ 

I then installed the home bridge plugin using "npm install -g homebridge-camera-ffmpeg" and all installed successfully.

I have edited my config.json to the following (I have omitted my username, password & ip address)

{
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Front Camera",
                    "videoConfig": {
                        "source": "-re -i rtsp://user:password@ip:554/h264Preview_01_main",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 25,
                        "maxBitrate": 1000,
                        "audio": false
                    }
                }
            ]
        }

I can the go ahead and add the camera to the home app no worries but I get the camera icon with a line through it.

This then proceeds to crash the homebridge and it restarts until the camera is selected again. The error given in the homebridge logs is:

Error: spawn avconv ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Someone please help!

**Comment by senadman** [comment]
@schmoofdie 

I am no pro with linux, my problem was exactly the same as yours although windows, and it turned out to be that the ffmpeg path had to be set properly.

if you run "ffmpeg -re -i rtsp://user:password@ip:554/h264Preview_01_main" do you get an output??

What is your actual path to ffmpeg executable, is it something like /usr/bin/ffmpeg/ffmpeg??

Whatever the path is try and place that path into config.json like:

{
"platform": "Camera-ffmpeg",
"videoProcessor": "/usr/bin/ffmpeg/ffmpeg",
"cameras": [
{
"name": "Front Camera",
"videoConfig": {
"source": "-re -i rtsp://user:password@ip:554/h264Preview_01_main",
"maxStreams": 2,
"maxWidth": 1920,
"maxHeight": 1080,
"maxFPS": 25,
"maxBitrate": 1000,
"audio": false
}
}
]
}

**Comment by schmoofdie** [comment]
@senadman

Thanks for your response

This is the output I get after running "ffmpeg -re -i rtsp://user:password@ip:554/h264Preview_01_main" with my correct credentials

 
ffmpeg version 3.2.10-1~deb9u1+rpt1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, rtsp, from 'rtsp://admin:SecurityRiddell759@192.168.0.61:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 14.83 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
At least one output file must be specified

It seems it has access to ffmpeg and the correct path but I'm not sure what it means one output must be specified?

Thanks again

**Comment by senadman** [comment]
@schmoofdie 

try this 'ffmpeg -re -i rtsp://user:password@ip:554/h264Preview_01_main test.mp4'

**Comment by senadman** [comment]
Have you added the  videoprocessor path to config.json

**Comment by schmoofdie** [comment]
No I haven't added the video processor path as it is the default /usr/bin/ffmpeg.exe should I add it anyway?

**Comment by schmoofdie** [comment]
what should it be in my case?

**Comment by senadman** [comment]
Yes, the OS can see ffmpeg but the plugin can’t. Try ‘/usr/bin/ffmpeg’

**Comment by schmoofdie** [comment]
Ok so the plugin id no longer exposing the camera to homekit. Deleting and re-installing the plugin now

**Comment by senadman** [comment]
You might need to re-introduce the cameras into HomeKit again. If it complains you might need to delete the camera files in the homebridge/persist folder, there will be two for each camera, just don't delete the homebridge persist files, then add the cameras again as an accessory.

**Comment by schmoofdie** [comment]
Ok so I had to remove my homebridge from homekit in order to re expose the camera.

I re added the camera and updated the config.json as below

{
"platform": "Camera-ffmpeg",
"videoProcessor": "/usr/bin/ffmpeg/",
"cameras": [
{

and still no dice so then I tried

{
"platform": "Camera-ffmpeg",
"videoProcessor": "/usr/bin/ffmpeg/ffmpeg",
"cameras": [
{

again no dice so then tried

{
"platform": "Camera-ffmpeg",
"videoProcessor": "ffmpeg",
"cameras": [
{

and again all the same issues throwing the same error

Error: spawn /usr/bin/ffmpeg ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by schmoofdie** [comment]
well same error but it doesn't seem to matter what my videoProcessor directory is, the plugin can find ffmpeg.exe

**Comment by senadman** [comment]
Is ffmpeg executable directly in /usr/bin or in a folder inside /usr/bin. 
What if you copy the ffmpeg executable directly to root and set the path as /ffmpeg.

**Comment by schmoofdie** [comment]
ffmpeg lives in /usr/bin ill try moving it to the root

**Comment by schmoofdie** [comment]
Same error

Error: spawn /ffmpeg ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by schmoofdie** [comment]
a permission issue maybe?

**Comment by senadman** [comment]
I had problems with folder permissions so that would be something to look at certainly. 

So if ffmpeg lives in /usr/bin then the path would be ‘/usr/bin/ffmpeg’ I noticed you used ‘/usr/bin/ffmpeg/‘.

**Comment by schmoofdie** [comment]
yeah I've tried it with and without..... I think it may be because I have setup a different password on my raspberry pi other than the default. I think this might be the case as I even moved ffmpeg to my pi home folder and pointed the plugin to it and it still gave me the error.

Now to test

**Comment by schmoofdie** [comment]
Nope today is not the day I get this working :(

**Comment by Robiv8** [comment]
Hallo, i have the same error.
Raspi 2, Homebridge Version 0.4.42
Only Plugin ffmepg is installed and running. [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
after put the code in config.json i put the camera in Homekit (iPad App)
The homebridge.log says:
Hofkamera is running on port 35445.
[Camera-ffmpeg] Snapshot from Hofkamera at 480x270
after a few seconds homebridge crash
homebridge.err say:
Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)

Is there a fix or workaround?
Thanks Robi

**Comment by dust999** [comment]
```
//Configure YoutubeMp3Downloader with your settings
var YD = new YoutubeMp3Downloader({
    "ffmpegPath": "c:\\pathToProject\\ffmpeg\\ffmpeg.exe",        // Where is the FFmpeg binary located?
    "outputPath": "c:\\pathToProject\\mp3\\",    // Where should the downloaded and encoded files be stored?
    "youtubeVideoQuality": "highest",       // What video quality should be used?
    "queueParallelism": 2,                  // How many parallel downloads/encodes should be started?
    "progressTimeout": 1000                 // How long should be the interval of the progress reports
});
```
Helped to me

**Comment by brocoLee** [comment]
> @TURSTY,
> You need install ffmpeg package via docker's terminal.
> Example for Debian based docker:
> 
> echo 'deb http://ftp.uk.debian.org/debian jessie-backports main' >> /etc/apt/sources.list
> 
> apt-get update
> 
> apt-get -y install ffmpeg

muchas gracias, me funciono en homebridge basado en debian instalado docker.

**Comment by James712346** [comment]
If you are using oznu/homebridge:latest docker image he is running it on Alpine Linux, so to fix the error go to the Dockers terminal and input `apk add  --no-cache ffmpeg` to install ffmpeg

**Comment by ginfts** [comment]
Hi, another newbie here, trying to get a Reolink RLC422 camera to work with Homebridge. I keep getting the following errors in the logs and no video shows within Home.app.

I have removed the snapshot line within config as I have yet to work out what to replace the default info with. I am running Homebridge on a RaspberryPi4 with Buster Lite(?) 10, and Node.js v12.16.0, Npm Version v6.13.4 

Any suggestions where I might be going wrong? I have shown below my Config text and also the error log. TIA.

 _{
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Gate",
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:MYPASSWORDREDACTED@192.168.2.67:554//h264Preview_01_sub",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "copy",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }_

**}
[2/22/2020, 10:41:44] [Camera ffmpeg] Snapshot from Gate at 480x270
ffmpeg -re -i rtsp://admin:MYPASSWORDREDACTED@192.168.2.67:554//h264Preview_01_sub -t 1 -s 480x270 -f image2 -
[2/22/2020, 10:41:44] [Camera ffmpeg] An error occurs while making snapshot request
[2/22/2020, 10:41:44] [Camera ffmpeg] Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-re',
    '-i',
    'rtsp://admin:MYPASSWORDREDACTED@192.168.2.67:554//h264Preview_01_sub',
    '-t',
    '1',
    '-s',
    '480x270',
    '-f',
    'image2',
    '-'
  ]
}**
