### ISSUE TITLE
Why converting video if camera broadcast in h264?

### ISSUE THREAD

**Issue by iShift** [KhaosT/homebridge-camera-ffmpeg#161]
Hi, why we need convert video and launch ffmpeg if camera broadcast in h264? i use home kit camera version and original camera app - original app bring more clear image with no lag ...

**Comment by KhaosT** [comment]
Because HomeKit is really restrict on the stream’s format and bitrate. Just because both are “H.264” doesn’t mean the content encoded in there is interchangeable.
