### ISSUE TITLE
FFmpeg exited with code 1

### ISSUE THREAD

**Issue by Yardco** [KhaosT/homebridge-camera-ffmpeg#163]
Hello,

Once in a while the camera stream won’t start (keeps loading and eventually times out) and outputs the error: FFmpeg exited with code 1. 

What is this error code exactly and is there a way to prevent it from occurring?

**Comment by jeffl78** [comment]
I have this problem all the time

**Comment by peterlee0127** [comment]
I had the same problem too.
I find the log file. It seems like ffmpeg can't access the /dev/video0. It may happened by ffmpeg didn't release the previous session of /dev/video0.

I extract the command in the ffmpeg.js
`$ ffmpeg -re -f video4linux2 -i /dev/video0 -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 20 -f rawvideo -tune zerolatency -b:v 1500k -bufsize 1500k -payload_type 99 -ssrc 16132552 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params omz31e5SiZSneUySvSsIaFfu+NW2uWUl9+FHs3HD srtp://192.168.10.112:58536?rtcpport=58536&localrtcpport=58536&pkt_size=1316`

<code>0|homebrid | /dev/video0: Input/output error
0|homebrid | [2018-3-24 22:28:22] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

0|homebrid | [video4linux2,v4l2 @ 0x1ef2740] Cannot open video device /dev/video0: No such file or directory
0|homebrid | /dev/video0: No such file or directory
0|homebrid | [2018-3-24 22:28:35] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

0|homebrid | [video4linux2,v4l2 @ 0x2294740]
0|homebrid | Cannot open video device /dev/video0: Device or resource busy
0|homebrid | /dev/video0: Device or resource busy
0|homebrid | [2018-3-24 22:29:07] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1</code>

**Comment by Yardco** [comment]
So, ffmpeg functions as should most of the time, and occasionally cant access the folder, resulting in the code 1 error. Is it save to presume that this has something to do with the filesystem/harddrive then? 

(Im using a raspberry pi so would a faster sdcard for example prevent this error?)

**Comment by peterlee0127** [comment]
I think it is the RPI kernel problem or ffmpeg.
And /dev/video0 is usb camera or RPI CSI camera module. It is not a folder. So, change sd card won’t work.
But I also change other build of ffmpeg, it still not work too. 
1: change some kernel options may work
2: Modify the ffmpeg.js to handle exit 1, like auto retry again.

**Comment by peterlee0127** [comment]
I have a workaround for this issue. You can try it.
This moody will ensure previous ffmpeg session will be killed. 

```
//in near 232 node_modules/homebridge-camera-ffmpeg/ffmpeg.js

const killffmpeg = spawn('killall', ['ffmpeg']);

  killffmpeg.stdout.on('data', (data) => {
	console.log(`stdout: ${data}`);
  });

  killffmpeg.stderr.on('data', (data) => {
	console.log(`stderr: ${data}`);
  });

  killffmpeg.on('close', (code) => {
	console.log(`child process exited with code ${code}`);
	 callback(response);
  });

```

**Comment by Gamer106** [comment]
I'm receiving this same error. I tried both the downloaded, apt-get, and compiled versions of FFmpeg. I also changed from a Pi B+ to a Pi 3 to see if it were the processor, but am still getting the error when trying to stream the video. Snapshots work great.

**Comment by Veldkornet** [comment]
On my RaspberryPi, I was only able to get it working with the ffmpeg version mentioned here  https://github.com/legotheboss/homebridge-camera-ffmpeg-omx/blob/master/README.md

**Comment by cogidoo** [comment]
I have the same problem on my rPI zero. If debugging output is disabled (meaning, there is no `debug: true` at the config.json), my stream is interrupted after roundabout 5 minutes. At the iOS device within homekit the camera does not response anymore and short after this, the iOS device will go to sleep. 
But at my rPI there is still a ffmpeg-process which is blocking `/dev/video0`. So there is no chance, that I will get another stream at homekit on my iOS device.
```
$ fuser /dev/video0
/dev/video0:          1484m

$ ps aux | grep 1484
cogidoo   1484  4.6 13.5 124628 51520 ?        Sl   13:33   0:28 ffmpeg -re -f video4linux2 -i /dev/video0 -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -b:v 300k -bufsize 300k -payload_type 99 -ssrc 11712016 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params uNkXcKGMDXWUP6tdpaDgbsyCkZXM06hSHmA/EyLg srtp://192.168.178.39:62109?rtcpport=62109&localrtcpport=62109&pkt_size=1316

If I kill the process then I can start a new stream.

But there is a strange thing: with enabled debugging output (`debug: true`) I can't reproduce the error.. The stream will not get interrupted. So this could be something with ffmpeg and the on-data-callback on stderr ?

**Comment by llemtt** [comment]
I have to add that using v4l2 if there's no input from /dev/videoX, ffmpeg blocks reading and doesn't exit.

If the above happens during the snapshot request, then there's no code in place to eventually kill that ffmpeg instance, and trying to start another one returns the "resource busy" error.
