### ISSUE TITLE
Latest version issue

### ISSUE THREAD

**Issue by sfeakes** [KhaosT/homebridge-camera-ffmpeg#169]
I have two implementations of homebridge-camera-ffmpeg, os & ffmpeg are same versions, only node / Homebridge &  homebridge-camera-ffmpeg differ.
The old version works perfectly, and the new fails on video playback.  The only difference I can see is ffmpeg is called with different arguments on the later version.  I have pointed both versions to the same camera to take out any stream differences. Here are the two process that get executed.

```
OLD Version (Works perfectly)
ffmpeg -rtsp_transport tcp -re -i rtsp://192.168.144.108:7447/5ab7dd43abce73763c47f321_1 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params WkGL6PXs9DbBlRaO4G/e5cYsBTWO8QCvvxZxHxMv srtp://192.168.144.90:62739?rtcpport=62739&localrtcpport=62739&pkt_size=1378
```
```
NEW Version (Fails on video)
ffmpeg -rtsp_transport tcp -re -i rtsp://192.168.144.108:7447/5ab7dd43abce73763c47f320_1 -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 15 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 11657086 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params YH1EqyLsQ9Fw6ygrGSEovrgwk9cguWior1dCqI29 srtp://192.168.144.46:54516?rtcpport=54516&localrtcpport=54516&pkt_size=1316
```

```
New version has these options
-map 0:0
-ssrc 11657086
-an
and drops this option.
-threads 0
```
(I cannot seem to find much information on any of those options, so not sure what they do. But I did try to add -threads 0 in the config of the new version and that didn't work)
 
Also note both were viewed from the same iPhone, and in the example the working streams directly to the phone, and the broken example streams to the AppleTV (that acts as the hub).  But those don't seem to matter, it seems very hit n miss as to where the ffmpeg stream get's directed.

**Comment by sfeakes** [comment]
Update.  Not sure on the correct place to read the versions, But going by package.js the old version I am using is 0.1.0, the new version is 0.1.8.
I modified 0.1.8 to use the ffmpeg options from the 0.1.0 version and that didn't work. So I replaced the whole 0.1.8 version with 0.1.0 version, and now everything is up an running as it should be.

**Comment by sfeakes** [comment]
It’s going to be a pain to track that down, since I’m sure you can’t replicate. I’ll do some more playing when I get chance and see if I can figure out what’s causing it.

**Comment by chrispi68** [comment]
On my installation the streaming ist not working. Params:

ffmpeg -re -i rtsp://192.168.1.42:7447/59d8f7f67542cb1515d91a29_1 -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 4572179 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 36Hin1E2iqplXZFneVq52qUSiY0WZ3xt7Wva6Nuh srtp://192.168.1.219:51733?rtcpport=51733&localrtcpport=51733&pkt_size=1316

Possible cause: srtp://192.168.1.219

The IP address of my Ubuntu 18.04 is 192.168.1.22. 192.168.1.219 is not existing and i do not know where this comes from.
