### ISSUE TITLE
VideoConfig help

### ISSUE THREAD

**Issue by nerve007** [KhaosT/homebridge-camera-ffmpeg#17]
I'm still really green in this whole thing (my background is more in electronics hardware design than anything software), though I have managed to get ubuntu installed as well as getting homebridge running stably with a number of plug-ins, including harmonyhub, nest, and wemo.  

Where I'm at now, I feel a little out of my element trying to get the camera-ffmpeg configured.  I'm pretty sure I have all the required software installed, and I was able to add the camera within the Home app, but I am completely certain that I have gone astray in my configuration.  

The specific area of concern for me is the "source" field in the VideoConfig.  I'm assuming since I'm using a webcam plugged into the same machine that is running homebridge (the same machine as has ffmpeg), I can use the IP address of that machine.  I also understand that I may need to have my username and password ahead of that as well. Beyond that, I'm completely stumped as to what to enter.  I'm pretty sure it's the port followed by something else.  How/Where do I find/set these parameters? (I feel pretty silly asking since it seems pretty common knowledge around here, it's just something I've never previously been exposed to)

Thanks for any help you guys can toss my way.

**Comment by KhaosT** [comment]
Would you mind to share a little bit more about your camera setup so I can help? In general, you might be able to figure out the parameter for camera from [ffmpeg wiki](https://trac.ffmpeg.org/wiki/Capture/Webcam). For your case I guess you can focus on Linux section with v4l2.

**Comment by nerve007** [comment]
Camera setup is just a Microsft Lifecam HD 3000.  I'm just confused as to which port etc. to put in my config.

**Comment by nerve007** [comment]
This is the field from the config I'm having trouble with:
`"source": "-re -i rtsp://[username]:[password]@192.168.0.15",`

**Comment by KhaosT** [comment]
The example I had is for remote camera. If the camera is plugged directly to the machine, you may want to try first run ``ffmpeg -f v4l2 -list_formats all -i /dev/video0`` in terminal and see what are supported resolution and then in the source put something like ``-re -f v4l2 -framerate 30 -video_size your_resolution -i /dev/video0``

**Comment by nerve007** [comment]
it says I need to specify an output file, something I'm not sure how to do. (my inexperience is showing)

**Comment by KhaosT** [comment]
can you post a screenshot?

**Comment by nerve007** [comment]
![screenshot from 2016-11-11 00-41-17](https://cloud.githubusercontent.com/assets/23200149/20207887/9878661a-a7a7-11e6-9950-363a72fac6d8.png)

**Comment by KhaosT** [comment]
so you got the right resolution. now you just need to put ``-re -f v4l2 -framerate 30 -video_size 1280x720 -i /dev/video0`` as the ``source`` in config file.

**Comment by nerve007** [comment]
well, that did it!  Thanks for the quick response and help.

**Comment by KhaosT** [comment]
:)
