### ISSUE TITLE
Xiaofang makes homebridge crash / doesn't work

### ISSUE THREAD

**Issue by Hohnjo** [KhaosT/homebridge-camera-ffmpeg#175]
Hi there ! I've managed to hack my xiaofang (with Mac adress 34..) and add it to home app but it doesn't get the video and makes homebridge crash :/ The camera works with vlc in rtsp mode.

I've copied the config of this link and have replaced the 2 ip adress : 
https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Tested-Configuration#xiaomi-xiaofang-small-white-square-with-raspberry-pi-3-model-b

**Comment by Brklnbnc** [comment]
Same here.. Homebridge 0.4.22 and Xiaofang camera Mac address starting with 34.

**Comment by werthdavid** [comment]
Log would be helpful
