### ISSUE TITLE
Cannot open video device /dev/video0: No such file or directory

### ISSUE THREAD

**Issue by raaffq** [KhaosT/homebridge-camera-ffmpeg#177]
ffmpeg [video4linux2,v4l2 @ 0x8cb5d0] Cannot open video device /dev/video0: No such file or directory

any idea how to fix it?

thanks

**Comment by georgo** [comment]
Your camera is probably not /dev/video0 or user don't have access.
Can you post, what camera you have and post listing of your /dev folder ?

**Comment by tgerring** [comment]
Try to add the user to the video group. For example, if you created a user called "homebridge" to run under, the command would look like this on Debian:
```
sudo usermod -a -G video homebridge
```

This resolve as similar error for me.

**Comment by pabloab** [comment]
I added myself to video group (`sudo adduser $USER video`), but was the case @georgo mentioned, is not listed on `/dev/video0` (`v4l2-ctl --list-devices` return `Cannot open device /dev/video0, exiting.`), but is listed with `lsusb` and could see its metadata with `lsusb -v -d 1bcf:idProduct | less` (`Sunplus Innovation Technology Inc. WebCamera`). 

No sure if adding to video group had something to do, but a reboot fixes the issue. Before I was getting some `kernel: BPF: Invalid name` errors (`journalctl -xef` when plugging) and now instead `usb 1-4: 3:1: cannot get freq ..`, but at least it's working.
