### ISSUE TITLE
Platform not registered by any plug-in

### ISSUE THREAD

**Issue by HunterJKirby** [KhaosT/homebridge-camera-ffmpeg#180]
Hello, I installed the plug in and validated my json file but yet I’m getting this error “the requested platform ‘Camera-ffmpeg’ was not registered by any plugin.”  Any advice? My package.json is set up exactly like the one in the readme

**Comment by werthdavid** [comment]
@Skydoggg did you install the plugin globally? 
Use `sudo npm install -g homebridge-camera-ffmpeg` and then restart the bridge
