### ISSUE TITLE
More than one Cameraa

### ISSUE THREAD

**Issue by arlettazm** [KhaosT/homebridge-camera-ffmpeg#186]
Hi,
I try to add more than one cam. 
But without success?
What i need to do?
Thanks for your support
Best regards
Matthieu

**Comment by bluntiless** [comment]
Hi,
What type of cameras do you have. Are they all the same type?

**Comment by fanlessfan** [comment]
I want to add two rtsp camera like below, but only the last one show up in homekit. Is the syntax correct?

                "platform": "Camera-ffmpeg",
                "cameras": [{
                        "name": "AntCam01",
                        "videoConfig": {
                                "source": "-re -i rtsp://AntCam01:554/ch0_0.h264",
                                "maxStreams": 2,
                                "maxWidth": 1280,
                                "maxHeight": 720,
                                "maxFPS": 30,
                                "vcodec":"h264_omx"
                        }
                }],
                "cameras": [{
                        "name": "AntCam02",
                        "videoConfig": {
                                "source": "-re -i rtsp://AntCam02:554/ch0_0.h264",
                                "maxStreams": 2,
                                "maxWidth": 1280,
                                "maxHeight": 720,
                                "maxFPS": 30,
                                "vcodec":"h264_omx"
                        }
                }]

**Comment by llemtt** [comment]
Have you paired the two cameras?

**Comment by fanlessfan** [comment]
No. They don’t show up in the home app

**Comment by llemtt** [comment]
Do you mean that you tried to add them (with + button) and they don't show up?

**Comment by fanlessfan** [comment]
Thanks @llemtt  I think I forget to delete the persistence data. I can add all of them now.
