### ISSUE TITLE
Stream only plays for 3-4 seconds

### ISSUE THREAD

**Issue by P1xellat3d** [KhaosT/homebridge-camera-ffmpeg#187]
I seem to be having trouble maintaining a steady video stream. This is my config (using a XiaoMi XiaoFang camera with Fang-Hacks enabled):

{{
>             "platform": "Camera-ffmpeg",
>             "cameras": [
>                 {
>                     "name": "XiaoFang",
>                     "videoConfig": {
>                         "source": "-rtsp_transport tcp -i rtsp://192.168.1.27/unicast",
>                         "stillImageSource": "-i rtsp://192.168.1.27/unicast -vframes 1 -r 1"
>                     }
>                 }
>             ]
>         }

The video would play for around 4 seconds before it freezes and no longer responds.

Without defining the resolution, bitrate and FPS, the plugin automatically sets it to 1280x720@299kBit. I have tried limiting or reducing the resolution but the same problem persists.

Does anyone have any ideas at all?

**Comment by rlambrecht** [comment]
I have the same issue. RTSP streaming from the camera directly works. Once the stream is added to this plugin, only a few seconds work and then it freezes up. I've also tested this on a different computers with varying CPU sizes to see if it was a transcoding resource issue, it is not.

**Comment by mrdc** [comment]
The same issue as #243
