### ISSUE TITLE
1 Foscam Streams, 1 Does not

### ISSUE THREAD

**Issue by JDogg016** [KhaosT/homebridge-camera-ffmpeg#188]
So I have a Foscam R2 and Foscam FI9803P.

For the R2 I have the following in the config.json

  {
                    "name": "Jonathan",
                    "videoConfig": {
                        "source": "-re -i rtsp://xxxx:xxxx@xx:88/videoMain",
                        "stillImageSource": "-i http://xxxx:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=xxxx&pwd=xxxx&",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10
                    }

This config streams just fine.

However, the Foscam FI9803P has the same setup and has the error "FFMPEG exited Code 1"

The specific log is:

![image](https://user-images.githubusercontent.com/20018778/40311701-a4ab7308-5cde-11e8-808a-2da248a4e26d.png)

I've read where this issue may arise where the resolutions of the cameras are not the same.

Does this mean within Foscam, config.json? Could 'Code 1' mean something else.

**Comment by toshibochan** [comment]
Try maxFPS to 30

**Comment by henkied** [comment]
I have the same problem. Until last week it worked fine now this error message. strange is that 2 of the 3 cameras (Foscam) work fine

**Comment by javierivi** [comment]
I have the same problems with my foscam 9804W.
