### ISSUE TITLE
Snapshot size

### ISSUE THREAD

**Issue by OlehProkopenko** [KhaosT/homebridge-camera-ffmpeg#190]
I've got Xiaomi xiaofang cam, connected to synology and homebridge. I don't care about video but snapshots are taken in 480x270. Is it possible to get better resolution snapshots?

**Comment by pax0707** [comment]
Also interested in this.

**Comment by bluntiless** [comment]
Me too!

**Comment by NorthernMan54** [comment]
The snapshot size comes as part of the snapshot request from Apple HomeKit, and not within our ability to control
