### ISSUE TITLE
How to customize ffmpeg command line - tune error

### ISSUE THREAD

**Issue by ccaramel** [KhaosT/homebridge-camera-ffmpeg#192]
It is explained in #165 that is possible to pass a command line in ffmpeg.
I got tune option error

 ```
Unrecognized option 'tune'.
Error splitting the argument list: Option not found
```
Can someone tell me how to customize default ffmpeg command line used by plugin?
Regards

**Comment by ccaramel** [comment]
I solved "tune" problem by using another version of ffmpeg (cf #85), but I plan to install on other arch (arm64), thus it probably will not work in the future.

Nevertheless, live streaming still not working (only snapshots are working), here one can see debug output:

`ffmpeg -i http://admin:xxxxxxxxx@192.168.0.13/cgi-bin/image.jpg?size=[1280]x[720]&noaudio -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 100k -bufsize 100k -payload_type 99 -ssrc 3242239 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params APW0fDSgr+phOwRSE6z5DDRd/LkVsYj39h0e1QRh srtp://192.168.0.25:62421?rtcpport=62421&localrtcpport=62421&pkt_size=1316
ffmpeg version N-81800-gf013ba4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-omx --enable-omx-rpi
  libavutil      55. 30.100 / 55. 30.100
  libavcodec     57. 58.103 / 57. 58.103
  libavformat    57. 51.100 / 57. 51.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 63.100 /  6. 63.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100

Input #0, jpeg_pipe, from 'http://admin:xxxxxxxx@192.168.0.13/cgi-bin/image.jpg?size=[1280]x[720]&noaudio':

  Duration: 
N/A
, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 640x240 [SAR 1:1 DAR 8:3], 25 tbr, 25 tbn, 25 tbc

[swscaler @ 0x23cd740] 
deprecated pixel format used, make sure you did set range correctly

[libx264 @ 0x23c0a10] 
VBV maxrate unspecified, assuming CBR

[libx264 @ 0x23c0a10] 
using SAR=3/2

[libx264 @ 0x23c0a10] 
using cpu capabilities: ARMv6 NEON

[libx264 @ 0x23c0a10] 
profile High, level 3.1

Output #0, rtp, to 'srtp://192.168.0.25:62421?rtcpport=62421&localrtcpport=62421&pkt_size=1316':

  Metadata:
    encoder         : Lavf57.51.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720 [SAR 3:2 DAR 8:3], q=-1--1, 100 kb/s, 10 fps, 90k tbn, 10 tbc
    Metadata:
      encoder         : Lavc57.58.103 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/100000 buffer size: 100000 vbv_delay: -1
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
Press [q] to stop, [?] for help

frame=    1 fps=0.0 q=52.0 size=       5kB time=00:00:00.00 bitrate=3454545.5kbits/s speed=1.82e-05x    
frame=    1 fps=0.0 q=52.0 Lsize=       5kB time=00:00:00.00 bitrate=3454545.5kbits/s speed=1.81e-05x    
video:5kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.800257%

[libx264 @ 0x23c0a10] frame I:1     Avg QP:50.10  size:  4666
[libx264 @ 0x23c0a10] mb I  I16..4: 23.6% 76.4%  0.0%
[libx264 @ 0x23c0a10] 8x8 transform intra:76.4%
[libx264 @ 0x23c0a10] coded y,uvDC,uvAC intra: 9.3% 29.2% 0.4%
[libx264 @ 0x23c0a10] i16 v,h,dc,p: 29% 53%  7% 11%
[libx264 @ 0x23c0a10] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 49%  7% 39%  1%  1%  1%  1%  0%  1%
[libx264 @ 0x23c0a10] i8c dc,h,v,p: 97%  1%  2%  0%
[libx264 @ 0x23c0a10] kb/s:373.28

[2018-6-19 16:25:32] [Camera-ffmpeg] Stopped streaming`

Any idea?
regards.

**Comment by AmauryVela** [comment]
I have the same problem on raspberry pi :(

**Comment by neutmute** [comment]
Use the `additionalCommandline` option under `videoConfig` and that stops `tune` option being passed in
eg:

`"additionalCommandline": "-loglevel info"`
