### ISSUE TITLE
Working great when ran manually but not when ran as service?

### ISSUE THREAD

**Issue by HighMasterGogo** [KhaosT/homebridge-camera-ffmpeg#193]
There's a very good chance this is something I've missed or done wrong but I can get everything working great if I run `homebridge` as user `pi`- I get an RTSP connection to my pi cam on my pi zero and I can view it in the home app.

However, I have homebridge setup to run as a service using `systemd` but when I do this, I can't view the camera in the home app.

Homebridge logs show the connection to the camera as does the logs on the pi.

I'm running `raspivid -o - -t 0 -w 1280-h 720 -fps 30 -b 250000 | cvlc -vvv stream:///dev/stdin --sout '#rtp{access=udp,sdp=rtsp$` on the pi zero to initiate a rtsp stream using vlc.

The only thing I've noticed is when I run as a service, view `top` and open the camera on the home app, I see FFMPEG appear for a few seconds and then it goes again. This is leading me to think it's permissions for running FFMPEG or similar?

Sorry for my massive lack of knowledge here, I am very much a noobie with this!

**Comment by georgo** [comment]
Try enable `debug`: true in your camera `videoConfig` and you will see, what is happening in log (e.g. `journalctl -f -u homebridge` if you're running homebridge as homebridge user)
