### ISSUE TITLE
Axis Camera Exited with Code 1

### ISSUE THREAD

**Issue by rennsport** [KhaosT/homebridge-camera-ffmpeg#194]
Hi guys,

I'm trying to use this plug-in with my Axis P3367, and I based my config file off of [this example](https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Tested-Configurations#configjson-25) in the Wiki. While the snapshot feature works perfectly, the video stream feature crashes and says `[Camera-FFmpeg] ERROR: FFmpeg exited with code 1`.

So I'm wondering what I'm doing wrong. Here is the camera-FFmpeg section from my config.json:
```
        {
          "platform": "Camera-ffmpeg",
          "cameras": [
            {
              "name": "Front Door",
              "videoConfig": {
                "source": "-rtsp_transport tcp -i rtsp://username:password@10.10.10.25:554/axis-media/media.amp?streamprofile=Media?tcp",
                "stillImageSource": "-i http://username:password@10.10.10.25/axis-cgi/jpg/image.cgi",
                "maxStreams": 3,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 12,
                "vcodec":"h264_omx"
              }
            }
          ]
        }
```
I've also installed all the dependancies for FFmpeg (or so I believe).

Thanks in advanced

Edit: Just to give some more info, I've tried this on macOS and Linux (Raspberry Pi). I also know my rtsp link works fine so that couldn't be the issue either.

**Comment by WDPX** [comment]
I see the same thing, here. :(

**Comment by henkied** [comment]
same here :(

**Comment by toshibochan** [comment]
Same here with q-see DVR

**Comment by chriscrowe** [comment]
This is happening to me too with a different hardware setup:

* Wyzecam v2 running Dafang-Hacks firmware (https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks)
    * Instructions for Homekit setup here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homekit/homekit.md
* Synology DS918 running Homebridge in Docker (https://github.com/oznu/homebridge-syno-spk)

The single snapshot on the preview tile in the Home app works fine, but when I tap it to view the live feed it fails. Snippet from the log of seeing the single frame + the attempt to stream:

```
[2018-6-23 21:14:05] [Camera-ffmpeg] Snapshot from Wyze1 at 480x270
[2018-6-23 21:14:07] [Camera-ffmpeg] Start streaming video from Wyze1 with 1280x720@299kBit
[2018-6-23 21:14:09] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1
```

Here's what my config looks like:

```json
{
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Wyze1",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://user:pass@192.168.1.100:8554/unicast",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://user:pass@192.168.1.100:8554/unicast -vframes 1 -r 1",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 25,
                        "vcodec": "h264_omx"
                    }
                }
            ]
        }
```

The same RTSP stream works fine in Synology Surveillance Station, so the camera/feed seem to be fine.

**Comment by chriscrowe** [comment]
After lots of tinkering I found the issue-- the `h264_omx` encoder is not valid (at least for this ffmpeg install) -- I had use regular `h264`:

```json
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Wyze1",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://user:pass@192.168.1.100:8554/unicast",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://root:ismart12@192.168.1.100:8554/unicast -vframes 1 -r 1",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 25,
                        "vcodec": "h264"
                    }
                }
            ]
```

**Comment by rennsport** [comment]
@chriscrowe thank so much that solved my issue entirely!

**Comment by iRayanKhan** [comment]
@rennsport Is your thing still working?

**Comment by rennsport** [comment]
@iRayanKhan yeah my axis cameras are still working with the video codec h264.

**Comment by iRayanKhan** [comment]
#220

**Comment by burnbrigther** [comment]
@rennsport I am still struggling to get my Axis 3343 to output to home.   Did your camera appear as in the add accessory section?  Been trying to get it to work.

**Comment by rennsport** [comment]
@burnbrigther If I recall correctly, they did appear in the add accessory section after the HomeBridge itself was added to my Home.
