### ISSUE TITLE
Rotate 180degrees

### ISSUE THREAD

**Issue by jheras1989** [KhaosT/homebridge-camera-ffmpeg#198]
Is possible to rotate image 180 degrees? Thanks! =)

**Comment by Dirk23** [comment]
I would be happy to have a option for that, too!

**Comment by Prouser123** [comment]
You could try adding ```-vf "transpose=2,transpose=2"``` to the source line as shown:

```"source": "-f v4l2 -r 30 -s 320x240 -i -vf "transpose=2,transpose=2" /dev/video0",```

**Comment by thymjan** [comment]
There seems to be a problem with the quotation marks ...

**Comment by jeanlars** [comment]
I added the following to config:
`"videoFilter": "rotate=PI/2",` for 90 degree clockwise rotation.
For 180 degree clockwise rotation it should look like:
`"videoFilter": "rotate=PI",`


Description and examples can be found at [https://www.ffmpeg.org/ffmpeg-filters.html#rotate](url)
