### ISSUE TITLE
What to use for stream settings when using ffmpeg on macbook isight camera?

### ISSUE THREAD

**Issue by tommyd75** [KhaosT/homebridge-camera-ffmpeg#2]
I've got it running and I was able to add the camera to my iOS device but when I touch the black window to see the camera it crashes, I assume because I don't the the proper stream in the config.
"source": "-re -i rtsp://myfancy_rtsp_stream", <-----WHAT SHOULD I USE HERE?

I already installed FFMPEG on my macbook.

**Comment by danielsen2009** [comment]
Having the same issue here, using rtsp://IPADDRESS:PORT/unicast on raspberry pi using  h264_v4l2_rtspserver. its saying unhanded error. Is this plugin looking for ffmpeg specifically or just an rtsp stream?

**Comment by KhaosT** [comment]
It uses ffmpeg to fetch the stream and forward it to iOS device. If it doesn't work, try to first use ffplay on the device and see if that can play the stream…

**Comment by tommyd75** [comment]
I assume we need ffmpeg installed on the Hombridge machine (raspberry Pi)?

**Comment by KhaosT** [comment]
@tommyd75 Yep, you may be able to find pre-compiled deb online. Or follow this to compile ffmpeg directly (http://www.jeffreythompson.org/blog/2014/11/13/installing-ffmpeg-for-raspberry-pi/)

**Comment by tommyd75** [comment]
Quick question,
Does the local rtsp link get forwarded to iOS through iCloud?
So I don't have to open ports right?
Do you know of any public demo type rtsp streams I could use to test with?

**Comment by KhaosT** [comment]
@tommyd75 Apple TV (4th Gen) will forward the stream for remote access. There is no need for you to do anything.
Not sure about public rtsp stream.

**Comment by tommyd75** [comment]
Thank you.

**Comment by tommyd75** [comment]
OK, so I was able to follow the link above to compile ffmpeg on the Pi3 and now I am using a local rtsp stream and I get this when I try to open the video window. I see the link I have put in the config file below and I have included the username and password but obviously removed it here. I tried that link with the user name and password on VLC on the iPhone and it shows live video on the phone.


[9/28/2016, 12:29:23 AM] Homebridge is running on port 51826.
[9/28/2016, 12:29:23 AM] Doorbell is running on port 35039.
-re -i rtsp://username:password@192.168.1.100:8557/mpeg/media.amp  -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params XQEkrYQshk9FUYh5fHfQ3GF87MJzgC2VZeso9Ee4 srtp://192.168.1.112:56865?rtcpport=56865&localrtcpport=56865&pkt_size=1378

But when I click on the window on the iOS app it just opens the window and shows a black screen with the spinning wheel but never shows any picture or video. It doesn't crash the server ether. Tried changing the max fps on the config to 1 instead of 30 but no luck, any ideas?

**Comment by KhaosT** [comment]
@tommyd75 can you try running ``ffmpeg -re -i rtsp://username:password@192.168.1.100:8557/mpeg/media.amp -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params XQEkrYQshk9FUYh5fHfQ3GF87MJzgC2VZeso9Ee4 "srtp://192.168.1.112:56865?rtcpport=56865&localrtcpport=56865&pkt_size=1378"`` in terminal and see what's the output?

**Comment by tommyd75** [comment]
It just sits there with flashing cursor like on the Pi server. No errors

**Comment by KhaosT** [comment]
@tommyd75 that's not right, it should print out a lot of stuff...

**Comment by tommyd75** [comment]
I followed the link above to install FFMPEG and when I type in ffmpeg in terminal I get this.....


pi@raspberrypi:~ $ ffmpeg
ffmpeg version N-81831-g97e7f03 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
  libavutil      55. 32.100 / 55. 32.100
  libavcodec     57. 60.101 / 57. 60.101
  libavformat    57. 51.102 / 57. 51.102
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 63.100 /  6. 63.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

**Comment by KhaosT** [comment]
That looks good, now what happens if you run the command above?

**Comment by tommyd75** [comment]
nothing, it just sits there and doesn't crash and I open the Home app and go to the camera and it shows a black screen and just spins.

**Comment by tommyd75** [comment]
I did notice this when I installed the plugin. 


pi@raspberrypi:~ $ sudo npm install -g homebridge-camera-ffmpeg

WARN engine homebridge-camera-ffmpeg@0.0.2: wanted: {"node":">=5.0.0","homebridge":">=0.4.5"} (current: {"node":"4.3.2","npm":"2.14.12"})
homebridge-camera-ffmpeg@0.0.2 /usr/local/lib/node_modules/homebridge-camera-ffmpeg
└── ip@1.1.3

**Comment by tommyd75** [comment]
OK, now I am getting something when i manually run this.





pi@raspberrypi:~ $ ffmpeg -re -i rtsp://user:password@10.10.10.19:8557/mpeg/media.amp -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params XQEkrYQshk9FUYh5fHfQ3GF87MJzgC2VZeso9Ee4 "srtp://10.10.10.212:56865?rtcpport=56865&localrtcpport=56865&pkt_size=1378"
ffmpeg version N-81831-g97e7f03 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
  libavutil      55. 32.100 / 55. 32.100
  libavcodec     57. 60.101 / 57. 60.101
  libavformat    57. 51.102 / 57. 51.102
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 63.100 /  6. 63.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100
[rtsp @ 0x1ed0400] method SETUP failed: 453 Not Enough Bandwidth
rtsp://user:password@10.10.10.19:8557/mpeg/media.amp: Server returned 4XX Client Error, but not one of 40{0,1,3,4}

**Comment by KhaosT** [comment]
@tommyd75 your camera response a 453 error. I'd suggest you contact your camera manufacturer and ask why it's doing that.

**Comment by tommyd75** [comment]
ok, I also tried an external rtsp stream and I get video just spinning wheel but it seems like its doing something. But no video ?


pi@raspberrypi:~ $ ffmpeg -re -i rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params XQEkrYQshk9FUYh5fHfQ3GF87MJzgC2VZeso9Ee4 "srtp://10.10.10.212:56865?rtcpport=56865&localrtcpport=56865&pkt_size=1378"
ffmpeg version N-81831-g97e7f03 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
  libavutil      55. 32.100 / 55. 32.100
  libavcodec     57. 60.101 / 57. 60.101
  libavformat    57. 51.102 / 57. 51.102
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 63.100 /  6. 63.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, rtsp, from 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov':
  Metadata:
    title           : BigBuckBunny_115k.mov
  Duration: 00:09:56.48, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 12000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (Constrained Baseline), yuv420p, 240x160, 24 fps, 24 tbr, 90k tbn, 48 tbc
[libx264 @ 0x2cfdd90] VBV maxrate unspecified, assuming CBR
[libx264 @ 0x2cfdd90] using cpu capabilities: ARMv6 NEON
[libx264 @ 0x2cfdd90] profile High, level 3.1
Output #0, rtp, to 'srtp://10.10.10.212:56865?rtcpport=56865&localrtcpport=56865&pkt_size=1378':
  Metadata:
    title           : BigBuckBunny_115k.mov
    encoder         : Lavf57.51.102
    Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720, q=-1--1, 299 kb/s, 30 fps, 90k tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.60.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/299000 buffer size: 299000 vbv_delay: -1
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> h264 (libx264))
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=BigBuckBunny_115k.mov
c=IN IP4 10.10.10.212
t=0 0
a=tool:libavformat 57.51.102
m=video 56865 RTP/AVP 99
b=AS:299
a=rtpmap:99 H264/90000
a=fmtp:99 packetization-mode=1
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:XQEkrYQshk9FUYh5fHfQ3GF87MJzgC2VZeso9Ee4

Press [q] to stop, [?] for help
Past duration 0.749992 too large       2kB time=00:00:00.26 bitrate=  58.6kbits/s dup=8 drop=0 speed=0.373x    
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 322.3kbits/s dup=24 drop=5 speed=0.274x    
[rtsp @ 0x2c8e400] RTP: missed 31 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 2 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 6 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 316.3kbits/s dup=25 drop=5 speed=0.277x    
[rtsp @ 0x2c8e400] RTP: missed 6 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 277.3kbits/s dup=60 drop=5 speed=0.316x    
[rtsp @ 0x2c8e400] RTP: missed 10 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 6 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 282.2kbits/s dup=81 drop=5 speed=0.331x    
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 7 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 7 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 2 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 6 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 6 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 3 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 249.2kbits/s dup=184 drop=5 speed=0.397x    
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 257.4kbits/s dup=197 drop=5 speed=0.394x    
[rtsp @ 0x2c8e400] RTP: missed 6 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 3 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 2 packets
[h264 @ 0x2d3ec80] Invalid level prefix
[h264 @ 0x2d3ec80] error while decoding MB 10 2
[h264 @ 0x2d3ec80] concealing 150 DC, 150 AC, 150 MV errors in I frame
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 262.2kbits/s dup=217 drop=5 speed=0.401x    
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 262.2kbits/s dup=225 drop=5 speed=0.402x    
[rtsp @ 0x2c8e400] RTP: missed 2 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 2 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 262.6kbits/s dup=231 drop=5 speed=0.401x    
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 4 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 262.7kbits/s dup=236 drop=5 speed=0.404x    
[rtsp @ 0x2c8e400] RTP: missed 2 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 13 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 263.2kbits/s dup=244 drop=5 speed=0.402x    
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 2 packets
[h264 @ 0x2cfb440] Invalid level prefix
[h264 @ 0x2cfb440] error while decoding MB 0 1
[h264 @ 0x2cfb440] concealing 150 DC, 150 AC, 150 MV errors in I frame
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 1 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packet
[rtsp @ 0x2c8e400] RTP: missed 2 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 267.5kbits/s dup=292 drop=5 speed=0.412x    
[rtsp @ 0x2c8e400] RTP: missed 138 packets
[rtsp @ 0x2c8e400] max delay reached. need to consume packetbitrate= 272.9kbits/s dup=299 drop=5 speed=0.407x    
[rtsp @ 0x2c8e400] RTP: missed 457 packets
frame=  960 fps= 14 q=25.0 Lsize=     996kB time=00:00:31.96 bitrate= 255.2kbits/s dup=819 drop=5 speed=0.472x    
video:984kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.238750%
[libx264 @ 0x2cfdd90] frame I:18    Avg QP:20.25  size:  6268
[libx264 @ 0x2cfdd90] frame P:942   Avg QP:22.60  size:   950
[libx264 @ 0x2cfdd90] mb I  I16..4: 48.7% 50.9%  0.4%
[libx264 @ 0x2cfdd90] mb P  I16..4:  0.8%  2.5%  0.0%  P16..4:  5.2%  0.4%  0.4%  0.0%  0.0%    skip:90.7%
[libx264 @ 0x2cfdd90] 8x8 transform intra:67.0% inter:83.5%
[libx264 @ 0x2cfdd90] coded y,uvDC,uvAC intra: 6.9% 18.0% 1.8% inter: 1.1% 3.1% 0.2%
[libx264 @ 0x2cfdd90] i16 v,h,dc,p: 52% 28% 13%  7%
[libx264 @ 0x2cfdd90] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 10% 54%  1%  1%  1%  1%  1%  1%
[libx264 @ 0x2cfdd90] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 33% 17%  4%  9%  5%  8%  3%  4%
[libx264 @ 0x2cfdd90] i8c dc,h,v,p: 79% 13%  7%  2%
[libx264 @ 0x2cfdd90] Weighted P-Frames: Y:1.4% UV:0.4%
[libx264 @ 0x2cfdd90] ref P L0: 86.8%  6.4%  5.4%  1.4%  0.0%
[libx264 @ 0x2cfdd90] kb/s:251.83
Exiting normally, received signal 2.
