### ISSUE TITLE
Hikvision cam suggested settings

### ISSUE THREAD

**Issue by maisun** [KhaosT/homebridge-camera-ffmpeg#201]
Hi,
Thanks for the great plugin! 
I'm trying to configure it for my 4 hikvision 2CD-2XXX IP cams. I run HomeBridge in a docker image on my X86 NAS (Qnap TS-453 with atom CPU). The snapshots work great with no issue, however I noticed a few issues with live video streaming:
1) It plays fine for a few seconds (up to 10) and then freezes
2) Some times it says the error connecting to the camera, and also noticed the error somebody else is viewing the stream (I'm the only one using it via homebridge)

I have tried several things:
1) Try to set the stream as close to the output and possible. So low profile H264 VGA 256/192Kbps 10FPS and on the camera, and the plugin transcode to VGA 132kbps with 10FPS, tried both CBR/VBR but the same result
2) Try to specify tpc protocol for rstp and different pack size, doesn't help either
3) It is not related to CPU, when transcoding the NAS barely use CPU more than 50% (and docker is allowed to access all CPU power). Network can also be excluded as all cams are cat6 cable wired. 

Anything else I should try? What would be the optimal setting for VGA resolution which requires minimal work for FFMpeg? Thank you in advance!

**Comment by maisun** [comment]
Hi, thank you for the reply!
All cameras are configured the same, below is the configuration for one of them:
`            {
               "name":"Entrance Camera",
               "videoConfig":{
                  "source":"-rtsp_transport tcp -re -i rtsp://user:XXXXXXXX@192.168.1.21:554/Streaming/Channels/102/",
                  "stillImageSource":"-i http://user:XXXXXXXX@http://192.168.1.21/Streaming/Channels/1/picture",
                  "maxStreams":2,
                  "maxWidth":640,
                  "maxHeight":360,
                  "maxFPS":10
            }
            `
The substream of the camera is configured like the following:

- Resolution: VGA 640X480, but the actual stream is 640X360 (verified in VLC)
- FPS: 10 
- Bitrate: CBR 192Kbps
- Encoding: H264 with low profile, normal quality

Network issue is excluded, cameras are wired with cat6e cable, play rtsp stream works perfectly in VLC at least for minutes. 
Bottleneck of CPU/memory can also be excluded, during transcode CPU usage barely hit 50%, and there is no resource limit for the docker container. I also tried 480X270 resolution but same problem.

**Comment by erokoder** [comment]
I also have have Hikvision camera, I use omx, but quality is bad, and video late.
If you want I can send configuration. @maisun

**Comment by mientki** [comment]
@erokoder Can you show your configuration here?

**Comment by erokoder** [comment]
@mientki 

I success to adjust. Quality is not bad, but video is still too late.
Configuration:

{ "name":"Entrance Camera", "videoConfig":{ "source":"**-rtsp_transport tcp** -re -i rtsp://user:XXXXXXXX@192.168.1.21:554/Streaming/Channels/102/", "stillImageSource":"-i http://user:XXXXXXXX@http://192.168.1.21/Streaming/Channels/1/picture", "maxStreams":2, "maxWidth":640, "maxHeight":360, "maxFPS":10 }

I add -rtsp_transport tcp and soloved problem with picture.

**Comment by mientki** [comment]
You are great! Now the umami also works :-) I added "-rtsp_transport tcp".

To improve the video quality, please set:
Stream 1:
/Streaming/Channels/**101**/

The resolution of 1280x720px:
"maxWidth": **1280**,
"maxHeight": **720**

and bitrate:
"maxBitrate": **512**,

**Comment by Partizan7676** [comment]
Did somebody get audio from Hikvision cameras ? Try to make videodoorbell from Hiwatch DS-i114 camera.

**Comment by erokoder** [comment]
My Hikvision Cameras dont have audio support. But I have Hikvision Intercom DS-KV8X02-IM 
https://www.hikvision.com/en/Products/Video-Intercom/Villa-Door-Station/DS-KV8X02-IM 
and I only can see video, I cant configure audio and snapshot picture. Any help about this?

**Comment by Partizan7676** [comment]
@erokoder do you have settings for main stream and sub stream channels? if does - you can easily get still image pictures from that camera. for that you must set codec for substream channel to jpeg.

**Comment by erokoder** [comment]
@Partizan7676 
![image](https://user-images.githubusercontent.com/29672138/46733618-19cd2880-cc91-11e8-8087-7f2a48950283.png)

**Comment by Partizan7676** [comment]
stream type - choose sub "stream" and as i remember in video encoding type you will see jpeg or mjpeg

**Comment by erokoder** [comment]
![image](https://user-images.githubusercontent.com/29672138/46735082-6b77b200-cc95-11e8-92b2-e390f1f6ed23.png)
I only saw STD_H264

**Comment by Partizan7676** [comment]
Try to change other options too. Video&audio choose only video, try others - may be it helps. I advice you from my experience with their cam i114

**Comment by erokoder** [comment]
I try change all option, but I cant find jpg or jpeg :/

**Comment by Partizan7676** [comment]
Try to ask hikvision about firmware which is support mjpeg on sub stream

**Comment by Partizan7676** [comment]
Can't edit post from iPad ((( also you can take picture from main stream
http://admin:passwd@ip-cam/ISAPI/Streaming/channels/101/picture?snapShotImageType=JPEG

**Comment by mrjackyliang** [comment]
I was configuring it for my Hikvision DS-7308HQHI-SH TurboHD DVR, and through some troubleshooting I got it working. Wanted to share, so here it is:
```
{
    "name": "The Camera",
    "videoConfig": {
        "source": "-rtsp_transport tcp -re -i rtsp://someuser:123456789012@1.2.3.4:9999/Streaming/Channels/101/",
        "maxStreams": 2,
        "maxWidth": 1920,
        "maxHeight": 1080,
        "maxFPS": 30,
        "maxBitrate": 8192
    }
}
```
Just a word of notice:
1. The password for the authenticated user must not be more than 12 characters and have any weird symbols. It took me a few hours to figure that out because the max allowed was 16 characters, and I maxed out the field.
2. Please don't use the admin user, and assign only live view and playback permissions for the user.
3. Might not be good for slow connections, but I have LTE here so the speed is decent.
