### ISSUE TITLE
no video in stream, screenshots work

### ISSUE THREAD

**Issue by ghost** [KhaosT/homebridge-camera-ffmpeg#206]
Hi,

my webcam was working fine some time ago, except viewing from remote never worked ;)

now even at home my camera just updates the still image,
heres my debug output: https://pastebin.com/dytHQi8V

it seems to me that ffmpeg just streams audio? what happens to the video?

edit: removing audio from the stream solves my problem,
but how can I avoid this? or how can I transcode the audio and keep the video stream?

edit 2: i managed to map my pids in the streams via avprobe & avconv "-map 0:1 -map 0:0"
and now everything works fine! even with audio remote.

I can close this issue now, but maybe someone works on the stream selection in camera-ffmpeg?

thanks!

**Comment by ifunlisted** [comment]
Same issue for me. In the Home app I can view the Still snapshot from the video, but when I tap on the Still to bring up the video stream, it says "Loading" (while the Still remains on the screen)... then after about 30 seconds it says "No Response...This camera is not responding". It won't load the video stream at all.

I'm connecting to the stream via a link generated by SecuritySpy. I am able to view the stream using the same link in a Safari window, but I am not able to view it using the same link in VLC. Maybe there is an issue using login credentials within the link? ...but that wouldn't explain why I can view the Still Image (it's link also has login creds).

{
"platform": "Camera-ffmpeg",
"cameras": [
{
"name": "DoorCam",
"videoConfig": {
"source": "-re -i http://{username:password}@{stream_address},
"stillImageSource": "-i http://{username:password}@{image_address},
"maxStreams": 1,
"maxWidth": 1920,
"maxHeight": 1080,
"maxFPS": 25
}
}
