### ISSUE TITLE
Errors on Linux (Raspbian jessie) with ffmpeg arguments/spawn

### ISSUE THREAD

**Issue by SphtKr** [KhaosT/homebridge-camera-ffmpeg#21]
I was working on something very similar to the folks in #10--I hit an unexpected blip. Whether it's the still image ffmpeg call or the video stream ffmpeg call, something happens with the arguments that causes ffmpeg to not start. I added `console.log` calls to spit out stdout and stderr and this is what I saw:

    -f v4l2 -ss 00:00:01 -i /dev/video1 -vframes 1  -t 1 -s 640x480 -f image2 -
    ffmpeg version git-2016-11-09-ab6ffc2
    Copyright (c) 2000-2016 the FFmpeg developers
    built with gcc 4.9.2 (Raspbian 4.9.2-10)
    configuration: --enable-gpl --enable-nonfree --enable-mmal --enable-omx --enable-omx-rpi --enable-libx264
    libavutil      55. 35.100 / 55. 35.100
    libavcodec     57. 66.101 / 57. 66.101
    libavformat    57. 57.100 / 57. 57.100
    libavdevice    57.  2.100 / 57.  2.100
    libavfilter     6. 66.100 /  6. 66.100
    libswscale      4.  3.100 /  4.  3.100
    libswresample   2.  4.100 /  2.  4.100
    libpostproc    54.  2.100 / 54.  2.100
    /dev/video1: could not seek to position 83848.268
    Input #0, video4linux2,v4l2, from '/dev/video1':
    Duration: N/A, start: 83847.267873, bitrate: 147456 kb/s
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 640x480, 147456 kb/s,
    30 fps,
    30 tbr, 1000k tbn, 1000k tbc
    [NULL @ 0x28e61c0] Unable to find a suitable output format for ''
    : Invalid argument

The `Unable to find a suitable output format for ''` was the same no matter what, and appeared both for the still and video feed.

I managed to workaround the issue by adding the `shell` parameter to the `spawn` options, that is, the options in my modified copy are now `{shell: '/bin/bash', env: process.env}`. With that option, it works correctly. But I'm not sure why this was necessary or how to better fix it. I'm also running the plugin on macOS and don't have this issue. The default shell for the user that this is running under is already `/bin/bash`. (or at least, I think so:

    root@hostname:/opt# su - homebridge
    homebridge@hostname:~$ echo $SHELL
    /bin/bash

). I'm inferring that something about the command parameters is being interpreted differently by `spawn` or whatever command interpreter it's using under the hood, but I'm not sure why. Any ideas? 

Obviously my "fix" requires a mod that isn't necessary on macOS and probably incurs some performance penalty. Also, the video stream process seems to never terminate with this fix in place...but I have no way of knowing if the `shell` option causes this, because without it it won't start at all.

**Comment by KhaosT** [comment]
This is really strange... is there by any chance you have 2 copy of ffmpeg installed on the machine?

**Comment by SphtKr** [comment]
Pretty sure not...it's sitting in the directory where it was built still, but that's not in anyone's PATH. Other than that it's in `/usr/local/bin`

**Comment by KhaosT** [comment]
Not really sure why this is occurring then ... Try print out the array after .split(' ') and see if anything strange got in there?

**Comment by NorthernMan54** [comment]
Not sure if this helps, but I found that on a RPI, if you are using the h264_omx codec you need to ensure that the user you are running homebridge as has access to /dev/vchiq.  ie `sudo usermod -aG video login` where login is the user you are running homebridge as.

**Comment by SphtKr** [comment]
@NorthernMan54 Oooh...Thanks, I'll check that. I figured out it needed access to /dev/video0 but what you said doesn't ring a bell. (Gotten away from this and messing with other things, but will have to try again).
