### ISSUE TITLE
FFMPEG exited with Error code 1

### ISSUE THREAD

**Issue by iRayanKhan** [KhaosT/homebridge-camera-ffmpeg#213]
Hello, Just got camera to add into HomeKit and I get this error:
![screen shot 2018-09-29 at 6 24 30 pm](https://user-images.githubusercontent.com/34495712/46251297-ed094d80-c414-11e8-93e1-15c8efb065e6.jpg)

Any ideas?
Thanks in advance!!!

**Comment by iRayanKhan** [comment]
Ignore reference ^

**Comment by bsowens** [comment]
I have the exact same problem

**Comment by iRayanKhan** [comment]
I hope someone finds a fix idk whats wrong

**Comment by cbpowell** [comment]
You might need to enable debugging using your config (`"debug": true`) to see why exactly FFmpeg is exiting with a code 1.

This was happening to me today, and I think the problem was my custom-compiled FFmpeg had been overwritten during an `apt upgrade`. I'm not 100% sure that is what happened, but 1) I ran an `apt upgrade` earlier in the day after not messing with anything since the last time it worked, and 2) reinstalling the .deb of my custom FFmpeg fixed the issue.

**Comment by iRayanKhan** [comment]
Mind sending ur custom FFMPEG deb?

**Comment by iRayanKhan** [comment]
@cbpowell here's what the debug said:
[2018-10-1 23:05:07] [Camera-ffmpeg] Start streaming video from TC01 with 480x360@100kBit
ffmpeg -re -i  rtsp://**admin:redacted**@redacted/ch01/1 -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 15 -f rawvideo -tune zerolatency -vf scale=480:360 -b:v 100k -bufsize 100k -payload_type 99 -ssrc 4066647 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params iYg0uZokbxs/VpaWEtE3LiDVl8aimEKC2kvzrQJm srtp://192.168.1.66:52501?rtcpport=52501&localrtcpport=52501&pkt_size=1316
ffmpeg version N-92079-gb577153231 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 31.102 / 58. 31.102
  libavformat    58. 18.103 / 58. 18.103
  libavdevice    58.  4.104 / 58.  4.104
  libavfilter     7. 33.100 /  7. 33.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100

: No such file or directory

[2018-10-1 23:05:07] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

**Comment by iRayanKhan** [comment]
@KhaosT Please help or anyone

**Comment by cbpowell** [comment]
@iRayanKhan I don't think I can send you the .deb, because it contains code that is non-distributable.

So your issue is the FFmpeg output "No such file or directory", that's what is causing the code 1 exit. Unfortunately FFmpeg output isn't great for debugging. It looks like you're trying to use `-vcodec h264_omx` but your FFmpeg does not appear to be compiled with h264_omx support. That could be the issue?

Try following the [FFmpeg compilation instructions](https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Raspberry-PI) in the Wiki to compile it on your own Pi. I personally followed a slightly modified version of the instructions on [this blog](https://maniaclander.blogspot.com/2017/08/ffmpeg-with-pi-hardware-acceleration.html).

**Comment by iRayanKhan** [comment]
@cbpowell After some research it appears it is trying to use the webcam at /dev/video0 which must be a USB port. I also tried h264 with out omx and even CAMERA-IP and CAMERA-ffmpeg-Omx

**Comment by iRayanKhan** [comment]
Followed the directions to no avail...

**Comment by KhaosT** [comment]
What's the outcome if you run `ffmpeg -re -i rtsp://admin:redacted@redacted/ch01/1 -o -` directly in terminal? Based on the error log I think your ffmpeg is not compiled with rtsp support...

**Comment by iRayanKhan** [comment]
Ran it and got this:
ffmpeg version N-92087-gdcbd89e000 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 31.102 / 58. 31.102
  libavformat    58. 18.104 / 58. 18.104
  libavdevice    58.  4.105 / 58.  4.105
  libavfilter     7. 33.100 /  7. 33.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
[rtsp @ 0x273e180] max delay reached. need to consume packet
[rtsp @ 0x273e180] RTP: missed 93 packets
[h264 @ 0x2740ff0] error while decoding MB 30 15, bytestream -12
[h264 @ 0x2740ff0] concealing 2419 DC, 2419 AC, 2419 MV errors in I frame
[rtsp @ 0x273e180] max delay reached. need to consume packet
[rtsp @ 0x273e180] RTP: missed 31 packets
[h264 @ 0x2740ff0] error while decoding MB 67 22, bytestream -5
[h264 @ 0x2740ff0] concealing 1822 DC, 1822 AC, 1822 MV errors in P frame
[rtsp @ 0x273e180] max delay reached. need to consume packet
[rtsp @ 0x273e180] RTP: missed 27 packets
[rtsp @ 0x273e180] max delay reached. need to consume packet
[rtsp @ 0x273e180] RTP: missed 19 packets
Input #0, rtsp, from 'rtsp://admin:Canada12@192.168.1.69:554/ch01/1':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.450000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1280x720, 20 fps, 20 tbr, 90k tbn, 180k tbc
At least one output file must be specified

**Comment by iRayanKhan** [comment]
![screen shot 2018-10-03 at 5 59 39 pm](https://user-images.githubusercontent.com/34495712/46444127-2227df80-c736-11e8-9122-6dede3e57526.jpg)

**Comment by iRayanKhan** [comment]
<img width="1440" alt="screen shot 2018-10-03 at 5 59 39 pm" src="https://user-images.githubusercontent.com/34495712/46444152-3d92ea80-c736-11e8-81b9-785a324bcc85.png">

**Comment by KhaosT** [comment]
@iRayanKhan I think you installed 2 ffmpeg on your device. The one homebridge is using have a version header of
```
fmpeg version N-92079-gb577153231 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
```
and the one you ran manually have
```
ffmpeg version N-92087-gdcbd89e000 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
configuration: --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
```

**Comment by KhaosT** [comment]
The one homebridge found wasn't compiled with rtsp support.

**Comment by iRayanKhan** [comment]
I think I have 2, too. I’m gonna wipe my Pi and do a fresh install of everything. Will report back later today.

**Comment by iRayanKhan** [comment]
Funny issue, May have fixed FFmpeg, now my garages died :). It may be unrelated, Homebridge-LiftMaster2
Gonna just try the cameras now

**Comment by iRayanKhan** [comment]
Tried again after wiping my pi;
Same issue.

**Comment by iRayanKhan** [comment]
Update: My garages also are dead, tried running both the cameras and Garages separate and no dice.

**Comment by KhaosT** [comment]
Can you post how you set up your Raspberry Pi? If you didn't unpair your garage before doing this all over again, you may need to manually remove it from HomeKit on iOS device before readding it.

**Comment by iRayanKhan** [comment]
Yeah I should have been more specific;
Homebridge install: https://github.com/nfarina/homebridge
FFMPEG Install; https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Raspberry-PI
Node Install; https://www.w3schools.com/nodejs/nodejs_raspberrypi.asp

**Comment by iRayanKhan** [comment]
In regards to the garage, it may be a coincidence, MyQ seems to have changed their api so the old GET and POST status have changed and the plugin dev has to update it. Or they completely shut down their API so we have to buy their bridge.

**Comment by Partizan7676** [comment]
Has same error. Try to add parameter like in that issue -https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/201#issuecomment-428621144

**Comment by Partizan7676** [comment]
Try that:
{ "name":"Entrance Camera", "videoConfig":{ "source":"-rtsp_transport tcp -re -i rtsp://user:XXXXXXXX@192.168.1.21:554/Streaming/Channels/102/", "stillImageSource":"-i http://user:XXXXXXXX@http://192.168.1.21/Streaming/Channels/1/picture", "maxStreams":2, "maxWidth":640, "maxHeight":360, "maxFPS":10 }

**Comment by iRayanKhan** [comment]
Pretty sure that isn't a proper json format?

**Comment by Partizan7676** [comment]
Why? This is json.

**Comment by iRayanKhan** [comment]
Closed: Re-opening in a few weeks once I get time to hack away with this.

**Comment by iRayanKhan** [comment]
Re-Opening, Going to attempt cameras again

**Comment by NSCHI** [comment]
@KhaosT i have the same problem:

Nov 08 21:59:04 raspberrypi homebridge[562]: [11/8/2018, 9:59:04 PM] [Camera-ffmpeg] Snapshot from Terasse at 480x270
Nov 08 21:59:44 raspberrypi homebridge[562]: [11/8/2018, 9:59:44 PM] [Camera-ffmpeg] Snapshot from Terasse at 480x270
Nov 08 22:00:15 raspberrypi homebridge[562]: [11/8/2018, 10:00:15 PM] [Camera-ffmpeg] Snapshot from Terasse at 480x270
Nov 08 22:00:40 raspberrypi homebridge[562]: [11/8/2018, 10:00:40 PM] [Camera-ffmpeg] Snapshot from Terasse at 480x270
Nov 08 22:00:41 raspberrypi homebridge[562]: [11/8/2018, 10:00:41 PM] [Camera-ffmpeg] Start streaming video from Terasse with 1280x720@299kBit
Nov 08 22:00:41 raspberrypi homebridge[562]: [11/8/2018, 10:00:41 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

pi@raspberrypi:~ $ ffmpeg -re -i rtsp://syno:7179133b0bbd6c326bca7093fb7f6075@192.168.178.7:554/Sms=13.unicast
ffmpeg version N-91067-g1c2e5fc Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10+deb8u1)
  configuration: 
  libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 19.101 / 58. 19.101
  libavformat    58. 13.102 / 58. 13.102
  libavdevice    58.  4.100 / 58.  4.100
  libavfilter     7. 22.100 /  7. 22.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
[rtsp @ 0x24be130] max delay reached. need to consume packet
[rtsp @ 0x24be130] RTP: missed 18 packets
[h264 @ 0x24c1000] error while decoding MB 14 16, bytestream -13
[h264 @ 0x24c1000] concealing 315 DC, 315 AC, 315 MV errors in I frame
Input #0, rtsp, from 'rtsp://syno:7179133b0bbd6c326bca7093fb7f6075@192.168.178.7:554/Sms=13.unicast':
  Metadata:
    title           : Session streamed by "ssrtspd"
    comment         : 1,13_medium.unicast
  Duration: N/A, start: 1.106822, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 640x360, 90k tbr, 90k tbn, 180k tbc
At least one output file must be specified

Can you help me?

**Comment by iRayanKhan** [comment]
Got this issue after another fresh install using Wiki page on repo to install.
Do I need the full version of this as in no raspberian lite?

**Comment by iRayanKhan** [comment]
@KhaosT any ideas?

**Comment by iRayanKhan** [comment]
Tried on another pi using a full version instead of lite and failed. Gonna re-wipe that one and try again

**Comment by iRayanKhan** [comment]
So I have gotten further, but I still get the same error, May the camera size needs to be specific?

**Comment by scheng123** [comment]
Try checking your config, I went through all the debugging, and then at last, found out that there was an extra space in the homebridge config:<pre>
`"source": "-re -i 
 rtsp://YOURUSERNAME:YOURPASSWORD@YOURIPADDRESS:YOURPORT/path/to/stream"`</pre>
It should be instead:
`"source": "-re -i 
 rtsp://YOURUSERNAME:YOURPASSWORD@YOURIPADDRESS:YOURPORT/path/to/stream"`

**Comment by iRayanKhan** [comment]
@scheng123 Thanks for this, I will try it out soon, I haven't tinkered with this in ages and will have to recompile ffmpeg on my pi.
