### ISSUE TITLE
streaming still image from local file

### ISSUE THREAD

**Issue by aphex3k** [KhaosT/homebridge-camera-ffmpeg#218]
I have a local file I want to stream.

I was using the following source configuration:
```javascript
"source": "-f image2 -loop 1 -pix_fmt yuvj422p -s 640x640 -i test.jpeg"
```
I made sure to have the test.jpg file on disk before starting homebridge but all I get is the video live image in HomeKit starting to load but never actually switching to LIVE...

Any ideas?

**Comment by aphex3k** [comment]
Nevermind, got it working...

**Comment by nicoh88** [comment]
@aphex3k Can you explain your solution?

**Comment by aphex3k** [comment]
> @aphex3k Can you explain your solution?

You have to make sure the path to the source image is correct.
