### ISSUE TITLE
Unable to successfully add motionEye to homebridge

### ISSUE THREAD

**Issue by lennart-hendriksma** [KhaosT/homebridge-camera-ffmpeg#221]
I currently have a MotionEye setup on a separate RaspberryPi. It works well, and when I go to the 8081 streaming port, I get a valid streaming source.

I also have added the MotionEye tot a different RaspberryPi running homebridge. I have added in in the Platforms part of the config.json file similar as the example

    {
        "platform": "Camera-ffmpeg",
        "cameras": [
            {"name": "MotionEyeOS",
                "videoConfig": {
                    "source": "-re -f mjpeg -i http://192.168.2.26:8081",
                    "stillImageSource": "-f mjpeg -i http://192.168.2.26/picture/1/current/",
                    "maxStreams": 2,
                    "maxWidth": 1280,
                    "maxHeight": 800,
                    "maxFPS": 10
                 }
            }
        ]
    }

When I clean the persist and accessories folder and restart my homebridge, I'm able to add the camera to my home app, but after that, all accessories stop responding and the camera produces no video. After I remove the camera all accessories start working but I’m unable to add the camera as accessories since it doesn’t show up when I want to add new accessories.

In the mean time the MotionEye 8081 port still works.

Any hints, tips or tricks on when I should do to resolve this?

**Comment by fklement** [comment]
@lennart-hendriksma Having currently the same issue. Did you find the mistake or a workaround?

**Comment by mrbeach69** [comment]
same here, any hints?

**Comment by Thedude7054** [comment]
Anyone reached a solution? I installed motionEye on a separate RaspberryPi after I couldn't get homebridge to play nice with my webcam. motionEye's port 8081 does indeed output video, so it's presumably something related ffmpeg on the RaspberryPi running homebridge.

**Comment by xinyue** [comment]
I have the same problem.
