### ISSUE TITLE
HomeKit does not see camera

### ISSUE THREAD

**Issue by brianerdelyi** [KhaosT/homebridge-camera-ffmpeg#222]
I'm unsure what I did wrong.  I am trying to get HomeKit working with my Raspberry Pi 3 B+.  HomeKit does not see the camera.  I can view the camera with VLC with the URL specified in the config.

1. I install Raspbian Lite (2018-10-09-raspbian-stretch-lite) to my SD card.

2. I install Node.js.
`
curl -sL https://deb.nodesource.com/setup_10.x > nodesetup.sh
sudo bash nodesetup.sh
sudo apt-get install -y nodejs
`

3. I install FFMPEG
`
sudo apt-get update
sudo apt-get install ffmpeg
`

4. I install Homebridge
`sudo npm install -g --unsafe-perm homebridge`

5. I install homebridge-camera-ffmpeg
`sudo npm install -g homebridge-camera-ffmpeg`

6. I run Homebridge and exit.  Then I create the config file.
`sudo nano /home/pi/.homebridge/config.json`

My config.json:

`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an initial config for RTSP cameras",

	"platforms": [{
		"platform": "Camera-ffmpeg",
		"Cameras": [{
			"name": "UniFi G3 Flex",
			"videoConfig": {
				"source": "-rtsp_transport http -re -i rtsp://myfancy_rtsp_stream",
				"maxStreams": 2,
				"maxWidth": 640,
				"maxHeight": 480,
				"maxFPS": 15,
				"audio": true,
				"debug": true
			}
		}]
	}]
}`

I start Homebridge again but there is no camera.

`[11/1/2018, 12:41:40 AM] Loaded config.json with 0 accessories and 1 platforms.
[11/1/2018, 12:41:40 AM] ---
[11/1/2018, 12:41:41 AM] Loaded plugin: homebridge-camera-ffmpeg
[11/1/2018, 12:41:41 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[11/1/2018, 12:41:41 AM] ---
[11/1/2018, 12:41:41 AM] Loading 1 platforms...
[11/1/2018, 12:41:41 AM] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
Setup Payload:
X-HM://0023ISYWYN496
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[11/1/2018, 12:41:41 AM] Homebridge is running on port 51826.
`

**Comment by Partizan7676** [comment]
Rename camera, if not help, change username and pin settings in bridge config.

**Comment by dbeltman** [comment]
> Rename camera, if not help, change username and pin settings in bridge config.

This hasn't worked for me, i am also having this issue starting out with homebridge cameras. I also do not see any CPU usage in `htop` from FFMPEG

**Comment by Partizan7676** [comment]
Has that issue with bridge and cams. When you unpair bridge or cam, reinstall os and just put config back - HomeKit app cannot see or discover you bridge and cams. Btw in logs did you see any messages about camera start. Usualy it seems like "camera starting on port" after whole bridge config started

**Comment by Partizan7676** [comment]
Btw did you enable rtsp in camera? Somewhere I see an article about that exactly for Ubiquiti camera.

**Comment by brianerdelyi** [comment]
Thank you for the responses.  I'm travel this week and won't be able to test until I get home.  Yes, RTSP was enabled on the camera.  I could access with VLC.

**Comment by brianerdelyi** [comment]
No, I do not see "camera starting on port" message.

**Comment by Partizan7676** [comment]
Only what is strange - even you don't have any accessory like camera.

**Comment by brianerdelyi** [comment]
You mean the "accessories" section is missing?  Seems like I accidentally removed this.  I can add t in but it is blank.

**Comment by brianerdelyi** [comment]
I should add, HomeKit sees Homebridge but there is no camera to select when adding devices.

**Comment by kalinchuk** [comment]
I take that back. I had to go to "Add Accessory" and then click on "Don't Have a Code". The camera showed up there.

**Comment by brianerdelyi** [comment]
I have changed the camera name, changes PIN and changed Username in config.  I still do not see the camera.  On start, I do not see "camera is running on port nnn".

I think this is a basic configuration error.  Can someone please share their config.json?

**Comment by Partizan7676** [comment]
Brian, don't know what is wrong, but can you use for install on clean system this script - https://github.com/geekslant/smartgarage
BTW also recommend you this UI for Homebridge - https://github.com/oznu/homebridge-config-ui-x

**Comment by brianerdelyi** [comment]
It is a clean install, regardless, I will rebuild following the links you provided.

Here are the exact steps I've followed.  I use Etcher to prepare my SD card with 2018-10-09-raspbian-stretch-lite image:

1. Install Node.js

> curl -sL https://deb.nodesource.com/setup_10.x > nodesetup.sh
> 
> # It's a good idea to inspect scripts before you run them:
> nano nodesetup.sh
> 
> sudo bash nodesetup.sh
> sudo apt-get install -y nodejs


2. Install FFmpeg

> sudo apt-get install git
> 
> # install build tools
> sudo apt-get install pkg-config autoconf automake libtool libx264-dev
> 
> # download and build fdk-aac
> git clone https://github.com/mstorsjo/fdk-aac.git
> cd fdk-aac
> ./autogen.sh
> ./configure --prefix=/usr/local --enable-shared --enable-static
> make -j4
> sudo make install
> sudo ldconfig
> cd ..
> 
> # download and build ffmpeg
> git clone https://github.com/FFmpeg/FFmpeg.git
> cd FFmpeg
> ./configure --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
> make -j4
> sudo make install
> cd ..


3. Install Homebridge

> sudo npm install -g --unsafe-perm homebridge

4. Install Homebridge-camera-ffmpeg

> sudo npm install -g homebridge-camera-ffmpeg

5. Create Homebridge config.json

> Homebridge (need to launch and close Homebridge once before editing config file)
> 
> sudo nano /home/pi/.homebridge/config.json


```
{
   "bridge":{
      "name":"Homebridge",
      "username":"11:22:33:44:55:66",
      "port":51826,
      "pin":"123-45-678"
   },
   "platforms":[
      {
         "platform":"Camera-ffmpeg",
         "cameras":[
            {
               "name":"UniFi G3 Flex",
               "videoConfig":{
                  "source":"-rtsp_transport http -re -i rtsp://192.168.2.26:7447/pqSBSzLFBznJlUHn",
                  "vcodec":"h264_omx",
                  "audio": true,
                  "maxStreams":2,
                  "maxWidth":640,
                  "maxHeight":480,
                  "maxFPS":15,
                  "debug": true
               }
            }
         ]
      }
   ]
}
```

**Comment by brianerdelyi** [comment]
@Partizan7676 I have formatted my SD card and used the Raspbian Stretch Lite image (dated 11/132018).  The script you provided included additional stuff I didn't want, however, I have run all the exact same commands (update_package_database, upgrade_installed_packages install_node_repo, install_nodejs_and_npm, install_avahi, install_ffmpeg, install_homebridge and install_homebridge_camera_plugin).  I did not yet setup systemd.  I then paste my configuration.

Main differences in the script you suggested is install avahi and install FFmpeg.  I followed instructions from the wiki for this project to compile my own.

I add the camera.  I get the thumbnail.  I get the following error when trying to view the camera live stream.

```
[2018-11-23 14:21:20] Homebridge is running on port 51826.
[2018-11-23 14:21:20] UniFi G3 Flex is running on port 33123.
[2018-11-23 14:22:11] [Camera-ffmpeg] Snapshot from UniFi G3 Flex at 480x270
ffmpeg -rtsp_transport http -re -i rtsp://192.168.2.26:7447/pqSBSzLFBznJlUHn -t 1 -s 480x270 -f image2 -
[2018-11-23 14:22:22] [Camera-ffmpeg] Start streaming video from UniFi G3 Flex with 640x360@132kBit
ffmpeg -rtsp_transport http -re -i rtsp://192.168.2.26:7447/pqSBSzLFBznJlUHn -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 15 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 49143 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params o/jvUhLHWId3kFzdTcgNcFaxLc2hNHRkaq3UMAP5 srtp://192.168.2.18:63222?rtcpport=63222&localrtcpport=63222&pkt_size=1316 -map 0:1 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -ac 1 -payload_type 110 -ssrc 12420316 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params L6T7lou4Dzkxty/XJkb4QZ97kwFJ2LT8ZavojiLA srtp://192.168.2.18:62654?rtcpport=62654&localrtcpport=62654&pkt_size=1316
ffmpeg version 3.2.10-1~deb9u1+rpt2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1+rpt2' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared

  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100

Input #0, rtsp, from 'rtsp://192.168.2.26:7447/pqSBSzLFBznJlUHn':
  Metadata:
    title           : 
FCECDA1F525A_2
  Duration: N/A, start: 0.180000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp
    Stream #0:1: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 15 fps, 15 tbr, 90k tbn, 30 tbc

Codec AVOption tune (Tune the encoding to a specific scenario) specified for output file #0 (srtp://192.168.2.18:63222?rtcpport=63222&localrtcpport=63222&pkt_size=1316) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.

Codec AVOption b (set bitrate (in bits/s)) specified for output file #0 (srtp://192.168.2.18:63222?rtcpport=63222&localrtcpport=63222&pkt_size=1316) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.

Codec AVOption b (set bitrate (in bits/s)) specified for output file #1 (srtp://192.168.2.18:62654?rtcpport=62654&localrtcpport=62654&pkt_size=1316) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.

Codec AVOption profile () specified for output file #1 (srtp://192.168.2.18:62654?rtcpport=62654&localrtcpport=62654&pkt_size=1316) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.

[swscaler @ 0x221c7e0] deprecated pixel format used, make sure you did set range correctly

Output #0, rtp, to 'srtp://192.168.2.18:63222?rtcpport=63222&localrtcpport=63222&pkt_size=1316':
  Metadata:
    title           : FCECDA1F525A_2
    encoder         : Lavf57.56.101

    Stream #0:0: Audio: pcm_mulaw, 48000 Hz, mono, s16, 384 kb/s
    Metadata:
      encoder         : Lavc57.64.101 pcm_mulaw

[mpeg4 @ 0x21ad9b0] Either both buffer size and max rate or neither must be specified
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> pcm_mulaw (native))
  Stream #0:1 -> #1:0 (h264 (native) -> mpeg4 (native))
Error while opening encoder for output stream #1:0 - maybe incorrect parameters such as bit_rate, rate, width or height

[2018-11-23 14:22:24] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1
```

**Comment by brianerdelyi** [comment]
@KhaosT any thoughts on how to troubleshoot this?

**Comment by brianerdelyi** [comment]
FYI, I let it continue to run and eventually get the following:

```
size=    1319kB time=00:00:27.81 bitrate= 388.6kbits/s speed=   1x    
video:0kB audio:1304kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.184456%
```

Weird, it shows no video but lots of audio.

**Comment by KhaosT** [comment]
For your case it looks like the rtsp source contains two separate stream and ffmpeg by default picked the audio stream instead of the view stream... Can you tweak the input so the ffmpeg knows it should only care about video instead of audio?

**Comment by brianerdelyi** [comment]
Not sure how to tweak the input.  You mean configure the camera to only output video?

I think there is an option to disable audio, i’ll Check.  If not, is there anything else I can do to tweak the ffmpeg command?

**Comment by KhaosT** [comment]
For your case I guess try manually flip `-map 0:0` and `-map 0:1`

**Comment by brianerdelyi** [comment]
Where do I flip these?

**Comment by KhaosT** [comment]
https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/master/ffmpeg.js#L290 Depends on the platform, npm may install the plugin at different places.

**Comment by Partizan7676** [comment]
@brianerdelyi did you set up your camera ? as i remember on this camera you must set it to get rtsp stream.

**Comment by brianerdelyi** [comment]
Yes the RTSP stream is enabled and set in my Homebridge config.

@KhaosT yes, I found this file in GitHub, however, I cannot find it on my system.  I'm not sure where the path to it is on my Raspberry Pi running Raspbian.

**Comment by brianerdelyi** [comment]
I modified /usr/lib/node_modules/homebridge-camera-ffmpeg/ffmpeg.js and it's now working.

I modified the following line:

`let ffmpegCommand = this.ffmpegSource + ' -map 0:0' +`
to
`let ffmpegCommand = this.ffmpegSource + ' -map 0:1' +`

`ffmpegCommand+= ' -map 0:1' +`
to
`ffmpegCommand+= ' -map 0:0' +`

**Comment by luizjunior** [comment]
> I take that back. I had to go to "Add Accessory" and then click on "Don't Have a Code". The camera showed up there.

Then HomeKit ask me for a 8 number code. 
Where can I find this 8 number code?

**Comment by llamafilm** [comment]
I'm also having trouble with this.  HomeKit sees my other platforms but does not see the camera.  I'm not seeing anything useful in the log.  @KhaosT do you know how I can troubleshoot this?  Here is my config and the log file after starting fresh (I removed cachedAccessories and persist)

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "033-44-255"
    },
    "description": "Homebridge on Raspberry Pi",
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "auto",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "f",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "accessoryControl": {
                "debug": true
            },
            "platform": "config"
        },
        {
            "platform": "LutronCasetaPlatform",
            "bridgeConnection": {
                "host": "192.168.3.6"
            },
            "accessories": [
                {
                    "name": "PicoRemote1",
                    "type": "PJ2-3BRL",
                    "integrationID": 4
                }
            ]
        },
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Pi Camera",
                    "videoConfig": {
                        "source": "-re -f v4l2 -i /dev/video0",
                        "stillImageSource": "-re -f v4l2 -ss 0.9 -i /dev/video0 -vframes 1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxBitrate": 1000,
                        "vcodec": "h264_omx",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                }
            ]
        }
    ]
}
```

```
$ DEBUG=* sudo -u homebridge homebridge -U /var/lib/homebridge/ -I -Q -D
[1/28/2020, 8:37:48 AM] Loaded config.json with 0 accessories and 3 platforms.
[1/28/2020, 8:37:48 AM] ---
[1/28/2020, 8:37:56 AM] Loaded plugin: homebridge-camera-ffmpeg
[1/28/2020, 8:37:56 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/28/2020, 8:37:56 AM] ---
[1/28/2020, 8:37:56 AM] Loaded plugin: homebridge-config-ui-x
[1/28/2020, 8:37:56 AM] Registering platform 'homebridge-config-ui-x.config'
[1/28/2020, 8:37:56 AM] ---
[1/28/2020, 8:37:56 AM] Loaded plugin: homebridge-lutron-caseta-smockle
[1/28/2020, 8:37:56 AM] Registering platform 'homebridge-lutron-caseta-smockle.LutronCasetaPlatform'
[1/28/2020, 8:37:56 AM] ---
[1/28/2020, 8:37:57 AM] Loading 3 platforms...
[1/28/2020, 8:37:57 AM] [Config] Initializing config platform...
[1/28/2020, 8:37:57 AM] [Config] Spawning homebridge-config-ui-x with PID 1603
[1/28/2020, 8:37:57 AM] [LutronCasetaPlatform] Initializing LutronCasetaPlatform platform...
[1/28/2020, 8:37:57 AM] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[1/28/2020, 8:37:57 AM] Loading 0 accessories...
Setup Payload:
X-HM://0023IX8JJEJKK
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 033-44-255 │     
    └────────────┘     
                       
[1/28/2020, 8:38:00 AM] Homebridge is running on port 51826.
[1/28/2020, 8:38:00 AM] Pi Camera is running on port 43555.
[1/28/2020, 8:38:00 AM] Please add [Pi Camera] manually in Home app. Setup Code: 033-44-255
[1/28/2020, 8:38:19 AM] [Config] [HapClient] Discovery :: Started
[1/28/2020, 8:38:20 AM] [Config] Homebridge Config UI X v4.8.1 is listening on :: port 8080
```
I trimmed the log after Config HapClient discovery started
