### ISSUE TITLE
Problems using an IP camera

### ISSUE THREAD

**Issue by carsten-h** [KhaosT/homebridge-camera-ffmpeg#227]
Hello!

I am having problems in getting an IP camera to work withe camera-ffmpeg.

The camera is using this URL to show the video:
http://admin@x.x.x.x/video/livemb.asp

When I am using this URL in a browser, the browser asks for username and password. You have to input admin as username and no password and then the browser shows the video without any problems.

There is a better URL, that also works in VLC:
http://admin@x.x.x.x/media/?action=stream
VLC will also show a login dialog, where you have to input admin as user and no password.

How can I create an URL so that no password dialog will be shown when using an empty password?

I used this config in homebridge:

 {
      "name": "Cam",
      "videoConfig": {
      "source": "-rtsp_transport tcp -re -i http://admin@x.x.x.x/video/livemb.asp",
      "vcodec": "h264_omx",
      "maxFPS": 30,
      "maxHeight": 1280,
      "maxWidth": 960,
      "maxStreams": 2,
      "packetSize": 188,
      "maxBitrate": 200,
      "debug": true
      }
 }

I also tried it without "-rtsp_transport tcp", but no change. The result in the logfile is this:

>[11/14/2018, 7:21:09 PM] [Camera-ffmpeg] Start streaming video from Cam with 640x360@132kBit
>ffmpeg -rtsp_transport tcp -re -i http://admin@x.x.x.x/video/livemb.asp -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 10870694 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 51RQPyVwm2/C9RvVgd7kDT3ED3DcFZF5LihAFlkG srtp://192.168.178.63:65404?rtcpport=65404&localrtcpport=65404&pkt_size=188
>ffmpeg version 3.2.10-1\~deb9u1+rpt2
 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1+rpt2' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg--enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
>[http @ 0xd069d0]
HTTP error 401 Unauthorized
http://admin@x.x.x.x/video/livemb.asp: Server returned 401 Unauthorized (authorization failed)
>[11/14/2018, 7:21:11 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

Is there anybody who can help me?

It seems that here: https://github.com/Motion-Project/motion/issues/565 someone had the same problem in motion.

Thanks in advance!

**Comment by qelanhari** [comment]
You probably also can use 
http://login:password@ip/video/livemb.asp

**Comment by carsten-h** [comment]
No, this is not possible because the "password" is empty and you can not use this URL with an empty password!

**Comment by qelanhari** [comment]
Oops my bad, I read that half wrong

**Comment by carsten-h** [comment]
No problem. :-)
