### ISSUE TITLE
Any success with Amcrest/Foscam cameras?

### ISSUE THREAD

**Issue by gijoecool** [KhaosT/homebridge-camera-ffmpeg#23]
I'm having a difficult time getting my Amcrest and Foscam cameras working with this. Has anyone had any luck? If so, would you mind sharing your configuration?

**Comment by gijoecool** [comment]
My issue was because I had closed ports on my test machine. 

Amcrest cameras can use something like this:
-re -i rtsp://[user]:[password]@[ip_address]:[port]/cam/realmonitor?channel=1&subtype=1

**Comment by robbinonline** [comment]
Foscam cameras:
`"source": "-re -i rtsp://*username*:*pass*@*ip:port*/videoMain"
"stillImageSource": "-i http://*ip:port*//cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&amp;usr=*username*&amp;pwd=*pass*",
`

**Comment by dangerusty** [comment]
@gijoecool can you share your amcrest configuration? I'm able to see the snapshot, but not the live view in Home app. Same rtsp URL works in VLC.

**Comment by gijoecool** [comment]
@dangerusty sorry I no longer have this set up. What platform are you on? If you’re using a raspberry pi, then there is a separate omx version that works better.
