### ISSUE TITLE
Output file is empty, nothing was encoded

### ISSUE THREAD

**Issue by Shinodas** [KhaosT/homebridge-camera-ffmpeg#234]
I am able to see the camera in homekit, but when i try to open it, the stream starts but i get no live view, i think this is because of a cache problem somewhere, because sometimes, after i removed the camera from homekit and add it again, the live view works! But only the first time that i open it. When i close it and try to open again, it goes back to the same problem....

Here is log

`ffmpeg -rtsp_transport tcp -re -i rtsp://username:password@192.168.178.26/videoMain -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 10628835 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params /K6OUlYkOkWRE27WsJtLodHtoJ+6QXKrZ0CeEzec srtp://192.168.178.15:60989?rtcpport=60989&localrtcpport=60989&pkt_size=1316
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gpl --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-opencl --enable-videotoolbox

  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100

Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://username: password@192.168.178.26/videoMain':

  Metadata:
    title           : videoMain
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720, 15 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s

Stream mapping:

  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help

frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[swscaler @ 0x7fa3f2890000] deprecated pixel format used, make sure you did set range correctly

Finishing stream 0:0 without any data written to it.

[libx264 @ 0x7fa3f2835e00] VBV maxrate unspecified, assuming CBR

[libx264 @ 0x7fa3f2835e00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX

[libx264 @ 0x7fa3f2835e00] profile High, level 3.1

Output #0, rtp, to 'srtp://192.168.178.15:60989?rtcpport=60989&localrtcpport=60989&pkt_size=1316':
  Metadata:
    title           : videoMain
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720, q=-1--1, 299 kb/s, 30 fps, 90k tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.35.100 libx264

    Side data:
      cpb: bitrate max/min/avg: 0/0/299000 buffer size: 299000 vbv_delay: -1

frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

Exiting normally, received signal 15.

[2018-11-29 10:47:14] [Camera-ffmpeg] Stopped streaming
`
So it says that the output file is empty... the stream is finished without any data written to it. Also the 
` time=-577014:32:22.77` is weird, since it is always the same, on 2 diffrent camera's

i also tryed to get the stream working with homebridge-foscamcamera plugin, with that one, i actually got 1 camera working, but the other camera's give exactly the same problem...
 
(i also asked this question on the github page of the homebridge-foscamcamera plugin, its exactly the same problem as described overthere....)

https://github.com/luisiam/homebridge-foscamcamera/issues/65

Here is my config.json

{
    "bridge": {
        "name": "Homebridge6",
        "username": "DC:22:3D:E3:CE:06",
        "pin": "031-45-106"
    },

    "accessories": [],

    "platforms": [

    {
      "platform": "Camera-ffmpeg",

      "cameras": [
                        {
                          "name": "FI9816P",
                          "videoConfig": {
                          	"source": "-rtsp_transport tcp -re -i rtsp://username:password@192.168.178.26/videoMain",
                          	"stillImageSource": "-i http://username:password@192.168.178.26/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=username&pwd=password",
                          	"maxStreams": 2,
                          	"maxWidth": 1280,
                          	"maxHeight": 720,
                          	"maxFPS": 30,
                            "debug": true,
                            "maxBitrate": 1500,
                            "additionalCommandline": "",
                            "packetSize": 1316
                          }
                        }
      ]
    }

  ]

}

**Comment by TippyLion28** [comment]
Did you ever find a solution to this? I'm trying to run the following on a h265 stream with no luck :(
`/usr/bin/ffmpeg -i rtsp://myusername:mypassword@192.168.1.13/ch0_0.264 -f mpegts -codec:v mpeg1video -r 30 -max_muxing_queue_size 4096 -`

**Comment by Sunoo** [comment]
@TippyLion28 If you’re have trouble please open a new issue and include your logs and your config.
