### ISSUE TITLE
Error:spawn ffmpeg ENOENT snapshot

### ISSUE THREAD

**Issue by Neosilver09** [KhaosT/homebridge-camera-ffmpeg#236]

**Comment by KhaosT** [comment]
`spawn ffmpeg ENOENT` means the plugin can't find ffmpeg. Please install ffmpeg follow the guide in [Wiki](https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Raspberry-PI).

**Comment by Neosilver09** [comment]
Thank you it’s working now your such a great person.But the stream it’s on 680p but it’s a 1920x1080p camera.What I have to do to have the full quality thx.

**Comment by Neosilver09** [comment]
When i use the wifi it's correct but in LTE it's 640p

**Comment by KhaosT** [comment]
Apple restricted the resolution for IP camera over cellular connection, there is nothing the camera can do to resolve this.
