### ISSUE TITLE
FFmpeg exited with code 1 on re-complied ffmpeg

### ISSUE THREAD

**Issue by paqpaqpaq** [KhaosT/homebridge-camera-ffmpeg#237]
on a pi3B+ It was impossible to get a smooth stream, whilst on VLC it runs just perfectly.
CPU loads approx 8% only when streaming.

So I recomplied ffmpeg with these steps:
sudo apt-get install libomxil-bellagio-dev -y
git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg
sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree
sudo make -j4
sudo make install

That took approx 50 mins.
After that There is no stream at all 

> Start streaming video from Voordeur 2 with 1280x720@299kBit
> ffmpeg -rtsp_transport  -re -i rtsp://192.168.108.245:554/user=admin&password=***&channel=1&stream=0.sdp? -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 20 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 9239099 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params KjKwRbf/zsj0moqzK1knTJpHTYp9BZvj3mgeyj2R srtp://192.168.108.102:51865?rtcpport=51865&localrtcpport=51865&pkt_size=188
> [2018-12-1 16:31:13] [Video-doorbell] ERROR: FFmpeg exited with code 1

I get this error immediately.

When I install ffmpeg omx plugin, it just keeps hanging without any errors, and without stream.

Any clues where this all went wrong?

**Comment by aivs** [comment]
Show your config.
Try to remove audio from config, it helped me.

**Comment by Samfox2** [comment]
If you are using h264_omx please make sure that the user that is running homebridge has permisson to use your grafix card.

**Comment by paqpaqpaq** [comment]
I managed to get a "fair' stream on a very low resolution, at 10 fps.
sometimes...

I found an old install of the ffmpeg.deb that was with the ffmpeg-omx plugin.
(the one in the readme.md is offline) 
So I downgraded ffmpeg back to that version, and it runs super now!

How come the differences between ffmpeg compiles are so very different in outcome?

**Comment by carmitage** [comment]
^^^^^ How did you do this?  i need my camera working!!

Thanks!!!

**Comment by paqpaqpaq** [comment]
@carmitage
I still had it on my pi, but the link in that plugin is offline. 
So here’s a mirror. 
Bit of a shady host, but it works. 
https://upload.cat/f711ad636cea3373
