### ISSUE TITLE
Raspberry PI ( Jessie ) and Vivotek IP Camera ( CC-8130 )

### ISSUE THREAD

**Issue by NorthernMan54** [KhaosT/homebridge-camera-ffmpeg#24]
I encountered a minor issue when attempting to set this up on my Raspberry PI with Jessie.   The package ffmpeg has been changed to libav-tools, and the ffmpeg command was changed to avconv.   After an install of libav-tools and doing a quick edit of ffmpeg.js to change the ffmpeg command to avconv, everything worked fine.

**Comment by macjl** [comment]
The alternative solution I use is : 
cd /usr/bin && ln -s avconv ffmpeg

**Comment by NorthernMan54** [comment]
Tks macjl, after updating I switched to this.

For me, I found that the following settings seemed to work okay with the Vivotek IP Camera

On the camera I had set the settings for Media->Video->Stream 1 to

H.264
Frame Size 640*400
Maximum frame rate 5
Intra Frame Period 1/4S
Video Quality: Good
Maximum bit rate 10 Mbps

And in config.json

{
"platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "Office Camera",
      "videoConfig": {
        "source": "-re -i rtsp://192.168.1.XX/live.sdp",
        "stillImageSource": "-i http://login:password@192.168.1.XX/video2.mjpg",
        "maxStreams": 2,
        "maxWidth": 640,
        "maxHeight": 480,
        "maxFPS": 5
      }
    }
  ]
}

**Comment by NorthernMan54** [comment]
Latest working configuration is in the wiki
