### ISSUE TITLE
targetAddress, stream is sent to iPhone on wifi and Apple TV remotely.

### ISSUE THREAD

**Issue by kyl3n** [KhaosT/homebridge-camera-ffmpeg#241]
I would just like to verify that the targetAddress is being sent correctly. As there have been other users that have encountered a problem where they can view the stream remotely over cellular but not locally. 

Now the reasoning for this is because when a camera stream is started locally on the wifi network. The srtp stream Is being sent directly to the iPhones IP address. 

When the stream is viewed remotely the stream is being sent directly to the Apple TV/  Home Hub. 

So first of all I would like to verify that the correct behavior is to send the stream directly to the phones IP address while on local wifi.

If this is the correct behavior then we know that there is a problem somewhere in-between where that stream is being dropped, either by the router, or maybe another factor related to phone.

### Example below:

**FFmpeg compile config:**
 
ffmpeg version N-92617-gea68e02c6d Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/usr --target-os=linux --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol='tcp,udp,srtp' --enable-demuxer=rtsp --disable-ffplay --enable-openssl

**Example of local wifi attempt at streaming:**

ffmpeg -rtsp_transport tcp -re -i rtsp://admin:admin@10.0.99.14:554/1/1 -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 20 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 368128 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params CEYuqUxoI16fsU/f7EySk78MrmDdBOCcm3ubEQSC srtp://10.0.99.15:60758?rtcpport=60758&localrtcpport=60758&pkt_size=1316

10.0.99.15 is my iPhones WIFI IP address

**Example of connection to stream while over cellular network (this works fine):** 

ffmpeg -rtsp_transport tcp -re -i rtsp://admin:admin@10.0.99.14:554/1/1 -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 20 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 4393027 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 9hLbyynNRH4SPpGNgC/ajZYR8jjp1AJq/vGsU3Gw srtp://10.0.99.7:61312?rtcpport=61312&localrtcpport=61312&pkt_size=1316

10.0.99.7 is my Apple TV/ Home Hub IP address

What would be the best way to go about tracking down this behavior. Has anyone looked further into this?

I fired up the Console.app to see what the home app was reporting on its end. While it's trying to connect to the camera stream it keeps repeating this bit, Before finally disconnecting on its own with a "No response". 

default	16:54:37.644604 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:705 AVCVideoStream: notified client 0x113f171b0 of downlinkQualityDidChange [<private>]
default	16:54:38.150908 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	16:54:38.151811 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:705 AVCVideoStream: notified client 0x113f171b0 of downlinkQualityDidChange [<private>]
default	16:54:38.642668 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	16:54:38.642842 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:705 AVCVideoStream: notified client 0x113f171b0 of downlinkQualityDidChange [<private>]
default	16:54:39.049448 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	16:54:39.050964 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:675 AVCVideoStream: notified client 0x113f171b0 received RTCP packets
default	16:54:39.640252 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	16:54:39.640769 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:705 AVCVideoStream: notified client 0x113f171b0 of downlinkQualityDidChange [<private>]
default	16:54:41.144466 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	16:54:41.144974 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:705 AVCVideoStream: notified client 0x113f171b0 of downlinkQualityDidChange [<private>]
default	16:54:41.644986 -0700	homed	AVConferenceXPCClient [INFO] -[
default	16:54:56.144479 -0700	homed	Watch dog timer fired, checking message kStartStreamRequestKey identifier F0D9EF22-B3F2-47EB-9ED7-DBF520B92A62

**Below we have a successful connection from outside the lan network, using cellular.
If you look closely the difference is that the successful connection first sends a** 

default	17:02:58.944590 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:705 AVCVideoStream: notified client 0x115e5e850 of downlinkQualityDidChange [<private>]

**Followed by:**

default	17:03:00.398048 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:03:00.398525 -0700	homed	AVCAudioStream [INFO] -[AVCAudioStream registerBlocksForDelegateNotifications]_block_invoke:851 AVCAudioStream: notified client 0x113878760 received RTCP packets

**Full successful connection below:** 

default	17:02:58.944060 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:02:58.944590 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:705 AVCVideoStream: notified client 0x115e5e850 of downlinkQualityDidChange [<private>]
default	17:03:00.398048 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:03:00.398525 -0700	homed	AVCAudioStream [INFO] -[AVCAudioStream registerBlocksForDelegateNotifications]_block_invoke:851 AVCAudioStream: notified client 0x113878760 received RTCP packets
default	17:03:00.960276 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:03:00.960452 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:675 AVCVideoStream: notified client 0x115e5e850 received RTCP packets
default	17:03:05.430468 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:03:05.430660 -0700	homed	AVCAudioStream [INFO] -[AVCAudioStream registerBlocksForDelegateNotifications]_block_invoke:851 AVCAudioStream: notified client 0x113878760 received RTCP packets
default	17:03:06.009036 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:03:06.009220 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:675 AVCVideoStream: notified client 0x115e5e850 received RTCP packets
default	17:03:10.442385 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:03:10.443696 -0700	homed	AVCAudioStream [INFO] -[AVCAudioStream registerBlocksForDelegateNotifications]_block_invoke:851 AVCAudioStream: notified client 0x113878760 received RTCP packets
default	17:03:11.016486 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:03:11.016600 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:675 AVCVideoStream: notified client 0x115e5e850 received RTCP packets
default	17:03:15.444878 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:03:15.445461 -0700	homed	AVCAudioStream [INFO] -[AVCAudioStream registerBlocksForDelegateNotifications]_block_invoke:851 AVCAudioStream: notified client 0x113878760 received RTCP packets
default	17:03:16.052470 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:03:16.052652 -0700	homed	AVCVideoStream [NOTICE] -[AVCVideoStream registerBlocksForDelegateNotifications]_block_invoke:675 AVCVideoStream: notified client 0x115e5e850 received RTCP packets
default	17:03:20.481042 -0700	homed	AVConferenceXPCClient [INFO] -[AVConferenceXPCClient createConnectionToServer]_block_invoke:263 XPC Client: processing registered reply for service <private>
default	17:03:20.481484 -0700	homed	AVCAudioStream [INFO] -[AVCAudioStream registerBlocksForDelegateNotifications]_block_invoke:851 AVCAudioStream: notified client 0x113878760 received RTCP packets

So why is over a cellular network picking up the stream and sending processing the signal after receiving "downlinkQualityDidChange".

**Comment by kyl3n** [comment]
Issue was found out to be related to multi-threaded processing of the stream. Which adds a delay of 1 frame per thread. I will post a follow up issue and commit detailing the fix.

**Comment by gprsnlty** [comment]
im late to this issue but for me its the same issue. via cellualr i get a live stream via wlan not.
my homebridge is setup on windows.

**Comment by Sunoo** [comment]
@gprsnlty Please don’t copy/paste the same response across various closed issues. If you’re having a problem, please open a new issue.
