### ISSUE TITLE
FFmpeg exited with code -2

### ISSUE THREAD

**Issue by platini76** [KhaosT/homebridge-camera-ffmpeg#246]
what is the problem?

[2018-12-18 02:54:59] [Camera-QNAP-QVRPro] Start streaming video from Soppalco with 1280x720@299kBit
[2018-12-18 02:54:59] [Camera-QNAP-QVRPro] An error occurs while making stream request
[2018-12-18 02:54:59] [Camera-QNAP-QVRPro] ERROR: FFmpeg exited with code -2

**Comment by bryangauvin** [comment]
Im getting the same. DId you figure it out?

**Comment by platini76** [comment]
I install ffmpeg decoding, sorry but I don't remember where I found the solution

**Comment by bryangauvin** [comment]
Do you remember what version of ffmpeg you installed? I have tried many

**Comment by FastHogi** [comment]
I had a [similar problem](https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/250) and looked for a solution to get more debug messages. There is an outstanding pull request [197](https://github.com/KhaosT/homebridge-camera-ffmpeg/pull/197}, which currently prevents the plugin to write out more debug details. Just replace line 334 in ffmpeg.js with `}.bind(this));` and add the "addionalCommandline" property "-loglevel verbose" in your camera config and you should be able to see more debug messages. Hope that will help you.
