### ISSUE TITLE
Support for viewing remotely

### ISSUE THREAD

**Issue by BeauGiles** [KhaosT/homebridge-camera-ffmpeg#25]
Hi!

So the server that Homebridge is running on is sitting in my DMZ (I like to live dangerously...) - is there any way that I can view my camera streams remotely?

Thanks to my Apple TV, other kit works fine (like an official Schlage lock, and a WeMo Switch) over 3g when I'm not at home, but I can't view the camera - I assume this is because the phone is being fed an internal address to connect to, not my external address?

**Comment by gijoecool** [comment]
Which Apple TV do you have? Apple only supports HomeKit cameras with the 4th generation Apple TV. https://support.apple.com/en-us/HT207057

**Comment by albertodig** [comment]
Hi!
I have a new Apple TV 4th generation and unfortunately I have the same problem.
Over 3G connection camera doesn't work.
All others accessory (switch, light ..) works properly. 
Other with same problem?
...I installed homebridge on raspberry pi 2..

**Comment by KhaosT** [comment]
@albertodig are you able to see snapshot update in Home app over remote access?

**Comment by albertodig** [comment]
@khaost no, snapshot is not update. Can be a app home bug? ..very strange

**Comment by KhaosT** [comment]
If the snapshot is also not updating then it might be a connectivity issue. Just to be sure, your 4th gen Apple TV is running tvOS 10 or higher right?

**Comment by Samfox2** [comment]
I had to do a signout/in at my apple tv to get remote access working, maybe that solves your problem.

**Comment by albertodig** [comment]
Thank you! i reboot one more time the tv and now it works! Thank you!!!

**Comment by ageorgios** [comment]
When trying to access live camera remotely I get a no-connectivity problem. I tried rebooting the Apple TV 4th gen but did not work.
Any other advice?

**Comment by klaasjoerg** [comment]
I was knowsie and also just installed this plugin (among some others) on my raspberry-pi3 and configured two different webcams (mobotix doorbell cam, hunter).
Short result: Works great and out-of-the-box.

Also tried to access the cams via Apple "Home"-App from remote which worked without any problems. I also didn't had to reboot/re-login anything. Running ATV4, iphone7, IOS10, Raspberrypi3 with jessie including zwave-me and some more stuff on it.

**Comment by ageorgios** [comment]
With this configuration

          "videoConfig": {
            "source": "-re -i http://raspberrypi:8081",
            "stillImageSource": "-i http://raspberrypi:8765/picture/1/current/",
            "maxStreams": 1,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 30
          }

I only get remote feed when on WiFi, when I have 4G the live feed does not work

**Comment by NorthernMan54** [comment]
Pls try this again, there was a fix implemented in December that should resolve this.
