### ISSUE TITLE
vcodec 'copy' and vcodec "h264_omx" exited with error 1, but "libx264" works fine

### ISSUE THREAD

**Issue by FastHogi** [KhaosT/homebridge-camera-ffmpeg#250]
I added some traffic webcams and they work pretty good in the homekit app eve. But the CPU load on my raspberry pi 3B is about 270% - 300% when the stream is started. Therefore the traffic video isn't running smooth at 25fps. I tried 2 different approaches to reduce the CPU load on the pi:

**1)** The traffic video source is a https request and it is already encoded as a h264 video file. Therefore I tried to use "-vcodec copy" in ffmpeg to not encode the video another time and just to use it as it is for the video stream. I already commented out the "-b:v {vbitrate}" , "-vf scale..." and "-maxrate {vbitrate}" lines in ffmpeg.js. 

But FFmpeg still exited with code 1. I added the "addionalCommandline" property in the config.json with " -loglevel verbose -report", but I can't find any created logfile. I assume FFmpeg couldn't be executed. If I run the exact same FFmpeg command (debug info from journalctl) on the console, FFmpeg is running fine and starts to stream the video. FFMpeg is version 3.2.12-1 running on OSMC.

Here is my camera config:

	{
		"name": "Gambach Nord",
		"videoConfig":
		{
			"source": "-re -i https://verkehrsservice.hessen.de/syncdata/video/k5076.mp4",
			"maxStreams": 2,
			"maxWidth": 704,
			"maxHeight": 576,
			"vcodec": "copy",
			"additionalCommandline": " -loglevel verbose -report",
			"audio": false,
			"debug": true
		}
	}
	
**Question**: why is FFmpeg running fine with default vcodec "libx264" but not with "copy"? Why isn't a log report created with command switch "-loglevel verbose -report"? 

**2)** The 2nd approch was to use h264_omx. I newly compiled FFmpeg under the user osmc with

```
sudo apt-get install libomxil-bellagio-dev openssl libssl-dev –y
git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg
sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree –-enable-openssl
sudo make –j4
```

Config for this approach:

	"platform": "Camera-ffmpeg",
	"videoProcessor": "/home/osmc/FFmpeg/ffmpeg",
	"cameras":
	[
		{
			"name": "Gambach Nord",
			"videoConfig":
			{
				"source": "-re -i https://verkehrsservice.hessen.de/syncdata/video/k5076.mp4",
				"maxStreams": 2,
				"maxWidth": 704,
				"maxHeight": 576,
				"vcodec": "h264_omx",
				"maxFPS": 25,
				"maxBitrate": 300,
				"additionalCommandline": " -loglevel verbose -report",
				"audio": false,
				"debug": true
			}
		}

homebridge is running under user osmc. FFmpeg command is running fine on the console with "libh264_omx" under the same user and the CPU load is reduced to about 45%. But when I start the stream via the homekit app eve I only receive "exited with error 1".

**Question**: How can I get more debug infos and get to know why FFmpeg exited or isn't running? syslog doesn't give me enough details here, except "error code 1".

Any hints or ideas appreciated.

**Comment by FastHogi** [comment]
I forget one thing to mention: for both approches I added at least a "additionalCommandline": "{blank space here}". Otherwise a command switch "-tune zerolatency" is added to FFMpeg and vcodec copy and vcodec h264_omx can't use "-tune zerolatency".

**Comment by FastHogi** [comment]
I found it by myself. With the outstanding pull request [197](https://github.com/KhaosT/homebridge-camera-ffmpeg/pull/197) the debug messages give me more details now what ffmpeg is doing or not. I've anyone else is having the same problem just replace line 334 in ffmpeg.js to "}.bind(this));"

**Comment by mrdc** [comment]
@FastHogi replacing https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/cd284406d1a67b88b6488fb455128a0b7a220e12/ffmpeg.js#L334
with "}.bind(this));" crashes Homebridge.

**Comment by nhatquang88** [comment]
I have same issue with you and still figuout how to solve that problem.
maybe if we try it with Laptop with Better GPU and it will solve?

**Comment by mrdc** [comment]
Problem is in incorrect vcodec copy implementation in ffmpeg.js

**Comment by nhatquang88** [comment]
@mrdc would u please post an example of your ffmpeg.js
I will try to put it at mine
