### ISSUE TITLE
Video problem with Vstarcam camera

### ISSUE THREAD

**Issue by Jaguaza** [KhaosT/homebridge-camera-ffmpeg#251]
Good I have this camera at home:
Model No: C7824WIP
-
Features | Features | Software limit position, lower Pan Tilt failure rate
System | OS | Embedded Linux OS
System security | Three level user authority management
Online users | Support 4 online visitors simultaneously
DDNS | Free DDNS
Control protocol | ONVIF 2.4 protocol, high interoperability
Processor | Hisilicon processor, built-in ARM926 @Max. 440MHz and a high-speed video co-processor.
Reset | Long press for 15 seconds to restore back to the factory settings
Collection | Image sensor | 1 / 4inch 720p Progressive scan CMOS sensor
CMOS | Support AWB, AGC, AE
Imaging area | 4.40mm × 2.52mm
SNR | ≥41dB
Minimum illumination | 0.8Lux / F1.4 (colorful model), 0.3Lux / F1. (B & W mode)
Lens / viewing angle | 3.6mm@F1.4/56.14˚
Night vision | Dual IR-CUT filter auto switch, 12pcs 850nmΦ5mm LED, 10m IR distance
IR control | IR turned on: night vision view enabled, infrared Ray, ICR auto detect. IR turned off: night vision disabled, infrared ray off, ICR stay in day view mode.
Video | Compression Format | H.264 Main Profile / H.264 Baseline Profile / MJPEG / JPEG Baseline
Video coding process | Multi-stream: 720P / 24fps + VGA / 30fps + QVGA / 30fps + 720P @ 1fsJPEG snapshot
Resolution | 720p / VGA / QVGA
Bit Rate | CBR / VBR, output bit rate range: 128 ~ 4096kbps
Max.Frame rate | 25fps
Picture Adjustment | Contrast, brightness, saturation, chroma are adjustable.
Audio | Input | Built in -48dB Microphone
Output | Built in speaker (8Ω1W) `
Sampling frequency / width | 8KHz / 16bit
Compression format | ADPCM / 32kbps
Network | Interface | 10Base-T / 100Base-TX, RJ45 connector
Network Protocol | TCP / IP, HTTP, TCP, UDP, SMTP, FTP, DHCP, DNS, DDNS, NTP, UPnP, RTSP, P2P, etc.
WIFI | WiFi802.11b / g / n
Antenna | 3dBi antenna, stronger signal, more stable
Wireless network security | One key setup WiFi
Storage | Storage mode | Local storage / client storage
Interface | Micro SD / TF
Pan-Tilt | P / T | Bread: 270 °, Tilt: 80 °
Preset Postion | Support up to 15 preset postions
Limit method | Software limit position, more accurate preset positions, lower Pan Tilt failure rate.
Alarm | Motion detection | Support motion detection
Alarm action | Video upload via email / FTP server, Mobile App alarm
Physical index | Rated Voltage | DC5 / 2A ± 0.3V
Power comsumption | Rated power: 3.0W (IR ON)
Working environment | Working Temperature: -20 ~ 70 ℃, Working Humidity 90%
Weight | Gross Weight: 330g (Note: in kind prevail)
Housing material | ABS plastics
Camera size | 145 x 110 x 125 mm (L × W × H)
Installation | Wall mounting, ceiling mounting

The issue is that I have it added to Home and I can see the image, but it plays a few seconds and freezes, in seconds seconds it continues playing and freezes again for several seconds.

Also when there is movement, for example, a person passing by, the image becomes pixilated, disfiguring the image that it shows.

This is the configuration that I have added to the homebridge installed on Synelogy.

 {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "CAMARA SALON",
                    "videoConfig": {
                        "source": "-rtsp_transport udp -re -i rtsp: // user: pass @ ip: port / udp / av0_0",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 30,
                        "maxBitrate": 300,
                        "packetSize": 1316
                    }

**Comment by Jaguaza** [comment]
Nobody can help me

**Comment by jobberns82** [comment]
Replace UDP by TCP

**Comment by Jaguaza** [comment]
If I replace udp with tcp, I lose the connection.

**Comment by jobberns82** [comment]
Is the stream in VLC working fine?

**Comment by Jaguaza** [comment]
If it works in VlC, ONVIF MANAGER, NAS SYNOLOGY AND 4 EYES.

**Comment by Jaguaza** [comment]
I play from iphone 7 plus

**Comment by jobberns82** [comment]
Try to make another url:
https://www.ispyconnect.com/man.aspx?n=Vstarcam#

**Comment by FrankBKK** [comment]
there is a firmware update available that adresses this issue BUT if you install this it disables web access to the cameras built-in configuration webserver  and you MUST manage it with VstarCam's IOS or Android App !
Not all functions are supported there and I highly recommend to check first if you can live with that.
