### ISSUE TITLE
config copy not working

### ISSUE THREAD

**Issue by netRunner0** [KhaosT/homebridge-camera-ffmpeg#254]
`        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Холл1",
                    "videoConfig": {
                        "source": "-i rtsp://10.0.0.36:8554/unicast",
                        "maxBitrate": 3000,
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "packetSize": 752,
                        "debug": true,
                        "audio": true
                    }
                }
            ]
        },

`

`Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://10.0.0.36:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2017.10.28
    comment         : LIVE555 Streaming Media v2017.10.28
  Duration: N/A, start: -0.350250, bitrate: N/A
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 1280x720, 25 fps, 24.92 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
**Filtergraph 'scale=1280:720' was defined for video output stream 0:0 but codec copy was selected.
Filtering and streamcopy cannot be used together**.`

**Comment by netRunner0** [comment]
Fix, 
https://github.com/KhaosT/homebridge-camera-ffmpeg/pull/181

**Comment by oleg77s** [comment]
296 -          ' -vf scale=' + width + ':' + height +
396 +          ((vcodec !== 'copy') ? (' -vf scale=' + width + ':' + height) : '') +

Fix not merged :(

**Comment by jeylites** [comment]
I'm having the same issue but don't know how to fix it.

**Cameras Used: REOLINK IP  (H264)**

I have a different syntax on the ffmpeg.js file?

```
((vf.length > 0) ? (' -vf ' + vf.join(',')) : ('')) +
          ' -b:v ' + vbitrate + 'k' +
          ' -bufsize ' + vbitrate+ 'k' +
          ' -maxrate '+ vbitrate + 'k' +
          ' -payload_type 99';
```
Config.js

    ```
  "name": "MAIN DOOR",
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:admin@192.168.1.200:554//h264Preview_01_main",
                        "stillImageSource": "-i http://192.168.1.200/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=admin",,
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxBitrate": 200,
                        "vcodec": "copy",
                        "audio": false,
                        "packetSize": 1316,
                        "hflip": false,
                        "additionalCommandline": "-x264-params intra-refresh=1:bframes=0",
                        "debug": false
```
