### ISSUE TITLE
Live disapperead

### ISSUE THREAD

**Issue by epalzeolithe** [KhaosT/homebridge-camera-ffmpeg#256]
Hello

i'm bit lost. Yesterday i setup on RPI3 a perfect camera Floureon HD 1080p with this JSON.
And today it dont work. I lost electrical supply during night. I tried to reboot several time but no way.

Snapshot every 10s works well. But now "no response" when i click on the camera.

I tried several things, including remove and rename the camera inside the JSON.

No way.

I tried to manually vlc the url, it works. I tried on command line ffmpeg with the command, i've got few errors but then i outputs correctly the video in a file.

Thanks in advance :)

{
  "platform":"Camera-ffmpeg",
  "cameras":[
     {
        "name":"Camera",
        "videoConfig":{
           "source":"-vcodec h264_mmal -re -i rtsp://192.168.3.9:554/rtsp_live2",
           "stillImageSource":"-i http://192.168.3.9/snapshot.cgi?user=admin&pwd=",
           "maxStreams":2,
           "maxWidth":320,
           "maxHeight":240,
           "maxFPS":16,
           "vcodec": "h264_omx",
           "packetSize": 188
        }
     }
  ]
}

**Comment by Tangheta** [comment]
Same issue. Adding "audio": false only helped for 1 out of 4 camera's

**Comment by frizby66** [comment]
Same with me..was working for a few days and no get No Response when try and view live stream.
"platforms": [{
		"platform": "Camera-ffmpeg",
		"logging": true,
		"cameras": [{
			"name": "Living Room",
			"videoConfig": {
				"source": "-re -i rtsp://xxxxxxxx@192.168.2.245:554/Streaming/Channels/101",
				"maxStreams": 2,
				"maxWidth": 480,
				"maxHeight": 270,
				"maxFPS": 10
			}
            }
