### ISSUE TITLE
HTTP Basic Auth with special characters

### ISSUE THREAD

**Issue by carlittoer** [KhaosT/homebridge-camera-ffmpeg#257]
Hi, 

My cam's running on port 8080 and requires basic HTTP authentication with both the username and password have special characters. 

i.e: http://user@domain.com:password!@ip:8080/path

I tried to escape @ in the username with %40 and ! with %21 which results in : 

http://user%40domain.com:password%21@ip:8080/path but the ffmpeg debug shows 401 unauthorized end of file....

From the browser, If I paste the escaped url, it doesn't work as well. 

Any hint on what i can do to make this work?

**Comment by jgmage** [comment]
Basic authentication isn't as simple as escaping characters, you need to do base64 encoding of the combination of the username:password.  Here is a starter link.  https://security.stackexchange.com/questions/29916/why-does-http-basic-authentication-encode-the-username-and-password-with-base64
