### ISSUE TITLE
ERROR: FFmpeg exited with code -2

### ISSUE THREAD

**Issue by dannyharuh** [KhaosT/homebridge-camera-ffmpeg#259]
is here anyone ho nows wat my problem is
 {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Overkapping",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:xxx@10.0.1.108:554/cam/realmonitor?channel=1&subtype=1",
                        "stillImageSource": "-i http://admin:xxx@10.0.1.108/cgi-bin/snapshot.cgi1",
                        "maxStreams": 10,
                        "maxWidth": 745,
                        "maxHeight": 576,
                        "maxFPS": 20,
                        "maxBitrate": 1024,
                        "packetSize": 1361
                    }
                }
            ]
        }

in vlc player the stream is working and also the snapshot is working but not in the homekit app

**Comment by llemtt** [comment]
I think that nothing can be said by only reading your config...

first of all test your input config launching ffmpeg!

ffmpeg -v verbose -rtsp_transport tcp -re -i rtsp://admin:xxx@10.0.1.108:554/cam/realmonitor?channel=1&subtype=1

then activate debug and post a log

**Comment by dannyharuh** [comment]
first of all test your source config launching ffmpeg! 
how do i test this ?

**Comment by dannyharuh** [comment]
apk add --no-cache ffmpeg ffmpeg-libs libpcap-dev
after this apk the problem is solved

**Comment by mrjackyliang** [comment]
Confirmed by @dannyharuh. The command works for me. All I had to do was put it into the startup script, and it will resolve itself every time I delete my Docker image and reinstall it.

**Comment by mapkyxa** [comment]
I'm using a Raspberry Pi and getting same problem with error -2
It also doesn't allow me to use apk command
I'm using geovision camera

**Comment by WAFFLE93** [comment]
@dannyharuh sorry to pester. I get "bash: apk: command not found" when attempting to use your possible solution. Im currently running Raspbian Buster Lite on a Pi 4.

**Comment by ServusNL** [comment]
> @dannyharuh sorry to pester. I get "bash: apk: command not found" when attempting to use your possible solution. Im currently running Raspbian Buster Lite on a Pi 4.

Run this command on your docker host. `sudo docker exec homebridge apk add --no-cache ffmpeg ffmpeg-libs libpcap-dev`

Fixed it for me, thanks!
