### ISSUE TITLE
The first image that slowly reveals then freezes

### ISSUE THREAD

**Issue by Maxmudjon** [KhaosT/homebridge-camera-ffmpeg#26]
The first image that slowly reveals then freezes
that can be a problem ?

**Comment by afrustagli** [comment]
I'm have the same problem. For me it seems it's ignoring the maxWidth and maxHeight properties. I've tried setting them at different resolutions (640x480, etc) but the "scale" seems to stay at 1920:1080 no matter what I do. Ideas?

```
-re -i rtsp://user:pass@192.168.1.xxx:10554/h264/ch1/main/av_stream -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 15 -f rawvideo -tune zerolatency -vf scale=1920:1080 -b:v 802k -bufsize 802k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params dGYJ7wWFnPUNFLgkq8AQf/QDhOFAoMMOGxDQ1nPQ srtp://192.168.1.xxx:64174?rtcpport=64174&localrtcpport=64174&pkt_size=1378
```

**Comment by KhaosT** [comment]
HomeKit caches the video resolution data. So if you already paired with the camera accessory and then change the maxWidth, it may ignore the changes. Please try unpair with the camera accessory and then reboot your phone before changing the maxWidth and re-pair with the camera.

**Comment by afrustagli** [comment]
I think the problem is actually in ffmpeg.js.  In all the conditionals that look like 

```javascript
if (maxWidth <= 640) {
```

should be

```javascript
if (maxWidth >= 640) {
```

Now scale is correctly set at 640:480, but that doesn't fix the streaming problem... I guess the pi can't handle processing the stream?

**Comment by Cloudore** [comment]
Same issue as OP, also using a Pi3
