### ISSUE TITLE
Camera external through firewall....

### ISSUE THREAD

**Issue by roe1974** [KhaosT/homebridge-camera-ffmpeg#260]
i have the problem to see the video in Homekit from external....due to my firewall.
Now my question:

Is the rtsp stream established between raspi and iOS Device (public IP) or between AppleTV and iOS Device (public IP) ... because the AppleTV is responsible for getting Home datas through the internet ?!?!?

thx for help

**Comment by tgerring** [comment]
I am able to view the video stream from an external IP without creating additional firewall rules, however I access the account through iCloud sharing as a Guest.

**Comment by roe1974** [comment]
i think my problen is that homebridge is running in my home network and the cam is in an other network (over OVPN) .. so the rtsp stream dont find the right way :(

**Comment by llemtt** [comment]
It depends, if your camera is on a different subnet (your ovpn is layer 3) it doesn't work locally, the whole HomeKit works only on the LAN.

If your ovpn is bridged (layer 2) it works.

**Comment by roe1974** [comment]
@llemtt 
its a layer 3 :( .... so there is no way over layer 3 ?
Home: 192.168.0.0/24
Garage: 192.168.2.0/24 (connected OVPN Layer 3 to Home)
But when i connect the iphone also over OVPN to the home router (192.168.10.0/24) then i have the stream in Apple Home App??

**Comment by llemtt** [comment]
no way with layer 3, only lan or remote via hub (AppleTV)

> But when i connect the iphone also over OVPN to the home router (192.168.z.0/24) then i have the stream in Apple Home App??

sounds very very strange

I can't understand how your iphone or your AppleTV can eventually see the cam because everything works on top of mdns, and multicasts (usually) don't get routed. Did you use Bonjour Discovery or similar app on iphone to check the hap announcements?

Curiosity... why vpn between garage and home? and why layer 3?

**Comment by roe1974** [comment]
@llemtt

the flat is in the 3rd floor... so no chance to connect undeeground garage directly ... therefore i have a mikrotik LTE router in the garage ... 
everything works on LAN ... and as described ... also when iphone is connected with OVPN (the screenshot funktion ... when you open the room in Home App ... even works without iphone in the tunnel)
i think its a firewall problem of the home router (mikrotik) ... because also the second cam which is in the same LAN as homebridge & ATV dont bring the rtsp stream when i am external....
