### ISSUE TITLE
FFmpeg command exits with "No such file or directory"

### ISSUE THREAD

**Issue by tgerring** [KhaosT/homebridge-camera-ffmpeg#261]
Hello and thank you for this project!

Currently, I am receiving a different execution result from FFmpeg depending on whether it is run inside this plugin or separately on the command line. Due to the use of Raspberry Pi, I have compiled FFmpeg with the OMX options. When setting this as `-vcodec`, it conflicts with the `-tune zerolatency` option that is defined at https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/master/ffmpeg.js#L31. Bypassing this option (initially resulting in an error `Unrecognized option 'tune'.`) was accomplished by adding `"additionalCommandline": " "` which I did not find documented anywhere, but very useful.

When I run the resulting on the command line, it works correctly and starts streaming data to my terminal session. Initially, I had a problem `* failed to open vchiq instance`, which was a result of running homebridge as a new user not added to the video group. After a quick `usermod -a -G video homebridge`, the command succeeds locally. Final working command (on terminal) is:

```
sudo -H -u homebridge bash -c 'ffmpeg -rtsp_transport tcp -i rtsp://192.168.1.20/axis-media/media.amp?streamprofile=Media?tcp -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 15 -f rawvideo   -vf scale=1280:720 -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 3360650 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ZNMaSE/KSSDA7SMmNNJquJOJfSehLJg5q7DdyE1C srtp://192.168.1.192:59258?rtcpport=59258&localrtcpport=59258&pkt_size=1316'
```
I was able to verify the stream is valid by viewing it in VLC. Similarly, to make watching logs easier, rather than run HomeBridge through systemd, I am mocking it on the command line with `sudo -H -u homebridge bash -c 'homebridge -U /var/lib/homebridge'` to ensure it starts with similar permissions.

However, when I view the log output from HomeBridge, FFmpeg exits with 1. Full related log output included below:
```
1/16/2019, 12:32:40 PM] [Camera-ffmpeg] Snapshot from Front Gate Gamera at 480x270
ffmpeg -i http://192.168.1.20/axis-cgi/jpg/image.cgi -t 1 -s 480x270 -f image2 -
[1/16/2019, 12:32:47 PM] [Camera-ffmpeg] Start streaming video from Front Gate Gamera with 1280x720@299kBit
ffmpeg -rtsp_transport tcp -i rtsp://192.168.1.20/axis-media/media.amp?streamprofile=Media?tcp -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 15 -f rawvideo   -vf scale=1280:720 -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 3360650 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ZNMaSE/KSSDA7SMmNNJquJOJfSehLJg5q7DdyE1C srtp://192.168.1.192:59258?rtcpport=59258&localrtcpport=59258&pkt_size=1316




ffmpeg version git-2019-01-15-95a27a8 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --enable-gpl --enable-nonfree --enable-mmal --enable-omx --enable-omx-rpi
  libavutil      56. 25.100 / 56. 25.100
  libavcodec     58. 44.100 / 58. 44.100
  libavformat    58. 26.100 / 58. 26.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100

Input #0, rtsp, from 'rtsp://192.168.1.20/axis-media/media.amp?streamprofile=Media?tcp':

  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 20 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
: No such file or directory

[1/16/2019, 12:32:50 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1
```

I did not see the comment about audio support until after I have compiled FFmpeg (for the third time ;), so I tried to set `"audio": false`, but that did not help either. At this point, I'm not sure what other things to try. Snapshots work correctly, but something is failing when FFmpeg tries to stream inside HomeBridge.

Any advice would be appreciated.

**Comment by tgerring** [comment]
I have re-compiled with libfdk-aac support to no avail. I also see that similar issues #213 #163 exist

**Comment by llemtt** [comment]
using command line you have to escape the & like this \&

otherwise they will be interpreted by the shell and result in command splitting and sending part to background...

**Comment by tgerring** [comment]
Ooops, good catch @llemtt! Updated the command and stream proceeds to deliver to my terminal at around 11fps

**Comment by tgerring** [comment]
**UPDATE:** It appears I have found a workaround! I tried turning on debug logging as much as possible. First I tried `DEBUG=* homebridge -D` without success.

From here, I decided to enable `-loglovel debug` on FFMpeg to see if I could capture the error there, but an error never occurred! Instead, the video streamed successfully. I tried the updated config on my older RasPi 1 (without libfdk-aac support) and it worked there as well. So finally what enabled me to move past this "No such file or directory" error was to update homebridge's config.json file to include the following setting for homebridge-camera-ffmpeg:

```
"videoConfig": {
    "additionalCommandline": "-loglevel info"
}
```

This had the dual benefit of fixing the conflict with the OMX coded and `-tune zerolatency` as well as resolving the abrupt exit from FFMpeg itself. I would love to know this fix works for others experiencing similar problems.

**Comment by tgerring** [comment]
Fixed by #263

**Comment by burnbrigther** [comment]
@tgerring Did you ultimately have success in getting your Axis camera to work?  I am still struggling to get my 3343 to display to home.  Any chance you could share your config?

**Comment by tgerring** [comment]
@burnbrigther Here is my working config. The main trick to fix streaming was setting additionalCommandLine. This gives more debug info in FFmpeg itself so even if it does not magically fix your problem, you should have better detail to debug the probem. Good luck!

```          "videoConfig": {
            "source": "-rtsp_transport tcp -i rtsp://192.168.1.20/axis-media/media.amp?streamprofile=Media?tcp",
            "stillImageSource": "-i http://192.168.1.20/axis-cgi/jpg/image.cgi",
            "maxStreams": 3,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 8,
            "vcodec": "h264_omx",
            "audio": false,
            "videoFilter": "scale=1280:720:in_range=mpeg",
            "additionalCommandline": "-loglevel verbose",
            "debug": true
          }
```

**Comment by burnbrigther** [comment]
Thank you for sharing.  Here is mine for comparison:
```
        "platform":"Camera-ffmpeg",
         "cameras": [
            {
                "name": "FRONT ENTRANCE",
                "videoConfig": {
                  "source": "-rtsp_transport tcp -i rtsp://192.168.1.231/axis-media/media.amp?streamprofile=Media?tcp",
                  "maxStreams": 3,
                  "maxWidth": 800,
                  "maxHeight": 600,
                  "maxFPS": 8,
		  "vcodec": "h264_omx",
		  "videoFilter": "scale=800:600:in_range=mpeg",
                  "additionalCommandline": "-loglevel verbose",
		  "debug": true
                }
            }
```
May i ask how you handle authentication to your camera?  I had a configuration for rtsp://user@pass:192....
Also - do you have any special parameters on startup?  For testing, I am simply starting with:
homebridge (not sudo).
And finally, where does the ffmpeg logging debug go to?  I cannot seem to locate it.
Thank you for your help.

**Comment by burnbrigther** [comment]
Axis P3343 camera is working fine.  Working on trying to get 2-way (intercom) audio working.
