### ISSUE TITLE
ERROR: FFmpeg exited with code 1

### ISSUE THREAD

**Issue by Crox77** [KhaosT/homebridge-camera-ffmpeg#265]
Hi after some help please

I have installed FFmpeg and the plugin on my Mac ok, ive successfully added the camera to my home App however everytime I click the video feed in my app Homebridge shows this error: ERROR: FFmpeg exited with code 1.
ive tried searching on GitHub and have found people with the similar fault but can not seem to find an answer as to what is wrong.
Please help
Thanks Paul

**Comment by Gamer106** [comment]
in your config, add "audio": false below your camera settings

**Comment by Tangheta** [comment]
Same issue. Adding "audio": false only helped for 1 out of 4 camera's

**Comment by llemtt** [comment]
Hi Paul, you should at least do the following:

- tell what your camera and his configuration are
- activate debugging (i.e. into config -> "debug": true) and post the log

btw exit code 1 usually means that some parameters to ffmpeg are wrong

**Comment by Tangheta** [comment]
My config is:
{
      "platform" : "Camera-ffmpeg",
      "cameras" : [
        {
          "name" : "Garage",
          "videoConfig" : {
            "vcodec" : "h264_omx",
            "source" : "-rtsp_transport tcp -re -i rtsp://<credentials>@10.0.1.21:554/Streaming/Channels/102",
            "maxFPS" : 20,
            "audio" : false,
            "maxHeight" : 360,
            "maxStreams" : 4,
            "maxWidth" : 640,
            "stillImageSource" : "-i http://<credentials>@10.0.1.21/ISAPI/Streaming/channels/101/picture"
          }
        },
        {
          "name" : "Gangnew",
          "videoConfig" : {
            "vcodec" : "h264_omx",
            "source" : "-rtsp_transport tcp -re -i rtsp://<credentials>@10.0.1.24/live",
            "maxFPS" : 20,
            "audio" : false,
            "maxHeight" : 360,
            "maxStreams" : 4,
            "maxWidth" : 640,
            "stillImageSource" : "-i http://<credentials>@10.0.1.24/cgi-bin/snapshot.cgi?1"
          }
        },
        {
          "name" : "Gangold",
          "videoConfig" : {
            "vcodec" : "h264_omx",
            "source" : "-rtsp_transport tcp -re -i rtsp://<credentials>@10.0.1.22:554/Streaming/Channels/102",
            "maxFPS" : 20,
            "audio" : false,
            "maxHeight" : 360,
            "maxStreams" : 4,
            "maxWidth" : 640,
            "stillImageSource" : "-i http://<credentials>@10.0.1.22/Streaming/channels/102/picture"
          }
        },
        {
          "name" : "Living",
          "videoConfig" : {
            "vcodec" : "h264_omx",
            "source" : "-rtsp_transport tcp -re -i rtsp://<credentials>@10.0.1.20/Streaming/Channels/102",
            "maxFPS" : 20,
            "audio" : false,
            "maxHeight" : 360,
            "maxStreams" : 4,
            "maxWidth" : 640,
            "stillImageSource" : "-i http://<credentials>@10.0.1.20/Streaming/channels/102/picture"
          }
        }
      ],
      "name" : "device"

**Comment by llemtt** [comment]
waiting for the debug log...

anyway I don't understand why you put "-rtsp_transport tcp" in your config

brand and model of your camera?

**Comment by tarbychark** [comment]
Also having the same issue. Here's one of my camera configs (Have 5 that are all identical other than IP):

{
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Kitchen Cam",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://10.0.1.44:8554/unicast",
                        "stillImageSource": "-i rtsp://10.0.1.44:8554/unicast",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 25,
                        "vcodec": "h264",
                        "packetSize": 752,
                        "maxBitrate": 512,
                        "debug": true
                    }
                },

Here are some logs with debugging enabled:

ffmpeg -rtsp_transport tcp -i rtsp://10.0.1.38:8554/unicast -map 0:0 -vcodec h264 -pix_fmt yuv420p -r 25 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 10630649 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params +3PoWxPOulyTitMt3O3uUNzovurRhB0/9HVr59pN srtp://10.0.1.17:63888?rtcpport=63888&localrtcpport=63888&pkt_size=752 -loglevel debug
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1_5 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack

  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Splitting the commandline.
Reading option '-rtsp_transport' ...
 matched as AVOption 'rtsp_transport' with argument 'tcp'.
Reading option '-i' ... matched as input url with argument 'rtsp://10.0.1.38:8554/unicast'.
Reading option '-map' ...
 matched as option 'map' (set input stream mapping) with argument '0:0'.
Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'h264'.
Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'yuv420p'.
Reading option '-r' ... matched as option 'r' (set frame rate (Hz value, fraction or abbreviation)) with argument '25'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.
Reading option '-tune' ...
 matched as AVOption 'tune' with argument 'zerolatency'.
Reading option '-vf' ... matched as option 'vf' (set video filters) with argument 'scale=1280:720'.
Reading option '-b:v' ... matched as option 'b' (video bitrate (please use -b:v)) with argument '299k'.
Reading option '-bufsize' ...
 matched as AVOption 'bufsize' with argument '299k'.
Reading option '-maxrate' ...
 matched as AVOption 'maxrate' with argument '299k'.
Reading option '-payload_type' ...
 matched as AVOption 'payload_type' with argument '99'.
Reading option '-ssrc' ...
 matched as AVOption 'ssrc' with argument '10630649'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rtp'.

Reading option '-srtp_out_suite' ...
 matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
Reading option '-srtp_out_params' ...
 matched as AVOption 'srtp_out_params' with argument '+3PoWxPOulyTitMt3O3uUNzovurRhB0/9HVr59pN'.
Reading option 'srtp://10.0.1.17:63888?rtcpport=63888&localrtcpport=63888&pkt_size=752' ... matched as output url.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Finished splitting the commandline.

Parsing a group of options: global .
Applying option loglevel (set logging level) with argument debug.
Successfully parsed a group of options.
Parsing a group of options: input url rtsp://10.0.1.38:8554/unicast.
Successfully parsed a group of options.
Opening an input file: rtsp://10.0.1.38:8554/unicast.

[tcp @ 0x7fd2be625140] No default whitelist set

[tcp @ 0x7fd2be625140] Original list of addresses:
[tcp @ 0x7fd2be625140] Address 10.0.1.38 port 8554

[tcp @ 0x7fd2be625140] Interleaved list of addresses:
[tcp @ 0x7fd2be625140] Address 10.0.1.38 port 8554
[tcp @ 0x7fd2be625140] Starting connection attempt to 10.0.1.38 port 8554

[tcp @ 0x7fd2be625140] Successfully connected to 10.0.1.38 port 8554

[rtsp @ 0x7fd2c3800000] SDP:
v=0
o=- 1549497936855297 1 IN IP4 10.0.1.38
s=LIVE555 Streaming Media v2017.10.28
i=LIVE555 Streaming Media v2017.10.28
t=0 0
a=tool:LIVE555 Streaming Media v2017.10.28
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:LIVE555 Streaming Media v2017.10.28
a=x-qt-text-inf:LIVE555 Streaming Media v2017.10.28
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:0
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=ffffc01f;sprop-parameter-sets=Z0LAH52oFAFuhAAAAwAEAAADAMoQ,aO48gA==
a=x-dimensions:1280,720
a=control:track1


Failed to parse interval end specification ''

[rtsp @ 0x7fd2c3800000] video codec set to: h264

[rtsp @ 0x7fd2c3800000] Extradata set to 0x7fd2c1203690 (size: 33)

[rtsp @ 0x7fd2c3800000] setting jitter buffer size to 0

[rtsp @ 0x7fd2c3800000] hello state=0

Failed to parse interval end specification ''

[h264 @ 0x7fd2c3004000] nal_unit_type: 7(SPS), nal_ref_idc: 3

[h264 @ 0x7fd2c3004000] nal_unit_type: 8(PPS), nal_ref_idc: 3

[h264 @ 0x7fd2c3004000] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x7fd2c3004000] nal_unit_type: 8(PPS), nal_ref_idc: 3

[h264 @ 0x7fd2c3004000] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2

[h264 @ 0x7fd2c3004000] Format yuv420p chosen by get_format().
[h264 @ 0x7fd2c3004000] Reinit context to 1280x720, pix_fmt: yuv420p

[h264 @ 0x7fd2c3004000] Frame num gap 136 134

[h264 @ 0x7fd2c3004000] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2

    Last message repeated 12 times
[h264 @ 0x7fd2c3004000] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x7fd2c3004000] nal_unit_type: 8(PPS), nal_ref_idc: 3

[h264 @ 0x7fd2c3004000] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x7fd2c3004000] nal_unit_type: 8(PPS), nal_ref_idc: 3
[h264 @ 0x7fd2c3004000] nal_unit_type: 5(IDR), nal_ref_idc: 3

[h264 @ 0x7fd2c3004000] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2

    Last message repeated 5 times
[rtsp @ 0x7fd2c3800000] All info found
[rtsp @ 0x7fd2c3800000] rfps: 24.416667 0.016680
    Last message repeated 1 times

[rtsp @ 0x7fd2c3800000] rfps: 24.500000 0.013078
[rtsp @ 0x7fd2c3800000] rfps: 24.583333 0.010223
[rtsp @ 0x7fd2c3800000] rfps: 24.666667 0.008115
[rtsp @ 0x7fd2c3800000] rfps: 24.750000 0.006755
    Last message repeated 1 times
[rtsp @ 0x7fd2c3800000] rfps: 24.833333 0.006141
[rtsp @ 0x7fd2c3800000] rfps: 24.916667 0.006275
[rtsp @ 0x7fd2c3800000] rfps: 25.000000 0.007155
[rtsp @ 0x7fd2c3800000] rfps: 25.083333 0.016606
[rtsp @ 0x7fd2c3800000] rfps: 25.083333 0.008783
[rtsp @ 0x7fd2c3800000] rfps: 25.166667 0.016025
[rtsp @ 0x7fd2c3800000] rfps: 25.166667 0.011158
[rtsp @ 0x7fd2c3800000] rfps: 25.250000 0.016192
[rtsp @ 0x7fd2c3800000] rfps: 25.250000 0.014280
[rtsp @ 0x7fd2c3800000] rfps: 25.333333 0.018149
[rtsp @ 0x7fd2c3800000] rfps: 25.416667 0.018765
[rtsp @ 0x7fd2c3800000] rfps: 50.000000 0.002679

Input #0, rtsp, from 'rtsp://10.0.1.38:8554/unicast':

  Metadata:
    title           : LIVE555 Streaming Media v2017.10.28
    comment         : LIVE555 Streaming Media v2017.10.28
  Duration: N/A, start: 0.839656
, bitrate: N/A

    Stream #0:0, 42, 1/90000: Video: h264 (Constrained Baseline), 1 reference frame, yuv420p(progressive, left), 1280x720, 0/1
, 25 fps, 50 tbr, 90k tbn, 50 tbc
Successfully opened the file.
Parsing a group of options: output url srtp://10.0.1.17:63888?rtcpport=63888&localrtcpport=63888&pkt_size=752.
Applying option map (set input stream mapping) with argument 0:0.

Applying option vcodec (force video codec ('copy' to copy stream)) with argument h264.
Applying option pix_fmt (set pixel format) with argument yuv420p.

Applying option r (set frame rate (Hz value, fraction or abbreviation)) with argument 25.
Applying option f (force format) with argument rawvideo.
Applying option vf (set video filters) with argument scale=1280:720.
Applying option b:v (video bitrate (please use -b:v)) with argument 299k.
Applying option f (force format) with argument rtp.
Successfully parsed a group of options.
Opening an output file: srtp://10.0.1.17:63888?rtcpport=63888&localrtcpport=63888&pkt_size=752.

Matched encoder 'libx264' for codec 'h264'.

[srtp @ 0x7fd2be43fa40] No default whitelist set

[rtp @ 0x7fd2c150b6c0] No default whitelist set

[udp @ 0x7fd2c17143c0] No default whitelist set

[udp @ 0x7fd2c150c480] No default whitelist set

[udp @ 0x7fd2c150c480] bind failed: Address already in use

srtp://10.0.1.17:63888?rtcpport=63888&localrtcpport=63888&pkt_size=752: Input/output error

[2/7/2019, 12:10:58 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1



This all worked fine on my previous Mac. Issue started after getting a new Mini and setting everything back up. Running 10.14.4 Beta 2 (Issue occurred on 10.14.2 and 10.14.3 as well)

Any suggestions would be appreciated!

**Comment by Crox77** [comment]
Ok so I have added debug to my Config file and this is what It says:

  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1_6 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Splitting the commandline.
Reading option 'http://user:password@192.168.0.6/videostream.cgi?resolution=8&rate=13' ... matched as output url.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:0'.
Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'libx264'.
Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'yuv420p'.
Reading option '-r' ... matched as option 'r' (set frame rate (Hz value, fraction or abbreviation)) with argument '15'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.
Reading option '-tune' ...
 matched as AVOption 'tune' with argument 'zerolatency'.
Reading option '-vf' ... matched as option 'vf' (set video filters) with argument 'scale=1280:720'.
Reading option '-b:v' ... matched as option 'b' (video bitrate (please use -b:v)) with argument '299k'.
Reading option '-bufsize' ...
 matched as AVOption 'bufsize' with argument '299k'.
Reading option '-maxrate' ...
 matched as AVOption 'maxrate' with argument '299k'.
Reading option '-payload_type' ...
 matched as AVOption 'payload_type' with argument '99'.
Reading option '-ssrc' ...
 matched as AVOption 'ssrc' with argument '10395826'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rtp'.
Reading option '-srtp_out_suite' ...
 matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
Reading option '-srtp_out_params' ...
 matched as AVOption 'srtp_out_params' with argument 'K8xFpnaAHB7lH3n2ipVrHuNfvOdoTiVJi5ZZgoj1'.
Reading option 'srtp://192.168.0.3:63282?rtcpport=63282&localrtcpport=63282&pkt_size=1316' ... matched as output url.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Finished splitting the commandline.

Parsing a group of options: global .
Applying option loglevel (set logging level) with argument debug.
Successfully parsed a group of options.
Parsing a group of options: output url http://user:password@192.168.0.6/videostream.cgi?resolution=8&rate=13.
Successfully parsed a group of options.
Opening an output file: http://user:password@192.168.0.6/videostream.cgi?resolution=8&rate=13.

[NULL @ 0x7fef20808800] Unable to find a suitable output format for 'http://user:password@192.168.0.6/videostream.cgi?resolution=8&rate=13'
http://user:password@192.168.0.6/videostream.cgi?resolution=8&rate=13: Invalid argument

[2/9/2019, 10:11:09 AM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

all seems to be ok right up until it looks for an output format,
Any ideas how to fix this?

Thanks

**Comment by llemtt** [comment]
your error

[NULL @ 0x7fef20808800] Unable to find a suitable output format for 'http://user:password@192.168.0.6/videostream.cgi?resolution=8&rate=13'
http://user:password@192.168.0.6/videostream.cgi?resolution=8&rate=13: Invalid argument

wrong config!

your log is missing the first part...

anyway, missing "-i " before "http..." ?

**Comment by Crox77** [comment]
Thank you I will edit my config later, 1 question should there be a space after the -i and the http?

**Comment by llemtt** [comment]
> should there be a space after the -i and the http?

yes
