### ISSUE TITLE
enabling audio .....

### ISSUE THREAD

**Issue by roe1974** [KhaosT/homebridge-camera-ffmpeg#268]
Hi ....
How this....
„To use audio ffmpeg must be compiled with --enable-libfdk-aac“
works exactly ?
nothing found in wiki 

richard

**Comment by llemtt** [comment]
these worked for me:

git clone https://github.com/mstorsjo/fdk-aac.git
cd fdk-aac
./autogen.sh
./configure --prefix=/usr/local --enable-shared --enable-static
make -j4
sudo make install
sudo ldconfig

sudo git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg/
sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree --enable-mmal --enable-libfdk-aac
sudo make -j4
sudo make install

**Comment by burnbrigther** [comment]
Problem:
```
pi@raspberrypi:~/fdk-aac/FFmpeg $ sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree --enable-mmal --enable-libfdk-aac
ERROR: OMX_Core.h not found
```

**Comment by burnbrigther** [comment]
This fixes that:
sudo apt-get install libomxil-bellagio-dev

**Comment by roe1974** [comment]
ffmpeg is allready installed on my PI (with sudo apt-get) .....
how is the process in this case ?
Richard

**Comment by tokfrans03** [comment]
https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Raspberry-PI
