### ISSUE TITLE
Google drive snapshot instructions no longer correct

### ISSUE THREAD

**Issue by Tangheta** [KhaosT/homebridge-camera-ffmpeg#269]
Dear, 

In the info it says:
> https://developers.google.com/drive/v3/web/quickstart/nodejs
> 
> In Step 1-h the working directory should be the .homebridge directory
> Skip Step 2 and 3
> And in step 4, use the quickstart.js included in the plugin itself. And to do this you need to run the command from the plugin directory. Then just follow steps a to c

However, I cannot find a step 1-H in https://developers.google.com/drive/v3/web/quickstart/nodejs.
I can't get this to work. I've added the credentials.json in the .homebridge directory. But when I start node quickstart from the ffmpeg folder I get the message " !Error: ENOENT: no such file or directory, open '/home/pi/.homebridge/client_secret.json'

Can someone please help me to enable this awesome feature?

**Comment by NorthernMan54** [comment]
It looks like google has updated there instructions and after looking at it, I believe the flow should be

In Step 1, download the configuration file into your `.homebridge` directory, and name it `client_secret.json`
Skip Step 2 and 3
And in step 4, from the homebridge-camera-ffmpeg directory, run
`node quickstart.js`

Then just follow steps a to c

If you can confirm the above worked, please let me know and I will update the README

**Comment by Tangheta** [comment]
I hereby confirm that this works. Thanks a lot!

**Comment by Andi-Coder** [comment]
What do you mean with "follow steps a to c"?

**Comment by Andi-Coder** [comment]
> It looks like google has updated there instructions and after looking at it, I believe the flow should be
> 
> In Step 1, download the configuration file into your `.homebridge` directory, and name it `client_secret.json`
> Skip Step 2 and 3
> And in step 4, from the homebridge-camera-ffmpeg directory, run
> `node quickstart.js`
> 
> Then just follow steps a to c
> 
> If you can confirm the above worked, please let me know and I will update the README

What you mean with „ Then just follow steps a to c“?

**Comment by NorthernMan54** [comment]
These are the steps

https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Uploading-Snapshots-to-Google
