### ISSUE TITLE
This plug-in works on raspberry pi 3

### ISSUE THREAD

**Issue by Maxmudjon** [KhaosT/homebridge-camera-ffmpeg#27]
This plug-in works on raspberry pi 3

**Comment by grabidou** [comment]
What steps did you take to get this running on Raspberry pi 3?

**Comment by Maxmudjon** [comment]
install homebridge
install plugin homebridge-camera-ffmpeg
edit config.json
install ffmpeg

**Comment by grabidou** [comment]
Sorry, i wasn't clear in my last post.  How did you install FFMPEG on the raspberry pi.  I have this running and installed on MacOS, but am in the process of moving over to a raspberry pi 3 and taking this off the Mac.  I am having trouble trying to find an install and instructions on how to get FFMPEG installed on the pi.  I already have the home bridge plugin and the config.json set (from my Mac).  Appreciate the help!

**Comment by Maxmudjon** [comment]
sudo wget http://goo.gl/B1w9DR -O ffmpeg.deb
sudo dpkg -i ffmpeg.deb

**Comment by Maxmudjon** [comment]
conversely, I want to install Mac OS Sierra

**Comment by grabidou** [comment]
Thank you!!!

Running the second command I get this below.  Sorry for the Noob questions, this is definitely a learning experience for me.

pi@raspberrypi:~ $ sudo dpkg -i ffmpeg.deb
dpkg: error processing archive ffmpeg.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 ffmpeg.deb

**Comment by Maxmudjon** [comment]
where the first team in what directory or place knocked

**Comment by Maxmudjon** [comment]
write command - ls

**Comment by grabidou** [comment]
Ok, finally got the FFMPEG installed... now the camera's are not showing in the home app...  this is what i have in my config.json...  this works on MacOS, is it different for the pi?

{
								"platform": "Camera-ffmpeg",
								"cameras": [
									{
										"name": "FrontIP",
										"videoConfig": {
											"source": "-re -i rtsp://user:pw@10.0.1.93/h264/ch1/sub/av_stream",
											"stillImageSource": "-i http://user:pw@10.0.1.93/Streaming/Channels/1/picture",
											"masStreams": 2,
											"maxWidth": 640,
											"maxHeight": 480,
											"maxFPS": 15
										}
									}
								]
							},

**Comment by dickdoof** [comment]
@grabidou 
i am facing the same issue that the cameras are not showing up in the home app. had you been able to solve the issue?
Thanks in advance!

**Comment by Maxmudjon** [comment]
![unknown](https://cloud.githubusercontent.com/assets/23142922/21596129/a41ee072-d158-11e6-8ec0-5e91d581e838.jpeg)
I just ran through the MAC and works fine
but on Raspberry PI 3 slows and there is 1 FPS

**Comment by grabidou** [comment]
@dickdoof
I haven't been able to get this to work on the rPi3. I've been running everything else on the pi and running another instance of home ridge for my cameras on the Mac. Hoping to try and get the cameras going on the pi soon, just haven't had a bunch of time.
