### ISSUE TITLE
mjpeg instead of rtsp ? 

### ISSUE THREAD

**Issue by roe1974** [KhaosT/homebridge-camera-ffmpeg#271]
hi
can i use as „source“ also the mjpeg stream instead of rtsp ?
and what are the parameters -re -i ?

regards, richard

**Comment by damianromanowski** [comment]
-re -f mjpeg -i [http://...]

**Comment by kafes33** [comment]
Hi, I have a similar problem. I have surveillance camera (on synology – AirCam OD-2060HD). Camera hasn't show in homekit... Is everythings all right, please?
Thank you very much:)

{
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "OKO",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://192.168.1.111:5033/webapi/entry.cgi?api=SYNO.SurveillanceStation.Stream.VideoStreaming&version=1&method=Stream&format=mjpeg&cameraId=7&StmKey=050a302be0d5f6a827d90f2c95fc0834",
                        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30
                    }
                }
            ]
        },
