### ISSUE TITLE
battery powered cam ... wake up the cam ?

### ISSUE THREAD

**Issue by roe1974** [KhaosT/homebridge-camera-ffmpeg#272]
i use one battery powered cam ... at this cam the first snapshot is always black... because the cam needs time to wake up...about 3seconds
is there a way to wake up the cam before showing the snapshot
in apple home app ?

Richard

**Comment by macjl** [comment]
Hello,
To solve same kind of issue, I've added '-ss 00:00:03' parameter in the 'stillImageSource' section.
Maybe it would help you!

Jean-Laurent

**Comment by macjl** [comment]
I'm using a UVC Cam for this, not an URL. I'm using this settings :
`"source": "-re -r 6 -s 1280x720 -f video4linux2 -i /dev/video0",
"stillImageSource": "-s 1280x720 -ss 00:00:03 -f video4linux2 -i /dev/video0"`
