### ISSUE TITLE
Cam -> Raspi (Homebridge) -> AppleTV -> Firewall -> iPhone (Internet) ... please help !

### ISSUE THREAD

**Issue by roe1974** [KhaosT/homebridge-camera-ffmpeg#273]
I have running a cam with the ffmpeg plugin.
In LAN everything is OK.
But i have problems to getthe rtsp traffic through the firewall.
From outside, when i open the room in the Home App, i get the snapshot, but when i open the cam, there is no stream. its probably blocked by the FW.
When i am outside, the log in Homebridge is as follows:

10.10.20.8: Cam
10.10.20.244: AppleTV

`Feb 04 19:16:53 homebridge-raspi homebridge[16971]: -re -i rtsp://10.10.20.8:554/mjpeg.sdp -threads 0 -vcodec h264_omx -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params EfRDtvIzqbTENsvWutLYc9wTvgZCNT srtp://10.10.20.244:51903?rtcpport=51903&localrtcpport=51903&pkt_size=1378
`
so my question: is the stream established from cam through raspi through AppleTV to iPhone ?

I see blocked incoming udp packets on firewall (dst-port 16403 or 16407 or 16405) .. i think these are  ports from Apple for RTP ?....
but when in NAT this traffic to the appleTV, i still have no stream.
Has anybody a similar installation behind a firewall (i use mikrotik)

thx for help
Richard

**Comment by llemtt** [comment]
> so my question: is the stream established from cam through raspi through AppleTV to iPhone ?

yes and no

cam streams to AppleTV (the hub) that has an (already established) IPv6 tunnel to iPhone through Apple cloud servers

the actual technology/infrastructure/frameworks/library used is the same as FaceTime

so there should be no problem being behind a nat/firewall

can't remember if 6on4 tunnel uses tcp or udp

and still don't know what happens if both iPhone and AppleTV, or cam, are on IPv6 or WAN (in such a case a direct streaming is possible without fancy nat/firewall punching...)

**Comment by roe1974** [comment]
i have internal disabled ipV6 .... should i enable this ?

**Comment by llemtt** [comment]
no, it's not necessary, everything is supposed to work over IPv4

anyway does your mobile provider use IPv6?

**Comment by roe1974** [comment]
ok, facetime works without problem......
what now ?
Richard

**Comment by llemtt** [comment]
so it's very unlikely that's a firewall/nat problem

anyway you can still try disabling firewall just for testing purposes!

do you have other homekit/homebridge devices? do they work from remote?

**Comment by roe1974** [comment]
i use homebridge-homematic plug in ... all devices works perfectly
ATV ist the latest 4k modell
initiating the stream from external i see always this in FW log:

`09:48:38 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:46 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:47 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:48 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:49 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:50 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:51 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:52 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:54 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:55 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:57 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80 
09:48:58 firewall,info drop-not-LAN-packets input: in:ether1_WAN out:(unknown 0), src-mac 00:01:5c:22:78:81, proto UDP, 213.162.73.89:55688->212.286.51.125:16403, len 80`

212.286.51.125 is my external IP
even when i forward all UDP traffic ... no change
even when i port forward UDP Port 16403 to internal IP ATV Port 16403 - no change

**Comment by llemtt** [comment]
disable firewall and try again

**Comment by roe1974** [comment]
so..... with FW deactivated it works.. but this is not an option ;-)
Here the log ... initiated the stream from external (iPhone on LTE).
No video until it shows "camera not available" in Home App
[syslog.txt](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/2844391/syslog.txt)

Hope the log can help to find the problem :-)
Richard

**Comment by roe1974** [comment]
found the following........
My ports for the two cams are: 42819, 34253

when i do a netstat -lnpt i see this ports listening tcp6 ?? tcp6 is disbaled on my router ... why ?

`pi@homebridge-raspi:~ $ netstat -lnpt
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 192.168.0.18:9090       0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp6       0      0 :::41313                :::*                    LISTEN      -
tcp6       0      0 :::40003                :::*                    LISTEN      -
tcp6       0      0 :::42819                :::*                    LISTEN      -
tcp6       0      0 :::18088                :::*                    LISTEN      -
tcp6       0      0 :::44137                :::*                    LISTEN      -
tcp6       0      0 :::18089                :::*                    LISTEN      -
tcp6       0      0 :::38635                :::*                    LISTEN      -
tcp6       0      0 :::34253                :::*                    LISTEN      -
tcp6       0      0 :::45135                :::*                    LISTEN      -
tcp6       0      0 :::39377                :::*                    LISTEN      -
tcp6       0      0 :::51826                :::*                    LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 :::44221                :::*                    LISTEN      -
tcp6       0      0 :::43581                :::*                    LISTEN      -
tcp6       0      0 :::33823                :::*                    LISTEN      -
`

**Comment by llemtt** [comment]
Disabling IPv6 on router basically means two things
- the router doesn't route ip6
- the router doesn't assign routable ip6 addresses to clients

The IPv6 stack has to be eventually enabled/disabled on the clients themselves, and if enabled they auto assign local addresses, i.e. addresses that work only on local lan.

**Comment by llemtt** [comment]
> so..... with FW deactivated it works.. but this is not an option ;-)
> Here the log ... initiated the stream from external (iPhone on LTE).
> No video until it shows "camera not available" in Home App
> [syslog.txt](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/2844391/syslog.txt)
> 
> Hope the log can help to find the problem :-)
> Richard

from your log everything between cam, ffmpeg and 192.168.0.244 (AppleTV?) works fine

**Comment by roe1974** [comment]
yes .... .244 is appleTV
so its a firewall problem ?

**Comment by roe1974** [comment]
i have only one NAT rule .... masquerade WAN
thats it .... hmmmmmm

**Comment by roe1974** [comment]
problem solved ;-)
it was the "up" Cache from my Internet Modem.
Modem reset .... and everything works fine now .....
Richard
