### ISSUE TITLE
Sometimes i see a wrong picture (2 cams installed)

### ISSUE THREAD

**Issue by roe1974** [KhaosT/homebridge-camera-ffmpeg#279]
Sometimes when i open the Home App an go in the room from the 1st cam, i see the last picture of the other cam, before the new snapshot is loaded .... anyone else this poblem ?

Richard

**Comment by nathankellenicki** [comment]
Yes, I have this problem too. It's not a huge issue, it's just a flash as it refreshes in about a second or two, but it is there.
