### ISSUE TITLE
Change Refresh Time for Snapshot Dafang/HomeKit/Homebridge

### ISSUE THREAD

**Issue by renedivx** [KhaosT/homebridge-camera-ffmpeg#281]
Hello,

i install this plugin and use the Xioami Dafang. All works fine.
In Homekit i see at favorites the Snapshot. Yesterday the snapshot refresh all 12 seconds. Today all 60 seconds. But i dont change anything.
Why happend this? Is it possible to change the time byself for snapshot. For example.5 seconds or again back to 12 seconds?

My Config looks like this

                    "name": "Camera Name",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://IP/unicast",
                        "stillImageSource": "-i http://user:pw@IP/cgi-bin/currentpic.cgi",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 21,
                        "maxBitrate": 299,
                        "vcodec": "h264_omx",
                        "audio": false,
                        "packetSize": 188

Thanks
Best regards rene

**Comment by x23piracy** [comment]
Hi,

for with this plugin and the xiaofang S1 the stillimage doesnt work but streaming does, but only for a specific distance maybe 3-5 minutes then it finally crashes the rtsp server on the cam until reboot or manually restart of the service.
