### ISSUE TITLE
"No Response" HomeKit Windows 10 DaFang Wyze Camera 2

### ISSUE THREAD

**Issue by bwt615** [KhaosT/homebridge-camera-ffmpeg#285]
Cannot get this working for the life of me! Confirmed that I can stream fine directly to my computer from the camera so it seems to be an issue with this homekit plugin.

**Comment by tokfrans03** [comment]
re-add the camera and change its name in config.json

**Comment by bwt615** [comment]
Didn’t work
On Apr 14, 2019, at 12:45 PM, tokfrans03 <notifications@github.com<mailto:notifications@github.com>> wrote:


re-add the camera and change its name in config.json

**Comment by tokfrans03** [comment]
Ok, so let me get this straight: the camera is added to HomeKit but streaming doesn’t work? Does the snapshot work?
If so there’s something wrong with the ffmpeg command. Add the debug option in your camera config and run Homebridge again in the terminal and reply with the error code (don’t forget to add your config too!)

**Comment by bwt615** [comment]
Snapshot appears to work.

FFMPEG command works fine when local. When I run with debug mode it looks like it's streaming fine per the command prompt but I get a loading in homekit and eventually CMD just says streaming stopped. No error that I've seen.

`	  "platform": "Camera-ffmpeg",
	  "cameras": [
		{
		  "name": "Camera - Kitchen",
		  "videoConfig": {
			"source": "-rtsp_transport tcp -re -i rtsp://XXX.XXX.X.XXX:8554/unicast",
			"stillImageSource": "-i rtsp://XXX.XXX.X.XXX:8554/unicast",
			"maxStreams": 2,
			"maxFPS": 15,
			"maxBitrate": 150,
			"packetSize": 1315
			}
		},
		{
		  "name": "Camera - Living Room",
		  "videoConfig": {
			"source": "-rtsp_transport tcp -re -i rtsp://XXX.XXX.X.XXX:8554/unicast",
			"stillImageSource": "-i rtsp://XXX.XXX.X.XXX:8554/unicast",
			"maxStreams": 2,
			"maxFPS": 15,
			"maxBitrate": 150,
			"packetSize": 1315
		  }
		}`

**Comment by tokfrans03** [comment]
Could you send the log?

**Comment by bwt615** [comment]
I have a very similiar issue on windows.

**Comment by bwt615** [comment]
Config:
                    "name": "Kitchen Front Door Camera",
                    "button": false,
                    "motion": false,
                    "throttle": 10000,
                    "videoConfig": {
                        "audio": false,
                        "source": "-i rtsp://admin:admin@XXX.XX.X.XXX:554/live/stream0",
                        "stillImageSource": "-rtsp_transport tcp -skip_frame nokey -i rtsp://admin:admin@XXX.XX.X.XXX:554/live/stream1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "vcodec": "libx264",
                        "debug": true,
                        "additionalCommandLine": "-loglevel verbose"

Notable errors in log,  even though it streams fine im CMD:

The profile-level-id field size is invalid (41)
Error parsing AU headers
circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
