### ISSUE TITLE
Stream freeze after 3 seconds In 3 cams 

### ISSUE THREAD

**Issue by pocoyo01** [KhaosT/homebridge-camera-ffmpeg#288]
Hello first of all forgive my English and thanks for this great plugin. I have a problem all installed ok but in live mode it freezes the image at 3-4 seconds. any ideas.

**Comment by ashtonaut** [comment]
I had this issue, live view broke up and froze within 5 seconds of watching live stream.

I fixed it by adding `-rtsp_transport tcp` to my "source" line in config.json.
