### ISSUE TITLE
No stream/screenshot with Dafang

### ISSUE THREAD

**Issue by misanthrophy** [KhaosT/homebridge-camera-ffmpeg#289]
Hi,

I can't get my dafang working for screenshots or livestream.

I hacked it with [dafang hack](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks)

I have access with through the IP address on my browser and see there my livefeed. 
(My first issue there, I am not sure id thats related to my actual issue is, that it always tells me, my SD crad is in read-only mode. That means other than the default settings I am not able change anything. But rtsp h264 Server is up and running. But rtsp mjpeg Server is not... 

I took the h264 path and added that into my config.json.

My config.json looks like this:

{
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Schlafzimmer",
                    "videoConfig": {
                        "source": "-re -i rtsp://192.168.1.XX:8554/unicast",
                        "stillImageSource": "-i rtsp://192.168.1.XX/cgi-bin/currentpic.cgi -vframes 1 -r 1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 25,
                        "debug": true
                    }
                }
            ]
        }

My log looks like this:

Mar 18 21:38:06 raspberrypi homebridge[16609]: [2019-3-18 21:38:06] [Camera-ffmpeg] Start streaming video from Schlafzimmer with 1280x720@299kBit
Mar 18 21:38:06 raspberrypi homebridge[16609]: ffmpeg -re -i rtsp://192.168.1.22:8554/unicast -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 25 -f rawvideo -tune ze
rolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 4422606 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 
IxgFTWON8K60d3aD8/zvq8sEZjdxiCDlKFDVIWet srtp://192.168.1.4:51257?rtcpport=51257&localrtcpport=51257&pkt_size=1316 -loglevel debug
Mar 18 21:38:06 raspberrypi homebridge[16609]: ffmpeg version N-93328-gf6803cfbd2 Copyright (c) 2000-2019 the FFmpeg developers
Mar 18 21:38:06 raspberrypi homebridge[16609]:   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
Mar 18 21:38:06 raspberrypi homebridge[16609]:   configuration: --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl 
--enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
Mar 18 21:38:06 raspberrypi homebridge[16609]:   libavutil      56. 26.100 / 56. 26.100
Mar 18 21:38:06 raspberrypi homebridge[16609]:   libavcodec     58. 47.103 / 58. 47.103
Mar 18 21:38:36 raspberrypi homebridge[16609]: [2019-3-18 21:38:36] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

There is no real change if Adjust my settings with "audio": false or "vcodec": "h264_omx" or "-rtsp_transport tcp...."

The only big difference I notice is, if I change the stillImage path to the same address as my livestream address and not currentpic.cgi, that in most cases it only tries to push a snapshot to HomeKit and even doubletapping the camera in fullscreen mode does not trigger the live video. If I remove that line or change it to currentpic.cgi, it tries at least to show me both. Sometimes I geta snapshot, but in most cases not. But a live video is not possible. 

@KhaosT suggested to start the stream directly in terminal, there I get this info:

ffmpeg -re -i rtsp://192.168.1.XX:8554/unicast
ffmpeg version N-93328-gf6803cfbd2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx
264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.103 / 58. 47.103
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
rtsp://192.168.1.XX:8554/unicast: Invalid data found when processing input

I don't know what I should do, to fix this issue... :-(

Thanks for any help!

**Comment by misanthrophy** [comment]
Tested the link with VLC player on my iPad Pro:

rtsp://192.168.1.XX:8554/unicast and it just works totally fine.

**Comment by tokfrans03** [comment]
Test the ffmpeg command with ffmpeg or ffplay
