### ISSUE TITLE
Fix the camera tcp listening port

### ISSUE THREAD

**Issue by macjl** [KhaosT/homebridge-camera-ffmpeg#29]
How can I fix the tcp port of the camera-ffmpeg in homebridge? I can fix the homebridge port, but didn't found how to fix the camera port : 

Here is my config file where I can specify the port 51828 for homebridge, but not for the camera-ffmpeg platform:
```
{
        "bridge": {
                "name": "Bridge webcams couloir",
                "username": "CC:55:77:88:55:02",
                "port": 51828,
                "pin": "123-45-678"
        },
        "platforms": [{
                "platform": "Camera-ffmpeg",
                "name": "Webcam couloir",
                "cameras": [{
                        "name": "Webcam couloir",
                        "videoConfig": {
                                "source": "-re -i http://webcam/stream.mjpg",
                                "maxStreams": 2,
                                "maxWidth": 1280,
                                "maxHeight": 720,
                                "maxFPS": 30
                        }
                }]
        }]
}
```

And in the log, when starting, the camera take the a random port. Here, the 54608 tcp port : 
```
[12/5/2016, 4:41:17 PM] Homebridge is running on port 51827.
[12/5/2016, 4:41:17 PM] Webcam salon is running on port 54608.
```

I'm running homebidge in a docker container, and it would be much better if I could fix that port in the configuration file.

**Comment by KhaosT** [comment]
Right now you can't. Since accessory can publish arbitrary amount of cameras, if I allow plugin to determine which port it want to publish the camera, I can see a lot of developers using the same port which causes address in use problem. I'll re-evaluate this decision and see if I can find a way to allow final user to do something to control the behavior.

**Comment by macjl** [comment]
Maybe it should be possible to specify a port range in the config file? It would be more predictable if you have 10 available ports to map, instead of 10000 now.

Today, I'm unable to determine which port I should map into my containers. So I use host networking mode instead, but it's less secure.

**Comment by KhaosT** [comment]
I'll see what I can do... sorry for the inconveniences.

**Comment by ramsnerm** [comment]
I completely agree that this is an important need. I personally use the Firewall settings Synology. Without knowing the port I only can make my station insecure and disable the firewall.

**Comment by sequencer** [comment]
I am wandering that if a firewall script can be add in this plugin, as we all know, it's not possible for homebridge's arbitrary random ports to open every port on server.
So if plugin can get the port info, and it can add a firewall rule to open a certain port for camera.

**Comment by jannnfe** [comment]
Have a look at this: https://github.com/nfarina/homebridge/issues/927#issuecomment-346006027
