### ISSUE TITLE
FFMPEG exited with code -2

### ISSUE THREAD

**Issue by RamB27** [KhaosT/homebridge-camera-ffmpeg#294]
Hi, i'm stuck with this error et tried many manipulations but still don't have any stream in the Home app...
I have a D-Link camera :  DCS-5222LB model

Here's my code if someone can help :

```
"platforms": [
                {
                        "platform": "Camera-ffmpeg",
                        "cameras": [
                          {
                                "name": "D-Link",
                                "videoConfig": {
                                        "source": "-rtsp_transport tcp -re -i rtsp://admin:PASSWORD@192.168.1.37:554/live1.sdp",
                                        "stillImageSource": "-f mjpeg -i http://admin:PASSWORD@192.168.1.37/image/jpeg.cgi",
                                        "maxStreams": 2,
                                        "maxWidth": 1280,
                                        "maxHeight": 720,
                                        "maxFPS": 25,
                               
                                }
                        }]
                }
        ]
```

The streams are working properly when pasting them in my web browser !

**Comment by zeligprod** [comment]
+1 

I have exactly the same problem with a doorbird D2101IKH.  The mjpeg stream works in the browser but not in home app, I also tried an rtsp stream. 
Thanks for helping!

**Comment by mapkyxa** [comment]
I'm using a Raspberry Pi and getting same problem with error -2
I'm using geovision camera and tried all kind of streaming addresses RTSP from different sources or even mjpeg stream

**Comment by bertnchatt** [comment]
I am having the same using Raspberry PI and Foscam QJ4.  RTSP and Snapshot work fine from VLC

**Comment by bertnchatt** [comment]
I resolved my issue after enabling debug and realizing the problem was ffmpeg not being able to spawn correctly.  Following PR 173 per a comment by KaosT gave me the info I needed... Happy Camper!!

**Comment by Rosariomattei1982** [comment]
hello also to me from error 2 have you solved ???
someone can help me I am a little denied in this
I thank you in advance
