### ISSUE TITLE
OMX is not working, Help Please.

### ISSUE THREAD

**Issue by madness0** [KhaosT/homebridge-camera-ffmpeg#296]
Im using Hoobs to use this plugin which is similar to Oznu UI, the OMX coding is not working ro supported, is there a fix for that, im currently using my dahua and i noticed that its using  H.264h encoding, can i use that, like I read somewhere that you can set the v codec to copy, one more issue the snapshots keep updating on 1 minute intervals currently (remotely), and 12 seconds approximately on Wifi, is there a way to fix that, Thanks in advance

**Comment by jeylites** [comment]
same issue... anyone has got a fix? It's like the "copy" is not working
