### ISSUE TITLE
Possible to use gstreamer as videoprocessor?

### ISSUE THREAD

**Issue by Samfox2** [KhaosT/homebridge-camera-ffmpeg#297]
Although itˋs called _homebridge-ffmpeg_ would it be possible to use gstreamer as video processor? Reason is that gstreamer supports gpu encoding on jetson nano while there is no ffmpeg version with gpu support for that platform.

**Comment by mentaluproar** [comment]
I'm watching this as I'd like that too.  Lots of boards have crap GPU support outside of android and if we get encoding support at all, its generally not in a format we want.  Maybe there is so sort of wrapper than can make gstreamer work similarly enough that it thinks it's talking to ffmpeg.
