### ISSUE TITLE
 [Camera-ffmpeg] ERROR: FFmpeg exited with code -4058

### ISSUE THREAD

**Issue by IamChrisHeX** [KhaosT/homebridge-camera-ffmpeg#299]
No feed on iPhone and error message in command prompt says:  [Camera-ffmpeg] ERROR: FFmpeg exited with code -4058

**Comment by IamChrisHeX** [comment]
Solved my own problem, set path variables in windows :)

**Comment by nhatquang88** [comment]
how you set the path in windows? please help? 
U mean FFMPEG path

**Comment by ElanX** [comment]
> Solved my own problem, set path variables in windows :)

Can you explain? Having the same error.

**Comment by Bad2dabone** [comment]
FFmpeg codec not installed have a look at bellow link will fix the problem

https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg
