### ISSUE TITLE
Very low frame rate with high CPU usage

### ISSUE THREAD

**Issue by skandragon** [KhaosT/homebridge-camera-ffmpeg#3]
It's possible the box I'm using is too underpowered, but I cannot get ffmpeg to use less than about 300% CPU on my machine, and it cannot keep up to realtime.

I have configured my cameras to only do 1 FPS, but I am not sure they respect that setting entirely.  However, I cannot get any video reliably no matter what the settings used.

These are two d-link 2330L cameras.

**Comment by KhaosT** [comment]
@skandragon What's the device are you running the plugin on?

**Comment by ersan** [comment]
Same issue here I suppose - for me it's a raspberry pi 3 which I'm sure is severely underpowered.  I haven't looked at the arguments but I think you are re-encoding the video?  If so is this necessary?  I thought HomeKit natively handled RTSP/h264 streams?

**Comment by klaasjoerg** [comment]
I am also using a raspberry-pi3 with a lot of more stuff running on it.
While accessing one of the two cams I configured, I don't seem to have any major CPU-Loads. (homebridge and ffmpeg process are usually below 20%)

**Comment by skandragon** [comment]
@KhaosT, sorry for the slow response.

I'm running it on a small Linux machine:

```Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 54
Model name:            Intel(R) Atom(TM) CPU D2550   @ 1.86GHz
Stepping:              1
CPU MHz:               1861.982
BogoMIPS:              3723.96
L1d cache:             24K
L1i cache:             32K
L2 cache:              512K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm arat```

**Comment by adrianmihalko** [comment]
It wasn't answered. Do we need convert h264 streams?
