### ISSUE TITLE
handleStreamRequest and prepareStream not called. The snapshot works

### ISSUE THREAD

**Issue by rickvdl** [KhaosT/homebridge-camera-ffmpeg#30]
First of all thanks @KhaosT for the plugin! Really cool.
I have been trying to get my cameras working for the past week, but so far I wasn't able to get it to work (I am running this on a raspberry pi). 

I am sure of a couple of things;

1. The streams works in VLC
2. I have installed FFMPEG and it works
3. The snapshot function works, I can see the snapshot being updated in the home app about every 10seconds.
4. The rest of homebridge works
5. The same thing happens while running it on my Mac

When I add the cameras to homebridge everything succeeds, and I can successfully view the snapshot being updated. But when I tap on a camera, it starts loading for about 4-5 seconds and the app then says that the camera doesn't respond.
I have tried running the FFMPEG command manually and then I see the following output;

```Input #0, mpjpeg, from 'http://admin:password@192.168.2.102/video.cgi':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 25 tbr, 25 tbn, 25 tbc
Codec AVOption tune (Tune the encoding params (cf. x264 --fullhelp)) specified for output file #0 (rtp://127.0.0.1:51293) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
[swscaler @ 0x2ba7350] deprecated pixel format used, make sure you did set range correctly
[h264_omx @ 0x2b68fc0] Using OMX.broadcom.video_encode
Output #0, rtp, to 'rtp://127.0.0.1:51293':
  Metadata:
    encoder         : Lavf57.51.100
    Stream #0:0: Video: h264 (h264_omx), yuv420p, 1280x720, q=2-31, 300 kb/s, 30 fps, 90k tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.58.103 h264_omx
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (h264_omx))
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 57.51.100
m=video 51293 RTP/AVP 96
b=AS:300
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1

Press [q] to stop, [?] for help
frame=   37 fps=2.6 q=-0.0 Lsize=      43kB time=00:00:01.16 bitrate= 303.7kbits/s dup=6 drop=0 speed=0.0833x    
video:43kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.361587%
Exiting normally, received signal 2.
```

And this is the last output I see from homebridge;
```
[12/11/2016, 12:06:31 PM] Homebridge is running on port 51826.
[12/11/2016, 12:06:31 PM] IPCam04 is running on port 45767.
[12/11/2016, 12:06:31 PM] IPCam04 is running on port 36020.
HANDLE SNAPSHOT
HANDLE SNAPSHOT
HANDLE SNAPSHOT
```

I have added a `console.log` with the function name in every function in `ffmpeg.js` so that's why you see the `HANDLE SNAPSHOT`.
But I don't see the FFMPEG command being printed to the console when I open the stream on any on my devices, which should happen. While debugging on my Mac using `console.log` I found out that both `FFMPEG.prototype.prepareStream` and `FFMPEG.prototype.handleStreamRequest` aren't being called. 
I think this is as far as I can get with debugging, and I don't have any ideas left on what it could be.

If you have any ideas or suggestions it is greatly appreciated. Thanks in advance.

**Comment by thorsten-gehrig** [comment]
Same issue here... any advise in troubleshooting would be appreciated.
How can we check what function is called when we start the stream? 
Can we insert some breakpoints?
Thanks for any hint or help!

**Comment by KhaosT** [comment]
If you believe none of those getting invoked, please try to view logs on the iOS side and see why HomeKit refuse to start stream. To view logs on iOS device, please use macOS Sierra, open Console.app and select your iOS device. You can filter log by process: homed.

**Comment by fennec622** [comment]
Hello for me same problem

No handlestreamrequest

log on iphone 

`par défaut	23:41:23.995220 +0100	homed	Done for IDSService delegate 0x10029c180 for incomingMessage with context - doesRespondToSelector? YES
par défaut	23:41:23.995403 +0100	homed	Calling out to IDSService delegate 0x10029c180 for incomingTopLevelMessage if it responds.
par défaut	23:41:23.995593 +0100	homed	Done for IDSService delegate 0x10029c180 for incomingTopLevelMessage - doesRespondToSelector? NO
par défaut	23:41:23.995796 +0100	homed	Failed to send secure message with error, Error Domain=HMErrorDomain Code=1044 "(null)", retrying sending message
par défaut	23:41:24.009449 +0100	homed	XPC object received <private>:<private>
par défaut	23:41:24.011456 +0100	homed	xpc object: [<private>] context: [<private>]
par défaut	23:41:24.011544 +0100	homed	Received XPC Response/Socket: -1    Error: (null)
par défaut	23:41:24.012498 +0100	homed	Session started <private>
par défaut	23:41:24.017585 +0100	homed	Attempting To Send message from account <private> to destinations <private>
par défaut	23:41:24.017635 +0100	homed	Attempting to send on a non local account, this message is allowed to progress
par défaut	23:41:24.019733 +0100	homed	Client request to send URGENT message (dictionary) service: com.apple.private.alloy.willow  to destinations: <private>   options: <private>]
par défaut	23:41:24.019788 +0100	homed	Client request to send message (dictionary) on service: com.apple.private.alloy.willow   guid: 5F2DFF6D-908A-446C-982F-AB562D442930   to destinations: <private>   options: <private>    size: 4] (1 pending)
par défaut	23:41:24.086030 +0100	homed	<private> outgoing message guid response: 5F2DFF6D-908A-446C-982F-AB562D442930  callbackID: (null)  response code: 11   error: (null)   lastCall: NO
par défaut	23:41:24.114718 +0100	homed	<private> outgoing message guid response: 5F2DFF6D-908A-446C-982F-AB562D442930  callbackID: (null)  response code: 0   error: (null)   lastCall: NO
par défaut	23:41:24.114874 +0100	homed	<private> got messageIdentifier <private> callbackID (null) updatedWithResponseCode: 0 error (null) lastCall NO
par défaut	23:41:24.115022 +0100	homed	  => <<private>:0x10020d8a0> finished handling message guid: <private>  (connection:messageIdentifier:alternateCallbackID:updatedWithResponseCode:error:lastCall:)
par défaut	23:41:24.115642 +0100	homed	<private> outgoing message guid response: 5F2DFF6D-908A-446C-982F-AB562D442930  callbackID: (null)  response code: 0   error: (null)   lastCall: NO
par défaut	23:41:24.115822 +0100	homed	<private> got messageIdentifier <private> callbackID (null) updatedWithResponseCode: 0 error (null) lastCall NO
par défaut	23:41:24.115919 +0100	homed	  => <<private>:0x10020d8a0> finished handling message guid: <private>  (connection:messageIdentifier:alternateCallbackID:updatedWithResponseCode:error:lastCall:)
par défaut	23:41:24.117853 +0100	homed	<private> outgoing message guid response: 5F2DFF6D-908A-446C-982F-AB562D442930  callbackID: (null)  response code: 0   error: (null)   lastCall: YES
par défaut	23:41:24.117968 +0100	homed	<private> got messageIdentifier <private> callbackID (null) updatedWithResponseCode: 0 error (null) lastCall YES
par défaut	23:41:24.118205 +0100	homed	  => <<private>:0x10020d8a0> finished handling message guid: <private>  (connection:messageIdentifier:alternateCallbackID:updatedWithResponseCode:error:lastCall:)
par défaut	23:41:24.118308 +0100	homed	<private> got identifier <private> didSendWithSuccess YES  error (null) num delegates: 4
par défaut	23:41:24.118500 +0100	homed	  => <<private>:0x10020d8a0> finished handling message guid: <private>  (connection:identifier:didSendWithSuccess:error:context:)
par défaut	23:41:24.782614 +0100	homed	Ignoring message to: <private> it is not to my aliases: (null) account uuid: <private>
par défaut	23:41:24.782818 +0100	homed	Ignoring message for topic com.apple.private.alloy.willow my topic is <private>
par défaut	23:41:24.782995 +0100	homed	Ignoring message for topic com.apple.private.alloy.willow my topic is <private>
par défaut	23:41:24.783139 +0100	homed	<private> received message: <private>  topic com.apple.private.alloy.willow  from: <private>  to: <private>   payload items: 4
par défaut	23:41:24.783267 +0100	homed	FromID <private>, strippedURI <private>, token <private>
par défaut	23:41:24.786354 +0100	homed	Comparing device token <private> to token <private>
par défaut	23:41:24.788887 +0100	homed	Comparing device token <private> to token <private>
`

**Comment by hackruu** [comment]
Same here, ios 10.2, previews updated once in 10s, no video streaming.

**Comment by metalshark** [comment]
Streams and still images work fine on my iPad (Air 2) but only the still images work on my iPhone 7 or my girlfriend's iPhone 5.

**Comment by EvianZhow** [comment]
@KhaosT Two errors found suspectious. 

The first is:
```
default	00:41:49.751193 +0800	homed	*** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL
```

Second one is:
```
default	00:41:49.795919 +0800	homed	[VStarCam/16/8A33479F-48DB-437A-9412-C14C94070B45/com.apple.Home] Failed to select video config
default	00:41:49.796348 +0800	homed	[VStarCam/16/8A33479F-48DB-437A-9412-C14C94070B45/com.apple.Home] Could not find the right match in the supported list
```

Console printed some support options, and I changed `config.json` to one of that parameters but still not working.

**Comment by KhaosT** [comment]
@EvianZhow homed should print out a list of available video config and a list of supported config in the log. Do you see those?

**Comment by EvianZhow** [comment]
@KhaosT I've tried supported resolution but got below console messages: 
```
default	00:44:59.145934 +0800	homed	*** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL
default	00:44:59.165601 +0800	homed	[ViceroyTrace][NOTICE] ErrorLogLevel=NOTICE ProductType=<private> BuildVersion=<private> GameKitServices=<private>
default	00:44:59.165732 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] -[(AVConferenceXPCClient*)0x1002e61e0 init]:63
default	00:44:59.165836 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] XPC Client: creating new connection to server
default	00:44:59.166154 +0800	homed	[ViceroyTrace][NOTICE] ErrorLogLevel=NOTICE ProductType=<private> BuildVersion=<private> GameKitServices=<private>
default	00:44:59.166287 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] -[(AVConferenceXPCClient*)0x1003e3f10 init]:63
default	00:44:59.166411 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] XPC Client: creating new connection to server
default	00:44:59.180800 +0800	homed	[VStarCam/16/6B01684D-56C6-4A4A-A3EC-0E86699ED167/com.apple.Home] Failed to select video config
default	00:44:59.180916 +0800	homed	[VStarCam/16/6B01684D-56C6-4A4A-A3EC-0E86699ED167/com.apple.Home] Could not find the right match in the supported list
default	00:44:59.181681 +0800	homed	[AVConference.AVCAudioStream][NOTICE] -[(AVCAudioStream*)0x1003e3db0 dealloc]:172
error	00:44:59.181811 +0800	homed	[AVConference.AVConferenceXPCClient][ERROR] XPC Client: received error from server while processing reply, Connection interrupted
default	00:44:59.181932 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] XPC Client: disposing off connection to server
error	00:44:59.182094 +0800	homed	[AVConference.AVConferenceXPCClient][ERROR] XPC Client: XPC Error, Connection interrupted
default	00:44:59.182808 +0800	homed	Answering incoming message kNegotiateStreamRequestKey (4F93D300-EDFD-4094-9249-E7336E857761) from client 'Home' that does expect a response
default	00:44:59.182937 +0800	homed	[VStarCam/16/6B01684D-56C6-4A4A-A3EC-0E86699ED167/com.apple.Home] Session is not in progress
default	00:44:59.183153 +0800	homed	[AVConference.AVCVideoStream][NOTICE] -[(AVCVideoStream*)0x100295a20 dealloc]:136
error	00:44:59.183412 +0800	homed	[AVConference.AVConferenceXPCClient][ERROR] XPC Client: XPC Error, Connection interrupted
default	00:44:59.183538 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] -[(AVConferenceXPCClient*)0x1003e3f10 dealloc]:74
error	00:44:59.184477 +0800	homed	[AVConference.AVConferenceXPCClient][ERROR] XPC Client: received error from server while processing reply, Connection interrupted
default	00:44:59.185682 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] XPC Client: disposing off connection to server
default	00:44:59.185987 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] -[(AVConferenceXPCClient*)0x1002e61e0 dealloc]:74
```

Homebridge still didn't print out the ffmpeg parameters.

**Comment by EvianZhow** [comment]
@KhaosT I found more detailed information in console logs. It seemed like `mediaserverd` first complaining about the error.  

**Could not infer operating mode from audioMode => 
thread state transition: 0 -> 1 => 
[VCAudioStream stop] => 
thread state transition: 1 -> 1 => 
thread state transition: 1 -> 3
VCRealTimeThread_ThreadProc(<private>) stop!**

```
default	14:39:41.448979 +0800	mediaserverd	[AVConference.VCAudioManager][INFO] Audio Session Parameters:<private>
error	14:39:41.449077 +0800	mediaserverd	[AVConference.VCAudioManager][ERROR] -[VCAudioManager setAudioSessionParameters:]: Could not infer operating mode from audioMode = <private>
default	14:39:41.450495 +0800	mediaserverd	[AVConference.AVConferenceXPCServer][INFO] XPC Server: AVConferenceXPCServer _xpc_handle_connection incoming request
default	14:39:41.450601 +0800	mediaserverd	[AVConference.AVConferenceXPCServer][INFO] XPC Server: _xpc_add_connection_to_list PID 126
default	14:39:41.450707 +0800	mediaserverd	[AVConference.AVConferenceXPCServer][INFO] XPC Server: dispatching registered block for service <private>, block 0x103263f50, queue 0x103263ed0
default	14:39:41.451043 +0800	mediaserverd	[ViceroyTrace][NOTICE] ErrorLogLevel=NOTICE ProductType=<private> BuildVersion=<private> GameKitServices=<private>
default	14:39:41.451102 +0800	mediaserverd	[AVConference][NOTICE] Starting SeqNum for PayloadType 0 = 18769
default	14:39:41.451152 +0800	mediaserverd	[AVConference][INFO] Successful thread state transition: 0 -> 1
default	14:39:41.451242 +0800	mediaserverd	[AVConference][INFO] JB Dump is Disabled
default	14:39:41.451350 +0800	mediaserverd	[AVConference][INFO] ### VCRealTimeThread_ThreadProc(<private>) start!
default	14:39:41.451451 +0800	mediaserverd	[AVConference.VCAudioStream][NOTICE] VCAudioStream[0x1033ce590] -[VCAudioStream init]
error	14:39:41.451543 +0800	mediaserverd	[AVConference][ERROR] VCMediaStream allocated new VCAudioStream 0x1033ce590
default	14:39:41.451666 +0800	mediaserverd	[AVConference.VCAudioStream][NOTICE] VCAudioStream[0x1033ce590] -[VCAudioStream setLocalParticipantInfo:networkSockets:withError:] infoDict = <private> networkSockets = <private> callID = <nil>
default	14:39:41.451828 +0800	mediaserverd	[AVConference][INFO] Start listening RTP on <private> sock 102
default	14:39:41.451934 +0800	mediaserverd	[AVConference][INFO] Start listening RTCP on <private> sock 103
default	14:39:41.452045 +0800	mediaserverd	[AVConference][INFO] RTP  vfd (102) accepts pkt (0210)
default	14:39:41.452148 +0800	mediaserverd	[AVConference][INFO] RTCP vfd (103) accepts pkt (0040)
default	14:39:41.452254 +0800	mediaserverd	[AVConference][INFO] RTP/RTCP ports for PayloadType 0 are 56142(102) and 56142(103)
default	14:39:41.452359 +0800	mediaserverd	[AVConference][INFO] RTPSetSockets hRTP 0x0, iSocRTP 102, dwRemoteSSRC 00000000, cellularUniqueTag 0
default	14:39:41.452727 +0800	mediaserverd	[AVConference][INFO] CNAME for RTP(0x100964200) is [<private>]
default	14:39:41.453106 +0800	homed	[ViceroyTrace][NOTICE] ErrorLogLevel=NOTICE ProductType=<private> BuildVersion=<private> GameKitServices=<private>
default	14:39:41.453215 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] -[(AVConferenceXPCClient*)0x103302bd0 init]:63
default	14:39:41.453321 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] XPC Client: creating new connection to server
default	14:39:41.453634 +0800	homed	[ViceroyTrace][NOTICE] ErrorLogLevel=NOTICE ProductType=<private> BuildVersion=<private> GameKitServices=<private>
default	14:39:41.453738 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] -[(AVConferenceXPCClient*)0x103339320 init]:63
default	14:39:41.453898 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] XPC Client: creating new connection to server
default	14:39:41.457884 +0800	mediaserverd	[AVConference.AVConferenceXPCServer][INFO] XPC Server: dispatching registered block for service <private>, block 0x103267650, queue 0x103263ed0
error	14:39:41.457986 +0800	mediaserverd	[AVConference][ERROR] VCMediaStream releasing old VCAudioStream[0x1033ce590]
default	14:39:41.458086 +0800	mediaserverd	[AVConference.VCAudioStream][NOTICE] VCAudioStream[0x1033ce590] -[VCAudioStream stop]
default	14:39:41.458190 +0800	mediaserverd	[AVConference.AVConferenceXPCServer][INFO] XPC Server: _xpc_remove_connection_from_list PID 126
default	14:39:41.458296 +0800	mediaserverd	[AVConference.VCAudioStream][NOTICE] -[(VCAudioStream*)0x1033ce590 dealloc]:1042
default	14:39:41.458397 +0800	mediaserverd	[AVConference][INFO] VCAudioReceiver_Finalize - Cleaning up audioReceiver (0x0x103414000)
default	14:39:41.458495 +0800	mediaserverd	[AVConference][INFO] ### VCRealTimeThread_Stop(<private>) called!
default	14:39:41.458600 +0800	mediaserverd	[AVConference][INFO] Successful thread state transition: 1 -> 1
default	14:39:41.458706 +0800	mediaserverd	[AVConference][INFO] Successful thread state transition: 1 -> 3
default	14:39:41.458807 +0800	mediaserverd	[AVConference][INFO] ### VCRealTimeThread_ThreadProc(<private>) stop!
default	14:39:41.458911 +0800	mediaserverd	[AVConference][INFO] WRMClient: stopping...
default	14:39:41.459015 +0800	mediaserverd	[AVConference][INFO] WRMClient: stopped.
default	14:39:41.459122 +0800	mediaserverd	[AVConference][INFO] Jitter Queue was reset
default	14:39:41.459216 +0800	mediaserverd	[AVConference.AVConferenceXPCServer][INFO] XPC Server: client connection fully disconnected or error from unrecognized client
default	14:39:41.459268 +0800	mediaserverd	[AVConference.AVConferenceXPCServer][INFO] XPC Server: dispatching registered block for service <private>, block 0x10333f790, queue 0x103263ed0
error	14:39:41.459320 +0800	mediaserverd	[AVConference][ERROR] VCMediaStream releasing old VCVideoStream 0x1033d8700
default	14:39:41.459395 +0800	mediaserverd	[AVConference.VCVideoStream][WARNING] -[(VCVideoStream*)0x1033d8700 stop]:953
default	14:39:41.459496 +0800	mediaserverd	[AVConference.AVConferenceXPCServer][INFO] XPC Server: _xpc_remove_connection_from_list PID 126
default	14:39:41.464620 +0800	homed	[VStarCam/9/6F331BB7-65AC-44F9-9CBE-9E95F265A030/com.apple.Home] Failed to select video config
default	14:39:41.464646 +0800	homed	[VStarCam/9/6F331BB7-65AC-44F9-9CBE-9E95F265A030/com.apple.Home] Could not find the right match in the supported list
default	14:39:41.465279 +0800	homed	[AVConference.AVCAudioStream][NOTICE] -[(AVCAudioStream*)0x1003ae770 dealloc]:172
error	14:39:41.465378 +0800	homed	[AVConference.AVConferenceXPCClient][ERROR] XPC Client: received error from server while processing reply, Connection interrupted
default	14:39:41.465582 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] XPC Client: disposing off connection to server
default	14:39:41.466182 +0800	homed	Answering incoming message kNegotiateStreamRequestKey (7CA96927-9388-4BDE-AF3C-1CB423A4AE5A) from client 'Home' that does expect a response
default	14:39:41.466548 +0800	homed	[VStarCam/9/6F331BB7-65AC-44F9-9CBE-9E95F265A030/com.apple.Home] Session is not in progress
default	14:39:41.466669 +0800	homed	[AVConference.AVCVideoStream][NOTICE] -[(AVCVideoStream*)0x1003db3e0 dealloc]:136
error	14:39:41.467400 +0800	homed	[AVConference.AVConferenceXPCClient][ERROR] XPC Client: XPC Error, Connection interrupted
error	14:39:41.468047 +0800	homed	[AVConference.AVConferenceXPCClient][ERROR] XPC Client: XPC Error, Connection interrupted
error	14:39:41.468532 +0800	homed	[AVConference.AVConferenceXPCClient][ERROR] XPC Client: received error from server while processing reply, Connection interrupted
default	14:39:41.468740 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] XPC Client: disposing off connection to server
default	14:39:41.468875 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] -[(AVConferenceXPCClient*)0x103339320 dealloc]:74
default	14:39:41.469305 +0800	homed	[AVConference.AVConferenceXPCClient][INFO] -[(AVConferenceXPCClient*)0x103302bd0 dealloc]:74
default	14:39:41.469676 +0800	Home	cameraStreamControl:<private> didStopStreamWithError:<private>
default	14:39:41.469905 +0800	Home	<private>: Starting log for: <private>
default	14:39:41.470008 +0800	Home	<private>: Starting update for sender: "<private>"
default	14:39:41.470110 +0800	Home	----- OPEN TRANSACTION (<private>) -----
default	14:39:41.470480 +0800	Home	Added/Updated item: <private>
default	14:39:41.470583 +0800	Home	----- COMMIT TRANSACTION (<private>) -----
default	14:39:41.470687 +0800	Home	Requested batched update for 1 items (+0 removed). Processing in: 0.00 sec...
default	14:39:41.470790 +0800	Home	Processed batch with 1 finished items
default	14:39:41.470892 +0800	Home	All batch item updates complete.
default	14:39:41.470993 +0800	Home	Update finished in 0.009135 seconds
default	14:39:41.472999 +0800	mediaserverd	[AVConference.VCVideoStream][NOTICE] VCVideoStream[0x1033d8700] -[VCVideoStream dealloc] remoteVideo release queue for streamToken=12
default	14:39:41.473134 +0800	mediaserverd	[AVConference][INFO] -[VCRemoteVideoManager releaseQueueForStreamToken:]: did release for streamToken=12, queueDict=<private>
default	14:39:41.473255 +0800	mediaserverd	[AVConference][INFO] Un-asserting NetworkAgent
default	14:39:41.473359 +0800	mediaserverd	[AVConference][INFO] NetworkAgent has been un-asserted
default	14:39:41.473461 +0800	mediaserverd	[AVConference.AVConferenceXPCServer][INFO] XPC Server: client connection fully disconnected or error from unrecognized client
default	14:39:41.473564 +0800	mediaserverd	[AVConference][INFO] VTPRecvProc thread(0x16e443000) end...
default	14:39:41.473772 +0800	Home	All executions complete. Cleaning up. Remaining running transactions: 0
```

Thanks for taking your time reading about this. :)

**Comment by KhaosT** [comment]
@EvianZhow please try to install [logging profile (HomeKit)](https://developer.apple.com/bug-reporting/profiles-and-logs/) on the device and try again. When ``homed`` drop this error

```
default	14:39:41.464620 +0800	homed	[VStarCam/9/6F331BB7-65AC-44F9-9CBE-9E95F265A030/com.apple.Home] Failed to select video config
default	14:39:41.464646 +0800	homed	[VStarCam/9/6F331BB7-65AC-44F9-9CBE-9E95F265A030/com.apple.Home] Could not find the right match in the supported list
```

it should also print out a list, I'm not sure why the list is not there. Did you filtered too much information from the log?

**Comment by EvianZhow** [comment]
@KhaosT I don't think so, my filter options are PROCESS homed PROCESS home PROCESS mediaserverd. 
The completed log is available at https://gist.github.com/EvianZhow/46d52a31929c598e2906e4e8d9e1558c in order not to cause this post to be too long.

**Comment by KhaosT** [comment]
Huh... maybe they changed the logging output. Would you mind to share the config section for the plugin at here?

**Comment by EvianZhow** [comment]
Sure.

```
"platforms": [{
        "platform": "Camera-ffmpeg",
        "cameras": [
        {
            "name": "VStarCam",
            "videoConfig": {
                "source": "-re -f mjpeg -i http://admin:vanelife34567890@192.168.1.144:81/videostream.cgi?user=admin&pwd=vanelife34567890",
                "stillImageSource": "-i http://admin:vanelife34567890@192.168.1.144:81/snapshot.cgi?user=admin&pwd=vanelife34567890",
                "maxStreams": 2,
                "maxWidth": 320,
                "maxHeight": 240,
                "maxFPS": 15
            }
        }
        ]
    }]
...
```

**Comment by EvianZhow** [comment]
Thanks to @KhaosT. It turn out to be an internal issue in iOS HomeKit. HomeKit only supports some combinations of maxWidth, maxHeight and maxFps. Try a higher/lower resolution, or different fps.

**Comment by metalshark** [comment]
@EvianZhow is there any public documentation on the max width/height/fps
available?

The cameras work fine on my iPad, but fail on the iPhones for live viewing.

**Comment by KhaosT** [comment]
@metalshark take a look at [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Camera.js#L34). If it works for iPad it should also work for iPhone.

**Comment by metalshark** [comment]
@EvianZhow

Thanks, am using 1920x1080@25fps (PAL) so will give the NTSC 30fps a go.

**Comment by metalshark** [comment]
@EvianZhow

Nope still no joy on an iPhone 5s, 6s and 7 (haven't got a Plus) but works
fine on an iPad Air 2 and and an iPad Mini 3.

**Comment by KhaosT** [comment]
@metalshark in this case I think in order to move forward, you need to get device log from iPhone. If you have a Mac running macOS Sierra, you can connect your iPhone to your Mac and open Console.app, select the iPhone from sidebar, and in the filter section pick ``process: homed`` and try to start stream again.

**Comment by metalshark** [comment]
Am sorry, I don't have a Mac
