### ISSUE TITLE
Synology Docker, Reolink Camera doesn't work

### ISSUE THREAD

**Issue by nhatquang88** [KhaosT/homebridge-camera-ffmpeg#300]
Hello, 
I installed and FFMPEG plug in for my Onzu Synology DS716+
the camera show the snap shot but it doesn't Live Scream well, even in LAN.
Did I do something wrong with the config? 
I tried to change the camera resolution, frame rate.. manything but it still doesn't work well which I don't know why.
Please help and thank you.

here is my config

 "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "54 Quang Trung",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:****@192.168.1.163:554//h264Preview_01_sub",
                        "stillImageSource": "-i http://192.168.1.163/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=****",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 25,
                        "maxBitrate": 300,
                        "packetSize": 188,
                        "audio": false
                    }
                }
            ]
        }

**Comment by jdawgydawg** [comment]
I have 2 Reolink Cameras (RLC-410-5MP) working with this plugin running on Synology Docker.

It was a struggle to do the initial set up and required some additional configuration outside the usual config file. 

I will have a look later this evening and see if I can remember what I did to get it working

**Comment by jdawgydawg** [comment]
Can you post your startup.sh file?

**Comment by nhatquang88** [comment]
Hello, this is my startup.sh files

thank you alot
`#!/bin/sh
apk add --no-cache ffmpeg ffmpeg-libs libpcap-de

#
# Docker Homebridge Custom Startup Script - oznu/homebridge
#
# This script can be used to customise the environment and will be executed as
# the root user each time the container starts.
#
# If using this to install plugins DO NOT use the global flag (-g).
#
# Example installing homebridge plugin:
#
# npm install homebridge-hue
#
# Example installing packages using default image (Alpine Linux):
#
# apk add --no-cache ffmpeg ffmpeg-libs libpcap-dev
#
# If you're running a debian based version of this container please use apt-get to install packages.
#apk add --no-cache ffmpeg ffmpeg-libs`

**Comment by jdawgydawg** [comment]
Yeah I think I had to add some extra lines of code to the startup.sh file. Here is my startup.sh for comparison. Not sure if you'll need to reboot/reinstall homebridge to get this to work. 

Sorry I can't be more specific - I'm a noob. Best of luck. 

[startup.txt](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/3192223/startup.txt)

**Comment by nhatquang88** [comment]
@jdawgydawg thank you so much for your start up .sh..
now my reolink work perfectly.
I will note here if someone ever need.

**Comment by knuckleheadsmiff** [comment]
Wonder if you guys could help. I have two riolink Argus 2 cameras, would not happen to have an idea if I could connect them up and would you have a sample config.json for it?

**Comment by duffy6** [comment]
Knuckleheadsmith: do you get it to work?
