### ISSUE TITLE
FFmpeg exited with code 1 but snap shot working

### ISSUE THREAD

**Issue by nhatquang88** [KhaosT/homebridge-camera-ffmpeg#302]
Hello,
Today I'm installing the Homebridge with FFMpeg plug in then edit config.json.
I manager to get it take a snap shot then it added in the iphone so I guess my config.json is setup correctly.
I enable an debug mode so anyone can help me.
Please help

here is the error code.

>
 Codec AVOption tune (Tune the encoding to a specific scenario) specified for out                                                                                                                                                             put file #0 (srtp://10.10.10.46:50898?rtcpport=50898&localrtcpport=50898&pkt_siz                                                                                                                                                             e=188) has not been used for any stream. The most likely reason is either wrong                                                                                                                                                              type (e.g. a video option with no video streams) or that it is a private option                                                                                                                                                              of some encoder which was not actually used for any stream.

[srtp @ 0x22889d0] No default whitelist set
[rtp @ 0x22ad270] No default whitelist set
[udp @ 0x22ac4c0] No default whitelist set
[udp @ 0x22ad550] No default whitelist set

Successfully opened the file.
Parsing a group of options: output url srtp://10.10.10.46:55197?rtcpport=55197&l                                                                                                                                                             ocalrtcpport=55197&pkt_size=188.
Applying option map (set input stream mapping) with argument 0:1.
Applying option acodec (force audio codec ('copy' to copy stream)) with argument                                                                                                                                                              libfdk_aac.
Applying option profile:a (set profile) with argument aac_eld.
Applying option f (force format) with argument null.
Applying option ar (set audio sampling rate (in Hz)) with argument 16k.
Applying option b:a (video bitrate (please use -b:v)) with argument 24k.
Applying option ac (set number of audio channels) with argument 1.
Applying option f (force format) with argument rtp.
Successfully parsed a group of options.
Opening an output file: srtp://10.10.10.46:55197?rtcpport=55197&localrtcpport=55                                                                                                                                                             197&pkt_size=188.
Unknown encoder 'libfdk_aac'
[AVIOContext @ 0x22ad6c0] Statistics: 0 seeks, 0 writeouts

[2019-5-12 10:56:32] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1
[2019-5-12 10:56:42] [Camera-ffmpeg] Snapshot from Camera Name at 480x270
ffmpeg -vcodec h264_mmal -re -i rtsp://admin:Cadillac11@10.10.10.45:554/onvif1 -                                                                                                                                                             t 1 -s 480x270 -f image2 -

> 

I used this command to install ffmpeg
sudo npm install -g homebridge-camera-ffmpeg

**Comment by llemtt** [comment]
Unknown encoder 'libfdk_aac'

your ffmpeg isn't compiled with libfdk_aac support

**Comment by nhatquang88** [comment]
I finally found it, because I didn't install FFMPEG on my RASberry PI.. that is the reason.

Here is how to install FFMPEG On your Rasberry Pi 3B+ if anyone has the same problem as me

> # install build tools
sudo apt-get install -y git pkg-config autoconf automake libtool libx264-dev

# download and build fdk-aac
git clone https://github.com/mstorsjo/fdk-aac.git
cd fdk-aac
./autogen.sh
./configure --prefix=/usr/local --enable-shared --enable-static
make -j4
sudo make install
sudo ldconfig
cd ..

# download and build ffmpeg
git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg
./configure --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
make -j4
sudo make install 

>

**Comment by mosbytom** [comment]
Jesus, this install only took 2 hours..

**Comment by scotch115** [comment]
Wow, this has been killing me for days. Thanks for posting this solution, I can sleep now!

**Comment by cyberralf83** [comment]
had to add the `"videoProcessor": "/home/ffmpeg/ffmpeg",` to the config file a line before the "camera"
