### ISSUE TITLE
Raspberry Pi 3b+ camera low quality

### ISSUE THREAD

**Issue by nhatquang88** [KhaosT/homebridge-camera-ffmpeg#304]
Hello,
after Install FFMPEG and configured 
![8371E3F8-1FDA-4F72-B2FB-40A284FD310E](https://user-images.githubusercontent.com/49787353/57617230-7b989c80-75aa-11e9-828d-d7706d4b10ef.jpeg)

 my RTSP camera correctly.
I 'm able to get it LIVE and Snapshot.
But I have a problem is the video is sometimes choppy and the quality is not clear,
I think it due to the weak graphic processor of the Raspberry even I enable H264_omx.
I have 2 camera in the systems.

so are there anyway I can use external video processor to stream the Video so it will get HD quality.
Thank you

**Comment by tokamac** [comment]
Before this, maybe try to increase the bitrate in the file
`/usr/local/lib/node_modules/homebridge-camera-ffmpeg/ffmpeg.js`
(assuming your homebridge installation is in /usr/local/lib, it could be in /usr/lib/ also)
There are also a couple of flags incompatible with the codec h264_omx (like `-tune zerolatency` alas, or `-f rawvideo`) 
Here is attached my own version of this file. Feel free to adapt it for your own camera.
Before changing this myself, I had a bitrate of 399 kbps only, which created artifacts in all moving portions of the image. I set mine to 1500 kbps VBR, but 800 or 1000 kbps CBR may be enough.
Let me know if this resolves your issue.

[ffmpeg.zip](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/3173715/ffmpeg.zip)

**Comment by nhatquang88** [comment]
hello, I use the GPU memory in my Raspberry is 128 instead of 64.

after I paste your ffmpeg.js files in to 2 folder and login as Root I got this message

>
 [Camera-ffmpeg] Start streaming video from Camera Name, resolution 1280Ã720 pixels, 30 fps, 299 kbit/s (1500 kbit/s forced).
[2019-5-14 08:24:12] [Bedroom TV] Failed to pair! Make sure TV is online and you click "Allow" on the popup
[2019-5-14 08:24:15] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

> 
the camera still take a snapshot but it even not stream anymore...hizz

here is the 2 folder of my ffmpeg.js

> 

/home/pi/node_modules/homebridge-camera-ffmpeg/ffmpeg.js

/usr/lib/node_modules/homebridge-camera-ffmpeg/ffmpeg.js

> 

and here is my config.json files. Thank you
[config.txt](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/3175439/config.txt)

**Comment by tokamac** [comment]
Good thing to have increased GPU memory from 64 to 128 MB, I forgot to tell that. I even set mine at 256 MB (but I plan to run an additional motion detection software with recording capabilities).

Sorry I thought you had the same kind of UVC USB camera as mine, but yours is different: it is an RTSP IP camera, with audio. Is the video normal in an app like VLC when you try to access the RTSP stream?

For homebridge you need to start from the original ffmpeg.js and made slight modifications to test (one each at a time). Also there is a single valid (active) node_modules directory, not two, so I think the one in your home folder may be just a copy. Make some tests to be sure.

As for your config.json file, it appears you have the same camera set up two times. You need to remove the first as I think they collide:
```
{
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Camera Name",
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:Cadillac11@10.10.10.45:554/onvif1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
						"vcodec": "h264_omx",
						"audio":true,
						"packetSize": 188
						
                    }
                },
                {
                    "name": "Phong Ngu",
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:Cadillac11@10.10.10.44:554/onvif1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
						"vcodec": "h264_omx",
						"audio":true,
						"packetSize": 188
						
                    }
                }
			]	
        },
```

First thing I would do to debug also would be to test at first with `"audio":false,` to try to discover if ffmpeg fails on the video or the audio transcoding/encoding stage.

**Comment by nhatquang88** [comment]
`10.10.10.66`

**Comment by tokamac** [comment]
Sorry I misread (two times in a row!) the IP of the two cameras, ad wrongly read same IP although there are two different IPs. So two different devices.

My USB camera also outputs a H.264 stream but its bitrate is too high. If the H.264 stream of your own camera is low enough (and correctly formatted/advertised) you could indeed try `"vcodec": "copy"` in config.json instead of `"vcodec": "h264_omx"`. But I am not aware if someone has already tried/succeeded in passing a non re-encoded H.264 stream in camera-ffmpeg.

**Comment by nhatquang88** [comment]
I see, I will try to enable Vcodec Copy and see what will happen then report to you.
Anyway I enable Debug mode and here is what I got

`rtsp://admin:Cadillac11@10.10.10.45:554/onvif1: Invalid data found when processing input
Exiting normally, received signal 15.

[2019-5-14 19:48:50] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1
`

**Comment by nhatquang88** [comment]
trying with Vcodec : copy then edit the Line 296 of ffmpeg.js as other people in forums suggest

` ((vcodec !== 'copy') ? (' -vf scale=' + width + ':' + height) : '') +`

and here is the error
`ffmpeg -re -i rtsp://admin:Cadillac11@10.10.10.45:554/onvif1 -map 0:0 -vcodec copy -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 5687134 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params oZdhKZrYkfz6YUZzewmLUGSEScEgeaUN6xvY5VW0 srtp://10.10.10.46:64232?rtcpport=64232&localrtcpport=64232&pkt_size=188
[2019-5-14 20:03:56] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1`

So I guess there 're no way to try this camera :( disable Audio has the same issue 👎 ..

**Comment by tokamac** [comment]
You must do such tests first outside of the plugin camera-ffmpeg, directly with the ffmpeg command entered at prompt, which should output a video file. Check there is no error and if the resulting file is playable with a program like VLC. I suggest you try:
`ffmpeg -re -i /dev/video1 -map 0:0 -vcodec copy -pix_fmt yuv420p -r 30 -tune zerolatency -b:v 299k -bufsize 299k -maxrate 299k ~/test.mp4`
entered in a terminal window. Remove `-f rawvideo` as it is incompatible with `-vcodec copy` and `-vcodec h264_omx`. Also, as you make a direct copy of the stream without re-encoding it, none of the target parameters (`-b:v 299k -bufsize 299k -maxrate 299k`, etc) will do anything in this case.
This should produce a test.m4 file in your home folder. You can check the bitrate during the encoding in the window and in VLC once the file has been opened.
If it works, try to make changes in ffmpeg.js accordingly.

**Comment by nhatquang88** [comment]
@tokamac 
u mean I tried that command in the Raspberry Pi command in desktop or tried it via SSH ?
I'm not good at linux just a beginner.. 
Thank you

**Comment by nhatquang88** [comment]
I tried both SSH and Inside the terminal not work.. I posted 2 Photos for you to see
Regards
![4A2C1508-E844-4C49-ADE6-1B0ADD535791](https://user-images.githubusercontent.com/49787353/57705953-f935d880-768e-11e9-83cc-53c1b51b1aeb.png)

**Comment by tokamac** [comment]
sorry `/dev/video1` is for my USB camera. 
For yours:
`ffmpeg -re -i rtsp://admin:Cadillac11@10.10.10.45:554/onvif1 -map 0:0 -vcodec copy -pix_fmt yuv420p -r 30 -tune zerolatency -b:v 299k -bufsize 299k -maxrate 299k ~/test.mp4`

`-i source`
means the source you feed as an input in ffmpeg

**Comment by nhatquang88** [comment]
![C921E227-16D7-4BA2-B155-5CB67681F7AE](https://user-images.githubusercontent.com/49787353/57706300-ac9ecd00-768f-11e9-8a91-11206a574b6d.png)
here is what I got.. it said missing package...

 I didn't run 
-I source 

yet cause I don't know what is it use for?

**Comment by nhatquang88** [comment]
![691CA382-0CDE-4A8E-BA89-22A9FB748ECB](https://user-images.githubusercontent.com/49787353/57706530-20d97080-7690-11e9-9927-72cc33a0d78a.png)
![328F2334-1825-445B-8951-6FFF7D50E4D3](https://user-images.githubusercontent.com/49787353/57706531-20d97080-7690-11e9-9216-97779b720f02.png)
![C55935F7-0610-45F2-8530-545B51F4EDA8](https://user-images.githubusercontent.com/49787353/57706532-21720700-7690-11e9-89a2-fe807ef1918d.png)
the VLC not streaming.. that is what I got

Thank you

**Comment by tokamac** [comment]
"source" was not  command… it was an example to replace by an actual source, inside the ffmpeg… line.

When the command ffmpeg is running on your pi, you have to press q (or ctrl C) to abort and stop encoding first. 
There is no missing _packages_, there are missing _packets_ across the stream of your network. In the end you are not streaming to VLC doing this, you produce a local MP4 file, from the stream of the camera recorded into that file. If this file does not properly open in VLC, then the file produced is not playable, that's all. If it doesn't work in this simplest case, it won't work in the complex case of the ffmpeg-camera plugin in homebridge neither.

I cannot help you further. Start to learn a bit about command prompts and ffmpeg, and experiment yourself. Good luck!

**Comment by nhatquang88** [comment]
@tokamac Thank you alot for your help today, I wish I can find it out.. thank you

**Comment by mrdc** [comment]
> 
> 
> trying with Vcodec : copy then edit the Line 296 of ffmpeg.js as other people in forums suggest
> 
> ` ((vcodec !== 'copy') ? (' -vf scale=' + width + ':' + height) : '') +`
> 

have you edited this line: https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/cd284406d1a67b88b6488fb455128a0b7a220e12/ffmpeg.js#L296?

**Comment by nhatquang88** [comment]
@mrdc : would u please upload your ffmpeg.js files?
I did edit the line 296 but I don't know if I did it correct or not.
I will try your files then load it then see what will happen.
Thank you

**Comment by nhatquang88** [comment]
@all..
My synology DS716+ has the same problem when I'm running the camera.
But on the Synology I ran the command in the startup.sh files

`echo 'deb http://ftp.uk.debian.org/debian jessie-backports main' >> /etc/apt/sources.list`

&
`apk add --no-cache ffmpeg ffmpeg-libs`
after that the video streaming smoothly..

I'm trying to run the same on my Pi but it not possible even with SUDO command in front of..
Anyone please help..
Thanks
