### ISSUE TITLE
Question about special character

### ISSUE THREAD

**Issue by fennec622** [KhaosT/homebridge-camera-ffmpeg#31]
Hi
first thanks for your project
I try to stream from zoneminder
this is form of adress

http://10.0.0.1/zm/cgi-bin/nph-zms?mode=jpeg&maxfps=3&buffer=1000&scale=35&monitor=1&user=user&pass=pass

So i configure config.json like this

{
                                "name": "1-porte",
                                "videoConfig": {
                                "source": "-re -i http://10.0.0.1/zm/cgi-bin/nph-zms?mode=jpeg&maxfps=3&buffer=1000&scale=35&monitor=5&user=user&pass=pass"
                                                }
                                }, 

Screenshot ok on home page but when i put on video live don't ok

ffmpeg don't like character & ...
So i try to add \ before &
"source": "-re -i http://10.0.0.1/zm/cgi-bin/nph-zms?mode=jpeg\&maxfps=3\&buffer=1000\&scale=35\&monitor=5\&user=user\&pass=pass"

But now it's json not valid ..

Do you have a idea for help me

Thanks a lot

**Comment by fennec622** [comment]
another option 
this syntax is flux jpeg
http://10.0.0.1/zm/cgi-bin/nph-zms?mode=jpeg&maxfps=3&buffer=1000&scale=35&monitor=1&user=user&pass=pass
and this syntax is just screenshot
http://10.0.0.1/zm/cgi-bin/nph-zms?mode=single&maxfps=3&buffer=1000&scale=35&monitor=1&user=user&pass=pass

**Comment by Luc-S** [comment]
Hey, I registered an issue today that was also thrown by the & character. My URL in the config is:
`"source": "-re -i 'http://192.168.1.251:8001/videostream.cgi?user=xx&pwd=xx'",`

This brought me 1 step further (I hope). I also had to modify the srtp URL that the plugin generates, take a look at my issue #40

**Comment by fennec622** [comment]
Thanks i try

**Comment by Luc-S** [comment]
I have solved my issue. For this I had to revert the streaming URL, it also doesn't like the quotes as I stated before. I'm on a Raspberry Pi2 with Raspbian Jessie and I had to update the libav-tools package and link ffmpeg to avconv. After that the ffmpeg command ran fine in terminal (without throwing errors about '&' characters).

**Comment by fennec622** [comment]
I work on UBUNTU and i don't see any command ffmpeg ...

I have a bug in ubuntu i think 

I don't see any console.log like console.log(ffmpegCommand);

ffmpeg is setup on ubuntu 
links /usr/bin/ffmpeg -> /opt/ffmpeg/bin/ffmpeg

If you have any idea 

thanks a lot

**Comment by Luc-S** [comment]
The ffmpeg stream it is trying to load is thrown in the homebridge log. Try the Ubuntu version of:
`cat /var/log/homebridge.log`

**Comment by fennec622** [comment]
Yes i know and i tail -f but i don't see handleStreamRequest start

just handleStreamRequest stop
