### ISSUE TITLE
Less logging in ffmpeg.js

### ISSUE THREAD

**Issue by RMCob** [KhaosT/homebridge-camera-ffmpeg#313]
Is there any chance that you could make the logging that goes on in ffmpeg at lines 153, 369 and 389  optional? My logfiles are getting filled up with messages every time an RSTP stream starts and stops, or a snapshot is taken.

Also, related to ffmpeg invocation options, I've found that leaving off the -re option gives better performance on my Raspbeey Pi 3B+. I also tried the -obx plugin version, which 'almost' worked ok. The stream starts OK using the Home app on IOS, or VLC on my Mac, but when using the obx version I can't connect to the camera using the Home widget on my Apple watch, which works great when using the non obx version.

All in all your plugin is working GREAT! Thanks!

**Comment by ctgreybeard** [comment]
According to the ffmpeg documentation about the `-re` option: `Should not be used with actual grab devices or live input streams (where it can cause packet loss).` I have no idea why this option is in all the suggested command options but IMHO it should be removed.
