### ISSUE TITLE
Dahua Camera poor quality

### ISSUE THREAD

**Issue by jelin23** [KhaosT/homebridge-camera-ffmpeg#315]
Hey, I added my Dahua Camera to Homekit, it works, but in home app it's really poor quality of the video. The delay is also about 3-4 seconds. 

Here is my config:

{
                    "name": "Kamera Dahua",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:xxxxxxxxx@xxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=1",
                        "stillImageSource": "-i http://admin:xxxxxxxxxxx@xxxxxxxxx/cgi-bin/snapshot.cgi?chn=1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxBitrate": 256,
                        "maxFPS": 25,
                        "vcodec": "h264_omx"
                    }

**Comment by ctgreybeard** [comment]
You might try a smaller packetSize. I have good luck using 940 or 752. I don't have that camera but I did have quality issues that were improved by adjusting packetSize.

**Comment by jelin23** [comment]
I did everything i could, it seems that raspi zero W is  too weak to stream hd to homebridge

**Comment by TylerD89** [comment]
Haven't used this is awhile and when I installed it on my Pi Zero W last night, I was in for a surprise. The quality was terrible! I don't remember it being that bad at all
