### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by samsonrosen** [KhaosT/homebridge-camera-ffmpeg#32]
Hello,

I have installed the plugin and FFMPEG but I am getting the following error when I run home bridge:

`crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:74:16)
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/uuid.js:14:11)
    at cmdSwitchPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:66:24)
    at cmdSwitchPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:40:10)
    at emitNone (events.js:91:20)
    at API.emit (events.js:185:7)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
Church-Server:~ churchserver$ 
`

I have attached my JSON code, I'm not sure if I am formatting this incorrectly.

Thanks,

Sam
![screen shot 2016-12-13 at 01 30 27](https://cloud.githubusercontent.com/assets/7211878/21123944/c3c0d0d8-c0d3-11e6-872d-103755eae8d9.png)
[config.json.zip](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/647713/config.json.zip)

**Comment by KhaosT** [comment]
You put the ffmpeg payload in the wrong level. It needs to be at top level.
```js
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "Homebridge",
	"accessories": [{
		"accessory": "WeMo",
		"name": "Bedroom Light",
		"wemo_name": "WeMo Switch"
	}],
	"platforms": [{
		"platform": "cmdSwitch2",
		"switches": [{
			"name": "Kettle",
			"on_cmd": "/Users/churchserver/iBrew/ibrewlegacy heat 192.168.1.5",
			"off_cmd": "/Users/churchserver/iBrew/ibrewlegacy stop 192.168.1.5",
			"state_cmd": "/Users/churchserver/iBrew/ibrewlegacy status 192.168.1.5 | grep 'Heating water 100ºC selected'",
			"polling": true,
			"interval": 10
		}, {
			"name": "TV",
			"on_cmd": "python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c PowerToshiba"
		}, {
			"name": "Amp",
			"on_cmd": "python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c PowerAmplifier"
		}, {
			"name": "Mute TV",
			"on_cmd": "python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c MuteTV"
		}, {
			"name": "Mute Amp",
			"on_cmd": "python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c MuteAmp"
		}, {
			"name": "ATV",
			"on_cmd": "python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c WakeATV"
		}, {
			"platform": "Camera-ffmpeg",
			"cameras": [{
				"name": "Webcam 3",
				"videoConfig": {
					"source": "-re -i rtsp://192.168.0.197:554/12",
					"maxStreams": 2,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 30
				}
			}]
		}]
	}]
}
```

**Comment by samsonrosen** [comment]
Amazing! Thank you very much. I've ordered a Mac compatible USB webcam, but I wanted to get the JSON correct before I started working on it.

Thanks,

Sam
