### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by stalkerj** [KhaosT/homebridge-camera-ffmpeg#320]
All my cameras started making this error. It was ok before but now it's not.
Here is my full debug

 [6/24/2019, 8:49:36 PM] [Camera-ffmpeg] Snapshot from detskaya2 at 480x270
0|homebridge  | ffmpeg -rtsp_transport tcp -y -i rtsp://10.0.1.65:8554/unicast -t 1 -s 480x270 -f image2 -
0|homebridge  | [6/24/2019, 8:49:40 PM] [Camera-ffmpeg] Start streaming video from detskaya2 with 1280x720@299kBit
0|homebridge  | ffmpeg -rtsp_transport tcp -y -i rtsp://10.0.1.65:8554/unicast -map 0:0 -vcodec copy -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 15641562 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params AdcQ2IB/mKqKqg5SSj1+CqJ6lETvSWqc9Kg6sg56 srtp://10.0.1.69:55787?rtcpport=55787&localrtcpport=55787&pkt_size=376 -map 0:1 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -ac 1 -payload_type 110 -ssrc 16680809 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params eNp8WOQEf7maWbOkRcKBAMDrgbbmuJ0Qw+YWq93y srtp://10.0.1.69:49422?rtcpport=49422&localrtcpport=49422&pkt_size=376 -loglevel debug
0|homebridge  | ffmpeg version N-93322-gd227ed5d59 Copyright (c) 2000-2019 the FFmpeg developers
0|homebridge  |   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
0|homebridge  |   configuration: --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
0|homebridge  |   libavutil      56. 26.100 / 56. 26.100
0|homebridge  |   libavcodec     58. 47.103 / 58. 47.103
0|homebridge  |   libavformat    58. 26.101 / 58. 26.101
0|homebridge  |   libavdevice    58.  6.101 / 58.  6.101
0|homebridge  |   libavfilter     7. 48.100 /  7. 48.100
0|homebridge  |   libswscale      5.  4.100 /  5.  4.100
0|homebridge  |   libswresample   3.  4.100 /  3.  4.100
0|homebridge  |   libpostproc    55.  4.100 / 55.  4.100
0|homebridge  | Splitting the commandline.
0|homebridge  | Reading option '-rtsp_transport' ... matched as AVOption 'rtsp_transport' with argument 'tcp'.
0|homebridge  | Reading option '-y' ... matched as option 'y' (overwrite output files) with argument '1'.
0|homebridge  | Reading option '-i' ... matched as input url with argument 'rtsp://10.0.1.65:8554/unicast'.
0|homebridge  | Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:0'.
0|homebridge  | Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'copy'.
0|homebridge  | Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'yuv420p'.
0|homebridge  | Reading option '-r' ... matched as option 'r' (set frame rate (Hz value, fraction or abbreviation)) with argument '10'.
0|homebridge  | Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.
0|homebridge  | Reading option '-tune' ...
0|homebridge  |  matched as AVOption 'tune' with argument 'zerolatency'.
0|homebridge  | Reading option '-vf' ... matched as option 'vf' (set video filters) with argument 'scale=1280:720'.
0|homebridge  | Reading option '-b:v' ... matched as option 'b' (video bitrate (please use -b:v)) with argument '299k'.
0|homebridge  | Reading option '-bufsize' ... matched as AVOption 'bufsize' with argument '299k'.
0|homebridge  | Reading option '-maxrate' ...
0|homebridge  |  matched as AVOption 'maxrate' with argument '299k'.
0|homebridge  | Reading option '-payload_type' ...
0|homebridge  |  matched as AVOption 'payload_type' with argument '99'.
0|homebridge  | Reading option '-ssrc' ...
0|homebridge  |  matched as AVOption 'ssrc' with argument '15641562'.
0|homebridge  | Reading option '-f' ...
0|homebridge  |  matched as option 'f' (force format) with argument 'rtp'.
0|homebridge  | Reading option '-srtp_out_suite' ...
0|homebridge  |  matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
0|homebridge  | Reading option '-srtp_out_params' ...
0|homebridge  |  matched as AVOption 'srtp_out_params' with argument 'AdcQ2IB/mKqKqg5SSj1+CqJ6lETvSWqc9Kg6sg56'.
0|homebridge  | Reading option 'srtp://10.0.1.69:55787?rtcpport=55787&localrtcpport=55787&pkt_size=376' ... matched as output url.
0|homebridge  | Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:1'.
0|homebridge  | Reading option '-acodec' ... matched as option 'acodec' (force audio codec ('copy' to copy stream)) with argument 'libfdk_aac'.
0|homebridge  | Reading option '-profile:a' ... matched as option 'profile' (set profile) with argument 'aac_eld'.
0|homebridge  | Reading option '-flags' ...
0|homebridge  |  matched as AVOption 'flags' with argument '+global_header'.
0|homebridge  | Reading option '-f' ... matched as option 'f' (force format) with argument 'null'.
0|homebridge  | Reading option '-ar' ... matched as option 'ar' (set audio sampling rate (in Hz)) with argument '16k'.
0|homebridge  | Reading option '-b:a' ... matched as option 'b' (video bitrate (please use -b:v)) with argument '24k'.
0|homebridge  | Reading option '-bufsize' ...
0|homebridge  |  matched as AVOption 'bufsize' with argument '24k'.
0|homebridge  | Reading option '-ac' ... matched as option 'ac' (set number of audio channels) with argument '1'.
0|homebridge  | Reading option '-payload_type' ...
0|homebridge  |  matched as AVOption 'payload_type' with argument '110'.
0|homebridge  | Reading option '-ssrc' ...
0|homebridge  |  matched as AVOption 'ssrc' with argument '16680809'.
0|homebridge  | Reading option '-f' ... matched as option 'f' (force format) with argument 'rtp'.
0|homebridge  | Reading option '-srtp_out_suite' ...
0|homebridge  |  matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
0|homebridge  | Reading option '-srtp_out_params' ...
0|homebridge  |  matched as AVOption 'srtp_out_params' with argument 'eNp8WOQEf7maWbOkRcKBAMDrgbbmuJ0Qw+YWq93y'.
0|homebridge  | Reading option 'srtp://10.0.1.69:49422?rtcpport=49422&localrtcpport=49422&pkt_size=376' ... matched as output url.
0|homebridge  | Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
0|homebridge  | Finished splitting the commandline.
0|homebridge  | Parsing a group of options: global .
0|homebridge  | Applying option y (overwrite output files) with argument 1.
0|homebridge  | Applying option loglevel (set logging level) with argument debug.
0|homebridge  | Successfully parsed a group of options.
0|homebridge  | Parsing a group of options: input url rtsp://10.0.1.65:8554/unicast.
0|homebridge  | Successfully parsed a group of options.
0|homebridge  | Opening an input file: rtsp://10.0.1.65:8554/unicast.
0|homebridge  | [tcp @ 0x2c77510] No default whitelist set
0|homebridge  | [tcp @ 0x2c77510] Original list of addresses:
0|homebridge  | [tcp @ 0x2c77510] Address 10.0.1.65 port 8554
0|homebridge  | [tcp @ 0x2c77510] Interleaved list of addresses:
0|homebridge  | [tcp @ 0x2c77510] Address 10.0.1.65 port 8554
0|homebridge  | [tcp @ 0x2c77510] Starting connection attempt to 10.0.1.65 port 8554
0|homebridge  | [tcp @ 0x2c77510] Successfully connected to 10.0.1.65 port 8554
0|homebridge  | [rtsp @ 0x2c75750] SDP:
0|homebridge  | v=0
0|homebridge  | o=- 1560974645332825 1 IN IP4 10.0.1.65
0|homebridge  | s=LIVE555 Streaming Media v2017.10.28
0|homebridge  | i=LIVE555 Streaming Media v2017.10.28
0|homebridge  | t=0 0
0|homebridge  | a=tool:LIVE555 Streaming Media v2017.10.28
0|homebridge  | a=type:broadcast
0|homebridge  | a=control:*
0|homebridge  | a=range:npt=0-
0|homebridge  | a=x-qt-text-nam:LIVE555 Streaming Media v2017.10.28
0|homebridge  | a=x-qt-text-inf:LIVE555 Streaming Media v2017.10.28
0|homebridge  | m=video 0 RTP/AVP 96
0|homebridge  | c=IN IP4 0.0.0.0
0|homebridge  | b=AS:0
0|homebridge  | a=rtpmap:96 H264/90000
0|homebridge  | a=fmtp:96 profile-level-id=ffffc01f;sprop-parameter-sets=Z0LAH52oFAFuhAAAAwAEAAADAHoQ,aO48gA==
0|homebridge  | a=x-dimensions:1280,720
0|homebridge  | a=control:track1
0|homebridge  | m=audio 0 RTP/AVP 97
0|homebridge  | c=IN IP4 0.0.0.0
0|homebridge  | b=AS:0
0|homebridge  | a=rtpmap:97 OPUS/48000
0|homebridge  | a=fmtp:97 
0|homebridge  | a=control:track2
0|homebridge  | Failed to parse interval end specification ''
0|homebridge  | [rtsp @ 0x2c75750] video codec set to: h264
0|homebridge  | [rtsp @ 0x2c75750] Extradata set to 0x2c78ac0 (size: 33)
0|homebridge  | [rtsp @ 0x2c75750] audio codec set to: opus
0|homebridge  | [rtsp @ 0x2c75750] audio samplerate set to: 48000
0|homebridge  | [rtsp @ 0x2c75750] audio channels set to: 1
0|homebridge  | [rtsp @ 0x2c75750] setting jitter buffer size to 0
0|homebridge  |     Last message repeated 1 times
0|homebridge  | [rtsp @ 0x2c75750] hello state=0
0|homebridge  | Failed to parse interval end specification ''
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 7(SPS), nal_ref_idc: 3
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 8(PPS), nal_ref_idc: 3
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 7(SPS), nal_ref_idc: 3
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 8(PPS), nal_ref_idc: 3
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
0|homebridge  | [h264 @ 0x2c78610] Format yuv420p chosen by get_format().
0|homebridge  | [h264 @ 0x2c78610] Reinit context to 1280x720, pix_fmt: yuv420p
0|homebridge  | [h264 @ 0x2c78610] Frame num gap 3 1
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
0|homebridge  |     Last message repeated 10 times
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 7(SPS), nal_ref_idc: 3
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 8(PPS), nal_ref_idc: 3
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 7(SPS), nal_ref_idc: 3
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 8(PPS), nal_ref_idc: 3
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 5(IDR), nal_ref_idc: 3
0|homebridge  | [h264 @ 0x2c78610] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
0|homebridge  |     Last message repeated 5 times
0|homebridge  | [rtsp @ 0x2c75750] All info found
0|homebridge  | [rtsp @ 0x2c75750] rfps: 24.750000 0.018507
0|homebridge  | [rtsp @ 0x2c75750] rfps: 24.833333 0.011759
0|homebridge  | [rtsp @ 0x2c75750] rfps: 24.916667 0.007045
0|homebridge  | [rtsp @ 0x2c75750] rfps: 25.000000 0.004365
0|homebridge  | [rtsp @ 0x2c75750] rfps: 25.083333 0.003719
0|homebridge  |     Last message repeated 1 times
0|homebridge  | [rtsp @ 0x2c75750] rfps: 25.166667 0.005108
0|homebridge  | [rtsp @ 0x2c75750] rfps: 25.250000 0.008531
0|homebridge  | [rtsp @ 0x2c75750] rfps: 25.333333 0.013989
0|homebridge  | [rtsp @ 0x2c75750] rfps: 50.000000 0.018606
0|homebridge  | Input #0, rtsp, from 'rtsp://10.0.1.65:8554/unicast':
0|homebridge  |   Metadata:
0|homebridge  |     title           : LIVE555 Streaming Media v2017.10.28
0|homebridge  |     comment         : LIVE555 Streaming Media v2017.10.28
0|homebridge  |   Duration: 
0|homebridge  | N/A, start: 0.000000, bitrate: N/A
0|homebridge  |     Stream #0:0, 40, 1/90000: Video: h264 (Constrained Baseline), 1 reference frame, yuv420p(progressive, left), 1280x720, 0/1, 15 fps, 25.08 tbr, 90k tbn, 30 tbc
0|homebridge  |     Stream #0:1, 26, 1/48000: Audio: opus, 48000 Hz, mono, fltp
0|homebridge  | Successfully opened the file.
0|homebridge  | Parsing a group of options: output url srtp://10.0.1.69:55787?rtcpport=55787&localrtcpport=55787&pkt_size=376.
0|homebridge  | Applying option map (set input stream mapping) with argument 0:0.
0|homebridge  | Applying option vcodec (force video codec ('copy' to copy stream)) with argument copy.
0|homebridge  | Applying option pix_fmt (set pixel format) with argument yuv420p.
0|homebridge  | Applying option r (set frame rate (Hz value, fraction or abbreviation)) with argument 10.
0|homebridge  | Applying option f (force format) with argument rawvideo.
0|homebridge  | Applying option vf (set video filters) with argument scale=1280:720.
0|homebridge  | Applying option b:v (video bitrate (please use -b:v)) with argument 299k.
0|homebridge  | Applying option f (force format) with argument rtp.
0|homebridge  | Successfully parsed a group of options.
0|homebridge  | Opening an output file: srtp://10.0.1.69:55787?rtcpport=55787&localrtcpport=55787&pkt_size=376.
0|homebridge  | Filtergraph 'scale=1280:720' was defined for video output stream 0:0 but codec copy was selected.
0|homebridge  | Filtering and streamcopy cannot be used together.
0|homebridge  | [6/24/2019, 8:49:42 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

**Comment by Partizan7676** [comment]
same here! At this moment i only get snapshot, but no video&audio.

[2019-6-26 13:06:07] [Video-doorbell] Start streaming video from DoorPhone2 99 with 1280x720@299kBit
ffmpeg -rtsp_transport tcp -y -i rtsp://admin:pass@192.168.170.3:554/h264/ch01/sub/av_stream -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 20 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 12562477 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params Sn1C6bMYjWfFtsi7X4MXtdPL+2pjF5+Z/LZAATx3 srtp://192.168.170.4:54519?rtcpport=54519&localrtcpport=54519&pkt_size=188 -map 0:1 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -ac 1 -payload_type 110 -ssrc 10411444 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ukOR73yn96mTVD15x7ONn/apGLAxYZw4Xeye5Bya srtp://192.168.170.4:52976?rtcpport=52976&localrtcpport=52976&pkt_size=188
[2019-6-26 13:06:11] [Video-doorbell] ERROR: FFmpeg exited with code 1

**Comment by stalkerj** [comment]
I also have only snapshot(( no live at all

**Comment by Partizan7676** [comment]
check your ffmpeg version. i find closed issue and solution was installing version 3.2.12

**Comment by Partizan7676** [comment]
try to do that... no way. still get ffmpeg exited with code 1 (((

**Comment by Partizan7676** [comment]
i'll check something in working configuration. as i remember i had make some changes for two way audio. in any way post here result.

**Comment by slavikme** [comment]
Same here, exit error 1
```
[8/11/2019, 7:41:20 PM] [Camera-ffmpeg] Start streaming video from Test Camera with 1280x720@299kBit
[8/11/2019, 7:41:22 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1
```
My version of ffmpeg:
```
/homebridge # ffmpeg -version
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.0 (Alpine 8.2.0)
configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --disable-asm --disable-debug
libavutil      56. 14.100 / 56. 14.100
libavcodec     58. 18.100 / 58. 18.100
libavformat    58. 12.100 / 58. 12.100
libavdevice    58.  3.100 / 58.  3.100
libavfilter     7. 16.100 /  7. 16.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  1.100 /  5.  1.100
libswresample   3.  1.100 /  3.  1.100
libpostproc    55.  1.100 / 55.  1.100
```

I noticed, that it tries to stream with 1280x720 resolution, but my configuration and camera capabilities are 1920x1080. This is the configuration I'm using:

```js
{
    "name": "Test Camera",
    "videoConfig": {
        "source": "-re -i rtsp://192.168.1.171:554/ch0_0.h264",
        "maxStreams": 2,
        "maxWidth": 1920,
        "maxHeight": 1080,
        "audio": true
    }
}
```

**Comment by meluvalli** [comment]
Was this issue never resolved?  I am getting this on a new setup.

**Comment by meluvalli** [comment]
Update; I figured out why I was getting Error 1.   My webcam link that I was using is Blue Iris and it uses Form based login.  Apparently, can't pass credentials using the http://user:pass@IP.   

So, to get around this, in Blue Iris, I am able to turn off "Use secure session keys and login page" under Settings/Web Server/Advanced.  This solved my problem.
