### ISSUE TITLE
Problem with Google drive

### ISSUE THREAD

**Issue by safrapetr** [KhaosT/homebridge-camera-ffmpeg#321]
Im not sure if Im doing something wrong, but.... camera is alive, doing snapshots everything is ok, only Google drive doesnt work. I make my client_secret.json with this manual https://www.instructables.com/id/Take-Snapshots-of-Who-Visits-Your-Door-With-Homebr/ section 5. Then I did everything copy url, than succesfully aproved app to have access and change files folders etc on my google drive, copied code and made token. Add "uploder": true, to my homebridge json and still nothing.

In debug when camera is taking snapshot is only 

čec 02 12:57:29 raspberrypi homebridge[442]: [2019-7-2 12:57:29] [Camera-ffmpeg] Snapshot from Zvonektest at 480x270
čec 02 12:57:29 raspberrypi homebridge[442]: ffmpeg -i http://10.0.1.8:81/snapshot.cgi?user=XXXX&pwd=XXXXX -t 1 -s 480x270 -f image2 -
čec 02 12:57:29 raspberrypi homebridge[442]: Tue, 02 Jul 2019 10:57:29 GMT CameraDrive getFolder
čec 02 12:57:29 raspberrypi homebridge[442]: Tue, 02 Jul 2019 10:57:29 GMT EventedHTTPServer [::ffff:10.0.1.16] HTTP Response is finished

Is there something Im missing??? I dont have any sensor, I hope that meaning of snapshots is that ones generating when picture is reloading.

Thanks!!!

**Comment by NorthernMan54** [comment]
Check your homebridge log file during startup, it must be logging an error in regards to google drive authentication failing.

**Comment by safrapetr** [comment]
Great! Thank you! Problem was that I made homebridge autostart on bootup of raspi with systemd guide here https://timleland.com/setup-homebridge-to-start-on-bootup/ I make user "homebridge" to start the service, so homebridge is looking for client_secret file in /home/homebridge/.homebridge/client_secret.json just moved the files client_secret and drive-nodejs-quickstart to that folder and it works now!!!
