### ISSUE TITLE
iOS 13 compatibility 

### ISSUE THREAD

**Issue by toshibochan** [KhaosT/homebridge-camera-ffmpeg#324]
I have one iPhone on iOS 13 beta and the streaming not working.
When select the camera for look the live stream I have black screen with this “This camera is in “off” mode and cannot stream or record.” Any idea how to fix?
![6D8BAA7D-6C36-4919-873A-57491F33E168](https://user-images.githubusercontent.com/15816913/60836011-6fc7f180-a179-11e9-829d-4ce93241d780.jpeg)

**Comment by saschawerner** [comment]
You will need to have your ATV / Ipad / ... watever is the main device in your homekit setup also on IOS13.

**Comment by toshibochan** [comment]
Oh okay thanks
