### ISSUE TITLE
vflip and hflip only affects stream not stills

### ISSUE THREAD

**Issue by thymjan** [KhaosT/homebridge-camera-ffmpeg#325]
I've used options vflip and hflip to rotate the stream by 180 degrees:
```
{
      "platform": "Camera-ffmpeg",
      "cameras": [
        {
          "name": "piCam",
          "uploader": true,
          "videoConfig": {
              "source": "-re -f video4linux2 -i /dev/video0",
              "stillImageSource": "-re -f video4linux2 -ss 0.9 -i /dev/video0 -vframes 1",
              "maxStreams": 2,
              "maxWidth": 1920,
              "maxHeight": 1080,
              "maxFPS": 30,
              "vcodec": "h264_omx",
              "vflip": true,
              "hflip": true
          }
}
```
This is working only for "source" not for "stillImageSource". Is there an option to do this either?

By the way: Can one change the resolution of the "stillImageSource". This time Camera-ffmpeg uses `[2019-7-16 14:31:45] [Camera-ffmpeg] Snapshot from piCam at 480x270`.

**Comment by mikeavdeev** [comment]
The same problem. Plus: still image and uploaded images are now not rotated too..

**Comment by mikeavdeev** [comment]
Hm. I made a filter to source (still and live):

"source": "-re -i /dev/video0 -vf vflip,hflip",
"stillImageSource": "-i /dev/video0 -vf vflip,hflip",

And its works!
