### ISSUE TITLE
vcodec 'copy' - found a bug in default value

### ISSUE THREAD

**Issue by MedvedBr** [KhaosT/homebridge-camera-ffmpeg#328]
I tried use 'copy' as vcodec to offload RPi from re-encoding to same size as source stream. 
As others here I end up with 'FFmpeg exited with code 1'. 
After some investigation, this error is due to wrong ffmpeg parameters where vcodec 'copy' can't be used together with videoFilter scale

`Filtergraph 'scale=640:360' was defined for video output stream 0:0 but codec copy was selected.`

There is some code which should avoid this in ffmpeg.js line 299, but it still passing default 'scale' params.

To avoid this, default for videoFilter (ffmpeg.js line 36) must be **null** and not empty string **''** as is now (and of course, videoFilter can't be present in config.json).

`this.videoFilter = ffmpegOpt.videoFilter || null; // null is a valid discrete value`

I'm not a programmer, but this should be solved better in code (if vcodec = copy ignore videoFilter... or something similiar)

**Comment by mrdc** [comment]
Unfortunately, it makes no difference in my case with "vcodec": "copy": 
`[Camera-ffmpeg] Start streaming video from Camera-test2 with 1280x720@299kBit`
And stream again stops after 1 second

**Comment by netRunner0** [comment]
@MedvedBr 

“videofilter”: “none”
