### ISSUE TITLE
snaps work, stream doesn't

### ISSUE THREAD

**Issue by mentaluproar** [KhaosT/homebridge-camera-ffmpeg#333]
I can't get this t stream to my phone, my Mac, or roommates phones.  The weird thing is snapshots work fine and I'm not getting any errors in the log.

**Comment by thymjan** [comment]
Which system/version and camera are you using? What does your config.json look like?

**Comment by mentaluproar** [comment]
One roommate has the latest stable iOS on his Xr.  The other's iPhone 7 and my X on the latest beta, as well as my Mac on the latest beta have the same symptoms.

On the server side, I have a rockpro64 running openmediavault x64.  Attached is a redacted version of my config.json.

[config.json.txt](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/3465288/config.json.txt)

**Comment by xses22** [comment]
> I can't get this t stream to my phone, my Mac, or roommates phones. The weird thing is snapshots work fine and I'm not getting any errors in the log.

I'm having the exact same issue. I hope we can get help.

**Comment by mentaluproar** [comment]
What’s weird is it works fine on my watch. Just nothing else.

**Comment by danielbalog** [comment]
I can confirm that it indeed works only on my Apple Watch, but not on iPhone or Macbook. 

Snapshots come from the same RTSP stream as live footage. Also not getting any debug output.

If there's anything I can do to help with debugging let me know.

**Comment by WEZANGO** [comment]
Same here. Was working just fine and after a while stopped without any reason. Even homebridge was not restarted in this period. iOS 13 Beta 5. Maybe it's an iOS issue, so...

**Comment by danielbalog** [comment]
I'm using iOS 12. Have been playing with various settings, including options to reduce quality, bitrate, resolution. Same effect.

**Comment by gprsnlty** [comment]
Same problem here.
