### ISSUE TITLE
Error getting stream and snap, but URLs work in VLC/web browser

### ISSUE THREAD

**Issue by tobdahl** [KhaosT/homebridge-camera-ffmpeg#337]
Hi, I am running Homebridge on a MacOS and have Ubiquiti UVC G3 Dome camera in stand alone mode (not connected to NVR).

While i start up homebridge everything looks fine, I can add the camera in Home app and so on. But in Home app, it cannot pull the snapshot or video from the camera. Both URLs work fine without autentication when opening them in VLC/Web browser.

Please find below the Terminal output from debug mode when trying to fetch snapshot and opening camera in Home app. You will also find my config below.

[8/12/2019, 1:22:31 PM] Homebridge is running on port 58637.
[8/12/2019, 1:22:31 PM] UniFi-G3-Dome is running on port 52100.
[8/12/2019, 1:22:31 PM] Please add [UniFi-G3-Dome] manually in Home app. Setup Code: 031-45-154
[8/12/2019, 1:22:55 PM] [Camera-ffmpeg] Snapshot from UniFi-G3-Dome at 480x270
ffmpeg -f mjpeg -i http://192.168.1.254/snap.jpeg -t 1 -s 480x270 -f image2 -
[8/12/2019, 1:22:55 PM] [Camera-ffmpeg] An error occurs while making snapshot request
[8/12/2019, 1:22:55 PM] [Camera-ffmpeg] Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-f',
    'mjpeg',
    '-i',
    'http://192.168.1.254/snap.jpeg',
    '-t',
    '1',
    '-s',
    '480x270',
    '-f',
    'image2',
    '-'
  ]
}
[8/12/2019, 1:23:10 PM] [Camera-ffmpeg] Start streaming video from UniFi-G3-Dome with 1280x720@299kBit
ffmpeg -rtsp_transport tcp -re -i rtsp://192.168.1.254:554/s1 -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 9983161 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params kp9i/6CTargh1zTqK/k5J8t4Ay4lSBawPEsyNeiC srtp://192.168.1.11:53155?rtcpport=53155&localrtcpport=53155&pkt_size=1316 -map 0:1 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -ac 1 -payload_type 110 -ssrc 12029266 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params wDBqNcP3txFaEB6qrnobn/oKo4IZVZaudnDUZeK9 srtp://192.168.1.11:61286?rtcpport=61286&localrtcpport=61286&pkt_size=1316 -loglevel debug
[8/12/2019, 1:23:10 PM] [Camera-ffmpeg] An error occurs while making stream request
[8/12/2019, 1:23:10 PM] [Camera-ffmpeg] Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-rtsp_transport',
    'tcp',
    '-re',
    '-i',
    'rtsp://192.168.1.254:554/s1',
    '-map',
    '0:0',
    '-vcodec',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-r',
    '30',
    '-f',
    'rawvideo',
    '-tune',
    'zerolatency',
    '-vf',
    'scale=1280:720',
    '-b:v',
    '299k',
    '-bufsize',
    '299k',
    '-maxrate',
    '299k',
    '-payload_type',
    '99',
    '-ssrc',
    '9983161',
    '-f',
    'rtp',
    '-srtp_out_suite',
    'AES_CM_128_HMAC_SHA1_80',
    '-srtp_out_params',
    'kp9i/6CTargh1zTqK/k5J8t4Ay4lSBawPEsyNeiC',
    'srtp://192.168.1.11:53155?rtcpport=53155&localrtcpport=53155&pkt_size=1316',
    '-map',
    '0:1',
    '-acodec',
    'libfdk_aac',
    '-profile:a',
    'aac_eld',
    '-flags',
    '+global_header',
    '-f',
    'null',
    '-ar',
    '16k',
    '-b:a',
    '24k',
    '-bufsize',
    '24k',
    '-ac',
    '1',
    '-payload_type',
    '110',
    '-ssrc',
    '12029266',
    '-f',
    'rtp',
    '-srtp_out_suite',
    'AES_CM_128_HMAC_SHA1_80',
    '-srtp_out_params',
    'wDBqNcP3txFaEB6qrnobn/oKo4IZVZaudnDUZeK9',
    'srtp://192.168.1.11:61286?rtcpport=61286&localrtcpport=61286&pkt_size=1316',
    '-loglevel',
    'debug'

Config:

> 

  "platforms": [
    {
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
  "name": "UniFi-G3-Dome",
  "videoConfig": {
    "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.254:554/s1",
    "stillImageSource": "-f mjpeg -i http://192.168.1.254/snap.jpeg",
    "audio": true,
    "maxStreams": 2,
    "maxWidth": 1920,
    "maxHeight": 1080,
    "maxFPS": 30,
    "debug": true
  }
}
  ]
}
  ]

**Comment by Bad2dabone** [comment]
is FFmpeg installed not the plugin but the codec for mac follow link
error ( errno: 'ENOENT', code: 'ENOENT',)means system can not find codec 

https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg
