### ISSUE TITLE
HikVision - Error 2 - No Video No Still

### ISSUE THREAD

**Issue by Cacus** [KhaosT/homebridge-camera-ffmpeg#343]
Hi I have a HikVision DS-7608NI-K2 / 8P and I am having trouble getting the video or still into homebridge. The json file is as follows:

{
"name": "Camera 1",
"videoConfig": {
"source": "-rtsp_transport tcp -re -i rtsp://username:password@192.168.1.250:554/Streaming/Channels/101/",
"stillImageSource": "-i http://username:password@192.168.1.250/ISAPI/Streaming/Channels/101/picture",
"maxStreams": 2,
"maxWidth": 1280,
"maxHeight": 720,
"maxFPS": 10
}
}

I have tried the above with the admin user to no avail and also as I read some of the comments on these pages I also tried setting up a new user with a password of less than 12 digits and only gave access to remote live view, but still no joy.

In home bridge I get the following:

[Camera-ffmpeg] Snapshot from Camera 1 at 480x270                                                                   
[Camera-ffmpeg] An error occurs while making snapshot request                                                       
[Camera-ffmpeg] Start streaming video from Camera 1 with 1280x720@299kBit                                           
{Camera-ffmpeg] An error occurs while making stream request                                                         
{Camera-ffmpeg] ERROR: FFmpeg exited with code -2            

Any assistance would be most appreciated.

Cheers

**Comment by ceraz68** [comment]
I have the same DVR but 4 port. Here is my videoconfig for the cameras. Note that I use channel 202 for streaming which is lower resolution. I jump to the hikvision app if I need higher resolution.

 "videoConfig": {
                     "source": "-re -i rtsp://user:password@NVR_IP_ADDRESS:554/Streaming/Channels/202",
                        "stillImageSource": "-i http://user:password@NVR_IP_ADDRESS:80/ISAPI/Streaming/channels/201/picture",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": false
                    }

**Comment by Cacus** [comment]
Thanks for reply but still get same error while connecting.

Reading other threads people have had it working by using :
sudo apt-get install -y ffmpeg

However I get the following response: 

sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"                                                                                                 
sudo: /usr/lib/sudo/sudoers.so must be only be writable by owner                                                                                                            
sudo: fatal error, unable to load plugins   

May be something to do with running it in QNAPs Container Station

**Comment by Cacus** [comment]
Small update...

It would appear that the ffmeg libraries aren't installed with the docker images by default. So installing the plugin on it's own doesn't work. Running the following:

apk add --no-cache ffmpeg ffmpeg-libs

followed by rebooting home bridge.
 
Using ceraz68 settings I now have HomeKit showing and updating the Snapshot every 10 seconds... (Incidentally is there a setting to alter the timeframe of the snapshot update?)

However on trying to view the video I get the following code 1 error:

[2/29/2020, 6:56:14 AM] [Camera-ffmpeg] Start streaming video from Alleyway with 1280x720@299kBit                                            
[2/29/2020, 6:56:14 AM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1   

Any advice would be appreciated.

Cheers
