### ISSUE TITLE
Adding to HomeKit 

### ISSUE THREAD

**Issue by AKWillows** [KhaosT/homebridge-camera-ffmpeg#347]
Hi

The instructions say to use the same set up code as Homebridge to add the camera to HomeKit... but when I try in the app, it says that the accessory has already been added... what I am I doing wrong?!

**Comment by IRONROCK20** [comment]
You have to change the name of the camera!

**Comment by AKWillows** [comment]
In the Config json? I did! But using the same set up code as the Honebridge (which I’ve already added to HomeKit with other accessories) it just recognised the same code

**Comment by AKWillows** [comment]
Resolved. I was trying to add using the QR code for Homebridge... instead I needed to say "I don't have a code" and the camera was there to add at which point I could add the set up code.
