### ISSUE TITLE
Config for my DCS-930L

### ISSUE THREAD

**Issue by Pistooli** [KhaosT/homebridge-camera-ffmpeg#35]
I've successfully setup Homebridge with my camera and I can see updated still images in HomeKit. How cool is that. Many thanks. 
But I am not able to make the video work. Could you kindly help?

My config is the following:

"videoConfig": {
        "source": "-re -i rtsp:://xxxxxxxx:yyyyyyyy@192.168.1.105/mjpeg.cgi",
        "stillImageSource": "-i http://xxxxxxxx:yyyyyyyy@192.168.1.105/image.jpg",
        "maxStreams": 1,
        "maxWidth": 640,
        "maxHeight": 480,
        "maxFPS": 5
      }

I can see the camera from a browser with this:
http://xxxxxxxx:yyyyyyyy@192.168.1.105/mjpeg.cgi

Thank you!

**Comment by KhaosT** [comment]
based on the url it's a mjpeg stream. To use that with ffmpeg, try changing the source to ``-f mjpeg -i  http://xxxxxxxx:yyyyyyyy@192.168.1.105/mjpeg.cgi`` and see if that works or not.

**Comment by Pistooli** [comment]
WOW! 

First, thank you for the quick response! :)

Second... it works indeed... THANKS! 

-----
Just for reference here is my current, working config:

"videoConfig": {
"source": "-f mjpeg -i http://xxxxxxxx:yyyyyyyy@192.168.1.105/mjpeg.cgi",
"stillImageSource": "-i http://xxxxxxxx:yyyyyyyy@192.168.1.105/image.jpg",
"maxStreams": 1,
"maxWidth": 640,
"maxHeight": 480,
"maxFPS": 5
}

**Comment by KhaosT** [comment]
glad to know. If possible can you share how's the frame rate for the stream? is it super slow or do you think it's acceptable?

**Comment by Pistooli** [comment]
I have originally set it to 5 fps and I believe it was ok. Now I've changed to 10 and it is perfect for the purpose. 

It is an entry level camera, the DCS-930L, with a maximum resolution of 640x480.

**Comment by KhaosT** [comment]
Okay :) Thanks for sharing. I'll close the issue for now. If you encountered any new issues, feel free to open a new issue.
