### ISSUE TITLE
Too many snapshots taken

### ISSUE THREAD

**Issue by ahartman** [KhaosT/homebridge-camera-ffmpeg#350]
A wonderful module. However, in my opinion, it does too much.  It takes snapshots approx. every 10 seconds, however:
= it always takes two snapshots instead of one, see datetimes in attached snapshot
= it also takes snapshots when camera is not used; it should take snapshots only when the camera is visible in some device. The camera-rpi module does that for example.

This conserves Raspberry performance.

Regards, André Hartman, Belgium

**Comment by NorthernMan54** [comment]
You must have other issues as the plugin only takes snapshots when the home app is open to the room with the camera or an appropriate sensor is triggered in the same room for a notification.  And an appropriate sensor would be a motion, contact etc

**Comment by ahartman** [comment]
Thank you for your quick answer.
After a reboot the Raspberry is behaving normally as you indicated.
I will probably never find out what went wrong.
Please find attached screen dump, proving that is was indeed taking double snapshots; this went on all through the night.


Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België
tel:		0032 3 666 0411
GSM:	0032 488 626 895




> Op 19 sep. 2019, om 23:44 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> You must have other issues as the plugin only takes snapshots when the home app is open to the room with the camera or an appropriate sensor is triggered in the same room for a notification. And an appropriate sensor would be a motion, contact etc
>

**Comment by NorthernMan54** [comment]
@ahartman you may want to edit your comment as your phone and address was posted

**Comment by ahartman** [comment]
Thank you, I did an edit in my previous message.

After a reboot homebridge started taking snapshots again without any Home app having been opened.
Please find attached the save terminal window output and my config.json.

Any suggestions to remedy this?


Met vriendelijke groeten, Kind regards, Meilleures salutations,
André Hartman

**Comment by NorthernMan54** [comment]
@ahartman your logs are not being attached to the issue

The every 10 seconds is a local device sitting on the home app room with the camera.  If you run homebridge in DEBUG mode the logging may show the IP address of the device.

**Comment by ahartman** [comment]
OK now
