### ISSUE TITLE
Since ios13 no snapshot on motion detect

### ISSUE THREAD

**Issue by fennec622** [KhaosT/homebridge-camera-ffmpeg#351]
Hi

Since update ios13 i have no snapshot with motion detect

and no option for notification for camera

on mojave all is ok for snapshot

![](https://photos5.appleinsider.com/gallery/31443-52590-HomeKit-Settings-l.jpg)

thanks

**Comment by tarbychark** [comment]
Same here. My guess is the motion sensor has to be bound to the camera for this to work in iOS 13.

**Comment by ashtonaut** [comment]
Same here. See existing issue #322.

**Comment by fennec622** [comment]
Do you think is it a issue ?

https://github.com/KhaosT/HAP-NodeJS/pull/704

**Comment by fennec622** [comment]
> Now in iOS13, you get a notification AND a live stream from the camera – even on the lock screen. Additionally, within the notification, you can choose to use two-way audio, along with the ability to control any other devices that are in the room, like lights, smart plugs or even a HomeKit door lock.

https://homekitnews.com/2019/07/03/changes-and-additions-to-the-home-app-in-ios13-beta-1/

**Comment by NorthernMan54** [comment]
@fennec622 as this is a duplicate to #332, please close this
