### ISSUE TITLE
Reolink RLC 410W

### ISSUE THREAD

**Issue by Thotty1986** [KhaosT/homebridge-camera-ffmpeg#352]
Good day everybody,

i have a Problem with my config can somebody help me here ?

` {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Hausseite",
                    "videoConfig": {
                        "source": "-re -i rtsp://Homekit:homekit@192.168.178.60:554/h264Preview_01_main",
                        "stillImageSource": "-i http://192.168.178.60/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=Homekit&password=homekit",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxBitrate": 200,
                        "vcodec": "h264_omx",
                        "debug": true
                    }
                }
            ]
        },`

`[9/21/2019, 9:31:56 AM] [Camera-ffmpeg] An error occurs while making stream request
[9/21/2019, 9:31:56 AM] [Camera-ffmpeg] { Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs:
   [ '-re',
     '-i',
     'rtsp://Homekit:homekit@192.168.178.60:554/h264Preview_01_main',
     '-map',
     '0:0',
     '-vcodec',
     'h264_omx',
     '-pix_fmt',
     'yuv420p',
     '-r',
     '30',
     '-f',
     'rawvideo',
     '-tune',
     'zerolatency',
     '-vf',
     'scale=1280:720',
     '-b:v',
     '200k',
     '-bufsize',
     '200k',
     '-maxrate',
     '200k',
     '-payload_type',
     '99',
     '-ssrc',
     '5957081',
     '-f',
     'rtp',
     '-srtp_out_suite',
     'AES_CM_128_HMAC_SHA1_80',
     '-srtp_out_params',
     'nGrThw0zbv86RCChy9pqT2ku+P8RDfcCfT5mCBlW',
     'srtp://192.168.178.74:58254?rtcpport=58254&localrtcpport=58254&pkt_size=1316',
     '-loglevel',
     'debug' ] }
`

somebody an idea ?

**Comment by iuliusmaximilian** [comment]
My woking config for RLC 410

"platform": "Camera-ffmpeg",
"cameras": [{
       "name": "RLC 410",
        "videoConfig": {
                "source": "-re -i rtsp://USER:PASSWORD@10.0.1.4711:554/h264Preview_01_sub",
                "stillImageSource": "-i http://10.0.1.4711:80/cgi-bin/api.cgi?cmd=Snap&channel=0&user=USER&password=PASSWORD",
                "maxStreams": 10,
                "maxWidth": 1920,
                "maxHeight": 1080,
                "maxFPS": 30
        }
}]

**Comment by fssantos95** [comment]
@iuliusmaximilian are you running hombridge in a py? What did you do to make it work? I already install ffmpeg. I have the same camera.

**Comment by iuliusmaximilian** [comment]
see https://github.com/thkl/homebridge-homematic/issues/466 for my configuration
