### ISSUE TITLE
Image flip

### ISSUE THREAD

**Issue by ahartman** [KhaosT/homebridge-camera-ffmpeg#354]
I set hflip: true, which gives a more natural image.
However, the hflip setting for me works only for the video and not for the stills.
This means that when opening the camera window, you see the still image and the view only flips when the video goes live. This looks odd in my opinion.
I think the flip setting should apply to video AND stills.
Please find attached my json.config.

Kind regards, ahartman, Belgium 

[config-json.txt](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/3653885/config-json.txt)

**Comment by ahartman** [comment]
Probleem disappeared

**Comment by urba1n** [comment]
I notice the same problem.

**Comment by mikeavdeev** [comment]
I've got it too
