### ISSUE TITLE
Works on Cellular, not on Wi-fi 

### ISSUE THREAD

**Issue by johnecb** [KhaosT/homebridge-camera-ffmpeg#358]
Hi

After anybody that can help - my cameras stream perfectly when away from home over cellular  but not at home.  I’ve tried 2 different wireless access points.  I have an Apple TV running IOS 13 and my phone and iPad the same.  Neither run the camera stream on Wi-Fi but work fine on cellular.  Is get the same streaming message whether on cellular or Wi-Fi on homebridge.  I ran a docker version of homebridge too to see if that would work but get the same result.  

Any ideas?

**Comment by odrobnik** [comment]
I see the same issue. Only on cellular I get the orange LIVE. As soon as I go on WiFi I don't get streaming video any more.

**Comment by BetoRn** [comment]
I have the same problem, but it stopped working suddenly, also now I cannot access my plex media server from outside, I think it may be something with my router

**Comment by gprsnlty** [comment]
hi im late to this issue but same here cellular works fine but on local wlan i dont get a live stream.
my homebridge is setup on windows
