### ISSUE TITLE
Corrupted snapshots

### ISSUE THREAD

**Issue by cuellarfr** [KhaosT/homebridge-camera-ffmpeg#359]
I noticed all the jpgs uploaded to Google Drive are corrupted since I updated the plugin to v0.1.13. The images still get uploaded to gDrive, but they are broken. I'm not using the new fake motion sensor feature and I haven't modified my config file.

**Comment by NorthernMan54** [comment]
Let me take a look at that ( going to be a few weeks as I’m on vacation till after the 15th ).  Do the snapshots work on your phone okay?

In the interim, you should be able to go back to the previous version.

**Comment by cuellarfr** [comment]
Yes, the snapshots still work on my phone, it's just the uploaded files to gDrive that get corrupted. Thanks for your help!

**Comment by NorthernMan54** [comment]
Off topic, would using google photo’s be better than drive?  I’m thinking very strongly to drop google drive and switch to google photo’s.

PS I’m the coder for the feature

**Comment by NorthernMan54** [comment]
Also could you check the logs for any errors?

**Comment by cuellarfr** [comment]
I'd vote yes to that, since Google Photos UI is a lot better for pictures. Some people might not like to mix personal and security camera pictures, but I guess they could always use a separate google account for this. 

About the errors, this is all I see in the logs
[2019-9-30 16:27:29] [Camera-ffmpeg] Snapshot from Yard Cam at 480x270
[2019-9-30 16:27:39] [Camera-ffmpeg] Snapshot from Garage Cam at 480x270
[2019-9-30 16:27:39] [Camera-ffmpeg] Snapshot from Nursery Cam at 480x270

**Comment by NorthernMan54** [comment]
I use a separate account for my cameras, then share the album with everyone.

Then my personal photo’s don’t get mixed/flooded with snapshots

**Comment by Andi-Coder** [comment]
Same problem here. Any solution for it? plugin v0.1.13.

**Comment by NorthernMan54** [comment]
I’m out of the country for another week, and will be able to look further when I’m back.

**Comment by JGitHubB** [comment]
Same issue here, uploader works well but pictures are corrupted. Running 13.2 with motion enabled, works great.
Logs don’t show any errors for both.

**Comment by NorthernMan54** [comment]
This is fixed with pull request #371 

Until @KhaosT can merge and publish you can pull it directly from repo with

npm install -g https://github.com/NorthernMan54/homebridge-camera-ffmpeg#patch-1
