### ISSUE TITLE
Cant see camera in Home App

### ISSUE THREAD

**Issue by benzman81** [KhaosT/homebridge-camera-ffmpeg#36]
The plugin initializes and the log shows that the camera is assigned a port.

Any idea?

Running on a synology diskstation in a docker container.

**Comment by MrsDelish** [comment]
"platforms": [{
                "platform": "Camera-ffmpeg",
                "name": "Entre Webcam",
                "cameras": [{
                        "name": "Entre Webcam",
                        "videoConfig": {
                                "source": "-re -i /dev/video0",
                                  "stillImageSource": "-i /dev/video0",
                                "maxStreams": 2,
                                "maxWidth": 640,
                                "maxHeight": 480,
                                "maxFPS": 10
                        }
                }]
        }],

try something like this, don't look at my source it is not working, but the camera should show up.

**Comment by benzman81** [comment]
I copied the camera from your snippet and added it to my config file. Still no cameras in home app. I now see that both cameras create open port in the log, but not more.

**Comment by benzman81** [comment]
Sorry, now I get it. Its not like with any other homebridge plugin where devices appear automatically. You need to add it manually. Well, I should have read the last step in the installation manual :-) sorry

**Comment by dietlow** [comment]
how do you add the camera manually
