### ISSUE TITLE
Homekit With Wyze Cam Pan - only still image no stream in HomeKit

### ISSUE THREAD

**Issue by macguru341** [KhaosT/homebridge-camera-ffmpeg#365]
hello
I'm using the Wyze cam pan with HomeKit and RTSP and I can see in HomeKit the photo from the camera but when I press into the photo in HomeKit I can only see the image and there's no video "it says No Response the camera is not responding" - the stream in Wyze app is working fine.
when I close HomeKit and turn it back on I see the photo with time counter . it seems it takes only snap shot .

what can be wrong

**Comment by jfarmer08** [comment]
These are my settings and they working fine on IOS 13
                {
                    "name": "Front Yard",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://admin:admin@10.0.1.9/live",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://admin:admin@10.0.1.9/live",
                        "maxStreams": 2,
                        "manufacturer": "Wyze",
                        "model": "Pan",
                        "serialNumber": "1234567890",
                        "firmwareRevision": "1.0",
                        "motion": true,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "audio": false,
                        "debug": false
                    }
                },
