### ISSUE TITLE
Hombridge video plays on iPhone, but not on iPad

### ISSUE THREAD

**Issue by TheRealGreatOldOne** [KhaosT/homebridge-camera-ffmpeg#368]
Hi, 

I have homebridge running on a Pi4, serving up 4 cameras to HomeKit. All works fine on my iPhone, but for some reason it does not on my iPad. My config is: 
```

       {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Living Room",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:URMDBV@192.168.1.3/h264_stream",
                        "stillImageSource": "-i rtsp://admin:URMDBV@192.168.1.3/Streaming/Channels/1/picture",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 15,
                        "packetSize": 376,
                        "maxBitrate": 802,
                        "videoFilter": "none",
                        "vcodec": "copy",
                        "audio": true
                    }
                },
                {
                    "name": "Dining Room",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:YPXSZG@192.168.1.17/h264_stream",
                        "stillImageSource": "-i rtsp://admin:YPXSZG@192.168.1.17/Streaming/Channels/1/picture",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 15,
                        "packetSize": 376,
                        "maxBitrate": 802,
                        "videoFilter": "none",
                        "vcodec": "copy",
                        "audio": true
                    }
                },
                {
                    "name": "Kitchen",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:NYZWHY@192.168.1.18/h264_stream",
                        "stillImageSource": "-i rtsp://admin:NYZWHY@192.168.1.18/Streaming/Channels/1/picture",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 15,
                        "packetSize": 376,
                        "maxBitrate": 802,
                        "videoFilter": "none",
                        "vcodec": "copy",
                        "audio": true
                    }
                },
                {
                    "name": "Hall",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:TKYPDW@192.168.1.19/h264_stream",
                        "stillImageSource": "-i rtsp://admin:TKYPDW@192.168.1.19/Streaming/Channels/1/picture",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 15,
                        "packetSize": 376,
                        "maxBitrate": 802,
                        "videoFilter": "none",
                        "vcodec": "copy",
                        "audio": true
                    }
                }
            ]
        }
```

Looking in the console when this is happening, the iPhone generates this in the log:
```
[16/10/2019, 17:28:09] [Camera-ffmpeg] Start streaming video from Living Room with 1280x720@299kBit
```

and I get video, audio & snapshots fine. However, when I try on my iPad I get this in the log, as if it was about to start:
```
[16/10/2019, 17:28:35] [Camera-ffmpeg] Start streaming video from Living Room with 1920x1080@802kBit
```
But the video on the iPad times out ("No response, This camera is not responding), and home bridge gives a 'stopped streaming' message in the log (no error codes). The snapshots seem to be very erratic - some times they update on a regular basis about every 12 seconds, like my iPhone does - but then sometimes it it goes minutes or hours before it updates.

I'm not sure what I'm doing wrong. Especially as there is the odd occasion the iPad will work. 

An advice would be appreciated.

Cheers

Jason

**Comment by AgentMcBride** [comment]
Are both the iPad and iPhone running the same version of iOS?

**Comment by TheRealGreatOldOne** [comment]
Yes - they’re both on 13.1.2

The iPhone is an XS, and the iPad is a 2 year old 10.5” Pro.

**Comment by skpio** [comment]
Curious if you've encountered the same [issue](https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/373) as me ... 

Remove `packetSize` from your camera configuration. Your audio will probably go to hell, but I'm curious if you're able to connect to the video stream again.

**Comment by TheRealGreatOldOne** [comment]
Tried that, and no dice I'm afraid... still the same. Works on iPhone, not on iPad.

What I have done to get it working is to remove the vcodec parameter. I was trying to go easy on my Pi by attempting to use the copy command to avoid transcoding. Funny thing is it's quicker to open a stream without it than with it. Weird.

My current config that works on both iPad and iPhone, 1920 x 1080 & 1280 x 720 streams respectively:

`"name": "Living Room",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:URMDBV@192.168.1.3/h264_stream",
                        "stillImageSource": "-i rtsp://admin:URMDBV@192.168.1.3/Streaming/Channels/1/picture",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 15,
                        "packetSize": 376,
                        "maxBitrate": 802,
                        "videoFilter": "none",
                        "audio": true`
