### ISSUE TITLE
ffmpeg not called?

### ISSUE THREAD

**Issue by thorsten-gehrig** [KhaosT/homebridge-camera-ffmpeg#37]
Hi
the still picture is working - but the streaming not.
It looks like FFMPEG is not called at all - i also didn't see a command in the log.

What i found is:
  Accessory [Garage] Getting value for Characteristic "Streaming Status" +0ms
  Accessory [Garage] Got Characteristic "Streaming Status" value: AQEA +0ms
  EventedHTTPServer [::ffff:192.168.0.62] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:192.168.0.62] HTTP request: /resource +2s
  HAPServer [B3:E9:3D:77:63:E4] HAP Request: POST /resource +0ms

I didn't find any FFMPEG call when i open the stream. In fact i didn't see anything on the DEBUG console when i start the stream.
My config is this:
                        "name": "Garage",
                        "videoConfig": {
                                "source": "-re -i rtsp://192.168.0.105/proxyStream-1",
                                "stillImageSource": "-i http://user:password@garage.gehrig.lan/Streaming/channels/1/picture?snapShotImageType=JPEG",
                                "maxStreams": 2,
                                "maxWidth": 1920,
                                "maxHeigh": 1080,
                                "maxFPS": 25
                                }

The source is a "LIVE555 Proxy Server". If i open the rtsp://192.168.0.105/proxyStream-1 with VLC it works perfect. I also see on the LIve555 that these stream is connected. If i try to connect with home bridge it doesn't show any client connected... 
So it looks like the stream is not tried to connect at all.. :-(
Any Idea how to fix or troubleshoot?

Gruß
Thorsten

**Comment by christo16** [comment]
I'm having what I think is the same problem.  I see the supposed call to ffmpeg in the homebridge log output, but I don't see an instance of ffmpeg being run.  My stream works in VLC like yours.

**Comment by thorsten-gehrig** [comment]
No - it´s different: i don't see the ffmpeg call in the homebridge log...

**Comment by rickvdl** [comment]
@thorsten-gehrig I'm having what I think is the same issue over at #30
