### ISSUE TITLE
Audio is pitched

### ISSUE THREAD

**Issue by odx** [KhaosT/homebridge-camera-ffmpeg#370]
On my configuration the Audio input is pitched. When I hold the iPhone close to the mic (ALSA) I can hear for each loop that the repeated sound is slightly higher. What might be the reason for this?

**Comment by lilynet336** [comment]
@odx did you ever resolve this? I tried playing a music video through HomeKit as a test and the audio is pitched upwards so much that it sounds quite bad. @Sunoo If you would please reopen this issue as it is very much not completed.

**Comment by odx** [comment]
i abondoned the implementation as I came across some issues with my physical enclosure for my doorbell / camera which were unsatisfying for me.

also i am nowadays uncertain if I got this sorted out. I played around a lot with the bitrates in the ffmpeg streams that seemed to me to be a promising approach.
