### ISSUE TITLE
Video vs. audio packet size; unable to connect to video stream on iPad/iOS 13.1.3

### ISSUE THREAD

**Issue by skpio** [KhaosT/homebridge-camera-ffmpeg#373]
I noticed an issue over the weekend with video vs. audio packet size. Like most people, I had to drop `packetSize` down below the default to achieve acceptable audio performance from my camera.

On an iPad Pro (A1652) running iPad OS 13.1.3, I couldn't connect to my UniFi G3 Pro. After I ruled out some other issues, I figured out that if I set `packetSize` lower than 940, my iPad won't connect to the video stream. Once I deleted the `packetSize` parameter from my configuration, I was able to connect again. I dropped down 188 bytes at a time and tested each new configuration. Once I hit 752, I could no longer connect to the stream. Unfortunately, 940 isn't low enough to solve the audio chop issue.

The behavior is the same on an iPhone XS Max (A1921) running iOS 13.1.3. which worked fine (with `"packetSize": 188,`) prior to an update to iOS 13.1.3. The last time I actively tested the camera setup on the same iPhone I was on iOS 12.x.

Here is the current configuration I'm running that allows me to connect to the camera stream, but with audio issues:

```
"videoConfig": {
  "source": "-rtsp_transport tcp -re -i rtsp://<camera_stream_url>",
  "additionalCommandline": "-profile:v high -level 4.2 -x264-params \"intra-refresh=1:bframes=0\"",
  "maxWidth": 1920,
  "maxHeight": 1080,
  "maxFPS": 30,
  "maxStreams": 2,
  "audio": true,
  "mapvideo": "0:1",
  "mapaudio": "0:0",
  "debug": true
```

I found a couple of comments that mentioned `packetSize` applies to both video and audio packet size. Is there a means to adjust the video and audio packet size individually? Would it make a difference? Or is there another adjustment that can be made to resolve the audio chop issue? 

Versions:
+-- homebridge@0.4.50
+-- homebridge-camera-ffmpeg@0.1.13

I can provide a copy of a debug, but didn't want to include it due to length if it isn't necessary.

**Comment by skpio** [comment]
I beat the hell out of this until I found a video setting that worked consistently to rule out any other issues, playing with each setting so I understood what it did. Then I looked at audio a second time. I found that a `packetSize` of 188 or 376 was almost a universal failure, but that I'd receive occasional success with 564. Unfortunately, even that low, audio would still chop a little. 

To test my theory, I modified ffmpeg.js and hard-coded the audio pkt_size to 188.

```
358c358
<               '&pkt_size=' + '188';
---
>               '&pkt_size=' + packetsize;
```

Resulted a video and audio stream of:

- srtp://<ipad_ip_addr>:61269?rtcpport=61269&localrtcpport=61269&pkt_size=1316
- srtp://<ipad_ip_addr>:52258?rtcpport=52258&localrtcpport=52258&pkt_size=188

Final configuration:

```
"videoConfig": {
  "source": "-rtsp_transport tcp -re -i rtsp://<camera_stream_url>",
  "additionalCommandline": "-preset slow -profile:v high -level 4.2 -x264-params \"intra-refresh=1:bframes=0\"",
  "maxWidth": 1920,
  "maxHeight": 1080,
  "maxFPS": 15,
  "mapvideo": "0:1", 
  "audio": true,
  "mapaudio": "0:0",
  "debug": true
}
```

This defaults to a 1920x1080@300Kbps stream (when HomeKit cooperates, I caught it requesting 640x360@132K for a while) with different video and audio packet sizes. So far it works well. 

Would it be possible to officially add a `videoPacketSize` and `audioPacketSize` variable?

_Side-note: iPad / HomeKit did not appreciate `maxBitrate` set to 3000. The default (300) seems to work consistently, but when I switched to 3000 (same bitrate as the actual stream from the camera) it didn't work nine times in ten. Video quality is decent considering the conversion, so I left it at 300Kbps._

**Comment by llemtt** [comment]
Glad to hear that you solved your issue but as I already said in #174 packet size should never be a configuration parameter but calculated from the "start" request sent from the ios client.

Video packet size has to be calculated from "mtu" which is the biggest IP packet that can be transmitted without fragmentation and can change depending on connection. So usually the best choice is to use maximum possible size considering all overheads, but it can depend also on codec parameters so writing an expression to calculate it is not easy.

Audio packet size has to be calculated indirectly because what is required by the ios client is that an audio packet is sent on average every "packet_time" milliseconds, this also depending on connection but usually is 30ms for aac codec. Unfortunately there's no ffmpeg aac codec parameter to directly set the packet time so you have to calculate packet size from bitrate and for 24kbit and 30ms calculation gives approximately 188 bytes.

Cheers

**Comment by skpio** [comment]
@llemtt 

Thanks for the additional info. I was curious about the actual mechanics and your explanation filled in some blanks. I'll use it to do some more research.

`packetSize` affects both the video and audio packet size in v0.1.13. If I adjust `packetSize` to 188 to fix the audio issues, none of my iOS devices will connect to the video stream. If I leave `packetSize` at its default 1316 then video works fine but audio is choppy.

The use of packet size to fix audio may not be ideal but it seems to be the only solution at this point, hence my request to have individually-adjustable `*packetSize`. Without a means to adjust video and audio packet size individually, or the ability to set packet_time, the only fix is a manual modification of the source code. Otherwise my options are choppy, unusable audio or no audio.

You mention that HomeKit client "start" and 30ms timing being non-negotiable - are you suggesting that the plug-in needs to better interpret the stream request from the client? Otherwise I'm not sure what else an end user (me) could do to make this work properly.

**Comment by burnbrigther** [comment]
@skpio Did you ever manage to solve this?
