### ISSUE TITLE
Only working in LAN

### ISSUE THREAD

**Issue by pulgagr** [KhaosT/homebridge-camera-ffmpeg#374]
I have tried everything for some days, but it won't work in celular connection, only when I am on my WiFi network.

**Comment by bluntiless** [comment]
What are you using for remote access, HomePod or iPad? Whichever it is, try signing out of your Apple ID account and back in again. Might be the two factor authentication issue. Do other devices other than cameras allow remote access over cellular?

**Comment by pulgagr** [comment]
I am using iPad as home hub. I will try signing out.
And I'm only using homebridge for cameras, other stuff like light, sensors and so on, are configured directly from home assistant, and is working fine over cellular.

**Comment by pulgagr** [comment]
Have tried signing out and did not work as well.
It seems it has some different config for homeassistant (homekit enabled) and hombridge, because homeassistant works just fine over cellular. And in the logs of homebridge when I try to watch the camera, it shows nothing in the debug, it seems that it is not reachable, odd.

**Comment by bluntiless** [comment]
Perhaps try rebooting and restarting all accessories including your router, iPhones, iPads and whatever device you have running homebridge on(Pi)?

**Comment by pimoon** [comment]
I had the same issue : work only in LAN and nothing in WAN whereas other official HomeKit devices were reachable.
The problem was I installed Homebridge in a new linux container by following this page : https://github.com/nfarina/homebridge

BUT there is many steps missing !
So I re-install everything by following this page and now it works well in WAN : https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux

**Comment by pulgagr** [comment]
> I had the same issue : works only in LAN and nothing in WAN whereas other official HomeKit devices were reachable.
> The problem was I installed Homebridge in a new linux container by following this page : https://github.com/nfarina/homebridge
> 
> BUT there is many steps missing !
> So I re-install everything by following this page and now it works well in WAN : https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux

Thanks pimoon, that worked for me as well, I have also installed the web UI, did not know about that one before, very cool!
