### ISSUE TITLE
Motion

### ISSUE THREAD

**Issue by Mark1102** [KhaosT/homebridge-camera-ffmpeg#375]
Sorry if this is a really obvious question.

I have a Neos SmartCam (rebranded Wyze Cam v2) all setup and working with camera-ffmpeg, everything works fine. The camera supports motion detection, can this plugin do motion detection or do I need to move to using homebridge-defang with mqtt etc in order to use motion detection?

Thanks
Mark

**Comment by AshPowell** [comment]
Hi @Mark1102 , Don't suppose you could share your platform config for the Neos SmartCam?

**Comment by Mark1102** [comment]
Hi @AshPowell I've moved over to using homebridge-defang now but config for that is below -

{
            "platform": "Dafang",
            "mqtt": {
                "hostBroker": true,
                "port": 1883,
                "host": "localhost",
                "debug": true,
                "mongoUrl": "mongodb://localhost:27017/mqtt"
            },
            "cameras": [
                {
                    "cameraName": "Office Camera",
                    "cameraRTSPStreamUrl": "rtsp://192.168.0.43:8554/unicast",
                    "mqttTopic": "myhome/dafang/#",
                    "folder": "/home/hoobs/Recordings/",
                    "accessories": [
                        {
                            "name": "Capture Image",
                            "type": "captureImage"
                        },
                        {
                            "name": "Reset Streaming",
                            "type": "resetFFMPEG"
                        }
                    ],
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://192.168.0.43:8554/unicast",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://192.168.0.43:8554/unicast",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "debug": true,
                        "audio": false
                    }
                }
            ]
        },

**Comment by AshPowell** [comment]
Cheers!
