### ISSUE TITLE
Streaming not working

### ISSUE THREAD

**Issue by Cyrelion** [KhaosT/homebridge-camera-ffmpeg#38]
Hi,

I can't figure out why the live stream isn't working. I've tried the command of the logfiles on the commandline:

ffmpeg -re -i 'rtsp://192.168.178.210:554/mcast/11' -threads 0 -vcodec 'h264_omx' -an -r 15 -f rawvideo -tune zerolatency -vf 'scale=1280:720' -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params wtr+AvPulFvzgHjcVfhj96z5guybAH175gTVwy/P 'srtp://192.168.178.36:57758?rtcpport=57758&localrtcpport=57758&pkt_size=1378'

Output:

ffmpeg version N-81800-gf013ba4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-omx --enable-omx-rpi
  libavutil      55. 30.100 / 55. 30.100
  libavcodec     57. 58.103 / 57. 58.103
  libavformat    57. 51.100 / 57. 51.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 63.100 /  6. 63.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://192.168.178.210:554/mcast/11':
  Metadata:
    title           : Media Presentation
    comment         : mpeg4
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p, 1280x720, 25 fps, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
Codec AVOption tune (Tune the encoding params (cf. x264 --fullhelp)) specified for output file #0 (srtp://192.168.178.36:57758?rtcpport=57758&localrtcpport=57758&pkt_size=1378) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
[h264_omx @ 0x2abf680] Using OMX.broadcom.video_encode
[h264_omx @ 0x2abf680] OMX_GetHandle(OMX.broadcom.video_encode) failed: 80001005
Output #0, rtp, to 'srtp://192.168.178.36:57758?rtcpport=57758&localrtcpport=57758&pkt_size=1378':
  Metadata:
    title           : Media Presentation
    comment         : mpeg4
    Stream #0:0: Video: h264, none, q=2-31, 15 fps
    Metadata:
      encoder         : Lavc57.58.103 h264_omx
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_omx))
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

homebridge-part config is:

        "platform": "Camera-ffmpeg",
        "cameras":
        [{
            "name": "Kamera Garten",
            "videoConfig": {
                "source": "-re -i rtsp://192.168.178.210:554/mcast/11",
                "stillImageSource": "-i http://192.168.178.4/snapshots/210/image.jpg",
                "maxStreams": 3,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 25
            }
        }]

Please help me :)

**Comment by josuearisty** [comment]
Hi, were you able to solve your problems? I managed to make hardware acceleration in rpi work just yesterday, I was missing the OMX headers or something like that.

One of this works and the other failed to install for me, try this:

apt-get install libomxil-bellagio-bin
apt-get install libomxil-bellagio-dev

Now h264_omx works for me and its really great!

**Comment by NorthernMan54** [comment]
For myself I found when using the h264_omx codec that I needed to ensure that the user you are running homebridge as has access to /dev/vchiq.  ie `sudo usermod -aG video login` where login is the user you are running homebridge as.

This fixed it for me ;-)

**Comment by cedricve** [comment]
@Cyrelion  any update, having the exact same issue?

**Comment by tmm1** [comment]
I'm having the same problem:

```
[h264_omx @ 0x1071020] Using OMX.broadcom.video_encode
[h264_omx @ 0x1071020] OMX_GetHandle(OMX.broadcom.video_encode) failed: 80001005
```

**Comment by KhaosT** [comment]
Please ask OMX related issue with ffmpeg OMX package provider instead of here… I have no idea how that thing works 😅

**Comment by georgo** [comment]
Not sure, if this is still relevant. I also faced issue with _80001005_ issue and it ended with facepalm. I had gpu_mem in my PI setup to 16, but it needs to be at least 128.
Check your /boot/config.txt ;)

**Comment by timcharper** [comment]
Thanks, @georgo , @josuearisty and @NorthernMan54 ; I was getting issue 80001000 (not 80001005) but changing the perms plus adding gpu_mem=128 resolved it for me.

**Comment by greatbody** [comment]
Change gpu_mem to 256 not working.
