### ISSUE TITLE
Foscam C1 no stream

### ISSUE THREAD

**Issue by pimoon** [KhaosT/homebridge-camera-ffmpeg#381]
I can't get the stream of my Foscam C1.
In VLC the RTSP stream work perfectly.
I have errors in FFMpeg especially : "cur_dts is invalid"

> [11/1/2019, 2:13:46 AM] [Camera ffmpeg] Start streaming video from Camera test with 1280x720@128kBit
ffmpeg -rtsp_transport tcp -re -i rtsp://admin:pass@192.168.1.62:554/videoMain -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -b:v 128k -bufsize 128k -maxrate 128k -payload_type 99 -ssrc 3530926 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 7owWh+tWnEBykVQrfzbVDIMWgI7V/Ayx5AZwHrcX srtp://192.168.1.188:60862?rtcpport=60862&localrtcpport=60862&pkt_size=188 -loglevel debug
ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Splitting the commandline.
Reading option '-rtsp_transport' ...
 matched as AVOption 'rtsp_transport' with argument 'tcp'.
Reading option '-re' ... matched as option 're' (read input at native frame rate) with argument '1'.
Reading option '-i' ...
 matched as input url with argument 'rtsp://admin:pass@192.168.1.62:554/videoMain'.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:0'.
Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'libx264'.
Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'yuv420p'.
Reading option '-r' ... matched as option 'r' (set frame rate (Hz value, fraction or abbreviation)) with argument '10'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.
Reading option '-tune' ...
 matched as AVOption 'tune' with argument 'zerolatency'.
Reading option '-b:v' ...
 matched as option 'b' (video bitrate (please use -b:v)) with argument '128k'.
Reading option '-bufsize' ...
 matched as AVOption 'bufsize' with argument '128k'.
Reading option '-maxrate' ...
 matched as AVOption 'maxrate' with argument '128k'.
Reading option '-payload_type' ...
 matched as AVOption 'payload_type' with argument '99'.
Reading option '-ssrc' ...
 matched as AVOption 'ssrc' with argument '3530926'.
Reading option '-f' ...
 matched as option 'f' (force format) with argument 'rtp'.
Reading option '-srtp_out_suite' ...
 matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
Reading option '-srtp_out_params' ...
 matched as AVOption 'srtp_out_params' with argument '7owWh+tWnEBykVQrfzbVDIMWgI7V/Ayx5AZwHrcX'.
Reading option 'srtp://192.168.1.188:60862?rtcpport=60862&localrtcpport=60862&pkt_size=188' ...
 matched as output url.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option loglevel (set logging level) with argument debug.
Successfully parsed a group of options.
Parsing a group of options: input url rtsp://admin:pass@192.168.1.62:554/videoMain.
Applying option re (read input at native frame rate) with argument 1.
Successfully parsed a group of options.
Opening an input file: rtsp://admin:pass@192.168.1.62:554/videoMain.
[tcp @ 0x561ca9eeff40] No default whitelist set
[tcp @ 0x561ca9eeff40] Original list of addresses:
[tcp @ 0x561ca9eeff40] Address 192.168.1.62 port 554
[tcp @ 0x561ca9eeff40] Interleaved list of addresses:
[tcp @ 0x561ca9eeff40] Address 192.168.1.62 port 554
[tcp @ 0x561ca9eeff40] Starting connection attempt to 192.168.1.62 port 554
[tcp @ 0x561ca9eeff40] Successfully connected to 192.168.1.62 port 554
[rtsp @ 0x561ca9eedd00] SDP:
v=0
o=StreamingServer 3331435948 1116907222000 IN IP4 192.168.1.62
s=videoMain
c=IN IP4 0.0.0.0
t=0 0
a=control:*
a=range:npt=0-
m=video 0 RTP/AVP 96
a=framerate:15
a=transform:1,0,0;0,1,0;0,0,1
a=control:trackID=0
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=420029; sprop-parameter-sets=Z00AH5WoFAFum4CAgIE=,aO48gA==
a=x-dimensions:1280,720
m=audio 0 RTP/AVP 0
a=control:trackID=1
a=rtpmap:0 PCMU/8000/1
Failed to parse interval end specification ''
[rtsp @ 0x561ca9eedd00] video codec set to: h264
[rtsp @ 0x561ca9eedd00] RTP Packetization Mode: 1
[rtsp @ 0x561ca9eedd00] RTP Profile IDC: 42 Profile IOP: 0 Level: 29
[rtsp @ 0x561ca9eedd00] Extradata set to 0x561ca9ef0500 (size: 26)
[rtsp @ 0x561ca9eedd00] audio codec set to: pcm_mulaw
[rtsp @ 0x561ca9eedd00] audio samplerate set to: 8000
[rtsp @ 0x561ca9eedd00] audio channels set to: 1
[rtsp @ 0x561ca9eedd00] setting jitter buffer size to 0
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] hello state=0
Failed to parse interval end specification ''
[h264 @ 0x561ca9ef16c0] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x561ca9ef16c0] nal_unit_type: 8(PPS), nal_ref_idc: 3
[rtsp @ 0x561ca9eedd00] Non-increasing DTS in stream 1: packet 15 with DTS 6884, packet 16 with DTS 6884
[rtsp @ 0x561ca9eedd00] Non-increasing DTS in stream 1: packet 34 with DTS 15792, packet 35 with DTS 15792
[h264 @ 0x561ca9ef16c0] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x561ca9ef16c0] nal_unit_type: 8(PPS), nal_ref_idc: 3
[h264 @ 0x561ca9ef16c0] unknown SEI type 229
[h264 @ 0x561ca9ef16c0] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x561ca9ef16c0] nal_unit_type: 8(PPS), nal_ref_idc: 3
[h264 @ 0x561ca9ef16c0] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x561ca9ef16c0] nal_unit_type: 5(IDR), nal_ref_idc: 3
[h264 @ 0x561ca9ef16c0] unknown SEI type 229
[h264 @ 0x561ca9ef16c0] Format yuvj420p chosen by get_format().
[h264 @ 0x561ca9ef16c0] Reinit context to 1280x720, pix_fmt: yuvj420p
[h264 @ 0x561ca9ef16c0] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
    Last message repeated 5 times
[rtsp @ 0x561ca9eedd00] Non-increasing DTS in stream 1: packet 52 with DTS 24561, packet 53 with DTS 24561
[rtsp @ 0x561ca9eedd00] Non-increasing DTS in stream 1: packet 55 with DTS 26200, packet 56 with DTS 26200
[rtsp @ 0x561ca9eedd00] Non-increasing DTS in stream 1: packet 69 with DTS 32571, packet 70 with DTS 32571
[rtsp @ 0x561ca9eedd00] Non-increasing DTS in stream 1: packet 82 with DTS 38971, packet 83 with DTS 38971
[rtsp @ 0x561ca9eedd00] All info found
[rtsp @ 0x561ca9eedd00] rfps: 9.750000 0.019849
[rtsp @ 0x561ca9eedd00] rfps: 9.833333 0.008634
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] rfps: 9.916667 0.002043
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] rfps: 10.000000 0.000075
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] rfps: 10.083333 0.002731
[rtsp @ 0x561ca9eedd00] rfps: 10.166667 0.010011
[rtsp @ 0x561ca9eedd00] rfps: 19.750000 0.019041
[rtsp @ 0x561ca9eedd00] rfps: 19.833333 0.008170
[rtsp @ 0x561ca9eedd00] rfps: 19.916667 0.001923
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] rfps: 20.000000 0.000299
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] rfps: 20.083333 0.003299
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] rfps: 20.166667 0.010923
[rtsp @ 0x561ca9eedd00] rfps: 29.750000 0.018383
[rtsp @ 0x561ca9eedd00] rfps: 29.833333 0.007856
[rtsp @ 0x561ca9eedd00] rfps: 29.916667 0.001953
[rtsp @ 0x561ca9eedd00] rfps: 30.000000 0.000673
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] rfps: 40.000000 0.001197
[rtsp @ 0x561ca9eedd00] rfps: 50.000000 0.001870
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] rfps: 60.000000 0.002692
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] rfps: 80.000000 0.004787
[rtsp @ 0x561ca9eedd00] rfps: 120.000000 0.010770
[rtsp @ 0x561ca9eedd00] rfps: 29.970030 0.000601
    Last message repeated 1 times
[rtsp @ 0x561ca9eedd00] rfps: 59.940060 0.002403
    Last message repeated 1 times
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://admin:pass@192.168.1.62:554/videoMain':
  Metadata:
    title           : videoMain
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0, 28, 1/90000: Video: h264 (Main), 1 reference frame, yuvj420p(pc, bt709, progressive, left), 1280x720, 0/1
, 10 tbr, 90k tbn, 180k tbc
    Stream #0:1, 86, 1/8000: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
Successfully opened the file.
Parsing a group of options: output url srtp://192.168.1.188:60862?rtcpport=60862&localrtcpport=60862&pkt_size=188.
Applying option map (set input stream mapping) with argument 0:0.
Applying option vcodec (force video codec ('copy' to copy stream)) with argument libx264.
Applying option pix_fmt (set pixel format) with argument yuv420p.
Applying option r (set frame rate (Hz value, fraction or abbreviation)) with argument 10.
Applying option f (force format) with argument rawvideo.
Applying option b:v (video bitrate (please use -b:v)) with argument 128k.
Applying option f (force format) with argument rtp.
Successfully parsed a group of options.
Opening an output file: srtp://192.168.1.188:60862?rtcpport=60862&localrtcpport=60862&pkt_size=188.
[srtp @ 0x561ca9f0e4c0] No default whitelist set
[rtp @ 0x561ca9f0c840] No default whitelist set
[udp @ 0x561ca9ef0440] No default whitelist set
[udp @ 0x561ca9f0d900] No default whitelist set
Successfully opened the file.
detected 4 logical cores
[h264 @ 0x561ca9f0d040] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x561ca9f0d040] nal_unit_type: 8(PPS), nal_ref_idc: 3
Stream mapping:
  Stream #0:0 -> #0:0
 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help
cur_dts is invalid (this is harmless if it occurs once at the start per stream)
    Last message repeated 43 times
[h264 @ 0x561ca9f0d040] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x561ca9f0d040] nal_unit_type: 8(PPS), nal_ref_idc: 3
[h264 @ 0x561ca9f0d040]
nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x561ca9f0d040] nal_unit_type: 5(IDR), nal_ref_idc: 3
[h264 @ 0x561ca9f0d040] unknown SEI type 229
[h264 @ 0x561ca9f0d040] Format yuvj420p chosen by get_format().
[h264 @ 0x561ca9f0d040] Reinit context to 1280x720, pix_fmt: yuvj420p
cur_dts is invalid (this is harmless if it occurs once at the start per stream)
    Last message repeated 434 times
[h264 @ 0x561caa005100] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
cur_dts is invalid (this is harmless if it occurs once at the start per stream)
    Last message repeated 744867 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 751005 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 750288 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 751822 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 754548 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 754775 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 753728 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 753231 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 753034 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 754193 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 751886 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 754097 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 752967 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 752721 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 752224 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 752133 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 752698 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 756004 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 756844 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 754201 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
[11/1/2019, 2:14:02 AM] [Camera ffmpeg] Snapshot from Camera test at 480x270
ffmpeg -i http://192.168.1.62:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=admin&pwd=pass -t 1 -s 480x270 -f image2 -
    Last message repeated 749994 times
cur_dts is invalid (this is harmless if it occurs once at the start per stream)bits/s speed=N/A    
    Last message repeated 689959 times
[graph 0 input from stream 0:0 @ 0x561ca9f28e40] Setting 'video_size' to value '1280x720'
[graph 0 input from stream 0:0 @ 0x561ca9f28e40] Setting 'pix_fmt' to value '12'
[graph 0 input from stream 0:0 @ 0x561ca9f28e40] Setting 'time_base' to value '1/90000'
[graph 0 input from stream 0:0 @ 0x561ca9f28e40] Setting 'pixel_aspect' to value '0/1'
[graph 0 input from stream 0:0 @ 0x561ca9f28e40] Setting 'sws_param' to value 'flags=2'
[graph 0 input from stream 0:0 @ 0x561ca9f28e40] Setting 'frame_rate' to value '10/1'
[graph 0 input from stream 0:0 @ 0x561ca9f28e40] w:1280 h:720 pixfmt:yuvj420p tb:1/90000 fr:10/1 sar:0/1 sws_param:flags=2
[format @ 0x561ca9f0ba80] Setting 'pix_fmts' to value 'yuv420p'
[auto_scaler_0 @ 0x561ca9f2f340] Setting 'flags' to value 'bicubic'
[auto_scaler_0 @ 0x561ca9f2f340] w:iw h:ih flags:'bicubic' interl:0
[format @ 0x561ca9f0ba80] auto-inserting filter 'auto_scaler_0' between the filter 'Parsed_null_0' and the filter 'format'
[AVFilterGraph @ 0x561ca9f5ccc0] query_formats: 4 queried, 2 merged, 1 already done, 0 delayed
[swscaler @ 0x561caa0fdac0] deprecated pixel format used, make sure you did set range correctly
[auto_scaler_0 @ 0x561ca9f2f340] w:1280 h:720 fmt:yuvj420p sar:0/1 -> w:1280 h:720 fmt:yuv420p sar:0/1 flags:0x4
Finishing stream 0:0 without any data written to it.
[libx264 @ 0x561ca9f0f940] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
[libx264 @ 0x561ca9f0f940] profile High, level 3.1
Output #0, rtp, to 'srtp://192.168.1.188:60862?rtcpport=60862&localrtcpport=60862&pkt_size=188':
  Metadata:
    title           : videoMain
    encoder         : Lavf58.20.100
    Stream #0:0, 0, 1/90000: Video: h264 (libx264), 1 reference frame, yuv420p(left), 1280x720, 0/1, q=-1--1, 128 kb/s, 10 fps, 90k tbn, 10 tbc
    Metadata:
      encoder         :
Lavc58.35.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 128000/0/128000 buffer size: 128000 vbv_delay: -1
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=   0x
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Input file #0 (rtsp://admin:pass@192.168.1.62:554/videoMain):
  Input stream #0:0 (video): 2 packets read (84239 bytes); 1 frames decoded;
  Input stream #0:1 (audio): 42 packets read (20160 bytes);
  Total: 44 packets (104399 bytes) demuxed
Output file #0 (srtp://192.168.1.188:60862?rtcpport=60862&localrtcpport=60862&pkt_size=188):
  Output stream #0:0 (video): 0 frames encoded; 0 packets muxed (0 bytes);
  Total: 0 packets (0 bytes) muxed
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
1 frames successfully decoded, 0 decoding errors
[AVIOContext @ 0x561ca9f12e80] Statistics: 0 seeks, 0 writeouts
Exiting normally, received signal 15.

**Comment by pimoon** [comment]
SOLVED
It was an authentification issue.
I had to stream it from motioneye with autentification set to none.
now it is working

**Comment by caius89** [comment]
Hello @pimoon 
Can you please describe how you solved the streaming issue with motioneye?
I am not an expert and am facing the same issue.
thank you
