### ISSUE TITLE
Public Webcam Streams?

### ISSUE THREAD

**Issue by chasenicholl** [KhaosT/homebridge-camera-ffmpeg#382]
Does anyone have a configuration example with using this plugin to stream from publicly accessible web cams. i.e. Stream sources from https://www.earthcam.com/?

**Comment by 350d** [comment]
Hello! Here is my demo for two cameras:

`                {
                    "name": "EARTHCAM #1",

                    "manufacturer": "EARTHCAM",
                    "model": "Manhattan View",
                    "serialNumber": "10874",
                    "firmwareRevision": "1.0",

                    "uploader": false,

                    "videoConfig":{
                        "source": "-re -i https://video3.earthcam.com/fecnetwork/10874.flv/playlist.m3u8",
                        "stillImageSource": "-skip_frame nokey -i https://video3.earthcam.com/fecnetwork/10874.flv/playlist.m3u8 -vframes 1 -r 1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "vcodec": "copy",
                        "_vcodec": "h264_omx",
                        "audio": false,
                        "_packetSize": 999,
                        "mapvideo": "0:1",
                        "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp",
                        "debug": false

                    }
                },
                {
                    "name": "EARTHCAM #2",

                    "manufacturer": "EARTHCAM",
                    "model": "Empire State Building",
                    "serialNumber": "13908",
                    "firmwareRevision": "1.0",

                    "uploader": false,

                    "videoConfig":{
                        "source": "-re -i http://video3.earthcam.com/fecnetwork/13908.flv/playlist.m3u8",
                        "stillImageSource": "-skip_frame nokey -i http://video3.earthcam.com/fecnetwork/13908.flv/playlist.m3u8 -vframes 1 -r 1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "vcodec": "copy",
                        "audio": false,
                        "mapvideo": "0:1",
                        "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp",
                        "debug": false

                    }
                },`

**Comment by plasmoa** [comment]
Rio de Janiero ;) 

```
"cameras": [
        {
            "name": "EARTHCAM 1",
            "manufacturer": "EARTHCAM",
            "model": "Manhattan View",
            "serialNumber": "10874",
            "firmwareRevision": "1.0",
            "uploader": false,
            "videoConfig":{
                "source": "-re -i https://videos3.earthcam.com/fecnetwork/6593.flv/playlist.m3u8",
                "stillImageSource": "-skip_frame nokey -i https://videos3.earthcam.com/fecnetwork/6593.flv/playlist.m3u8 -vframes 1 -r 1",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 15,
                "vcodec": "copy",
                "_vcodec": "h264_omx",
                "audio": false,
                "_packetSize": 999,
                "mapvideo": "0:1",
                "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp",
                "debug": false
            }
        },
```

**Comment by chasenicholl** [comment]
Thanks @350d @plasmoa

**Comment by chasenicholl** [comment]
@350d @plasmoa How did you find the Earthcam m3u8 links? i.e. https://videos3.earthcam.com/fecnetwork/6593.flv/playlist.m3u8

When I visit the website there isn't any information on this, and when I view the source code I don't see any of these videos being loaded. Perhaps because my browser supports HTML5?

**Comment by 350d** [comment]
@chasenicholl I'm scanning whole earth cam network time to time for personal needs [like this one](https://www.youtube.com/watch?v=3wUb933sXy4)
