### ISSUE TITLE
No stills since update. 

### ISSUE THREAD

**Issue by xeronex** [KhaosT/homebridge-camera-ffmpeg#383]
Hi I’m running this plugin on a raspberry Pi since the update i don’t get any still camera shots in the homekit app any ideas why?

**Comment by desq42** [comment]
same here. No Snapshots…

**Comment by HarrySteff** [comment]
Same here. Everything worked well until update... still image is not updated automatically. Only if I click on camera, watch stream a couple of seconds an go back, then still image is updated one time.

**Comment by t1dals** [comment]
I had the same issue with my two cameras. It was either the ffmpeg encoder wasn't installed on my docker (Synology NAS) or I had to tweak the still image url.

I have no issues getting still image updates now. 

I had this issue a few weeks ago.

**Comment by HarrySteff** [comment]
Love stream is working... and before update still image was working.... what do you mean with „tweak still image source“ if I paste it into Browser everything works fine

**Comment by HarrySteff** [comment]
Very Strange, now it is working again :-o 
I have no idea what’s Happening...
