### ISSUE TITLE
streaming update

### ISSUE THREAD

**Issue by marcgrc** [KhaosT/homebridge-camera-ffmpeg#388]
why the streaming of some ip cams on the home apple app updates every 10 seconds and other ipcam do not update until i click the live?
thanks

**Comment by andreyxc** [comment]
I have, too, 60 seconds, need to 10 seconds

**Comment by marcgrc** [comment]
some of my cams don't update, why?
Can you help me ?

Inviato da iPhone

Il giorno 18 nov 2019, alle ore 07:29, andreyxc <notifications@github.com> ha scritto:

﻿

I have, too, 60 seconds, need to 10 seconds

**Comment by andreyxc** [comment]
{
                    "name": "Задний двор",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:IADWZG@192.168.1.45:554/h264/ch01/main/av_stream",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 25,
                        "maxBitrate": 4000,
                        "vcodec": "h264_omx",
                        "audio": true,
                        "packetSize": 1316,
                        "videoProcessor": "ffmpeg",
                        "debug": false
                    }
                }

**Comment by Vannixxo** [comment]
> I have, too, 60 seconds, need to 10 seconds

 I noticed that mine updates every 10 seconds on wifi but 60 seconds on 4g, check that

**Comment by marcgrc** [comment]
Thank

Inviato da iPhone

Il giorno 29 nov 2019, alle ore 16:07, Vannixxo <notifications@github.com> ha scritto:

﻿

I have, too, 60 seconds, need to 10 seconds

I noticed that mine updates every 10 seconds on wifi but 60 seconds on 4g, check that
