### ISSUE TITLE
Snapshots from rtsp is possible

### ISSUE THREAD

**Issue by houser42** [KhaosT/homebridge-camera-ffmpeg#389]
Hello,

I was wondering if there was a way to have the snapshots created from the rtsp streams? 
Perhaps you already are aware..but edit2: answering my own question:
It seems at least for my setup and with the live reporter iPhone app this url appears to work so far:
-re -i rtsp://user:pass@192.168.1.129:554/Streaming/Channels/2/snap.jpg
FWIW, YMMV

**Comment by ahgharian** [comment]
You can use the following: 
`-i rtsp://user:pass@192.168.1.1/live -vframes 1 -r 1` as your `stillImageSource"` value. 

tested on Wyze cameras

**Comment by 350d** [comment]
To avoid corrupted frames on crappy cameras I have this config for preview:
`-skip_frame nokey -i rtsp://user:pass@192.168.1.1/live -vframes 1 -r 1`

**Comment by houser42** [comment]
Hello @350d 
I have an issue with stills that look like pic below. Basically garbage bars where there is actually some forest.  Any hints on how to get rid of those? I tried your code like this:

"stillImageSource": "-skip_frame nokey -i rtsp://u:p@192.168.1.181:554/Streaming/Channels/1/snap.jpg -vframes 1 -r 1",

Correct? I get those issues still..
Many thanks for any hints anyone can provide..

<img width="239" alt="Screenshot 2020-01-04 at 14 53 46 (1)" src="https://user-images.githubusercontent.com/15192440/71766690-d9477380-2f02-11ea-91f3-56c934e7cd1e.png">

**Comment by 350d** [comment]
@houser42 Looks like you trying to get video snapshot from jpg source. My command line command targeted to fetch key frame (without any possible artifacts) from mpeg stream.

**Comment by houser42** [comment]
Thanks @350d !
If so, my command might be incorrect. 
Should I try something else without the .jpg ending? That was from an example.
I am just trying to capture frames from rtsp H264 streams.
It works but I get  occasional garbage frames that would be nice to get rid of.

**Comment by 350d** [comment]
@houser42 just use your regular video rtsp stream url in that command.

**Comment by houser42** [comment]
@350d 
That is what I use. But added your code as quoted.
Not sure, but it does seem to get rid of some garbage, but not all...
Ah well. Can live with it I guess ... Thanks again!

**Comment by iuliusmaximilian** [comment]
Having some Reolink cameras I could solve it by changing the encoding profile in the camera settings from High to Main.
