### ISSUE TITLE
Any tweak to get a smoother video

### ISSUE THREAD

**Issue by benzman81** [KhaosT/homebridge-camera-ffmpeg#39]
The video I get has a delay of about 3 seconds an is just not running smoothly.

The output line is:

`-re -i rtsp://USER:PASSWORD@x.x.x.x:xxxx/ipcam_h264.sdp -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=640:360 -b:
v 132k -bufsize 132k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params Avm+tJYsEIRaWFMSQdSgYTo5oHzjkUpOd+oRMi6q srtp://x.x.x
.x:49546?rtcpport=49546&localrtcpport=49546&pkt_size=1378`

If I run `rtsp://USER:PASSWORD@x.x.x.x:xxxx/ipcam_h264.sdp` in vlc the video has only a second dely, if any.

So is there anything I can use to tweak it? Even cloning the repo is an option for me to change source, just wouldnt know where to start.

**Comment by visnaut** [comment]
Yes, adding `-rtsp_transport tcp` just before `-re -i` greatly improved the quality and performance of the stream for me. 

Without it, the my cameras in the Home app would constantly stutter and be covered in streaks and artifacts. This cleaned it right up.

If that doesn't work out quite as well for you, it's also worth looking at the [RTSP-specific options](http://ffmpeg.org/ffmpeg-protocols.html#rtsp) in ffmpeg to further tweak the output.

Lastly, if you have more than one client streaming from your cameras, consider setting up an [RTSP proxy](http://www.live555.com/proxyServer/) to reduce the amount of work the cameras' chipsets have to do.

**Comment by tmur11** [comment]
@visnaut this has completely changed my opinion of this plugin. This fix is working great! By nature is RTSP not UDP based?

**Comment by Jborn4christ** [comment]
Perfect! Thanks for the solution to the choppy streams.
