### ISSUE TITLE
Full Live Stream fix for Raspberry Pi3b+

### ISSUE THREAD

**Issue by mrdc** [KhaosT/homebridge-camera-ffmpeg#390]
Hello,

I was able to completely fix not working Live Stream on Raspberry Pi3b+ with a config from this issue:
https://github.com/KhaosT/homebridge-camera-ffmpeg/pull/258
Plus installed ffmpeg version 4.1.4 (built with gcc 8.3.0 (Alpine 8.3.0)
`  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --disable-asm --disable-debug
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100`

@KhaosT I think it can be added to Wiki.

**Comment by NorthernMan54** [comment]
@mrdc The beauty of the Wiki is that everyone can publish ;-)

**Comment by mrdc** [comment]
@NorthernMan54 
Done :)

**Comment by malhal** [comment]
And here is the link to the wiki page:
https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/wiki/Fix-Live-Stream-vcodec-copy-on-Raspberry-Pi3b--(maybe-also-for-Pi2-etc)
