### ISSUE TITLE
Feature Request: Grab snapshot from HomeBridge/HomeKit Camera

### ISSUE THREAD

**Issue by ctschach** [KhaosT/homebridge-camera-ffmpeg#391]
Is there any way to grab a snapshot from a HomeBridge/HomeKit Camera and save this locally to a drive?

This basically means I need a HomeClient hat can access the camera - basically the oposite of this project.

Thanks...

**Comment by macjl** [comment]
There is an option to store snapshots to Google Drive. Unfortunately, I didn't see any option to store these snapshots localy.
