### ISSUE TITLE
Can't stream video

### ISSUE THREAD

**Issue by idjul** [KhaosT/homebridge-camera-ffmpeg#394]
Hi,

I can't stream video using the h264_omx codec, I searched for hours, but impossible to find the solution .... Could someone help please?

Here's my conf: 

{
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Salon",
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:password@192.168.1.50:554/live1.sdp",
                        "stillImageSource": "-i http://admin:password@192.168.1.50/dms?nowprofileid=2",
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 25,
                        "vcodec": "h264_omx",
                        "audio": true,
                        "debug": true,
                        "additionalCommandline": "-loglevel verbose"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }

And here's the log:

Dec 02 12:11:25 raspberrypi homebridge[530]: [12/2/2019, 12:11:25] [Camera ffmpeg] Start streaming video from Salon with 1280x720@299kBit
Dec 02 12:11:25 raspberrypi homebridge[530]: ffmpeg -re -i rtsp://admin:password@192.168.1.50:554/live1.sdp -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 25 -f rawvideo -loglevel verbose -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 13073588 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params JCE2ju5mRvR9awAPzqBkLGc7C4EE5tH7VP+hzmf5 srtp://192.168.1.16:61747?rtcpport=61747&localrtcpport=61747&pkt_size=1316 -map 0:1 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -ac 1 -payload_type 110 -ssrc 11370109 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params IKXhzxFRfqXJ6SjvW6wX2kVGrt1ZzZa2KfNeFjYs srtp://192.168.1.16:57639?rtcpport=57639&localrtcpport=57639&pkt_size=1316 -loglevel debug
Dec 02 12:11:25 raspberrypi homebridge[530]: ffmpeg version N-95859-g93414ce831 Copyright (c) 2000-2019 the FFmpeg developers
Dec 02 12:11:25 raspberrypi homebridge[530]:   built with gcc 8 (Raspbian 8.3.0-6+rpi1)
Dec 02 12:11:25 raspberrypi homebridge[530]:   configuration: --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
Dec 02 12:11:25 raspberrypi homebridge[530]:   libavutil      56. 36.100 / 56. 36.100
Dec 02 12:11:25 raspberrypi homebridge[530]:   libavcodec     58. 62.100 / 58. 62.100
Dec 02 12:11:25 raspberrypi homebridge[530]:   libavformat    58. 35.100 / 58. 35.100
Dec 02 12:11:25 raspberrypi homebridge[530]:   libavdevice    58.  9.101 / 58.  9.101
Dec 02 12:11:25 raspberrypi homebridge[530]:   libavfilter     7. 67.100 /  7. 67.100
Dec 02 12:11:25 raspberrypi homebridge[530]:   libswscale      5.  6.100 /  5.  6.100
Dec 02 12:11:25 raspberrypi homebridge[530]:   libswresample   3.  6.100 /  3.  6.100
Dec 02 12:11:25 raspberrypi homebridge[530]:   libpostproc    55.  6.100 / 55.  6.100
Dec 02 12:11:25 raspberrypi homebridge[530]: Successfully parsed a group of options.
Dec 02 12:11:25 raspberrypi homebridge[530]: Parsing a group of options: input url rtsp://admin:password@192.168.1.50:554/live1.sdp.
Dec 02 12:11:25 raspberrypi homebridge[530]: Applying option re (read input at native frame rate) with argument 1.
Dec 02 12:11:25 raspberrypi homebridge[530]: Successfully parsed a group of options.
Dec 02 12:11:25 raspberrypi homebridge[530]: Opening an input file: rtsp://admin:password@192.168.1.50:554/live1.sdp.
Dec 02 12:11:25 raspberrypi homebridge[530]: [tcp @ 0x3092970] No default whitelist set
Dec 02 12:11:25 raspberrypi homebridge[530]: [tcp @ 0x3092970] Original list of addresses:
Dec 02 12:11:25 raspberrypi homebridge[530]: [tcp @ 0x3092970] Address 192.168.1.50 port 554
Dec 02 12:11:25 raspberrypi homebridge[530]: [tcp @ 0x3092970] Interleaved list of addresses:
Dec 02 12:11:25 raspberrypi homebridge[530]: [tcp @ 0x3092970] Address 192.168.1.50 port 554
Dec 02 12:11:25 raspberrypi homebridge[530]: [tcp @ 0x3092970] Starting connection attempt to 192.168.1.50 port 554
Dec 02 12:11:25 raspberrypi homebridge[530]: [tcp @ 0x3092970] Successfully connected to 192.168.1.50 port 554
Dec 02 12:11:25 raspberrypi homebridge[530]: [rtsp @ 0x3090970] SDP:
Dec 02 12:11:25 raspberrypi homebridge[530]: v=0
Dec 02 12:11:25 raspberrypi homebridge[530]: o=- 1574533783532011 1 IN IP4 192.168.1.50
Dec 02 12:11:25 raspberrypi homebridge[530]: s=RTSP/RTP stream 1 from DCS-5222LB
Dec 02 12:11:25 raspberrypi homebridge[530]: i=live1.sdp with v2.0
Dec 02 12:11:25 raspberrypi homebridge[530]: t=0 0
Dec 02 12:11:25 raspberrypi homebridge[530]: a=type:broadcast
Dec 02 12:11:25 raspberrypi homebridge[530]: a=control:*
Dec 02 12:11:25 raspberrypi homebridge[530]: a=range:npt=0-
Dec 02 12:11:25 raspberrypi homebridge[530]: a=x-qt-text-nam:RTSP/RTP stream 1 from DCS-5222LB
Dec 02 12:11:25 raspberrypi homebridge[530]: a=x-qt-text-inf:live1.sdp
Dec 02 12:11:25 raspberrypi homebridge[530]: m=video 0 RTP/AVP 96
Dec 02 12:11:25 raspberrypi homebridge[530]: c=IN IP4 0.0.0.0
Dec 02 12:11:25 raspberrypi homebridge[530]: b=AS:1500
Dec 02 12:11:25 raspberrypi homebridge[530]: a=rtpmap:96 H264/90000
Dec 02 12:11:25 raspberrypi homebridge[530]: a=fmtp:96 packetization-mode=1;profile-level-id=42001F;sprop-parameter-sets=Z0IAH5WoFAFuQA==,aM48gA==
Dec 02 12:11:25 raspberrypi homebridge[530]: a=control:track1
Dec 02 12:11:25 raspberrypi homebridge[530]: m=audio 0 RTP/AVP 0
Dec 02 12:11:25 raspberrypi homebridge[530]: c=IN IP4 0.0.0.0
Dec 02 12:11:25 raspberrypi homebridge[530]: b=AS:64
Dec 02 12:11:25 raspberrypi homebridge[530]: a=control:track2
Dec 02 12:11:25 raspberrypi homebridge[530]: Failed to parse interval end specification ''
Dec 02 12:11:25 raspberrypi homebridge[530]: [rtsp @ 0x3090970] video codec set to: h264
Dec 02 12:11:25 raspberrypi homebridge[530]: [rtsp @ 0x3090970] RTP Packetization Mode: 1
Dec 02 12:11:25 raspberrypi homebridge[530]: [rtsp @ 0x3090970] RTP Profile IDC: 42 Profile IOP: 0 Level: 1f
Dec 02 12:11:25 raspberrypi homebridge[530]: [rtsp @ 0x3090970] Extradata set to 0x3094208 (size: 22)
Dec 02 12:11:25 raspberrypi homebridge[530]: [rtp @ 0x3092e50] No default whitelist set
Dec 02 12:11:25 raspberrypi homebridge[530]: [udp @ 0x3095870] No default whitelist set
Dec 02 12:11:25 raspberrypi homebridge[530]: [udp @ 0x3095870] end receive buffer size reported is 131072
Dec 02 12:11:25 raspberrypi homebridge[530]: [udp @ 0x30a5bc0] No default whitelist set
Dec 02 12:11:25 raspberrypi homebridge[530]: [udp @ 0x30a5bc0] end receive buffer size reported is 131072
Dec 02 12:11:25 raspberrypi homebridge[530]: [rtsp @ 0x3090970] setting jitter buffer size to 500
Dec 02 12:11:25 raspberrypi homebridge[530]: [rtp @ 0x30b63a0] No default whitelist set
Dec 02 12:11:25 raspberrypi homebridge[530]: [udp @ 0x30b6840] No default whitelist set
Dec 02 12:11:25 raspberrypi homebridge[530]: [udp @ 0x30b6840] end receive buffer size reported is 131072
Dec 02 12:11:25 raspberrypi homebridge[530]: [udp @ 0x30c6b80] No default whitelist set
Dec 02 12:11:25 raspberrypi homebridge[530]: [udp @ 0x30c6b80] end receive buffer size reported is 131072
Dec 02 12:11:25 raspberrypi homebridge[530]: [rtsp @ 0x3090970] setting jitter buffer size to 500
Dec 02 12:11:25 raspberrypi homebridge[530]: [rtsp @ 0x3090970] hello state=0
Dec 02 12:11:25 raspberrypi homebridge[530]: Failed to parse interval end specification ''
Dec 02 12:11:25 raspberrypi homebridge[530]: [h264 @ 0x3093d80] nal_unit_type: 7(SPS), nal_ref_idc: 3
Dec 02 12:11:25 raspberrypi homebridge[530]: [h264 @ 0x3093d80] nal_unit_type: 8(PPS), nal_ref_idc: 3
Dec 02 12:11:26 raspberrypi homebridge[530]: [h264 @ 0x3093d80] nal_unit_type: 7(SPS), nal_ref_idc: 3
Dec 02 12:11:26 raspberrypi homebridge[530]: [h264 @ 0x3093d80] nal_unit_type: 8(PPS), nal_ref_idc: 3
Dec 02 12:11:26 raspberrypi homebridge[530]: [h264 @ 0x3093d80] nal_unit_type: 7(SPS), nal_ref_idc: 3
Dec 02 12:11:26 raspberrypi homebridge[530]: [h264 @ 0x3093d80] nal_unit_type: 8(PPS), nal_ref_idc: 3
Dec 02 12:11:26 raspberrypi homebridge[530]: [h264 @ 0x3093d80] nal_unit_type: 5(IDR), nal_ref_idc: 3
Dec 02 12:11:26 raspberrypi homebridge[530]: [h264 @ 0x3093d80] Format yuv420p chosen by get_format().
Dec 02 12:11:26 raspberrypi homebridge[530]: [h264 @ 0x3093d80] Reinit context to 1280x720, pix_fmt: yuv420p
Dec 02 12:11:26 raspberrypi homebridge[530]: [h264 @ 0x3093d80] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 5 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] All info found
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 24.500000 0.017275
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 24.583333 0.012611
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 24.666667 0.008682
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 24.750000 0.005488
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 24.833333 0.003028
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 24.916667 0.001303
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 25.000000 0.000312
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 25.083333 0.000057
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 25.166667 0.000536
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 25.250000 0.001750
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 25.333333 0.003699
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 25.416667 0.006382
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 25.500000 0.009800
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 25.583333 0.013953
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 25.666667 0.018841
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtsp @ 0x3090970] rfps: 50.000000 0.001250
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: Guessed Channel Layout for Input Stream #0.1 : mono
Dec 02 12:11:27 raspberrypi homebridge[530]: Input #0, rtsp, from 'rtsp://admin:password@192.168.1.50:554/live1.sdp':
Dec 02 12:11:27 raspberrypi homebridge[530]:   Metadata:
Dec 02 12:11:27 raspberrypi homebridge[530]:     title           : RTSP/RTP stream 1 from DCS-5222LB
Dec 02 12:11:27 raspberrypi homebridge[530]:     comment         : live1.sdp with v2.0
Dec 02 12:11:27 raspberrypi homebridge[530]:   Duration: N/A, start: 0.000000, bitrate: N/A
Dec 02 12:11:27 raspberrypi homebridge[530]:     Stream #0:0, 28, 1/90000: Video: h264 (Baseline), 1 reference frame, yuv420p(progressive, left), 1280x720, 0/1, 25.08 tbr, 90k tbn, 180k tbc
Dec 02 12:11:27 raspberrypi homebridge[530]:     Stream #0:1, 8, 1/8000: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
Dec 02 12:11:27 raspberrypi homebridge[530]: Successfully opened the file.
Dec 02 12:11:27 raspberrypi homebridge[530]: Parsing a group of options: output url srtp://192.168.1.16:61747?rtcpport=61747&localrtcpport=61747&pkt_size=1316.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option map (set input stream mapping) with argument 0:0.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option vcodec (force video codec ('copy' to copy stream)) with argument h264_omx.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option pix_fmt (set pixel format) with argument yuv420p.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option r (set frame rate (Hz value, fraction or abbreviation)) with argument 25.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option f (force format) with argument rawvideo.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option b:v (video bitrate (please use -b:v)) with argument 299k.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option f (force format) with argument rtp.
Dec 02 12:11:27 raspberrypi homebridge[530]: Successfully parsed a group of options.
Dec 02 12:11:27 raspberrypi homebridge[530]: Opening an output file: srtp://192.168.1.16:61747?rtcpport=61747&localrtcpport=61747&pkt_size=1316.
Dec 02 12:11:27 raspberrypi homebridge[530]: [srtp @ 0x30f1b10] No default whitelist set
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtp @ 0x30ef8f0] No default whitelist set
Dec 02 12:11:27 raspberrypi homebridge[530]: [udp @ 0x30efcb0] No default whitelist set
Dec 02 12:11:27 raspberrypi homebridge[530]: [udp @ 0x30d7640] No default whitelist set
Dec 02 12:11:27 raspberrypi homebridge[530]: Successfully opened the file.
Dec 02 12:11:27 raspberrypi homebridge[530]: Parsing a group of options: output url srtp://192.168.1.16:57639?rtcpport=57639&localrtcpport=57639&pkt_size=1316.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option map (set input stream mapping) with argument 0:1.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option acodec (force audio codec ('copy' to copy stream)) with argument libfdk_aac.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option profile:a (set profile) with argument aac_eld.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option f (force format) with argument null.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option ar (set audio sampling rate (in Hz)) with argument 16k.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option b:a (video bitrate (please use -b:v)) with argument 24k.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option ac (set number of audio channels) with argument 1.
Dec 02 12:11:27 raspberrypi homebridge[530]: Applying option f (force format) with argument rtp.
Dec 02 12:11:27 raspberrypi homebridge[530]: Successfully parsed a group of options.
Dec 02 12:11:27 raspberrypi homebridge[530]: Opening an output file: srtp://192.168.1.16:57639?rtcpport=57639&localrtcpport=57639&pkt_size=1316.
Dec 02 12:11:27 raspberrypi homebridge[530]: [srtp @ 0x31db390] No default whitelist set
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtp @ 0x30efeb0] No default whitelist set
Dec 02 12:11:27 raspberrypi homebridge[530]: [udp @ 0x30f0260] No default whitelist set
Dec 02 12:11:27 raspberrypi homebridge[530]: [udp @ 0x30f01a0] No default whitelist set
Dec 02 12:11:27 raspberrypi homebridge[530]: Successfully opened the file.
Dec 02 12:11:27 raspberrypi homebridge[530]: detected 4 logical cores
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x310a370] nal_unit_type: 7(SPS), nal_ref_idc: 3
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x310a370] nal_unit_type: 8(PPS), nal_ref_idc: 3
Dec 02 12:11:27 raspberrypi homebridge[530]: Stream mapping:
Dec 02 12:11:27 raspberrypi homebridge[530]:   Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_omx))
Dec 02 12:11:27 raspberrypi homebridge[530]:   Stream #0:1 -> #1:0 (pcm_mulaw (native) -> aac (libfdk_aac))
Dec 02 12:11:27 raspberrypi homebridge[530]: Press [q] to stop, [?] for help
Dec 02 12:11:27 raspberrypi homebridge[530]: cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph_1_in_0_1 @ 0x324d890] Setting 'time_base' to value '1/8000'
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph_1_in_0_1 @ 0x324d890] Setting 'sample_rate' to value '8000'
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph_1_in_0_1 @ 0x324d890] Setting 'sample_fmt' to value 's16'
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph_1_in_0_1 @ 0x324d890] Setting 'channel_layout' to value '0x4'
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph_1_in_0_1 @ 0x324d890] tb:1/8000 samplefmt:s16 samplerate:8000 chlayout:0x4
Dec 02 12:11:27 raspberrypi homebridge[530]: [format_out_1_0 @ 0x324dc70] Setting 'sample_fmts' to value 's16'
Dec 02 12:11:27 raspberrypi homebridge[530]: [format_out_1_0 @ 0x324dc70] Setting 'sample_rates' to value '16000'
Dec 02 12:11:27 raspberrypi homebridge[530]: [format_out_1_0 @ 0x324dc70] Setting 'channel_layouts' to value '0x4'
Dec 02 12:11:27 raspberrypi homebridge[530]: [format_out_1_0 @ 0x324dc70] auto-inserting filter 'auto_resampler_0' between the filter 'Parsed_anull_0' and the filter 'format_out_1_0'
Dec 02 12:11:27 raspberrypi homebridge[530]: [AVFilterGraph @ 0x30f1850] query_formats: 4 queried, 6 merged, 3 already done, 0 delayed
Dec 02 12:11:27 raspberrypi homebridge[530]: [auto_resampler_0 @ 0x324e490] [SWR @ 0x324e620] Using s16p internally between filters
Dec 02 12:11:27 raspberrypi homebridge[530]: [auto_resampler_0 @ 0x324e490] ch:1 chl:mono fmt:s16 r:8000Hz -> ch:1 chl:mono fmt:s16 r:16000Hz
Dec 02 12:11:27 raspberrypi homebridge[530]: Output #1, rtp, to 'srtp://192.168.1.16:57639?rtcpport=57639&localrtcpport=57639&pkt_size=1316':
Dec 02 12:11:27 raspberrypi homebridge[530]:   Metadata:
Dec 02 12:11:27 raspberrypi homebridge[530]:     title           : RTSP/RTP stream 1 from DCS-5222LB
Dec 02 12:11:27 raspberrypi homebridge[530]:     comment         : live1.sdp with v2.0
Dec 02 12:11:27 raspberrypi homebridge[530]:     encoder         :
Dec 02 12:11:27 raspberrypi homebridge[530]: Lavf58.35.100
Dec 02 12:11:27 raspberrypi homebridge[530]:     Stream #1:0, 0, 1/16000: Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, delay 288, 24 kb/s
Dec 02 12:11:27 raspberrypi homebridge[530]:     Metadata:
Dec 02 12:11:27 raspberrypi homebridge[530]:       encoder         : Lavc58.62.100 libfdk_aac
Dec 02 12:11:27 raspberrypi homebridge[530]: cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 8596 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [libfdk_aac @ 0x31daaf0] Queue input is backward in time
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtp @ 0x3129b30] Non-monotonous DTS in output stream 1:0; previous: 1760, current: 352; changing to 1760. This may result in incorrect timestamps in the output file.
Dec 02 12:11:27 raspberrypi homebridge[530]: [rtp @ 0x3129b30] Non-monotonous DTS in output stream 1:0; previous: 1760, current: 864; changing to 1760. This may result in incorrect timestamps in the output file.
Dec 02 12:11:27 raspberrypi homebridge[530]: cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
Dec 02 12:11:27 raspberrypi homebridge[530]:     Last message repeated 1 times
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x310a370] nal_unit_type: 7(SPS), nal_ref_idc: 3
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x310a370] nal_unit_type: 8(PPS), nal_ref_idc: 3
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x310a370] nal_unit_type: 5(IDR), nal_ref_idc: 3
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x310a370] Format yuv420p chosen by get_format().
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x310a370] Reinit context to 1280x720, pix_fmt: yuv420p
Dec 02 12:11:27 raspberrypi homebridge[530]: cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x31d2160] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
Dec 02 12:11:27 raspberrypi homebridge[530]: cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x30ebc70] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
Dec 02 12:11:27 raspberrypi homebridge[530]: cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x31c1070] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
Dec 02 12:11:27 raspberrypi homebridge[530]: [h264 @ 0x31c5b00] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph 0 input from stream 0:0 @ 0x31969f0] Setting 'video_size' to value '1280x720'
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph 0 input from stream 0:0 @ 0x31969f0] Setting 'pix_fmt' to value '0'
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph 0 input from stream 0:0 @ 0x31969f0] Setting 'time_base' to value '1/90000'
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph 0 input from stream 0:0 @ 0x31969f0] Setting 'pixel_aspect' to value '0/1'
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph 0 input from stream 0:0 @ 0x31969f0] Setting 'sws_param' to value 'flags=2'
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph 0 input from stream 0:0 @ 0x31969f0] Setting 'frame_rate' to value '301/12'
Dec 02 12:11:27 raspberrypi homebridge[530]: [graph 0 input from stream 0:0 @ 0x31969f0] w:1280 h:720 pixfmt:yuv420p tb:1/90000 fr:301/12 sar:0/1 sws_param:flags=2
Dec 02 12:11:27 raspberrypi homebridge[530]: [format @ 0x3109420] Setting 'pix_fmts' to value 'yuv420p'
Dec 02 12:11:27 raspberrypi homebridge[530]: [AVFilterGraph @ 0x310b010] query_formats: 4 queried, 3 merged, 0 already done, 0 delayed
Dec 02 12:11:27 raspberrypi homebridge[530]: [12/2/2019, 12:11:27] [Camera ffmpeg] Stopped streaming

**Comment by daciand** [comment]
I had the same issue, running homebridge as service, until someone recommended me to add the user to the ```video``` group:
```sudo usermod -a -G video <username>```
where ```<username>``` is the user homebridge use it to run. In my case it's like this:
```sudo usermod -a -G video homebridge```
Afterwards, don't forget to restart homebridge.

**Comment by idjul** [comment]
Hi, thank you for the answer, but unfortunately, it doesn't work :(

**Comment by cuellarfr** [comment]
This is so helpful, thanks! I just rebuilt my homebridge setup from scratch and I was missing this last piece of information. Maybe we should add it to the wiki > https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Raspberry-PI

**Comment by pax0707** [comment]
> I had the same issue, running homebridge as service, until someone recommended me to add the user to the `video` group:


After months of dealing with buggy video streams and trying everything this finally worked!
Cheers for this info.

**Comment by afbenevides** [comment]
Hi I've been searching for a solution, maybe you can help. I have the Still images working every12s on OSX or IOS home.app. But the video stream only works on OSX home.app. The IOS home.app opens the stream, but after 1rst image it hangs up and only have a black screen.

I installed from scratch on new raspian image, compiled FFmpeg on the pi with h264 and all...
also used the command shown in this post above.
sudo usermod -a -G video homebridge (my user is homebridge)

The debug output finishes with: 

[h264_omx @ 0x1c0ca10] OMX state changed to 2
[h264_omx @ 0x1c0ca10] OMX state changed to 1
Exiting normally, received signal 15.
[1/21/2020, 02:06:01] [Camera-ffmpeg] Stopped streaming

any idea?
