### ISSUE TITLE
Rich push notification only showing still image (but stream works in Home app)

### ISSUE THREAD

**Issue by techbert** [KhaosT/homebridge-camera-ffmpeg#395]
Hi, I love this plugin! Thank you so much for your work on it ❤️

I've followed the instructions in the wiki to set up proper push notifications on iOS 13 and it works! 🎉The only thing I'm missing is getting a live stream in the push notification itself when expanding it. Is this even possible? Currently I just see the same still image when expanding the push notification.

The config is to some degree properly set up, as I see a still image in the push notification and I'm seeing the live stream in the Home app. The fact the stream works in Home I assume also eliminates ffmpeg installation or codes on my raspberry pi (where homebridge is installed) being the root cause.

Any idea what could be the problem or how I could fix it? If not, is there an alternative such as having the sill image/snapshot in the push notification update more frequently or similar?

**Comment by NorthernMan54** [comment]
based on my understanding of the feature, that is the expected behavior
