### ISSUE TITLE
Motion being disabled

### ISSUE THREAD

**Issue by Johannp02180** [KhaosT/homebridge-camera-ffmpeg#396]
I would enable motion in the config but whenever I restart or add things it will automatically disable and remove it. Is this because it isn’t an option through the plugin’s settings?

**Comment by NorthernMan54** [comment]
I’m sorry I don’t understand the issue and where the setting is changing

**Comment by Johannp02180** [comment]
Sorry, so under the "Plugins" tab when something is edited in the ffmpeg plugin, the motion parameter I add directly in config disappears, even sometimes restart it randomly disappears and I have to add it again and set the motion automation again. I think the fix would be to add a motion checkbox in the plugin settings editor.

**Comment by NorthernMan54** [comment]
What is the plugins tab?  Homebridge doesn’t have a plugins tab as it doesn’t have a GUI

**Comment by Johannp02180** [comment]
Oh maybe this is a homebridge UI-X issue.
