### ISSUE TITLE
Issue/Request: Error FFmpeg exited with code 1

### ISSUE THREAD

**Issue by meluvalli** [KhaosT/homebridge-camera-ffmpeg#398]
I have noticed you switch between cameras two quickly, you will get the FFmpeg exit error.

There is no notification on iOS for a VERY long time.   

Instead of just exiting the script, would be nice if it was possible to retry X amount of times (User defined preferably)

Usually, you just have to close and restart the FFmpeg stream, so it seams as though this could be build into the code to automatically do it since iOS sits waiting for the camera to load still.

**Comment by Theofanis-Theograms** [comment]
Check the camera accessory config, probably an error at the `videoSource` (that was the case for me).
