### ISSUE TITLE
Crash when try to view camera online

### ISSUE THREAD

**Issue by JekaKey** [KhaosT/homebridge-camera-ffmpeg#4]
Hello!
In home screen i see screenshot from camera, but when i try to view online homekit crash with error:

> /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/StreamController.js:445
>   var data = Buffer.from(value, 'base64');
>                     ^
> 
> TypeError: base64 is not a function
>     at Function.from (native)

I use imac, FFMPEG also install on system.

> ffmpeg version 3.0.2 Copyright (c) 2000-2016 the FFmpeg developers
>  built with Apple LLVM version 7.3.0 (clang-703.0.31)

What there can be a problem?
Thank you!

**Comment by KhaosT** [comment]
@JekaKey What's the version of node on your computer? Try update to latest v6.x and see if it fix the problem.

**Comment by JekaKey** [comment]
Thats right! My node is 4.6, update to 6.7 solved problem. Everything is fine!
Thank you!
FFMPEG eat 60% CPU when decode my camera =)

**Comment by KhaosT** [comment]
@JekaKey there may have better way to handle the encoding but just to be safe I didn't use any fancy stuff...
