### ISSUE TITLE
Multiple Xiaomi Xiaofang Not Working

### ISSUE THREAD

**Issue by recom273** [KhaosT/homebridge-camera-ffmpeg#400]
I have had one camera working for a week or more now, I flashed another with Dafang hacks and I have it up working simultaneously with the other camera via web interface.

I tried to add the camera through the settings interface on homebridge, when I click 'add accessory' there is no camera to add.

I understood the plugin managed the ports? I just completed the settings with info and compared the two. 

Do I need to change the ports on the web interface and the plugin will manage?

My current view of the 'entry' camera has frozen and I don't seem to be getting info on the log screen other than snapshot report when rebooting the install.

What am I missing here?

```
 {
            "name": "Cameras",
            "cameras": [
                {
                    "name": "Entry",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://192.168.0.171:8554/unicast",
                        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
                        "maxStreams": 2,
                        "maxWidth": 720,
                        "maxHeight": 480,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "h264_omx",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                },
                {
                    "name": "Garage",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://192.168.0.180:8554/unicast",
                        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
                        "maxStreams": 2,
                        "maxWidth": 720,
                        "maxHeight": 480,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "h264_omx",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
```

**Comment by NorthernMan54** [comment]
Homebridge and this plugin do not have a UI for entering settings, so I’m not sure what your asking.

**Comment by recom273** [comment]
> Homebridge and this plugin do not have a UI for entering settings, so I’m not sure what your asking.
> […](#)

If you have ozone/ homebridge-config-ui-x  then there is a GUI

I cannot get multiple cameras working

**Comment by NorthernMan54** [comment]
Then that is an issue for the GUI and not this plugin

**Comment by recom273** [comment]
So, is the config correct? 

I will just add the correct info into the config manually, will the result be different?

**Comment by recom273** [comment]
> Then that is an issue for the GUI and not this plugin
> […](#)

OK, I see - the GUI creates a non-standard config .. 

I will try using a standard config and see what happens

**Comment by recom273** [comment]
Still no additional camera showing in home app after I update the config.
 
`{
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Entry",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://192.168.0.171:8554/unicast",
                        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
                        "maxStreams": 2,
                        "maxWidth": 720,
                        "maxHeight": 480,
                        "maxFPS": 10,
                        "vcodec": "h264_omx",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                },
                {
                    "name": "Garage",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://192.168.0.180:8554/unicast",
                        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
                        "maxStreams": 2,
                        "maxWidth": 720,
                        "maxHeight": 480,
                        "maxFPS": 10,
                        "vcodec": "h264_omx",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                }
            ]
        },`

**Comment by NorthernMan54** [comment]
Did you add it in the home app?  Each camera is a separate accessory and needs to be added individually in the home app

**Comment by recom273** [comment]
Yes, I understand.

No, it’s not showing up in the ‘add accessory’ - I have added a second camera in the past, but it was a different manufacturer with a different port. I have since removed it.

My question is wether or not, I need to change the port on either the camera settings or the config?

**Comment by NorthernMan54** [comment]
The 8554?  No this doesn’t matter

**Comment by NorthernMan54** [comment]
Your last config posting has an extra ‘ after cameras, besides that it looks reasonable

"platform": "Camera-ffmpeg",
            "cameras": ['

**Comment by recom273** [comment]
> Your last config posting has an extra ‘ after cameras, besides that it looks reasonable
> 
> "platform": "Camera-ffmpeg",
> "cameras": ['

I think that appeared when I posted using the code box - ignore that.

Hmmm .. OK, thanks for your time.

I think it’s time for another install, it seems like it should be straightforward as adding one camera / two from different manufacturers, which has been no issue in the past.
