### ISSUE TITLE
Synology with Reolink

### ISSUE THREAD

**Issue by solidola** [KhaosT/homebridge-camera-ffmpeg#403]
Hi I'm trying to configure "Homebridge Camera Ffmpeg". 
I get ther following error:

[Camera ffmpeg] Snapshot from Rear Camera 2 at 480x270
[Camera ffmpeg] An error occurs while making snapshot request
[Camera ffmpeg] Start streaming video from Rear Camera 2 with 1280x720@299kBit
[Camera ffmpeg] An error occurs while making stream request
[Camera ffmpeg] ERROR: FFmpeg exited with code -2

My config is as follows:

                        "name": "Camera ffmpeg",
                        "cameras": [
                                {
                                    "name": "Front yard",
                                    "videoConfig": {
                                           "source": "-re -i rtsp://USER:PASSWORD@XXX.XXX.XXX.XXX:554//h264Preview_01_main",
                        "stillImageSource": "-i http://XXX.XXX.XXX:80/cgi-bin/api.cgi?cmd=Snap&channel=0&user=ADMIN&password=PASSWORD",
                        "maxStreams": 2,
                        "maxWidth": 2048,
                        "maxHeight": 1536,
                        "maxFPS": 30,
                        "maxBitrate": 8192,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}

**Comment by arjohnson15** [comment]
Here is what i got to work with my ReoLink camera that i use with Synology also. snapshot updates every minute audio in the stream works. 

```json
        {
            "name": "Front Drive",
            "cameras": [
                {
                    "name": "Front Drive",
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:Aj0440925@10.0.1.61:554/h264Preview_01_sub",
                        "stillImageSource": "-i http://10.0.1.61/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=Aj0440925",
                        "maxStreams": 5,
                        "maxWidth": 2560,
                        "maxHeight": 1920,
                        "maxFPS": 30,
                        "audio": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Comment by arjohnson15** [comment]
Here is what I got to work with my reolink cameras I also use on synology. Snapshots update and the audio feature I was able to get to work also. 

```json
        {
            "name": "Front Drive",
            "cameras": [
                {
                    "name": "Front Drive",
                    "videoConfig": {
                        "source": "-re -i rtsp://myusername:mypassword@/ipaddress:554/h264Preview_01_sub",
                        "stillImageSource": "-i http://ipaddress/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=myusername&password=mypassword",
                        "maxStreams": 5,
                        "maxWidth": 2560,
                        "maxHeight": 1920,
                        "maxFPS": 30,
                        "audio": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Comment by Davaogedy** [comment]
This does not solve my problem. 
I have fresh installed the docker, installed homebridge and the ffmpeg plugin on my synology DiskStation.

My Config.json is:
{
		"name": "Camera ffmpeg",
		"cameras": [{
				"name": "Reolink",
				"manufacturer": "Reolink",
    				"model": "RLC-420-5MP",
    				"serialNumber": "123456",
				"videoConfig": {
					"source": "-re -i rtsp://myuser:mypassword@192.168.x.xxx:554/h264Preview_01_sub",
					"stillImageSource": "-i http://192.168.x.xxx/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=myuser&password=mypassword",
					"maxStreams": 5,
					"maxWidth": 2560,
					"maxHeight": 1920,
					"maxFPS": 30,
					"audio": true
				}
			},
			],
		"platform": "Camera-ffmpeg"
	}


The protocoll shows:
[Camera ffmpeg] Snapshot from Reolink Flur at 480x270
[Camera ffmpeg] An error occurs while making snapshot request
[Camera ffmpeg] Start streaming video from Reolink Flur with 1280x720@299kBit
[Camera ffmpeg] An error occurs while making stream request
[Camera ffmpeg] ERROR: FFmpeg exited with code -2

I can launch the rtsp stream with VLC and it works perfectly.

Really dont know what is the issue right here.

**Comment by resgroupmsr** [comment]
I failed to get it working on Synology / Docker install as well.  I believe this is related somehow to Synology not liking the ffmpeg running.  I have gotten it running well on a Raspberry Pi 4.

**Comment by arjohnson15** [comment]
I might note I am running this container of homebridge that has ffmpeg. [https://registry.hub.docker.com/r/nicholasrobinson/ffmpeg-homebridge](url)

**Comment by arjohnson15** [comment]
try and use the exact code I used also just with replacing your IP and credentials and see what happens. 

I messed around with it for an entire day before I got this config to work and just stuck with it.

**Comment by Davaogedy** [comment]
> I might note I am running this container of homebridge that has ffmpeg. [https://registry.hub.docker.com/r/nicholasrobinson/ffmpeg-homebridge](url)

Your suggested container does not create any files.
There is no config.json in my folder.. do i have to create them manually?

**Comment by arjohnson15** [comment]
> > I might note I am running this container of homebridge that has ffmpeg. [https://registry.hub.docker.com/r/nicholasrobinson/ffmpeg-homebridge](url)
> 
> Your suggested container does not create any files.
> There is no config.json in my folder.. do i have to create them manually?

I just set the mount path the same as my original homebridge docker container so I didnt have to change anything. 
I just setup a new test container with it and It setup just like a normal homebridge docker container. I logged into its UI on the port i set it to and all the files were in the /homebridge path I set.

**Comment by resgroupmsr** [comment]
Just wanted to pass along that while I stopped trying to get this working via Docker / Synology, I did use your suggested config.json entries on my RaspberryPI install however and they work perfectly!  The only item I didn't add was the snapshot line item but will try that later as well.

Thank you for sharing, saved me more hours of fighting with this.
