### ISSUE TITLE
Cameras can't be removed from home screen ("Include in favourites" not working)

### ISSUE THREAD

**Issue by ceraz68** [KhaosT/homebridge-camera-ffmpeg#404]
Likely due to the latest iOS 13.3 but the toggle button "Include in Favourites" always stays on.

Deactivating the toggle button does not remove the camera from the home window. All ffmpeg cameras remain listed under "Favourite Cameras".

**Comment by ceraz68** [comment]
I was able to remove them from the home screen on the mac just after triggering a homebridge restart (from the homebridge-config-ui-x 4.6.7). But only at the very beginning of the restart process.

I'm running homebridge in a synology docker.

**Comment by iRayanKhan** [comment]
This isn't controlled by HomeBridge it's self, it's only in the Home app its self. This happens for me a lot, except the opposite, where if I switch favorites on it stays off, but eventually corrects its self.

**Comment by 350d** [comment]
I was able to remove ffmpeg camera using desktop Home App

**Comment by ceraz68** [comment]
Thanks for your feedback, I eventually managed to remove all cameras from the favourites list using the home app on the mac desktop. I must have been lucky up to now as I never experienced this issue before.
