### ISSUE TITLE
using ffmpeg to stream from windows webcam

### ISSUE THREAD

**Issue by teymur1988** [KhaosT/homebridge-camera-ffmpeg#405]
Hi there videoexperts,
Could you please advise,
I'm running Homebridge on windows 10
Just trying to add the local windows webcam camera config as following:

        {
            "platform": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "webcam",
                    "videoConfig": {
                        "source": "-f dshow -i video=HP Truevision HD",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "audio": false,
                        "vcodec": "mjpeg",
                        "packetSize": 1316,
                        "debug": true
                    }
                }
            ]
        }

This is a valid config as far as json is concerned. When trying to stream it says ffmpeg exited with code 1.
 However the actual ffmpeg command line should include "" and be like this:
ffmpeg -f dshow  -vcodec mjpeg -i video="HP Truevision HD" output.mp4

which works in cmd, but json doesn't like it. How can I workaround the issue with the "" in json?

**Comment by alexndrs** [comment]
@teymur1988 Thought about implementing Yawcam? It gives you a mjpg feed that works in this plugin. Then you also get the opportunity to setup motion detection.

**Comment by teymur1988** [comment]
> @teymur1988 Thought about implementing Yawcam? It gives you a mjpg feed that works in this plugin. Then you also get the opportunity to setup motion detection.

Hi there, It's been a long time since I looked here, and yes I ended up using Yawcam at the end. It  Did the job. Thanks!

**Comment by alexndrs** [comment]
@teymur1988 Have you been experiencing any problem connecting to the camera on lan. I’m only able to watch the camera feed on cellular. I guess we have the same setup, Windows 10 with Yawcam.
