### ISSUE TITLE
Raspberry PI 4 - Cannot get a second camera to stream consistently

### ISSUE THREAD

**Issue by resgroupmsr** [KhaosT/homebridge-camera-ffmpeg#408]
Have installed Homebridge and homebridge-camera-ffmpeg successfully on a new Raspberry PI 4 with 4 gb of RAM and 64 GB SD card.  Everything seems to work ok however when I try and add a second identical camera to my set up only the first camera connects consistently.

On the positive side the one camera now appears on my Home on all family iDevices, have several more to add but not putting them on until can figure out why this second camera keeps disconnecting.   Will post my config later today.

**Comment by WAFFLE93** [comment]
Sorry to latch onto your thread. Can you point me into the right direction for installing ffmpeg onto pi?

I'm struggling to get my camera's viewable. I'm able to get them into the Home app but just get the "This Camera is not responding"

I'm using the same Pi config as yourself, as initially my Pi 2 seemed to struggle.

**Comment by resgroupmsr** [comment]
This is what I've got 'working' on my set up. Please note that the second camera, while identical to the first, often appears as offline in Home app - on the native Reolink app both cameras are always connected.  I'm living with this now as can always jump on to Reolink app if really want a live view.


OS | Raspbian GNU/Linux Buster (10)
-- | --
Hostname | raspberrypi
IPv4 (eth0) | 192.168.#.#
IPv6 (eth0) | ###
Node.js Version | v12.14.0
Npm Version | v6.13.4
User | homebridge
Storage Path | /var/lib/homebridge
Config Path | /var/lib/homebridge/config.json

[config Homebridge - 12Jan2020 - edited no personal.txt](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/4050740/config.Homebridge.-.12Jan2020.-.edited.no.personal.txt)
