### ISSUE TITLE
how can i add a rtmp camera device

### ISSUE THREAD

**Issue by mengma021** [KhaosT/homebridge-camera-ffmpeg#414]
hey gus, i have a rtmp protocol camera, and i can receive video by comand:
" ffmpeg -i rtmp://192.168.50.251/live/test -c:v h264_omx -preset fast 123.flv"
it works fine, BUT when i setup the homebridge config.json by 
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "BasementCam",
                    "videoConfig": {
                        "source": "-i rtmp://192.168.50.251:1935/live/test -c:v mkv -s 1920x1080",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "debug": true
                    }
                }
            ]
        }
    ]

and starting the homebridge, when i touch the camera, got an erro like :
"Codec AVOption b (set bitrate (in bits/s)) specified for output file #0 (srtp://192.168.50.24:65000?rtcpport=65000&localrtcpport=65000&pkt_size=1316) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream."

the Specific log in attach files, i am appreciate if some guys can help, caus this Took me a lot of time, so tired.
[homebridge.log](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/4075828/homebridge.log)

**Comment by MadMacMad** [comment]
have you tried to compile your own FFmpeg binary?
than it should work...
plz report back...

**Comment by MadMacMad** [comment]
got it working with my Reolink camera...
"source": "-i rtmp://192.168.178.93/bcs/channel0_ext.bcs?channel=0&stream=2&user=admin&password=xxx -map 0 -dn -an -flags -global_header",

you have to compile FFmpeg and add -map 0 -dn -an -flags -global_header to the end of the url
