### ISSUE TITLE
Cannot add Reolink camera E1 using homebridge on my Mac 

### ISSUE THREAD

**Issue by leesoyavh** [KhaosT/homebridge-camera-ffmpeg#417]
Hello

Im new to this and im trying to learn as I go. I have added my smartlife devices using the TUYA plug in and this works great, and next im trying to ad my Reolink camera.

Ive looked at a few articles on GitHub and got to this point editing the Json as shown, but I keep getting error on my terminal app

Please if you wouldn't mind look at my Jason file, it refuses to work... would someone mind having a look and see what im doing wrong?

<img width="1280" alt="Screenshot 2020-01-22 at 20 06 08" src="https://user-images.githubusercontent.com/59931575/72933580-e9ac7a80-3d59-11ea-85b9-c6ee0da669d3.png">

<img width="682" alt="Screenshot 2020-01-22 at 20 21 43" src="https://user-images.githubusercontent.com/59931575/72933736-3bed9b80-3d5a-11ea-9e3d-2da885ff17b9.png">

**Comment by joberembt** [comment]
I would suggest running your json file through the jsonlint website as the error message says? You likely have a syntax error, likely a missing comma or endquote.

**Comment by leesoyavh** [comment]
Hi there, thank you for replying !

I ran it through the Json validator and got this.... (Ive added the lower part of my Json File"

						"maxStreams": 2,
						"maxWidth": 1280,
						"maxHeight": 720,
						"maxFPS": 30
					}
				}]
			}



Error: Parse error on line 32:
...0					}				}]			}
--------------------^
Expecting ',', ']', got 'EOF'

<img width="1097" alt="Screenshot 2020-01-23 at 16 20 41" src="https://user-images.githubusercontent.com/59931575/73002693-54ae8d80-3dfc-11ea-84ce-3bf645bf5835.png">

**Comment by joberembt** [comment]
Hard to tell since you posted screenshots of the file, instead of the config file text, so I can't easily run it through JSONlint without retyping everything, but I believe you are missing a ] that should go on line 36 of the Atom editor screen posted above.

**Comment by leesoyavh** [comment]
Hi jobermbt

got it sorted !!!

**Comment by leesoyavh** [comment]
thanks for helping
