### ISSUE TITLE
[Camera ffmpeg] ERROR: FFmpeg exited with code 1

### ISSUE THREAD

**Issue by leesoyavh** [KhaosT/homebridge-camera-ffmpeg#419]
HI

I installed homebrew and then i installed ffmpeg, is this wrong ?

I am trying to get my Reolink E1 to work with HomeKit but i am struggling. Its states on Reolink website that the E1 does not allow still image and also will not work with VLC player. I am using HomeKit but i am wondering if i'm wasting my time with this E1 camera as i have read what i read on Reolink website, or is this not relevant

https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player

**Comment by leesoyavh** [comment]
Also i seem to have 2 accessories showing as 'cameras' I only have 1 camera here at the house 

<img width="1035" alt="Screenshot 2020-01-25 at 07 37 06" src="https://user-images.githubusercontent.com/59931575/73117982-a31b7380-3f45-11ea-8b34-10e46a0d11f4.png">

**Comment by grzegorz914** [comment]
If U set in config”max stream” to 2 then U have 2 stream Tile

**Comment by leesoyavh** [comment]
Ah ok thank you. I wondered if that may have been part of the problem but obviously not

Thank you.

Can you shed any light on my first question?

**Comment by leesoyavh** [comment]
@KhaosT could you help to look at a log please?

If so what would you need ?

**Comment by leesoyavh** [comment]
Ive extracted this:

(also im on this zsh thing which shows in terminal)

[1/25/2020, 10:18:33 AM] [Camera ffmpeg] Start streaming video from Cam1 with 1280x720@299kBit
ffmpeg -re -i rtsp://admin:CAMERA_PASSWORD@192.168.1.18:554//h264Preview_01_main -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 7410274 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params tWjyhLNTUcVtLsI1ouuGwVraBRN3Me8Xnz0ZM4uZ srtp://192.168.1.5:56414?rtcpport=56414&localrtcpport=56414&pkt_size=1316 -map 0:1 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -ac 1 -payload_type 110 -ssrc 12717114 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params HSpCzIY2IxBLuGsG4H1Dv95peQJECARruc19XtGm srtp://192.168.1.5:63899?rtcpport=63899&localrtcpport=63899&pkt_size=1316 -loglevel debug
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.16)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk/Contents/Home/include/darwin -fno-stack-check' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack

  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Splitting the commandline.
Reading option '-re' ... matched as option 're' (read input at native frame rate) with argument '1'.
Reading option '-i' ... matched as input url with argument 'rtsp://admin:CAMERA_PASSWORD@192.168.1.18:554//h264Preview_01_main'.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:0'.
Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'libx264'.
Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'yuv420p'.
Reading option '-r' ... matched as option 'r' (set frame rate (Hz value, fraction or abbreviation)) with argument '10'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.
Reading option '-tune' ...
 matched as AVOption 'tune' with argument 'zerolatency'.
Reading option '-b:v' ... matched as option 'b' (video bitrate (please use -b:v)) with argument '299k'.
Reading option '-bufsize' ...
 matched as AVOption 'bufsize' with argument '299k'.
Reading option '-maxrate' ...
 matched as AVOption 'maxrate' with argument '299k'.
Reading option '-payload_type' ...
 matched as AVOption 'payload_type' with argument '99'.
Reading option '-ssrc' ...
 matched as AVOption 'ssrc' with argument '7410274'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rtp'.
Reading option '-srtp_out_suite' ...
 matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
Reading option '-srtp_out_params' ...
 matched as AVOption 'srtp_out_params' with argument 'tWjyhLNTUcVtLsI1ouuGwVraBRN3Me8Xnz0ZM4uZ'.
Reading option 'srtp://192.168.1.5:56414?rtcpport=56414&localrtcpport=56414&pkt_size=1316' ... matched as output url.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:1'.
Reading option '-acodec' ... matched as option 'acodec' (force audio codec ('copy' to copy stream)) with argument 'libfdk_aac'.
Reading option '-profile:a' ... matched as option 'profile' (set profile) with argument 'aac_eld'.
Reading option '-flags' ...
 matched as AVOption 'flags' with argument '+global_header'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'null'.
Reading option '-ar' ... matched as option 'ar' (set audio sampling rate (in Hz)) with argument '16k'.
Reading option '-b:a' ... matched as option 'b' (video bitrate (please use -b:v)) with argument '24k'.
Reading option '-bufsize' ...
 matched as AVOption 'bufsize' with argument '24k'.
Reading option '-ac' ... matched as option 'ac' (set number of audio channels) with argument '1'.
Reading option '-payload_type' ...
 matched as AVOption 'payload_type' with argument '110'.
Reading option '-ssrc' ...
 matched as AVOption 'ssrc' with argument '12717114'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rtp'.
Reading option '-srtp_out_suite' ...
 matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
Reading option '-srtp_out_params' ...
 matched as AVOption 'srtp_out_params' with argument 'HSpCzIY2IxBLuGsG4H1Dv95peQJECARruc19XtGm'.
Reading option 'srtp://192.168.1.5:63899?rtcpport=63899&localrtcpport=63899&pkt_size=1316' ... matched as output url.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option loglevel (set logging level) with argument debug.
Successfully parsed a group of options.

Parsing a group of options: input url rtsp://admin:CAMERA_PASSWORD@192.168.1.18:554//h264Preview_01_main.
Applying option re (read input at native frame rate) with argument 1.
Successfully parsed a group of options.
Opening an input file: rtsp://admin:CAMERA_PASSWORD@192.168.1.18:554//h264Preview_01_main.

[tcp @ 0x7fc2a041b340] No default whitelist set

[tcp @ 0x7fc2a041b340] Original list of addresses:

[tcp @ 0x7fc2a041b340] Address 192.168.1.18 port 554
[tcp @ 0x7fc2a041b340] Interleaved list of addresses:
[tcp @ 0x7fc2a041b340] Address 192.168.1.18 port 554
[tcp @ 0x7fc2a041b340] Starting connection attempt to 192.168.1.18 port 554

[tcp @ 0x7fc2a041b340] 
Connection attempt to 192.168.1.18 port 554 failed: Connection refused
[tcp @ 0x7fc2a041b340] Connection to tcp://192.168.1.18:554?timeout=0 failed: Connection refused
rtsp://admin:CAMERA_PASSWORD@192.168.1.18:554//h264Preview_01_main: Connection refused

[1/25/2020, 10:18:33 AM] [Camera ffmpeg] ERROR: FFmpeg exited with code 1

**Comment by grzegorz914** [comment]
It is wrong definition:
`rtsp://admin:CAMERA_PASSWORD@192.168.1.18:554//h264Preview_01_main`
right one:
`rtsp://admin:CAMERA_PASSWORD@192.168.1.18:554/h264Preview_01_main`

**Comment by leesoyavh** [comment]
Hi

Changed it to 1 forward slash after 554 and still not working...?

**Comment by leesoyavh** [comment]
should i have any ports open on my router ?

**Comment by llamafilm** [comment]
Can you share the logs again after fixing that typo?

**Comment by leesoyavh** [comment]
Hi there, thank you for replying, here is the log:

[1/27/2020, 7:47:35 AM] [Config] Homebridge restart request received
[1/27/2020, 7:47:36 AM] [Config] No restart command defined, killing process...
[1/27/2020, 7:47:36 AM] [HB Supervisor] Stopping services...
[1/27/2020, 7:47:36 AM] Got SIGTERM, shutting down Homebridge...
[1/27/2020, 7:47:41 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/27/2020, 7:47:42 AM] [HB Supervisor] Homebridge Storage Path: /Users/**myuseraccountname**/.homebridge
[1/27/2020, 7:47:42 AM] [HB Supervisor] Homebridge Config Path: /Users/**myuseraccountname**/.homebridge/config.json
[1/27/2020, 7:47:42 AM] [HB Supervisor] Logging to /Users/**myuseraccountname**/.homebridge/homebridge.log
[1/27/2020, 7:47:42 AM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[1/27/2020, 7:47:42 AM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[1/27/2020, 7:47:42 AM] [HB Supervisor] Started Homebridge with PID: 3799
[1/27/2020, 7:47:42 AM] Loaded config.json with 0 accessories and 3 platforms.
[1/27/2020, 7:47:42 AM] ---
[1/27/2020, 7:47:44 AM] [Config] Homebridge Config UI X v4.8.1 is listening on :: port 8581
[1/27/2020, 7:47:44 AM] Loaded plugin: homebridge-camera-ffmpeg
[1/27/2020, 7:47:44 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/27/2020, 7:47:44 AM] ---
[1/27/2020, 7:47:44 AM] Loaded plugin: homebridge-config-ui-x
[1/27/2020, 7:47:44 AM] Registering platform 'homebridge-config-ui-x.config'
[1/27/2020, 7:47:44 AM] ---
[1/27/2020, 7:47:44 AM] Loaded plugin: homebridge-tuya-web
[1/27/2020, 7:47:44 AM] Registering platform 'homebridge-tuya-web.TuyaWebPlatform'
[1/27/2020, 7:47:44 AM] ---
[1/27/2020, 7:47:44 AM] Loading 3 platforms...
[1/27/2020, 7:47:44 AM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[1/27/2020, 7:47:44 AM] [Config] Initializing config platform...
[1/27/2020, 7:47:44 AM] [Config] Running in Standalone Mode.
[1/27/2020, 7:47:44 AM] [Camera ffmpeg] Initializing Camera-ffmpeg platform...
[1/27/2020, 7:47:44 AM] Loading 0 accessories...
[1/27/2020, 7:47:44 AM] [TuyaWebPlatform] Configuring cached accessory [Jens Desk] bf4cd96cb140b86263o6s6 e1af25f1-6755-4541-95f8-d5fc871463da
[1/27/2020, 7:47:44 AM] [TuyaWebPlatform] Configuring cached accessory [Lamp] bf6235a725da3bd972knma 0e174c25-1f0a-446f-88ce-6837e5c5d121
[1/27/2020, 7:47:44 AM] [TuyaWebPlatform] Configuring cached accessory [Lights] 107200463c71bf3da227 c0c518dc-3780-4db3-95de-238e7952141d
Setup Payload:
X-HM://0023ISYWYDP9O
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[1/27/2020, 7:47:44 AM] [TuyaWebPlatform] Initializing TuyaWebPlatform...
[1/27/2020, 7:47:44 AM] Homebridge is running on port 51826.
[1/27/2020, 7:47:44 AM] TestCam is running on port 51779.
[1/27/2020, 7:47:44 AM] Please add [TestCam] manually in Home app. Setup Code: 031-45-154
[1/27/2020, 7:47:45 AM] [TuyaWebPlatform] Adding: Jens Desk (switch / bf4cd96cb140b86263o6s6)
[1/27/2020, 7:47:45 AM] [TuyaWebPlatform] Existing Accessory found [Jens Desk] [bf4cd96cb140b86263o6s6] [e1af25f1-6755-4541-95f8-d5fc871463da]
[1/27/2020, 7:47:45 AM] [TuyaWebPlatform] Adding: Lamp (switch / bf6235a725da3bd972knma)
[1/27/2020, 7:47:45 AM] [TuyaWebPlatform] Existing Accessory found [Lamp] [bf6235a725da3bd972knma] [0e174c25-1f0a-446f-88ce-6837e5c5d121]
[1/27/2020, 7:47:45 AM] [TuyaWebPlatform] Adding: Lights (switch / 107200463c71bf3da227)
[1/27/2020, 7:47:45 AM] [TuyaWebPlatform] Existing Accessory found [Lights] [107200463c71bf3da227] [c0c518dc-3780-4db3-95de-238e7952141d]
[1/27/2020, 7:48:22 AM] [Camera ffmpeg] Snapshot from TestCam at 480x270
ffmpeg -i http://192.168.1.18/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=CameraPassword -t 1 -s 480x270 -f image2 -
[1/27/2020, 7:48:32 AM] [Camera ffmpeg] Snapshot from TestCam at 480x270
ffmpeg -i http://192.168.1.18/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=CameraPassword -t 1 -s 480x270 -f image2 -
[1/27/2020, 7:48:35 AM] [Camera ffmpeg] Start streaming video from TestCam with 1280x720@299kBit
ffmpeg -re -i rtsp://admin:CameraPassword@192.168.1.18:554/h264Preview_01_main -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 13561725 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params BSzvzUFL753f4iISP5UHnEz6dJQeodQyIjPG5KvW srtp://192.168.1.7:53202?rtcpport=53202&localrtcpport=53202&pkt_size=1316 -map 0:1 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -ac 1 -payload_type 110 -ssrc 7974347 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params MLLmQ9HJq5+fXA0N1NNDRifDvQ3wjIKBbDN9Regy srtp://192.168.1.7:65202?rtcpport=65202&localrtcpport=65202&pkt_size=1316 -loglevel debug
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.16)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk/Contents/Home/include/darwin -fno-stack-check' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack

  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Splitting the commandline.
Reading option '-re' ... matched as option 're' (read input at native frame rate) with argument '1'.
Reading option '-i' ... matched as input url with argument 'rtsp://admin:OurHome173@192.168.1.18:554/h264Preview_01_main'.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:0'.
Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'libx264'.
Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'yuv420p'.
Reading option '-r' ... matched as option 'r' (set frame rate (Hz value, fraction or abbreviation)) with argument '10'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.
Reading option '-tune' ...
 matched as AVOption 'tune' with argument 'zerolatency'.
Reading option '-b:v' ... matched as option 'b' (video bitrate (please use -b:v)) with argument '299k'.
Reading option '-bufsize' ...
 matched as AVOption 'bufsize' with argument '299k'.
Reading option '-maxrate' ...
 matched as AVOption 'maxrate' with argument '299k'.
Reading option '-payload_type' ...
 matched as AVOption 'payload_type' with argument '99'.
Reading option '-ssrc' ...
 matched as AVOption 'ssrc' with argument '13561725'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rtp'.
Reading option '-srtp_out_suite' ...
 matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
Reading option '-srtp_out_params' ...
 matched as AVOption 'srtp_out_params' with argument 'BSzvzUFL753f4iISP5UHnEz6dJQeodQyIjPG5KvW'.
Reading option 'srtp://192.168.1.7:53202?rtcpport=53202&localrtcpport=53202&pkt_size=1316' ... matched as output url.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:1'.
Reading option '-acodec' ... matched as option 'acodec' (force audio codec ('copy' to copy stream)) with argument 'libfdk_aac'.
Reading option '-profile:a' ... matched as option 'profile' (set profile) with argument 'aac_eld'.
Reading option '-flags' ...
 matched as AVOption 'flags' with argument '+global_header'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'null'.
Reading option '-ar' ... matched as option 'ar' (set audio sampling rate (in Hz)) with argument '16k'.
Reading option '-b:a' ... matched as option 'b' (video bitrate (please use -b:v)) with argument '24k'.
Reading option '-bufsize' ...
 matched as AVOption 'bufsize' with argument '24k'.
Reading option '-ac' ... matched as option 'ac' (set number of audio channels) with argument '1'.
Reading option '-payload_type' ...
 matched as AVOption 'payload_type' with argument '110'.
Reading option '-ssrc' ...
 matched as AVOption 'ssrc' with argument '7974347'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rtp'.
Reading option '-srtp_out_suite' ...
 matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
Reading option '-srtp_out_params' ...
 matched as AVOption 'srtp_out_params' with argument 'MLLmQ9HJq5+fXA0N1NNDRifDvQ3wjIKBbDN9Regy'.
Reading option 'srtp://192.168.1.7:65202?rtcpport=65202&localrtcpport=65202&pkt_size=1316' ... matched as output url.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option loglevel (set logging level) with argument debug.
Successfully parsed a group of options.
Parsing a group of options: input url rtsp://admin:OurHome173@192.168.1.18:554/h264Preview_01_main.
Applying option re (read input at native frame rate) with argument 1.
Successfully parsed a group of options.
Opening an input file: rtsp://admin:CameraPassword@192.168.1.18:554/h264Preview_01_main.

[tcp @ 0x7f9596617c80] No default whitelist set

[tcp @ 0x7f9596617c80] Original list of addresses:

[tcp @ 0x7f9596617c80] Address 192.168.1.18 port 554
[tcp @ 0x7f9596617c80] Interleaved list of addresses:
[tcp @ 0x7f9596617c80] Address 192.168.1.18 port 554
[tcp @ 0x7f9596617c80] Starting connection attempt to 192.168.1.18 port 554

[tcp @ 0x7f9596617c80] Connection attempt to 192.168.1.18 port 554 failed: Connection refused

[tcp @ 0x7f9596617c80] Connection to tcp://192.168.1.18:554?timeout=0 failed: Connection refused
rtsp://admin:CameraPassword3@192.168.1.18:554/h264Preview_01_main: Connection refused

[1/27/2020, 7:48:36 AM] [Camera ffmpeg] ERROR: FFmpeg exited with code 1

**Comment by llamafilm** [comment]
I think you need quotes around the RTSP URL, so in the JSON you would have to escape them with backslashes like this:
`"source": "-re -i \"rtsp://admin:CameraPassword@192.168.1.18:554/h264Preview_01_main\"`

To test the connection to the camera, use ffplay with similar parameters like this:
`ffplay -i "rtsp://admin:CameraPassword@192.168.1.18:554/h264Preview_01_main"`

**Comment by leesoyavh** [comment]
Hi There

Should I put a Cooma after the “ see below: ?

"-re -i \"rtsp://admin:CameraPassword@192.168.1.18:554/h264Preview_01_main\ <rtsp://admin:CameraPassword@192.168.1.18:554/h264Preview_01_main\>”,

**Comment by llamafilm** [comment]
Yes, a comma is required at the end of the line because it separates items.  I suggest doing a little research to get familiar with JSON syntax, and after making any changes you can validate it at https://jsonlint.com to check for errors

**Comment by leesoyavh** [comment]
Hi there

It didnt like either…. Comma or no comma, it refused it, said bad syntax

I think it may be a port issue...

**Comment by leesoyavh** [comment]
im not sure the Reolink e1 camera is gonna be compatible after reading their support pages

**Comment by llamafilm** [comment]
Did you validate with jsonlint?
Try using single quotes instead 
`"source": "-re -i 'rtsp://admin:CameraPassword@192.168.1.18:554/h264Preview_01_main'"`

**Comment by leesoyavh** [comment]
Hi, I tried the single quotes, still no good, I think it is the camera, im gonna send it back and try the next version up which seems to allow, for example; VLC player, port modifications, web browser access so it may be more 'open' to HomeKit access

thanks anyway
