### ISSUE TITLE
Using the wiki to document working configs

### ISSUE THREAD

**Issue by NorthernMan54** [KhaosT/homebridge-camera-ffmpeg#42]
Does it make sense to use the wiki to document known working configs?   There is so much variability in cameras, would it make it easier for everyone if there was a place with working configs?

**Comment by KhaosT** [comment]
Good idea :) Try [this page](https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Tested-Configurations). I think everyone can edit it.

**Comment by NorthernMan54** [comment]
I cloned the wiki, made some local edits, then using github desktop published back and received this.

You may not have permission to access homebridge-camera-ffmpeg.wiki. Check Preferences to make sure you’re still logged in.

I'm logged in.   I'm also not an expert on this so I may have done something wrong.

**Comment by KhaosT** [comment]
If you go to the link I sent above, do you see the edit button in the page?

**Comment by NorthernMan54** [comment]
End user error. Tks
