### ISSUE TITLE
Unknown encoder 'libfdk_aac'

### ISSUE THREAD

**Issue by leesoyavh** [KhaosT/homebridge-camera-ffmpeg#423]
how do i get round this error message please ?

Unknown encoder 'libfdk_aac'

**Comment by Que20** [comment]
have you tried this : https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/302 ?

**Comment by MadMacMad** [comment]
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/428#issuecomment-593063695

you need to compile your own FFmpeg ... how too in link above...
audio is working then also...

**Comment by jonasophie** [comment]
you can install 'libfdk_aac' following instructions here:
https://github.com/homebridge/ffmpeg-for-homebridge

works for me on raspberry.
