### ISSUE TITLE
RESTful trigger

### ISSUE THREAD

**Issue by uspino2** [KhaosT/homebridge-camera-ffmpeg#424]
I'm trying to use the RESTful motion interface as explained here:

https://github.com/desvdp/homebridge-camera-ffmpeg-rest-motion
[](https://github.com/desvdp/homebridge-camera-ffmpeg-rest-motion)

It's not working with the proposed Home Assistant configuration, and I find no way to trigger the sensor from direct url hit. Has anybody here managed to get it working?

**Comment by NorthernMan54** [comment]
This is not that plugin which might the issue
