### ISSUE TITLE
Audio copy / pass thru to home app from client

### ISSUE THREAD

**Issue by AtomicLight** [KhaosT/homebridge-camera-ffmpeg#428]
Is there a way to directly pass the audio stream through to the home app from the camera client? 

I am using "vcodec": "copy" for the video, and it works great. I'd love to pass the audio through as well, but "acodec": "copy" does not appear to be valid.

**Comment by MadMacMad** [comment]
hi,
you have to make your own FFmpeg with libfdk-aac-dev...

first you need to add following to your source list:
cd /home

Now we’re going to edit a file which contains the sources of debian repositories. We’ll do this with nano – a text editor.

sudo nano /etc/apt/sources.list

Then use the cursor keys to get to line 2 and add…

deb http://www.deb-multimedia.org/ wheezy main non-free
deb http://www.deb-multimedia.org/ jessie main

Then
CTRL-X to exit
y to confirm you want to save
enter to confirm the filename (don’t change it)

sudo apt-get update

It will update some package lists and give two errors. W: GPG error and W: Duplicate sources… We’ll deal with those next…

sudo apt-get install deb-multimedia-keyring
y confirm install without verification

sudo apt-get update

cd /home

Now we need to install all the development libraries required to build FFMPEG. From sudo to libvorbis-dev is is all one line.
sudo apt-get install libfdk-aac-dev libmp3lame-dev libx264-dev libxvidcore-dev libgsm1-dev libtheora-dev libvorbis-dev

Now let’s get the FFMPEG files themselves.

sudo git clone git://source.ffmpeg.org/ffmpeg.git

This is quite a large download and will take a little while (10-20 mins). Once complete…

cd ffmpeg

Note that the following command from ./configure to --enable-nonfree is all one continuous command.

sudo ./configure --enable-libmp3lame --enable-libtheora --enable-libx264 --enable-libgsm --enable-postproc --enable-libxvid --enable-libfdk-aac --enable-pthreads --enable-libvorbis --enable-gpl --enable-nonfree

After a minute or so, you will get a warning about pkg-config not found. Ignore it. It’ll still work. Now to compile. :)

WARNING! Once you press <enter> for the sudo make command it will tie up your Pi4 for about 1.5 hours until the compile is finished. (If you are accessing your Pi via ssh, you might want to run it via screen, so you can detach and reattach without killing the process.)

sudo make

This will show you what it is doing as it goes. There will be lots of scary messages you don’t understand. Best go and do something else. And best run the “sudo make” directly on the Pi if you can. If you do it by ssh you’ll have to leave your other computer on and connected until it finishes.

Once compiled, the install is a fair bit faster.
sudo make install
sudo ldconfig
sudo chown -R pi /home/ffmpeg

now in homebridge conf.
add  "videoProcessor": "/home/ffmpeg/ffmpeg",
to the setup like shown below...
audio works now with all cameras that support it...
testet with Logitech USB Cam and Reolink 

i did it all and ended with compiling my own ... that works perfect now

{
            "name": "Camera ffmpeg",
            "videoProcessor": "/home/ffmpeg/ffmpeg",
            "cameras": [
                {
                    "name": "Reolink",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:xxx@192.168.178.93:554/h264Preview_01_sub",
                        "stillImageSource": "-i http://192.168.178.93/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=xxx",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "vcodec": "copy",
                        "audio": true,
                        "debug": false
                    }
                },

hope this help's and others too... :-)

**Comment by AtomicLight** [comment]
Thanks for the reply. Unfortnuly, on HOOBS I am getting a lot of errors and can't proceed

******************
`hoobs@hoobs:~ $ cd /home
hoobs@hoobs:/home $ sudo nano /etc/apt/sources.list
hoobs@hoobs:/home $ sudo apt-get update
Get:1 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                   
Err:1 https://dl.yarnpkg.com/debian stable InRelease                           
  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease
Ign:4 http://www.deb-multimedia.org wheezy InRelease           
Err:5 http://www.deb-multimedia.org wheezy Release
  404  Not Found [IP: 2001:41d0:1:c3c4::1 80]
Get:6 http://www.deb-multimedia.org jessie InRelease [24.6 kB]
Err:6 http://www.deb-multimedia.org jessie InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5C808C2B65558117
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
E: The repository 'http://www.deb-multimedia.org wheezy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://www.deb-multimedia.org jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5C808C2B65558117
E: The repository 'http://www.deb-multimedia.org jessie InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
hoobs@hoobs:/home $ sudo apt-get install deb-multimedia-keyring
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package deb-multimedia-keyring`

**Comment by cyberralf83** [comment]
you need to run the `apt-get update --allow-insecure-repositories` instead of `sudo apt-get update`
