### ISSUE TITLE
Synology Surveillance Station Multicast Stream Path

### ISSUE THREAD

**Issue by Salvora** [KhaosT/homebridge-camera-ffmpeg#430]
First of all, this is a great addon.
I do have one problem though. I have a synology NAS DS1815+ and running the homebrigge on it via docker. I have installed this one added my cameras. For the stream path, I used the synology surveilance station stream paths which makes it easier to manage all of them. I have multicast enabled on my diskstation and tried to use the stream path of multicast but it always gives me error 1. If I change the stream path to unicast rtsp URL it works just fine. Any idea what could be the problem?P

**Comment by Salvora** [comment]
Well,
I did some more digging and found that using
-rtsp_transport udp_multicast -re -i rtsp://

works.

**Comment by domborovicova** [comment]
May I ask you where did you find these arguments ?

**Comment by Salvora** [comment]
ffmpeg docs
https://ffmpeg.org/ffmpeg-all.html

**Comment by domborovicova** [comment]
@Salvora Thank you
