### ISSUE TITLE
Connect to Reolink 410

### ISSUE THREAD

**Issue by jackkorber** [KhaosT/homebridge-camera-ffmpeg#431]
I am trying to use the following code and It Told me that I am missing parameters
[
    {
        "platform": "Camera-ffmpeg",
        "videoProcessor": "/usr/bin/ffmpeg",
        "cameras": [
            {
                "name": "ReoLink",
                "manufacturer": "Reolink",
                "model": "RLC-410W",
                "videoConfig": {
                    "source": "-re -i rtsp://USER:PASSWORD@XXX.XXX.XXX.XX:554/h264Preview_01_main",
                    "maxStreams": 5,
                    "maxWidth": 1280,
                    "maxHeight": 720,
                    "maxFPS": 15,
                    "maxBitrate": 300,
                    "vcodec": "libx264",
                    "packetSize": 1316,
                    "audio": false,
                    "debug": true
                }
            }
        ]
    }
]

**Comment by neutmute** [comment]
Works for me from a Rasperry Pi - RLC-410 5MP 

```
{
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Front Door",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:secretPassword@192.168.30.100:554//h264Preview_01_sub",
                        "stillImageSource": "-i http://192.168.30.100/cgi-bin/api.cgi?cmd=Snap&channel=0&user=admin&password=secretPassword&rs=randomStuff",
                        "maxStreams": 1,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 5,
                        "vcodec": "h264_omx",
                        "maxBitrate ": "150",
                        "debug": true
                    }
                }
            ]
        },
```

**Comment by MadMacMad** [comment]
this works without recode!

"videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:xxx@192.168.178.93:554/h264Preview_01_sub",
                        "stillImageSource": "-i http://192.168.178.93/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=xxx",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "vcodec": "copy",
                        "audio": false,
                        "debug": false
                    }
