### ISSUE TITLE
Motion sensor hypersensitive

### ISSUE THREAD

**Issue by IAmBrenna** [KhaosT/homebridge-camera-ffmpeg#432]
Hello there! I've installed this plugin from a day, and the motion sensor still activate always, even if I cover the camera.
I'm using a Raspberry pi zero w with an [IR camera](https://www.amazon.it/dp/B07SKF1K87/ref=cm_sw_em_r_mt_dp_U_IyfvEb7C2YR2R), (running Raspbian lite) does anyone knows how to set the sensitivity or which file I have to adjust?

**Comment by NorthernMan54** [comment]
There is no motion sensor logic in this plugin, please read this

https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/iOS-13-and-Photo-Notifications <https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/iOS-13-and-Photo-Notifications>

You need to provide your own logic or disable the function.

**Comment by IAmBrenna** [comment]
> You need to provide your own logic

How can I do that? Forgive me but I'm quite new to all that stuff

**Comment by NorthernMan54** [comment]
You need to supply a motion sensor.

**Comment by IAmBrenna** [comment]
Any way to emulate, even with an other plugin ? @NorthernMan54

**Comment by NorthernMan54** [comment]
I use real motion sensors, so I have no idea
