### ISSUE TITLE
vflip not working

### ISSUE THREAD

**Issue by thehauntedmattress** [KhaosT/homebridge-camera-ffmpeg#438]
I have the vertical flip attribute in my config set to true, but in homebridge the camera is not being flipped.  Is there a way to fix this?

        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "PiCamera",
                    "videoConfig": {
                        "source": "-f v4l2 -r 30 -s 1280x720 -i /dev/video0",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "audio": false,
                        "maxHeight": 720,
                        "vflip": true,
                        "hflip": true,
                        "maxFPS": 30,
                        "vcodec": "h264_omx",
                        "mapaudio": "0:1",
                        "debug": false
                    }
                }
            ]
        },

**Comment by milmber** [comment]
Same problem here. `vflip` and `hflip` parameters stopped working for me after upgrading to 0.1.17 from 0.1.14 for still images.
 
If I specify `-vf vflip,hflip` as a workaround in the video source, this works for video but not for still images.

**Comment by thehauntedmattress** [comment]
@milmber can you post your full config for ffmpeg camera?

**Comment by milmber** [comment]
@thehauntedmattress ,
See below. This has worked when I have manually added `-vf vflip,hflip` to the `source` and `stillImageSource`

`        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Pi 3B Camera",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -r 30 -video_size 1280x720 -f video4linux2 -i /dev/video0 -vf vflip,hflip",
                        "stillImageSource": "-video_size 1280x720 -f video4linux2 -i /dev/video0 -vf vflip,hflip -ss 1.5",
                        "maxStreams": 4,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "vflip": true,
                        "hflip": true,
                        "maxFPS": 30,
                        "vcodec": "h264_omx",
                        "audio": false,
                        "debug": true
                    }
                }
            ]
        }`

Log output is below for capturing a still image. As `stillImageSource` seems to be passed to ffmpeg correctly, I would suggest that the issue is with the `ffmpeg-for-homebridge` binaries as this is one of the main changes between 0.0.17 and 0.1.14? 

`[4/26/2020, 11:49:08] [Camera-ffmpeg] Snapshot from Pi 3B Camera at 480:270
ffmpeg -video_size 1280x720 -f video4linux2 -i /dev/video0 -vf vflip,hflip -ss 1.5 -t 1 -vf scale=480:270 -f image2 -`

**Comment by thehauntedmattress** [comment]
@milmber what kind of camera are you using?

**Comment by thehauntedmattress** [comment]
@milmber Actually nevermind.  Using 

`"source":` "-re -r 30 -video_size 1280x720 -f video4linux2 -i /dev/video0 -vf vflip,hflip",'

worked for me.  Thanks!

**Comment by milmber** [comment]
> @milmber what kind of camera are you using?

Raspberry Pi Camera v2

**Comment by milmber** [comment]
Managed to fix this issue by editing ffmpeg.js.

https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/9e96dacd65fc6fc38d32ad66d73b99f8934aa4c1/ffmpeg.js#L176

It seems that video filters must be defined together. By adding `vflip` and `hflip` to the ffmpeg command spawned for snapshots, the image is correctly rotated.

**Comment by thehauntedmattress** [comment]
@milmber does this fix vflip and hflip being able to flip the video in the homebridge config now without editing the source?

**Comment by milmber** [comment]
> @milmber does this fix vflip and hflip being able to flip the video in the homebridge config now without editing the source?

I have raised a pull request to fix this without source code edits required. See #466.

Unfortunately the `vflip` and `hflip` video filters must precede the `scale` video filter for some reason based on my testing.

**Comment by milmber** [comment]
For anyone still having this issue an noticing that the `vflip` and `hflip` filters do not work with the `copy` code - a better solution is to flip the camera at the v4l level as per this post (https://github.com/moritzmhmk/homebridge-camera-rpi/issues/4#issuecomment-336959417)

`v4l2-ctl --set-ctrl vertical_flip=1`
