### ISSUE TITLE
Connecting cameras for homeKit remote access

### ISSUE THREAD

**Issue by homekit-worker** [KhaosT/homebridge-camera-ffmpeg#44]
Maybe someone can give us some questions or ideas for this plugin: 
@see https://github.com/nfarina/homebridge/issues/1057

**Comment by MrsDelish** [comment]
Option for piping in raspicam would be nice, it works with just `-re -i /dev/video0` but we are stuck with default settings then.

**Comment by elvisimprsntr** [comment]
It's easy.  You need a tvOS or iOS 10 device on your LAN. For tvOS as your HomeKit hub, you first need to enable iCloud 2FA.  For iOS 10 you just have to enable HomeKit and turn on "use as HomeKit hub".  Presto!  You not only have remote HomeKit control, but the camera feeds will be automatically fed thru which ever device you pick as the HomeKit hub thru your iCloud account.  Obviously, the devices all need to be logged into the same iCloud account or I think you can invite other iCloud accounts to access your HomeKit devices.    For cameras, it help if you have both a RTSP and JPEG URL defined in Homebridge

https://support.apple.com/en-us/HT207057
