### ISSUE TITLE
Camera ffmpeg and Koogeek KSC2 Camera Setup

### ISSUE THREAD

**Issue by Chimpepe** [KhaosT/homebridge-camera-ffmpeg#442]
Hi Guys,

does anyone know how to setup the Koogeek KSC2 Camera with Camera ffmpeg?

I have tried this settings but unfortunately it's a really poor quality.

                    "name": "Terrasse",
                    "videoConfig": {
                        "source": "-re -i rtsp://10.0.0.102/H264",
                        "stillImageSource": "-i http://10.0.0.102:554/snapshot",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "maxBitrate": 600,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": false

**Comment by jonasophie** [comment]
Hi,

does the quality the same when you open the rasp link in VLC ?

**Comment by iRayanKhan** [comment]
Change codec to copy

**Comment by Chimpepe** [comment]
> Hi,
> 
> does the quality the same when you open the rtsp link in VLC ?

The quality in VLC is ok.
It’s a clear and fluent stream.

**Comment by Chimpepe** [comment]
> Change codec to copy

What you mean with „change codec to copy“?

**Comment by iRayanKhan** [comment]
In your config you have the vcodec set to libx264. Change that to ```copy```

**Comment by Chimpepe** [comment]
> In your config you have the vcodec set to libx264. Change that to `copy`

Gorgeous! Much better! Any other optimizations to get a more fluent stream?

**Comment by Chimpepe** [comment]
Even an idea how to get a clearer still image?
