### ISSUE TITLE
Motion config parameter in the wrong place through Homebridge Config UI X

### ISSUE THREAD

**Issue by fguchelaar** [KhaosT/homebridge-camera-ffmpeg#458]
When you're using Homebridge Config UI X, the `motion` parameter is not being set in the correct place. It gets placed under `videoConfig`, but should be a direct child of `cameras[]`.

Using the Config UI X this results in:
```json
"cameras": [
    {
        "name": "Garage",
        "videoConfig": {
            "source": "-re -i rtsp://****",
            "stillImageSource": "-i http://****",
            "motion": true
        }
    }
],
```

**Expected behavior:**
```json
"cameras": [
    {
        "name": "Garage",
        "motion": true,
        "videoConfig": {
            "source": "-re -i rtsp://****",
            "stillImageSource": "-i http://****"
        }
    }
],
```

Probably quite simple to resolve in `config.schema.json`.

**Comment by forresthamilton** [comment]
For still image source, do you use the same ip address as you did for rtsp source?

**Comment by fguchelaar** [comment]
@forresthamilton unrelated to this issue, but yes: I use the same ip-address, but it's a different URL though.
