### ISSUE TITLE
Video and Image don't load. Camera password protected

### ISSUE THREAD

**Issue by luciadp** [KhaosT/homebridge-camera-ffmpeg#46]
Is it possible to use the plugin for password protected cameras? If so, where should I provide username and password (I tried to pass them in the URL)? Everything seems to work fine but the video and the still image don't load
Thank you!

**Comment by KhaosT** [comment]
what do you mean by "password"? Like HTTP Basic Authentication? That should work by passing the username and password in URL.

**Comment by luciadp** [comment]
Yes I mean password. I am setting up a DLink 5222L and if I disable user
access control is all fine otherwise it doesn't load

**Comment by luciadp** [comment]
Sorry I mean Dlink DCS-5020L

**Comment by KhaosT** [comment]
... no I mean what kind of password are you talking about? Do you have a screenshot of the website promoting you to enter the password?

**Comment by luciadp** [comment]
sorted out. I used user:pass@ip
