### ISSUE TITLE
ffmpeg Seems slow to start stream

### ISSUE THREAD

**Issue by meluvalli** [KhaosT/homebridge-camera-ffmpeg#462]
Not sure if this is normal or not, but for whatever reason, ffmpeg seams really slow at starting my stream to HomeKit.  I can expect to wait 10+ seconds before my stream actually starts live feed.

Watching the logs, it get stuck after the h264 section.  It will hang there for about 5+ seconds before it continues and starts the stream...

Any thoughts or workarounds for this?

```
[mpegts @ 0000029692f30200] Probe with size=2395, packets=1 detected aac with score=51
[mpegts @ 0000029692f30200] probed stream 1

[h264 @ 000002969340f4c0] nal_unit_type: 9(AUD), nal_ref_idc: 0
[h264 @ 000002969340f4c0] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2

[h264 @ 000002969340f4c0] nal_unit_type: 9(AUD), nal_ref_idc: 0
[h264 @ 000002969340f4c0] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2

[h264 @ 000002969340f4c0] nal_unit_type: 9(AUD), nal_ref_idc: 0
[h264 @ 000002969340f4c0] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2

[h264 @ 000002969340f4c0] nal_unit_type: 9(AUD), nal_ref_idc: 0
[h264 @ 000002969340f4c0] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
```

Seems to stop here for 5+ seconds

Then once it gets past that, stream starts and I can see in HomeKit.

```
[mpegts @ 0000029692f30200] max_analyze_duration 5000000 reached at 5000000 microseconds st:0
[mpegts @ 0000029692f30200] Setting avg frame rate based on r frame rate

[mpegts @ 0000029692f30200] After avformat_find_stream_info() pos: 1231964 bytes read:1245184 seeks:0 frames:92

```

**Comment by meluvalli** [comment]
I ended up researching this more on my own.

Found a solution.  I have reduced the delay from 6-7 seconds down to 2 seconds.

I did this by adding the following to the beginning of my "source" options:
```-probesize 32 -analyzeduration 0```

Found the solution from stackoverflow.com 
source: https://stackoverflow.com/questions/16658873/how-to-minimize-the-delay-in-a-live-streaming-with-ffmpeg

- ```probesize 32``` sets the probing size in bytes (i.e. the size of the data to analyze to get stream information). A higher value will enable detecting more information in case it is dispersed into the stream, but will increase latency. Must be an integer not lesser than 32. It is 5000000 by default.

- ```analyzeduration 0``` specifies how many microseconds are analyzed to probe the input. A higher value will enable detecting more accurate information, but will increase latency. It defaults to 5000000 microseconds (5 seconds).

**Comment by resgroupmsr** [comment]
Could you post a sample of the ffmpeg section of your config that shows all the options you have set?

**Comment by meluvalli** [comment]
Sure!

```
                {
                    "name": "Porch",
                    "motion": true,
                    "videoConfig": {
                        "source": "-probesize 32 -analyzeduration 0 -re -i http://192.168.1.50/h264/porch/temp.ts -vf scale=480:270 -hide_banner",
                        "stillImageSource": "-i http://192.168.1.50/image/porch?q=75",
			"packetSize": 188,
			"audio": true,
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "debug": false
                    }
                },
```

This is with Blue Iris system.

**Comment by resgroupmsr** [comment]
So I tried, makes a big difference on cameras using the Rpi for encoding but shuts off streams set to 'copy'.  Here's what works for me (two cameras of 7 working as example).  
Note that I also found the  "vcodec": "libx264 **-preset ultrafast**" made a big difference.

Thanks again for the tip!

        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Camera Driveway",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://xxx:xxx@192.168.1.241:554/h264Preview_01_main",
                        "stillImageSource": "-i http://192.168.1.241/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=xxx",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxBitrate": 300,
                        "vcodec": "copy",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                }
            ]
        },
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Camera Living Room",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -probesize 32 -analyzeduration 0 -re -i rtsp://xxx:xxx@192.168.1.221/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46bG9sYTk2OTg=",
                        "stillImageSource": "-i http://xxx:xxx@192.168.1.221/cgi-bin/snapshot.cgi?1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "maxBitrate": 300,
                        "vcodec": "libx264 -preset ultrafast",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                }

**Comment by joshsepos** [comment]
N00b here. Any reason why when I apply the `-probesize 32 -analyzeduration 0 -re` to two cameras in Homebridge it breaks both? Works like a dream on one when applied only to one, taking the load time down by half, but breaks both when applied to both. Looking to apply to four cameras in the end. 

Thanks for any insight.

**Comment by Sunoo** [comment]
@joshsepos It basically tells FFmpeg that it should look at effectively none of the video stream to try to identify what formats it will be handling. Because of this, it will be unable to determine what codecs to use in many situations when you set the values that low.

**Comment by bartekpacia** [comment]
Whet I set `-probesize 32 -analyzeduration 0` on 1 of my 6 RTSP streams, it breaks that 1 stream. Why might it happen?

**Comment by Sunoo** [comment]
@bartekpacia https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/462#issuecomment-841002535

**Comment by bartekpacia** [comment]
Thanks for your fast response @Sunoo. But I have 6 cameras, and used `-probesize 32 -analyzeduration 0` in only one of them, yet it still broke.

**Comment by Sunoo** [comment]
@bartekpacia Yes? It would only impact the camera you add it to. Some cameras work with that setting, some don’t.

**Comment by bartekpacia** [comment]
Neither adding `-probesize 32 -analyzeduration 0` to my `source` nor setting `"vcodec": "libx264 -preset ultrafast"` work in my case :/ I measured it a few times, it averages around 15s (from clicking on camera tile in Home.app to actually receiving live video feed). What can I do to reduce that time?

**Comment by Sunoo** [comment]
Unfortunately in my experience, some cameras are just slow.

**Comment by meluvalli** [comment]
I only have one camera that comes up almost instantly, but it’s a low
resolution camera.

All my other ones take around 3-5 seconds.

All my cameras link through Blue Iris.  So, I pull my cameras from there
instead of directly on the camera URL.
