### ISSUE TITLE
One of your plugins incorrectly registered an external accessory using the platform name (Camera-ffmpeg) and not the plugin identifier. Please report this to the developer!

### ISSUE THREAD

**Issue by julien94800** [KhaosT/homebridge-camera-ffmpeg#465]
**Describe The Bug:**
When launching homebridge 1.0.0 with this plugin, I get this warning message:
"One of your plugins incorrectly registered an external accessory using the platform name (Camera-ffmpeg) and not the plugin identifier. Please report this to the developer!"

**To Reproduce:**
Launch homebridge 1.0.0 with this plugin and one camera defined

**Expected behavior:**
Fix what is described? Only a warning so everything still working but could be better to solve

**Logs:**
[4/27/2020, 11:51:54 AM] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[4/27/2020, 11:51:54 AM] One of your plugins incorrectly registered an external accessory using the platform name (Camera-ffmpeg) and not the plugin identifier. Please report this to the developer!
[4/27/2020, 11:51:54 AM] Camera Garage is running on port 52100.
[4/27/2020, 11:51:54 AM] Please add [Camera Garage] manually in Home app.

**Homebridge Config:**

        {
            "cameras": [
                {
                    "name": "Camera Garage",
                    "manufacturer": "D-Link",
                    "model": "DCS-932L",
                    "serialNumber": "123456",
                    "firmwareRevision": "1.14",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://XXX:XXX@XXX/mjpeg.cgi -i http://XXX:XXX@XXX/audio.cgi",
                        "stillImageSource": "-f mjpeg -i http://XXX:XXX@XXX/mjpeg.cgi",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 30,
                        "audio": false,
                        "motion": true,
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }

**Screenshots:**

**Environment:**

* **Node.js Version**: 12,16,2
* **NPM Version**: 6,14,4
* **Homebridge Version**: 1,0,0
* **Homebridge Camera FFmpeg Version**:0,1,17
* **Homebridge Config UI X Plugin Version**:4,16,0
* **Operating System**: Docker

**Comment by onefish2** [comment]
I am seeing the same thing. I also noticed this error message in the last beta before homebridge was updated to v1.0

**Comment by richie510** [comment]
I think this is more of a feature request, and I think it is referring to this specifically:

> Cameras can now be added to the bridge using a DynamicPlatformPlugin and the methods configureCameraSource or configureController of the PlatformAccessory (removing the need to create an external accessory)

**Comment by vcdx71** [comment]
I setup a new instance in a new home today and this plugin isn't fully working with HomeBridge 1.0.x. It loads fine, I can configure it and my camera shows in the logs but I can't add it to the Home app as I could in previous HomeBridge releases.

**Comment by teymur1988** [comment]
Hi there,

I have the same error coming up in my logs, however my cameras keep working.

Teymur

**Comment by hoefs** [comment]
Same here on homebridge 1.0.3:
`[4/29/2020, 9:03:24 AM] One of your plugins incorrectly registered an external accessory using the platform name (Camera-ffmpeg) and not the plugin identifier. Please report this to the developer!`

**Comment by donavanbecker** [comment]
> Same here on homebridge 1.0.3:
> `[4/29/2020, 9:03:24 AM] One of your plugins incorrectly registered an external accessory using the platform name (Camera-ffmpeg) and not the plugin identifier. Please report this to the developer!`

this is just an awareness for the developer.

**Comment by donavanbecker** [comment]
Just submitted a [PR](https://github.com/KhaosT/homebridge-camera-ffmpeg/pull/470) to fix this.

**Comment by julien94800** [comment]
Thanks very much!
