### ISSUE TITLE
Camera stream only works on cellular

### ISSUE THREAD

**Issue by alexndrs** [KhaosT/homebridge-camera-ffmpeg#472]
Camera feed only shows when on cellular not on local network. But logs stays the same on cellular and local. 

**Homebridge config:**

 "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "fesdcd5cth",
                    "videoConfig": {
                        "source": "-i http://192.168.1.7:8081/video.mjpg",
                        "stillImageSource": "-i http://192.168.1.7:8081/video.mjpg",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 420,
                        "maxFPS": 10,
                        "audio": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"

**Environment:**

* **Node.js Version**: 13.13
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.04
* **Homebridge Camera FFmpeg Version**: 2020-04-17
* **Homebridge Config UI X Plugin Version**: 4.17.1
* **Operating System**: Windows

**Comment by alexndrs** [comment]
I thought I had fixed it no. It seems like local connection works within 1 minute of using cellular.

**Comment by alexndrs** [comment]
Ended up changing operating system to MacOSX and it solved my problem. My setup used Yawcam and their for needed Windows but when I switched to Mac I virtualized Windows and run homebridge on Mac.

**Comment by gprsnlty** [comment]
hi im late to this issue but same for me the stream works well on cellular but not on local wlan.
my homebridge is set up on windows.

**Comment by alexndrs** [comment]
I think there is a problem with Windows 10 and homebridge. Changing to Mac OSX solved my problem. But right now I'm changing to Windows server 2019. I can let you know if it works.

**Comment by Sunoo** [comment]
Interesting, Windows should work. If you continue to have trouble with it there, I’d recommend opening an issue on the Homebridge GitHub page, hopefully they’ll be able to get things sorted.

**Comment by alexndrs** [comment]
Yep homebridge and ffmpeg plug-in works fine in Windows server 2019. Actually much quicker than Windows 10 used to be and OSX with same specs.
