### ISSUE TITLE
max delay reached

### ISSUE THREAD

**Issue by Cloudore** [KhaosT/homebridge-camera-ffmpeg#48]
Hey,

First of all thanks for the work on the plug-in

I am experiencing an issue with it though, the stream says its live but if there is any movement on the camera it freezes until it eventually disconnects.

tried running 

`ffmpeg -re -i rtsp://xx.x.x.xx:554/stream1 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 300k -bufsize 300k -f rtp rtp://127.0.0.1:5129`

and got this output:

`pi@raspberrypi:~ $ ffmpeg -re -i rtsp://xx.x.x.xx:554/stream1 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 300k -bufsize 300k -f rtp rtp://127.0.0.1:5129
ffmpeg version git-2017-02-04-b1e2192 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
  libavutil      55. 46.100 / 55. 46.100
  libavcodec     57. 75.100 / 57. 75.100
  libavformat    57. 66.101 / 57. 66.101
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 72.100 /  6. 72.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, rtsp, from 'rtsp://10.0.1.11:554/stream1':
  Metadata:
    title           : Ambarella streaming
    comment         : Ambarella streaming
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 848x480 [SAR 1:1 DAR 53:30], 14.99 fps, 14.99 tbr, 90k tbn, 29.97 tbc
    Stream #0:1: Audio: aac (LC), 48000 Hz, mono, fltp
[swscaler @ 0x33c3b20] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0x333bdc0] VBV maxrate unspecified, assuming CBR
[libx264 @ 0x333bdc0] using SAR=159/160
[libx264 @ 0x333bdc0] using cpu capabilities: ARMv6 NEON
[libx264 @ 0x333bdc0] profile High, level 3.1
Output #0, rtp, to 'rtp://127.0.0.1:5129':
  Metadata:
    title           : Ambarella streaming
    comment         : Ambarella streaming
    encoder         : Lavf57.66.101
    Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720 [SAR 159:160 DAR 53:30], q=-1--1, 300 kb/s, 30 fps, 90k tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.75.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/300000 buffer size: 300000 vbv_delay: -1
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=Ambarella streaming
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 57.66.101
m=video 5129 RTP/AVP 96
b=AS:300
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1

Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help
Past duration 0.929985 too large      66kB time=00:00:02.33 bitrate= 233.1kbits/s dup=70 drop=0 speed=0.357x    
[rtsp @ 0x32ce310] max delay reached. need to consume packetbitrate= 223.6kbits/s dup=88 drop=5 speed=0.374x    
[rtsp @ 0x32ce310] RTP: missed 705 packets
[h264 @ 0x3352050] error while decoding MB 17 22, bytestream -57
[h264 @ 0x3352050] concealing 456 DC, 456 AC, 456 MV errors in I frame
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 3 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packetbitrate= 222.0kbits/s dup=90 drop=5 speed=0.282x    
[rtsp @ 0x32ce310] RTP: missed 412 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 5 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packetbitrate= 232.8kbits/s dup=376 drop=5 speed=0.429x    
[rtsp @ 0x32ce310] RTP: missed 245 packets
[h264 @ 0x34e6c90] error while decoding MB 43 20, bytestream -15
[h264 @ 0x34e6c90] concealing 536 DC, 536 AC, 536 MV errors in I frame
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 8 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 6 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 948 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packetbitrate= 233.3kbits/s dup=384 drop=5 speed=0.429x    
[rtsp @ 0x32ce310] RTP: missed 1365 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packetbitrate= 252.3kbits/s dup=504 drop=5 speed=0.412x    
[rtsp @ 0x32ce310] RTP: missed 256 packets
[h264 @ 0x34e6c90] error while decoding MB 41 9, bytestream -43
[h264 @ 0x34e6c90] concealing 1121 DC, 1121 AC, 1121 MV errors in I frame
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 4 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 582 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 518 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 41 packets
More than 1000 frames duplicated
[rtsp @ 0x32ce310] max delay reached. need to consume packetbitrate= 260.2kbits/s dup=1388 drop=5 speed=0.458x    
[rtsp @ 0x32ce310] RTP: missed 2786 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 534 packets
[h264 @ 0x34d7540] error while decoding MB 35 16, bytestream -23
[h264 @ 0x34d7540] concealing 756 DC, 756 AC, 756 MV errors in I frame
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 6 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packetbitrate= 261.0kbits/s dup=1391 drop=5 speed=0.458x    
[rtsp @ 0x32ce310] RTP: missed 1271 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packetbitrate= 262.5kbits/s dup=1393 drop=5 speed=0.448x    
[rtsp @ 0x32ce310] RTP: missed 5 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 3 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packet
[rtsp @ 0x32ce310] RTP: missed 2771 packets
[rtsp @ 0x32ce310] max delay reached. need to consume packetbitrate= 263.6kbits/s dup=2672 drop=5 speed=0.44x    
[rtsp @ 0x32ce310] RTP: missed 9 packets
[h264 @ 0x34d7540] error while decoding MB 39 23, bytestream -39ate= 264.8kbits/s dup=3168 drop=5 speed=0.433x    
[h264 @ 0x34d7540] concealing 381 DC, 381 AC, 381 MV errors in I frame
frame= 3243 fps= 13 q=24.0 Lsize=    3514kB time=00:01:48.06 bitrate= 266.4kbits/s dup=3186 drop=5 speed=0.431x    
video:3479kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.016440%
[libx264 @ 0x333bdc0] frame I:13    Avg QP:25.20  size: 29016
[libx264 @ 0x333bdc0] frame P:3230  Avg QP:15.00  size:   986
[libx264 @ 0x333bdc0] mb I  I16..4: 19.8% 65.7% 14.5%
[libx264 @ 0x333bdc0] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  5.3%  0.3%  0.4%  0.0%  0.0%    skip:93.9%
[libx264 @ 0x333bdc0] 8x8 transform intra:64.3% inter:78.9%
[libx264 @ 0x333bdc0] coded y,uvDC,uvAC intra: 51.4% 42.2% 6.2% inter: 1.2% 3.1% 0.1%
[libx264 @ 0x333bdc0] i16 v,h,dc,p: 25% 32%  8% 34%
[libx264 @ 0x333bdc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 19% 26%  3%  3%  3%  5%  3%  5%
[libx264 @ 0x333bdc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 38% 26% 11%  3%  4%  4%  8%  3%  4%
[libx264 @ 0x333bdc0] i8c dc,h,v,p: 62% 16% 21%  1%
[libx264 @ 0x333bdc0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x333bdc0] ref P L0: 94.2%  1.0%  3.9%  1.0%
[libx264 @ 0x333bdc0] kb/s:263.63`

This is a copy of the plug in section in my config.json
`"platforms": [

                {
                        "platform": "Camera-ffmpeg",
                        "cameras": [{
                                "name": "Sala Cam",
                                "videoConfig": {
                                        "source": "-rtsp_transport tcp -re -i rtsp://xx.x.x.xx:554/stream1",
                                        "maxStreams": 2,
                                        "maxWidth": 640,
                                        "maxHeight": 480,
                                        "maxFPS": 15
                                }
                        }]
`

I have tried:

1. Adding -rtsp_transport tcp before -re -i
2. udo usermod -aG video homebridge
3. apt-get install libomxil-bellagio-bin
4. apt-get install libomxil-bellagio-dev

And none have improved the issue. Does anyone have any other suggestions?

Appreciate it

**Comment by KhaosT** [comment]
This is more of a ffmpeg issue instead of a plugin issue. I'm afraid I won't be able to help on this one since I'm not really familiar with ffmpeg, you may have a better chance to search it online or ask in one of the ffmpeg mailing list.

**Comment by Cloudore** [comment]
Stream now running smooth on raspberry pi by using the following fork:
https://github.com/legotheboss/homebridge-camera-ffmpeg-omx

**Comment by KhaosT** [comment]
Ah then this is an issue with machine CPU power being under power then. Good to know ^^

**Comment by AVBIT** [comment]
Don't use flag '-re'!!!

`-re (input)

**Read input at native frame rate.** Mainly used to simulate a grab device, or live input stream (e.g. when reading from a file). Should not be used with actual grab devices or live input streams (where it can cause packet loss).`
http://ffmpeg.org/ffmpeg.html#Advanced-options

**Comment by Cloudore** [comment]
Thanks a lot for the input on my settings, @AVBIT, have it working reliably now, alas with some delay (omg fork). Will try removing the re flag to see how things change.

Regards!
