### ISSUE TITLE
No Camera in Home app

### ISSUE THREAD

**Issue by RienduPre** [KhaosT/homebridge-camera-ffmpeg#5]
Hi,

Installed a clean Homebridge on OSX and added homebridge-camera-ffmpeg.
Configured my camera in the config.json and started the Homebridge without errors.
Add the homebridge to the Home app, but I don't see any camera in the Home App.

What am I missing here.

Config.json
`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platform": "Camera-ffmpeg",
	"cameras": [{
		"name": "Webcam 3",
		"videoConfig": {
			"source": "-re -i rtsp://192.168.0.197:554/12",
			"maxStreams": 2,
			"maxWidth": 1280,
			"maxHeight": 720,
			"maxFPS": 30
		}
	}]
}`

And the startup screen of the Homebridge:
`[2016-09-29 21:41:04] Loaded plugin: homebridge-camera-ffmpeg
[2016-09-29 21:41:04] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2016-09-29 21:41:04] ---
[2016-09-29 21:41:04] Loaded config.json with 0 accessories and 0 platforms.
[2016-09-29 21:41:04] ---
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2016-09-29 21:41:04] Homebridge is running on port 51826.`

**Comment by KhaosT** [comment]
You placed the config in the wrong place...

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "Camera-ffmpeg",
		"cameras": [{
			"name": "Webcam 3",
			"videoConfig": {
				"source": "-re -i rtsp://192.168.0.197:554/12",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 720,
				"maxFPS": 30
			}
		}]
	}]
}
```

**Comment by RienduPre** [comment]
Ah stupid of me 

Now I see the Camera, but no video.

In the log I see:
[2016-09-29 21:56:15] Homebridge is running on port 51826.
[2016-09-29 21:56:15] Webcam 3 is running on port 60675.
-re -i rtsp://192.168.0.197:554/12 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params /hmyFHls7jFl/jA158mIYc1sHO50Ahq7maVebQ+4 srtp://192.168.0.57:55327?rtcpport=55327&localrtcpport=55327&pkt_size=1378

**Comment by RienduPre** [comment]
On OSX

**Comment by KhaosT** [comment]
Huh... If you have VLC on your Mac, try running ``ffmpeg -re -i rtsp://192.168.0.197:554/12 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k - | /Applications/VLC.app/Contents/MacOS/VLC -`` in Terminal and see if VLC can play the video.

**Comment by RienduPre** [comment]
See below

I don't see where the username and password is set.

ffmpeg -re -i rtsp://192.168.0.197:554/12 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k - | '/Applications/VLC.app/Contents/MacOS/cVLC' 
-bash: /Applications/VLC.app/Contents/MacOS/cVLC: No such file or directory
ffmpeg version 3.0 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.38)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.0 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-vda
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[rtsp @ 0x7ff028000000] method DESCRIBE failed: 401 Unauthorized
rtsp://192.168.0.197:554/12: Server returned 401 Unauthorized (authorization failed)

**Comment by KhaosT** [comment]
@RienduPre Ah... it follows HTTP Basic access authentication. If your video feed requires a password, try rtsp://username:password@192.168.0.197:554/12

**Comment by RienduPre** [comment]
YES !!!
It works :-)
