### ISSUE TITLE
Possible to add a Doorbell service to ffmpeg config?

### ISSUE THREAD

**Issue by brownad** [KhaosT/homebridge-camera-ffmpeg#51]
I'm using ffmpeg for my DoorBird camera stream :+1: and tried to use the Doorbell service as a standalone service, this didnt work for long.  Wanted to see if its possible to combine the two and get a video doorbell working?

Could this be done inside ffmpeg as an optional accessory?

**Comment by MrsDelish** [comment]
Not sure how your doorbell works, but if you configure a motion sensor in homekit in the same room as the camera, homekit will attach the camera snapshot to the motion sensor push notification.

I use a pi-cameramodule at my outdoor with motion running on a rpi3b, with homebridge-camera-ffmpeg as camera and homebridge-motion-fifo as motion sensor. (then I use mqtt and node-red to display the cam on my htpc, when there is motion)

**Comment by brownad** [comment]
Yep - good idea.  I've just now committed that to replace the doorbell service (fed up watching it fail).  The experience is a bit richer with doorbell service - you can control devices from the iOS notification directly, whatever is in the room.  That was pretty sweet.  And there isnt a generic approach with video doorbells yet.  It seems from discussion the only way to make doorbell service work is by combining with a camera, hence coming here to see if an addition could be made, thus completing a video doorbell in a very tight way.
