### ISSUE TITLE
IP Cam isn't going live 

### ISSUE THREAD

**Issue by QuinnDD** [KhaosT/homebridge-camera-ffmpeg#52]
hi, I'm trying to put my dahua security camera into home bridge. 
the snapshot is working great but the live view won't work. i see in the log that he starts the stream but it just doesn't get live :/

anybody some ideas why ?

**Comment by MrsDelish** [comment]
try a different resolution, on my rpi3b it does not work on 1920x1080, but works fine with 1280x720 or1280x960 and lower.
Homekit caches the resolution so you need to remove camera, and reboot ios device before it will see the new resolution. tip is to check the resolution in the log in homebridge when ffmpeg starts streaming.

**Comment by QuinnDD** [comment]
@MrsDelish after changing still no live stream :/

**Comment by tmur11** [comment]
@QuinnDD see #39 this happen me significantly

**Comment by sunjunlishi** [comment]
"eboot ios device before it will see the new resolution" me too

**Comment by sunjunlishi** [comment]
@MrsDelish hi,i have same problem as you,when it slowly or halt,i need reboot ios device;
have you resolved it
