### ISSUE TITLE
After a few days stillimage is just black in the home app and won't update

### ISSUE THREAD

**Issue by pponce** [KhaosT/homebridge-camera-ffmpeg#54]
i'm using the homebridge-camera-ffmpeg-omx plugin. 
Everything works for 3 or 4 days quite well.  Still image updates every 10 seconds on local home network.
Updates every 1 minute when remote. Video plays just fine.
Except after 3 or 4 days my still image is just black. won't update. when i click on it in the home app i can see the video stream just fine.  When i manually go to my still image url as configured in the config.json that url works just fine.  
The only fix is to remove the camera from the home app.
I delete the persist files for the camera.
Then re-pair the camera with the same exact config.json setup.
Then everything works again for a few days.
Any ideas what might be happening?

my config below:

{
          "platform": "Camera-ffmpeg",
          "cameras": [
                {
                  "name": "FrontDoorIPCam",
                  "videoConfig": {
                        "source": "-rtsp_transport udp -re -i rtsp://admin:pass@ip:554/profile2/media.smp",
                        "stillImageSource": "-f mjpeg -i http://ip:81/image/FrontDoor",
                        "maxStreams": 6,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 30
                  }
                }
          ]
        },

**Comment by visnaut** [comment]
I too am encountering this issue. 

I'm using the lastest version of `homebridge-camera-ffmpeg` and I've also verified that the output from ffmpeg generated in `FFMPEG.prototype.handleSnapshotRequest` is a valid JPEG.

**Comment by rakimbadu** [comment]
Me too. Same exact problem. I'm using omx fork. Videos are always working instead images works only for few days than black screen in the preview box. If remove and re add the camera pictures return.

**Comment by pponce** [comment]
when i opened this issue i had just done a fresh re-paring of the video camera to homebridge and now today is see the issue again. It appears to be refreshing the still image but it's black every time.
NO errors reported with debug on. This is what i see when the image updates to the latest fully black image.
  EventedHTTPServer [::ffff:192.168.1.135] HTTP request: /resource +21s
  HAPServer [0D:A9:64:A8:88:3D] HAP Request: POST /resource +1ms
  EventedHTTPServer [::ffff:192.168.1.135] HTTP Response is finished +245ms

**Comment by matevzg** [comment]
Same issue. 

Funny thing is, I share my Home with two other iPhones (plus mine, which is Home owner) and snapshots work on both shared iPhones. 

I only get black after a few days. Strange.

**Comment by pponce** [comment]
Interesting. I'll check my wife's phone when it happens to me again.
I've surpassed the 5 days now with no black image issue cropping up.

**Comment by init4** [comment]
I'm having this problem too. 

I think we must be triggering some kind of HomeKit bug because on another iOS device with the same Apple ID the camera preview works properly. A third iOS device with a different Apple ID also works properly.

**Comment by KhaosT** [comment]
When you're in this state, does rebooting your iOS device fix the issue?

**Comment by init4** [comment]
How embarrassing - yes rebooting my iOS device fixed it for me

**Comment by KhaosT** [comment]
If reboot iOS device fixed the issue, I assume it's a bug in HomeKit instead of an implementation error on our side...

**Comment by matevzg** [comment]
OMG, yes. :/

It seems we don't reboot frequently enough to notice this. Thanks @KhaosT.

**Comment by pponce** [comment]
i'll see if that fixed things when it happens again to me and confirm here.

**Comment by fafoulon** [comment]
Hi,
I just wanted to add my input.
Since few days I had also black thumbnails, so I rebooted my phone this morning. I have two cameras. One was working correctly again after the reboot, but my second camera was in fact offline at the time I rebooted, and it turns out Homekit showed me the thumbnail from yesterday evening. But in fact it was a few days all black in the app. 
It could mean Homekit is in fact correctly getting the thumbnail from the camera but the bug is only with displaying it.

**Comment by dkrizic** [comment]
I would like also to note, that some cameras see to stop sending still images due to memory leak problems. I have this case with a few Reolink cameras. The RTSP stream continues to work, but images are not updated. In the Home app I see an old picture with the info "4h" or so when it was able to update it last time.

**Comment by visnaut** [comment]
The black thumbnail problem has ceased to occur for me in iOS 11.

**Comment by init4** [comment]
It hasn't happened on iOS 11 yet for me, but previously with late builds of iOS 10 it was a rare occurrence anyway

**Comment by malhal** [comment]
Black screen here on latest iOS 11.2.2

**Comment by darconeous** [comment]
Happened to me, rebooting my phone fixed it. Seems like a homekit bug.
