### ISSUE TITLE
One cam updates, other two not after systemd homebridge as a service

### ISSUE THREAD

**Issue by valentinoua** [KhaosT/homebridge-camera-ffmpeg#55]
In order to make homebridge launch automatic from the start of Pi3, I installed it as a systemd. 

All 3 ffmpeg cameras work fine if homebridge is launched manually. 
If launched under systemd, 1 cam works properly with every 3-5s update, but other 2 would not refresh, i.e. would show same image from the time homebridge was manual. 
I used the same config file in .Homebridge and systemd
My config file is below:
{
	"bridge": {
		"name": "Homebridge",
        "username": "CC:22:3D:E3:CE:20",
        "port": 51826,
        "pin": "031-45-154"
	},

	"platforms": [{
		"platform": "Nest",
		"username": "valentino_ua@me.com",
        "password": "valentine12"
        },
        {
        	"platform": "PhilipsHue",
        "name": "Val Philips hue",
        "ip_address": "192.168.1.11",
        "username": "yxLPT8SZJtrjMIMk7YeD-ZoWWYGTMoX3m0B-5fLT"
        },
       	{
         	"platform": "BelkinWeMo",
         "name": "WeMo Platform",
         "noMotionTimer": 60,
         "ignoredDevices": []
       	},
	{
		"platform": "Camera-ffmpeg",
	"cameras":[
	      {
		"name":"Front facade",
		"videoConfig":{
			"source":"-re -i rtsp://admin:12345@192.168.1.99/video.h264",
			"maxStreams":2,
			"maxWidth":1280,
			"maxHeight":720,
			"maxFPS":30
		}
	       },
	      {
                "name":"Backyard alp hill",
                "videoConfig":{
                        "source":"-re -i rtsp://admin:yssup250@192.168.1.64/video.h264",
                        "maxStreams":2,
                        "maxWidth":640,
                        "maxHeight":480,
                        "maxFPS":30
                }
               },
  		{
                "name":"Front yard",
                "videoConfig":{
                        "source":"-re -i rtsp://admin:12345@192.168.1.98/video.h264",
                        "maxStreams":2,
                        "maxWidth":1280,
                        "maxHeight":720,
                        "maxFPS":30
                }
               }

	]

	}
	]
  
}

**Comment by jeylites** [comment]
Just wondering if you manage to fix the issue ?

**Comment by tristanmhmx** [comment]
I am facing the same issue, I have 2 cameras when I start homebridge manually it works but if I start it from systemd it doesn't, were you able to figure this out?

**Comment by valentinoua** [comment]
No, not yet

Valentyn
