### ISSUE TITLE
ffmpeg portrait 

### ISSUE THREAD

**Issue by kartikkannan** [KhaosT/homebridge-camera-ffmpeg#57]
Hi, 
Firstly, great plugin for homebridge!!

I use a Hikvision 2032 model camera which works well with zoneminder.

I added the configuration file as follows:
{
"platform": "Camera-ffmpeg",
"cameras": [
{
"name": "Front Door",
"videoConfig": {
"source": "-re -i rtsp://10.0.1.206:554/Streaming/Channels/1 scale=720:1280",
"maxStreams": 1,
"maxWidth": 720,
"maxHeight": 1280,
"maxFPS": 15
}
}
]
}

I can view the stream but a stretched landscape view is only visible, even after adding the scale parameter in the stream. From the log file output below, I can see that some other scale parameter 640:360 is being added. Any idea where this could be coming from? Thanks!

homebridge[29447]: -re -i rtsp://zm:zx78io12@10.0.1.206:554/Streaming/Channels/1 scale=720:1280 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 15 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params eMlM7qcF3NpHXBZMCrykUfLvIhyPfiDGUfh8qDNn srtp://10.0.1.115:49536?rtcpport=49536&localrtcpport=49536&pkt_size=1378

**Comment by KhaosT** [comment]
It's added by the plugin since HomeKit requested that resolution. Currently there is no support for vertical video stream...
