### ISSUE TITLE
Camera stops refreshing after a while

### ISSUE THREAD

**Issue by brownad** [KhaosT/homebridge-camera-ffmpeg#58]
Is there a limitation somewhere with the camera streaming if I leave it running on iOS for sometime? As over 45mins maybe less it stops refreshing requiring a manual pull down to fetch latest and resume.

Normally one camera gets a refresh every 10s and second camera on same home view refreshes after 20sec again random - any clarity please?

**Comment by iCarl** [comment]
I'm having the same issue, did you get your camera to work properly?

**Comment by brownad** [comment]
Nope it's random when it stops
