### ISSUE TITLE
homebridge ffmpeg camera not found port

### ISSUE THREAD

**Issue by kingxmc** [KhaosT/homebridge-camera-ffmpeg#59]
I am a 2015 Apple notebook, there are two Hikvision poe cameras, homebridge running on this computer, Vlc and ffplay everything normal，Start homebridge can not find camera ffmpeg port ,I need that you help,thank you!
look this   why now not found nothing ,Loaded config.json with 0 accessories and 0 platforms.
I don't know mistakes where ?

sMacBook-Pro:~ s$ homebridge
[2017-3-1 19:58:55] Loaded plugin: homebridge-camera-ffmpeg
[2017-3-1 19:58:55] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2017-3-1 19:58:55] ---
[2017-3-1 19:58:55] Loaded plugin: homebridge-camera-isight
[2017-3-1 19:58:55] Registering platform 'homebridge-camera-isight.Camera-iSight'
[2017-3-1 19:58:55] ---
[2017-3-1 19:58:55] Loaded config.json with 0 accessories and 0 platforms.
[2017-3-1 19:58:55] ---
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-camera-isight.Camera-iSight
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2017-3-1 19:58:55] Homebridge is running on port 51826.
[2017-3-1 19:58:55] iSight Camera is running on port 51408.

This is my configuration file  config.json
```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "platform": "Camera-ffmpeg",
    "cameras": [
                {
                "name": "my camera1",
                "videoConfig": {
                "source": "-re -i rtsp://admin:xxxxxx@192.100.0.164:554/h264/ch1/main/av_stream",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 25
                }
                },
                {
                "name": "my camera2",
                "videoConfig": {
                "source": "-re -i rtsp://admin:xxxxxx@192.100.0.163:554/h264/ch1/main/av_stream",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 25
                }
                }
                ]
}
```

**Comment by kingxmc** [comment]
I need our's help,Thanks!

**Comment by KhaosT** [comment]
You placed the configuration in the wrong section.

**Comment by kingxmc** [comment]
How will i put these configurations correctly, homebridge started to find ffmpeg-camera port, but also because of configuration errors caused by it? Seek God guidance, thanks!

**Comment by KhaosT** [comment]
the one you saw from log is created by iSight, not ffmpeg plugin.

The full configuration file should look like this, notice the "platforms" section.

```json
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "Camera-ffmpeg",
		"cameras": [{
			"name": "my camera1",
			"videoConfig": {
				"source": "-re -i rtsp://admin:xxxxxx@192.100.0.164:554/h264/ch1/main/av_stream",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 720,
				"maxFPS": 25
			}
		}, {
			"name": "my camera2",
			"videoConfig": {
				"source": "-re -i rtsp://admin:xxxxxx@192.100.0.163:554/h264/ch1/main/av_stream",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 720,
				"maxFPS": 25
			}
		}]
	}]
}
```
