### ISSUE TITLE
ffmpeg doesnt launch SRTP stream on Pi 1

### ISSUE THREAD

**Issue by yahms** [KhaosT/homebridge-camera-ffmpeg#62]
- Raspberry Pi 1 model B (two usb) & Pi cam module v1 | Raspbian Jessie
- UV4L driver / streaming server, serving mjpeg via http
- iphone 6s | iOS 10.2.1

Pairs fine, Home App snapshots work, but i cant load the live stream.

As the precompiled ffmpeg package for armhf doesnt suit the Pi Zero / Model Bs, i had to compile my own ffmpeg. (took hours!) configure script options were:

./configure --enable-gpl --enable-mmal --enable-omx-rpi --enable-omx --prefix=/usr --enable-nonfree --enable-hwaccel=h264_mmal

i also had to mod the ffmpeg.js file to change the 'vcodec' param to h264_omx, and remove the '-tune zerolatency' to suit my compiled ffmpeg

but for whatever reason i cant get ffmpeg to get to the point of running the SRTP stream. ffmpeg itself seems to hang/crash and sit doing nothing, yet works fine to more basic outputs. doing a CTRL+C goes back to the prompt but pgrep shows up some ffmpeg processes (1 per failed attempt)

it stops at this point below(showing full logging): (the homebridge console logs the command syntax every time a stream is attempted, but nothing else)

> pi@picam1:~ $ ffmpeg -loglevel trace -re -i http://192.168.0.151:8080/stream/video.mjpeg -threads 0 -vcodec h264_omx -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params `**SNIPPED**` srtp://192.168.0.108:64597?rtcpport=64597&localrtcpport=64597&pkt_size=1378
> [3] 950
> [4] 951

> pi@picam1:~ $ ffmpeg version N-83795-g195784e Copyright (c) 2000-2017 the FFmpeg developers
>   built with gcc 4.9.2 (Raspbian 4.9.2-10)
>   configuration: --enable-gpl --enable-mmal --enable-omx-rpi --enable-omx --prefix=/usr --enable-nonfree --enable-hwaccel=h264_mmal
>   libavutil      55. 48.100 / 55. 48.100
>   libavcodec     57. 82.102 / 57. 82.102
>   libavformat    57. 66.104 / 57. 66.104
>   libavdevice    57.  3.100 / 57.  3.100
>   libavfilter     6. 74.100 /  6. 74.100
>   libswscale      4.  3.101 /  4.  3.101
>   libswresample   2.  4.100 /  2.  4.100
>   libpostproc    54.  2.100 / 54.  2.100

the following text shows up directly below the text above but only when enabling `-loglevel trace`
> Splitting the commandline.
> Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'trace'.
> Reading option '-re' ... matched as option 're' (read input at native frame rate) with argument '1'.
> Reading option '-i' ... matched as input url with argument 'http://192.168.0.151:8080/stream/video.mjpeg'.
> Reading option '-threads' ... matched as AVOption 'threads' with argument '0'.
> Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'h264_omx'.
> Reading option '-f' ... matched as option 'f' (force format) with argument 'rtp'.
> Reading option '-srtp_out_suite' ... matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
> Reading option '-srtp_out_params' ... matched as AVOption 'srtp_out_params' with argument '`**SNIPPED**`'.
> Reading option 'srtp://192.168.0.108:64597?rtcpport=64597' ... matched as output url.
> Finished splitting the commandline.
> Parsing a group of options: global .
> Applying option loglevel (set logging level) with argument trace.
> Successfully parsed a group of options.

does anyone have a working ffmpeg for the pre- pi2 which does work? or any other suggestions? i have found the following:

- if i download avconv and run the same command (replacing ffmpeg with avconv), this works, but without the hardware accel, slowly. (not tried within homebridge)
- if i run my compiled version of ffmpeg using the same input params but output to a local file instead of SRTP it works fine - successfully reading from the http stream, writing a file, and using the hardware accel as cpu is ~20%

uv4l-raspicam.conf config is mjpeg, 640x360, 15 fps

config.json:

```
{
    "bridge": {
        "name": "Homebridge-B",
        "username": "BB:BB:BB:11:22:33",
        "port": 51826,
        "pin": "000-00-002"
    },
        "description": "The Onion!",
    "platforms": [
{
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "Camera Name",
      "videoConfig": {
        "source": "-re -i http://192.168.0.151:8080/stream/video.mjpeg",
        "stillImageSource": "-i http://192.168.0.151:8080/stream/snapshot.jpeg?delay_s=0",
        "maxStreams": 1,
        "maxWidth": 640,
        "maxHeight": 360,
        "maxFPS": 30 
      }
    }
  ]
}


],

   "accessories": [
    ]
}
```

**Comment by yahms** [comment]
Further to this, ive noticed ffmpeg spawns two processes, and one of them doesnt end. the [3] and [4] are the PIDs. Is this an RTP or SRTP thing? 

im actually compiling a run of avconv with the omx/mmal hardware encode/decode stuff rolled in, and im going to make a copy of this project, replacing ffmpeg with avconv..

will try that. in parallel im going to do a standard install on a pi3 to see if its just a rpiB/rpiZero thing (which would be a real shame, but handy to know for sure)

**Comment by KhaosT** [comment]
It's running 2 because you didn't escape reserved bash operands… try adding "…" between urls

**Comment by yahms** [comment]
haha! ok yes, that turned out to be it. Works fine on a pi3, using an ffmpeg i compiled on the device (getting lag down to about 1second) but its a mission finding an optimised ffmpeg for the pi1. I wonder if the encryption element is too much for the earlier pi? Closing issue anyways. thanks @KhaosT
