### ISSUE TITLE
Installation instructions not clear

### ISSUE THREAD

**Issue by ooii** [KhaosT/homebridge-camera-ffmpeg#65]
Hi,

That may be related to issue #64 but what does `Add extra camera accessories in Home app. The setup code is the same as homebridge.` mean? 

Thanks.

**Comment by KhaosT** [comment]
This means you need to pair with the camera separately. In Home app, click the add button on the upper right, select Add Accessory, then select the camera here to add it to home.

**Comment by ooii** [comment]
Thanks a lot. That was not very clear to me.
I'll do it as soon as I can and report back here.

Thanks again.

**Comment by KhaosT** [comment]
Err... I'm not sure what else I can do to make it more clear, any suggestion?

**Comment by ooii** [comment]
May be by adding something like `(with the + button on the upper right corner)`.
But, if I'm the only one complaining about that then you should not worry about it ;)
