### ISSUE TITLE
Gets an error when ffmpeg -re i my RTSP string

### ISSUE THREAD

**Issue by Klangen82** [KhaosT/homebridge-camera-ffmpeg#66]
I have a camera that stream RTSP via the string rtsp://192.168.5.34/stream2 (want to use stream two) I have configure the second stream on the camera to be 640x480 12ips and when I playback it on my PC via VLC I get video without any problem.

I run homebrigde on my Raspberry Pi 3 and its works fine:) But when I run `ffmpeg -re i rtsp://192.168.5.34/stream2` I get this responce:

![image](https://cloud.githubusercontent.com/assets/25564168/24070305/e83ec726-0bba-11e7-9d56-ea7a1761bb00.png)

Would be very thankful if someone could guide me in the correct direction what can be wrong:)

**Comment by KhaosT** [comment]
A few things… first, “-re” requires you to have an output, in this case you don’t have that so it throw out the first error. Second instead of “i”, it’s actually “-i” ...

Best Wishes,
Tian Zhang

**Comment by Klangen82** [comment]
Thanks! seams to work, agree?

![image](https://cloud.githubusercontent.com/assets/25564168/24070348/083025e2-0bbc-11e7-840e-9ef55e535742.png)

Now I should be able to use this as config:

![image](https://cloud.githubusercontent.com/assets/25564168/24070361/3e540e68-0bbc-11e7-8438-edfea3e66adc.png)

**Comment by KhaosT** [comment]
Please put 30 as maxFPS even if camera can’t support that otherwise HomeKit will not be happy. other than that it looks good.

Best Wishes,
Tian Zhang
