### ISSUE TITLE
Add model / manufacturer / serial support.

### ISSUE THREAD

**Issue by hjdhjd** [KhaosT/homebridge-camera-ffmpeg#67]
First...great plugin, works beautifully.

A minor cosmetic addition that would be appreciated would be support for model / manufacturer / serial configuration as other plugins do.  Primarily cosmetic, but would be helpful for my use case as well.  Thanks!

**Comment by Veldkornet** [comment]
I was hoping to see the same! Please! :)

**Comment by jwebbstevens** [comment]
![manufacturer](https://user-images.githubusercontent.com/7277574/49627793-d2bc9480-f9ae-11e8-873b-f053a5a35115.jpeg)

+1 Yes! Adding that in would be awesome.

It would also be super cool to link back to the device app associated with the Camera Manufacturer.  For instance if you hard press, nav into Settings you can open the Related App.

Would this be as simple as modifying the config file for each camera with the variables?

https://developer.apple.com/documentation/homekit/hmaccessory
