### ISSUE TITLE
Works, but live is in slow motion.

### ISSUE THREAD

**Issue by NicAshby** [KhaosT/homebridge-camera-ffmpeg#73]
Any ideas?

**Comment by magichew** [comment]
Same here. I'm using a Raspberry Pi so I'm going to put it down to that. I'm going to try on a more powerful computer and see if there's any performance improvement.

**Comment by NorthernMan54** [comment]
The PI is underpowered for this, you need to use a special version of ffmpeg, compiled with hardware acceleration enabled.  Look at the fork of this called homebridge-camera-ffmpeg-omx

**Comment by magichew** [comment]
Great. Actually found this and installed and it's working much better now. Good stuff. Thanks.

**Comment by NicAshby** [comment]
Weird that a raspberry pi zero w can output a solid stream but a pi 3b can't receive with homebridge just as well. I'll try the version mentioned in the next week or so and comment with results.
