### ISSUE TITLE
Ring Doorbell

### ISSUE THREAD

**Issue by macjeff** [KhaosT/homebridge-camera-ffmpeg#74]
There is a mention here that this plugin has been made to work with Ring Doorbell video

https://github.com/homespun/homebridge-platform-ring-video-doorbell  
(scroll down to bottom)

Can someone post any info on how to do this?

Thanks,

Jeff

**Comment by jocamero** [comment]
After seeing the same post at homebridge-platform-ring-video-doorbell I came here for more info.  Anyone get this working?

**Comment by bassrock** [comment]
Looking for the same

**Comment by paulg1981** [comment]
I came here for the exact same info, someone please help out!

**Comment by tokamac** [comment]
Same here. It's incredible that despite so much reviews on Amazon (over 25,000 for the Doorbell and over 8,000 for the Pro model, with very high ranking) there is not a _single_ person who tried homebridge plugins and report his testing here. Totally incomprehensible.

**Comment by sdorilas** [comment]
Lol, we are all in the same boat. I came on here hoping to find quite a few posts...Negative.

**Comment by kylerphillips** [comment]
Anyone manage to get this working? I have the Ring plugin working set up as a motion sensor but no camera... @barkerja

**Comment by sdorilas** [comment]
I don’t believe it’s possible.

**Comment by macjeff** [comment]
I confirmed with Ring that there video is only available from their apps or website.   No way to get it any other way except amazon show.   

Jeff

**Comment by traviscollins** [comment]
Looks like the thing we lack is a SIP implementation for Python. 

http://www.kidder.io/2017/07/04/ring-doorbell-api/
