### ISSUE TITLE
Crash when try to view camera

### ISSUE THREAD

**Issue by unaxboy** [KhaosT/homebridge-camera-ffmpeg#75]
Using with Doorbird D110

**My config:**

```
    "platforms": [{
			"platform": "Camera-ffmpeg",
			"cameras": [{
    	  "name": "Camera",
    	  "videoConfig": {
        	"source": "-re -i rtsp://username:password@192.168.10.91:554/mpeg/media.amp",
        	"stillImageSource": "-i http://username:password@192.168.10.91/bha-api/image.cgi",
        	"maxStreams": 1,
        	"maxWidth": 1280,
        	"maxHeight": 720,
        	"maxFPS": 30
				}
			}]
		}]
```

**Comment by unaxboy** [comment]
```
Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by KhaosT** [comment]
ENOENT means either you didn't install ffmpeg or ffmpeg is not in a place where nodejs can access.

**Comment by unaxboy** [comment]
I'm using [homebridge-docker](https://hub.docker.com/r/benzman81/homebridge-docker/), ffmpeg already in docker and everything worked 2 mounths ago

**Comment by KhaosT** [comment]
Then I'm not really sure... based on the error I can only say check where ffmpeg is being installed and see why spawn failed to run it.

**Comment by unaxboy** [comment]
I'll be very appreciate if you help me to do it, I'm have no idea how to do this

**Comment by KhaosT** [comment]
I knew how to do that in normal system but I have no idea how to solve this with docker ¯\_(ツ)_/¯

**Comment by unaxboy** [comment]
Maybe you know how to install ffmpeg in seperate docker?

**Comment by unaxboy** [comment]
Or via install.sh

**Comment by KhaosT** [comment]
Check [this](https://github.com/jrottenberg/ffmpeg) or [this](https://medium.com/coconut-stories/using-ffmpeg-with-docker-94523547f35c)?

**Comment by unaxboy** [comment]
Thanks, will try.

**Comment by unaxboy** [comment]
I found the problem. Docker don't include ffmped for some reason, but description says vise versa.

Solution for those who has the same problem:

1. Use docker with clean HomeBridge install (for example [this](https://github.com/marcoraddatz/homebridge-docker)).
2. Add in the top of install.sh a code bellow:

```
echo 'deb http://ftp.uk.debian.org/debian jessie-backports main' >> /etc/apt/sources.list
apt-get update
apt-get -y install ffmpeg
ffmpeg
```

3. Start docker and wait until it loads everything (2-15 mins, depend on your hardware and internet speed).

**Comment by DanielWeeber** [comment]
debian changed the sources of ffmpeg, it should be libav-tools.
But its not working for me (with libav-tools). Your workaround is working! Thanks!
