### ISSUE TITLE
Live camera streams do not connect to Apple Watch 

### ISSUE THREAD

**Issue by elvisimprsntr** [KhaosT/homebridge-camera-ffmpeg#77]
Stills and live streams work both on my WLAN and via LTE on the iPhone. 

Only stills will update on the Apple Watch.  Live RTSP streams will not connect on AW.  

![img_3398](https://cloud.githubusercontent.com/assets/1215508/25771476/dd17ae80-3220-11e7-9b8b-37c6be00066c.PNG)

I confirmed a FFMPEG instance is launched to stream the smaller scaled feed to the iPhone IP address, but the stream does not appear on the AW. 

```
May  6 05:56:26 qnap-hb homebridge[6000]: -rtsp_transport tcp -re -i rtsp://username:password@192.168.69.13:554/ISAPI/Streaming/channels/102 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 2 -f rawvideo -tune zerolatency -vf scale=320:240 -b:v 68k -bufsize 68k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ******************************* srtp://192.168.69.35:52633?rtcpport=52633&localrtcpport=52633&pkt_size=1378
```

Is this a limitation (Apple imposed or BTLE), a bug in iOS 10, or something that needs to be tweaked in this plugin?

**Comment by fennec622** [comment]
same problem all is ok on iphone but not on AW

**Comment by Arduingo** [comment]
Same problem, perfect on iPhone only still on Apple Watch. 
Using a RPi2, iOS 10.3.3, WatchOS 3.2.3

**Comment by simonrb2000** [comment]
Same here.. Just says connecting, then some times unavailable.

Anyone know how to fix this?

Although I find the Homekit so slow to initially load..

**Comment by drewcassidy** [comment]
I'm having the same issue. I was going to try to debug it but I cant get the watch to connect through console.app to see the logs

**Comment by timurvalishev** [comment]
Same problem, would appreciate a fix.

**Comment by htschmed** [comment]
Was able to hook up my apple watch to the console today and view the event log using this method:

> _Install the sysdiagnose profile to Apple Watch_
 
> _Download the watchOS profile from here:_
> _https://developer.apple.com/bug-reporting/profiles-and-logs/?name=sysdiagnose_
 
> _Airdrop it to your iPhone and then you will get the choice to choose "Apple Watch" to install it to. Once you install it and click "Done" then you will start seeing Apple Watch logs in Console.app_

Once I was able to view the logs I notice there were many errors coming in about the audio codec not being valid.  Did some further digging in the issue list for this project and came across issue https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/224

Went into my node plugin module folder (on raspberry pi it is located under /usr/lib/node_modules) and made the following two changes to ffmpeg.js as recommended by [llemtt](https://github.com/llemtt)

### ffmpeg.js
 
**Line 283**
change
`' -map 0:0' +`
to
`' -an -sn -dn' +`

**Line 302**
change
`' -map 0:1' +`
to
`' -vn -sn -dn' +`

Save and restart homebridge and you should now be able to view live video streams from your apple watch.  Hopefully this update will get applied to the main code base soon and you can just do an npm update, but in the meantime give the above work around a try and see if it fixes your issue.

**Comment by simonrb2000** [comment]
I just tried the above however that is no in my ffmpeg.js

`'use strict';
var uuid, Service, Characteristic, StreamController;

var fs = require('fs');
var ip = require('ip');
var spawn = require('child_process').spawn;

module.exports = {
  FFMPEG: FFMPEG
};

function FFMPEG(hap, ffmpegOpt) {
  uuid = hap.uuid;
  Service = hap.Service;
  Characteristic = hap.Characteristic;
  StreamController = hap.StreamController;

  if (!ffmpegOpt.source) {
    throw new Error("Missing source for camera.");
  }

  this.ffmpegSource = ffmpegOpt.source;
  this.ffmpegImageSource = ffmpegOpt.stillImageSource;

  this.services = [];
  this.streamControllers = [];

  this.pendingSessions = {};
  this.ongoingSessions = {};

  var numberOfStreams = ffmpegOpt.maxStreams || 2;
  var videoResolutions = [];
  
  var maxWidth = ffmpegOpt.maxWidth;
  var maxHeight = ffmpegOpt.maxHeight;
  var maxFPS = (ffmpegOpt.maxFPS > 30) ? 30 : ffmpegOpt.maxFPS;

  if (maxWidth >= 320) {
    if (maxHeight >= 240) {
      videoResolutions.push([320, 240, maxFPS]);
      if (maxFPS > 15) {
        videoResolutions.push([320, 240, 15]);
      }
    }

    if (maxHeight >= 180) {
      videoResolutions.push([320, 180, maxFPS]);
      if (maxFPS > 15) {
        videoResolutions.push([320, 180, 15]);
      }
    }
  }

  if (maxWidth >= 480) {
    if (maxHeight >= 360) {
      videoResolutions.push([480, 360, maxFPS]);
    }

    if (maxHeight >= 270) {
      videoResolutions.push([480, 270, maxFPS]);
    }
  }

  if (maxWidth >= 640) {
    if (maxHeight >= 480) {
      videoResolutions.push([640, 480, maxFPS]);
    }

    if (maxHeight >= 360) {
      videoResolutions.push([640, 360, maxFPS]);
    }
  }

  if (maxWidth >= 1280) {
    if (maxHeight >= 960) {
      videoResolutions.push([1280, 960, maxFPS]);
    }

    if (maxHeight >= 720) {
      videoResolutions.push([1280, 720, maxFPS]);
    }
  }

  if (maxWidth >= 1920) {
    if (maxHeight >= 1080) {
      videoResolutions.push([1920, 1080, maxFPS]);
    }
  }

  let options = {
    proxy: false, // Requires RTP/RTCP MUX Proxy
    srtp: true, // Supports SRTP AES_CM_128_HMAC_SHA1_80 encryption
    video: {
      resolutions: videoResolutions,
      codec: {
        profiles: [0, 1, 2], // Enum, please refer StreamController.VideoCodecParamProfileIDTypes
        levels: [0, 1, 2] // Enum, please refer StreamController.VideoCodecParamLevelTypes
      }
    },
    audio: {
      codecs: [
        {
          type: "OPUS", // Audio Codec
          samplerate: 24 // 8, 16, 24 KHz
        },
        {
          type: "AAC-eld",
          samplerate: 16
        }
      ]
    }
  }

  this.createCameraControlService();
  this._createStreamControllers(numberOfStreams, options); 
}

FFMPEG.prototype.handleCloseConnection = function(connectionID) {
  this.streamControllers.forEach(function(controller) {
    controller.handleCloseConnection(connectionID);
  });
}

FFMPEG.prototype.handleSnapshotRequest = function(request, callback) {
  let resolution = request.width + 'x' + request.height;
  var imageSource = this.ffmpegImageSource !== undefined ? this.ffmpegImageSource : this.ffmpegSource;
  let ffmpeg = spawn('ffmpeg', (imageSource + ' -t 1 -s '+ resolution + ' -f image2 -').split(' '), {env: process.env});
  var imageBuffer = Buffer(0);

  ffmpeg.stdout.on('data', function(data) {
    imageBuffer = Buffer.concat([imageBuffer, data]);
  });
  ffmpeg.on('close', function(code) {
    callback(undefined, imageBuffer);
  });
}

FFMPEG.prototype.prepareStream = function(request, callback) {
  var sessionInfo = {};

  let sessionID = request["sessionID"];
  let targetAddress = request["targetAddress"];

  sessionInfo["address"] = targetAddress;

  var response = {};

  let videoInfo = request["video"];
  if (videoInfo) {
    let targetPort = videoInfo["port"];
    let srtp_key = videoInfo["srtp_key"];
    let srtp_salt = videoInfo["srtp_salt"];

    let videoResp = {
      port: targetPort,
      ssrc: 1,
      srtp_key: srtp_key,
      srtp_salt: srtp_salt
    };

    response["video"] = videoResp;

    sessionInfo["video_port"] = targetPort;
    sessionInfo["video_srtp"] = Buffer.concat([srtp_key, srtp_salt]);
    sessionInfo["video_ssrc"] = 1; 
  }

  let audioInfo = request["audio"];
  if (audioInfo) {
    let targetPort = audioInfo["port"];
    let srtp_key = audioInfo["srtp_key"];
    let srtp_salt = audioInfo["srtp_salt"];

    let audioResp = {
      port: targetPort,
      ssrc: 1,
      srtp_key: srtp_key,
      srtp_salt: srtp_salt
    };

    response["audio"] = audioResp;

    sessionInfo["audio_port"] = targetPort;
    sessionInfo["audio_srtp"] = Buffer.concat([srtp_key, srtp_salt]);
    sessionInfo["audio_ssrc"] = 1; 
  }

  let currentAddress = ip.address();
  var addressResp = {
    address: currentAddress
  };

  if (ip.isV4Format(currentAddress)) {
    addressResp["type"] = "v4";
  } else {
    addressResp["type"] = "v6";
  }

  response["address"] = addressResp;
  this.pendingSessions[uuid.unparse(sessionID)] = sessionInfo;

  callback(response);
}

FFMPEG.prototype.handleStreamRequest = function(request) {
  var sessionID = request["sessionID"];
  var requestType = request["type"];
  if (sessionID) {
    let sessionIdentifier = uuid.unparse(sessionID);

    if (requestType == "start") {
      var sessionInfo = this.pendingSessions[sessionIdentifier];
      if (sessionInfo) {
        var width = 1280;
        var height = 720;
        var fps = 30;
        var bitrate = 300;

        let videoInfo = request["video"];
        if (videoInfo) {
          width = videoInfo["width"];
          height = videoInfo["height"];

          let expectedFPS = videoInfo["fps"];
          if (expectedFPS < fps) {
            fps = expectedFPS;
          }

          bitrate = videoInfo["max_bit_rate"];
        }

        let targetAddress = sessionInfo["address"];
        let targetVideoPort = sessionInfo["video_port"];
        let videoKey = sessionInfo["video_srtp"];

        let ffmpegCommand = this.ffmpegSource + ' -threads 0 -vcodec h264_omx -an -pix_fmt yuv420p -r '+ fps +' -f rawvideo -tune zerolatency -vf scale='+ width +':'+ height +' -b:v '+ bitrate +'k -bufsize '+ bitrate +'k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params '+videoKey.toString('base64')+' srtp://'+targetAddress+':'+targetVideoPort+'?rtcpport='+targetVideoPort+'&localrtcpport='+targetVideoPort+'&pkt_size=1378';
        console.log(ffmpegCommand);
        let ffmpeg = spawn('ffmpeg', ffmpegCommand.split(' '), {env: process.env});
        this.ongoingSessions[sessionIdentifier] = ffmpeg;
      }

      delete this.pendingSessions[sessionIdentifier];
    } else if (requestType == "stop") {
      var ffmpegProcess = this.ongoingSessions[sessionIdentifier];
      if (ffmpegProcess) {
        ffmpegProcess.kill('SIGKILL');
      }

      delete this.ongoingSessions[sessionIdentifier];
    }
  }
}

FFMPEG.prototype.createCameraControlService = function() {
  var controlService = new Service.CameraControl();

  this.services.push(controlService);
}

// Private

FFMPEG.prototype._createStreamControllers = function(maxStreams, options) {
  let self = this;

  for (var i = 0; i < maxStreams; i++) {
    var streamController = new StreamController(i, options, self);

    self.services.push(streamController.service);
    self.streamControllers.push(streamController);
  }
}
`

**Comment by htschmed** [comment]
Hey sorry for the confusion with my earlier post.  At the time I was referring to this revision of ffmpeg.js which appears to have changed quite substantially since then:

https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/23d7bbcc0a0f14f7f50119595c0f2d10f5d7d877/ffmpeg.js

My only issue with this plugin, at least for my camera dvr setup, is that the mapping parameters " -map 0:0 " simply will not work at all for me, console keeps reporting bad payloads and incomplete frames when the home app is processing the video.  The parameters I'm specifying are not including audio, subtitles, and data streams and just doing automatic stream selection (see https://ffmpeg.org/ffmpeg.html#toc-Stream-selection).   I will probably end up just keeping my own separate repo somewhere for this, plugin works well for me other than the muxing issues I'm having with the ffmpeg mapping parameters. Thanks for the help everyone, wouldn't have been able to troubleshoot the issue without people posting to these issue lists.
