### ISSUE TITLE
Bad Streaming Quality

### ISSUE THREAD

**Issue by ghost** [KhaosT/homebridge-camera-ffmpeg#79]
Hello,

I connect a USB Camera to my Raspberry Pi3 and create a stream with "motioneye"! When I directly view the stream, the quality is perfect. When I use any available "homebridge camera plugin" I get a bad video quality in the Home App of my Apple device. Is there any setting to get a better quality?

**Comment by HomePI3** [comment]
When I add the "-rtsp_transport tcp" in the "source" line of the Config.json my live stream won't start. I only see every few minutes a actual picture of my video (but in perfekt quality).
