### ISSUE TITLE
Homebridge not working with camera enabled

### ISSUE THREAD

**Issue by augustozanellato** [KhaosT/homebridge-camera-ffmpeg#8]
When I add a webcam to the file config.json I get this when i start homebridge
`*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] Loaded plugin: homebridge-camera-ffmpeg
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] ---
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] Loaded plugin: homebridge-gpio-wpi
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] Registering accessory 'homebridge-gpio-wpi.GPIO'
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] ---
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] Loaded plugin: homebridge-people
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] Registering accessory 'homebridge-people.people'
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] ---
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] Loaded plugin: homebridge-pi
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] Registering accessory 'homebridge-pi.PiTemperature'
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] ---
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] Loaded config.json with 4 accessories and 0 platforms.
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] ---
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] Loading 4 accessories...
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] [GPIO23] Initializing GPIO accessory...
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] [Temperatura Raspberry Pi] Initializing PiTemperature accessory...
[Sun Oct 02 2016 14:28:51 GMT+0200 (CEST)] [Temperatura Raspberry Pi] Model BCM2709/a02082 Serial 000000003d014e6a
/usr/local/lib/node_modules/homebridge/lib/api.js:46
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:46:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:251:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:78:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)`

My config.json file:
`{
  "bridge": {
       "name": "Homebridge",
       "username": "CA:21:3F:E2:DE:24",
       "port": 51826,
       "pin": "031-45-154"
    },
  "accessories": [
    {
      "accessory": "GPIO",
      "name": "GPIO23",
      "pin": 23
    },
    {
      "accessory": "PiTemperature",
      "name": "Raspberry Pi Temperature"
    },
    {
      "platform": "Camera-ffmpeg",
      "cameras": [
        {
          "name": "Camera1",
          "videoConfig": {
          "source": "-re -i rtsp://192.168.1.21:555/webcam0.sdp",
          "maxStreams": 1,
          "maxWidth": 640,
          "maxHeight": 480,
          "maxFPS": 10
          }
        }
      ]
    },
    {
    "accessory" : "people",
    "name" : "People",
    "people" : [
      { "name" : "My PC", "target" : "192.168.1.5" },
      { "name" : "WiFi Extender", "target" : "192.168.1.2" }
    ],
    "threshold" : 15
  }
  ]
}`

**Comment by cruse123** [comment]
Having the same comment.
Maybe have something to do with versions of nodejs and npm.
When installing the plug it says "WARN engine homebridge-camera-ffmpeg@0.0.2: wanted: {"node":">=5.0.0","homebridge":">=0.4.5"} (current: {"node":"4.2.6","npm":"3.5.2"})"

I tried to upgrade node.js via npm, but after that homebridge itself wouldn't work either.
