### ISSUE TITLE
username error

### ISSUE THREAD

**Issue by AdySan** [KhaosT/homebridge-camera-ffmpeg#82]
Hello, firs time homebridge user, so forgive me if I'm missing something.

I'm using @legotheboss's omx fork. I get this error:

```
pi@AdyPi3:~ $ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[5/14/2017, 10:48:39 AM] Loaded plugin: homebridge-camera-ffmpeg-omx
[5/14/2017, 10:48:39 AM] Registering platform 'homebridge-camera-ffmpeg-omx.Camera-ffmpeg-omx'
[5/14/2017, 10:48:39 AM] ---
/usr/lib/node_modules/homebridge/lib/server.js:202
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:202:31)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

Here's my config.json

```

{
        "name": "Kitchen",
        "videoConfig": {
                "source": "-rtsp_transport http -re -i rtsp://192.168.1.190:554/s0",
                "maxStreams": 2,
                "maxWidth": 1270,
                "maxHeight": 720,
                "maxFPS": 15
        }
}

```

**Comment by legotheboss** [comment]
Looks like the error has to do with the main configuration of Homebridge. Can you post your homebridge config?

**Comment by AdySan** [comment]
Looking at another [issue](https://github.com/nfarina/homebridge/issues/1189), i added this to the beginning of my config.json,
```
{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
```

Is something like this required?

**Comment by AdySan** [comment]
So are there two config.json filed? one for homebridge and one for the plugin? Also, how do i do the second step here,
```
5. Run Homebridge

6. Add extra camera accessories in Home app. The setup code is the same as homebridge.

```

**Comment by legotheboss** [comment]
@AdySan Nope, you just need one homebridge config. You needed to add the specific part to the beginning of your config.json. After that, add the rest of the camera configuration. This should solve the homebridge error you keep getting.

**Comment by AdySan** [comment]
Yep, sorry didn't realize how homebridge works. Now I got it working. Although, the stream from my ubiquiti micro cam is very choppy. Will try lower resolutions.

**Comment by AdySan** [comment]
@legotheboss BTW, should i get the same performance if I use your fork for RPi3 or enable `"vcodec": "h264_omx" ` on the main repo?

**Comment by legotheboss** [comment]
@AdySan I don't think it will make a difference at all... You should expect to see the same performance between both repos if you enable H264_omx. Regarding your choppy video, is your Pi using ethernet as the primary network connection?

**Comment by AdySan** [comment]
Yes it's using only Ethernet. It streams better if I stream from camera directly with something like VLC player on a Mac or iOS device. Anyway to tell if this is the RPi3 not keeping up?

**Comment by legotheboss** [comment]
@AdySan try running top to see usage. The pi tends to create some lag due to the encryption requirements HomeKit enforces on video streams. Try increasing the video RAM split to see if that makes the stream smoother.

**Comment by AdySan** [comment]
So ffmpeg seems to idle at around 130%. Is this expected?

` 6016 pi        20   0  198948  44700   8648 R 130.6  4.7   0:51.82 ffmpeg`

Also, unrelated, but in there anything like `forever` for running homebridge? Perhaps `screen`?

**Comment by NorthernMan54** [comment]
@AdySan On my RPI 2, it sits at about 90% cpu when running the OMX enabled version of ffmpeg.   And to run homebridge on startup, take a look at the homebridge wiki, and this section.

https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd
