### ISSUE TITLE
WiFi Live-Stream don`t work, remote Live-Stream work?

### ISSUE THREAD

**Issue by FaceMan4** [KhaosT/homebridge-camera-ffmpeg#88]
Hi, i have a funky problem. Installed on RPI 3. Try with omx and without.

Ipad as Homekit Hub -> Remote Stream (4G / LTE...) to Iphone worked
Iphone in the local WiFi -> Live Stream don`t worked. Snapshots just works fine?

I reinstalled the complete Raspberry twice, but it won`t worked for me, alway the same problem with the WLAN stream? 

I don`t know where to start to solve the problem :(
Can you help me with any ideas? 

Thanks!

**Comment by adrianosantos** [comment]
I'm having the same problem. Installed on RPI 2.

Remote stream is working very slow, the delay is almost 5 s.
I couldn't make it work on local WiFi. I keep showing the still image.

Any ideas?

Thanks

**Comment by FaceMan4** [comment]
@adrianosantos 
Are you on IOS 10.3.2 too?

**Comment by adrianosantos** [comment]
Yes, I’m. I just switched my raspberry pi to wired connection instead of wireless and I’m able to see the live video in the home app.
I’m trying to debug why when in the wi-fi in local home doesn’t work. 

Thanks,
Adriano

**Comment by FaceMan4** [comment]
I switched from Raspi LAN connection to wireless Raspi connection (used the build in Raspi 3 WiFi Modul) and Live Stream in Home App worked in the WiFi. But i need to plugin the LAN Cable too when booting was done, otherwise it wont worked :D

I hope you find the problem :)

Thanks.

**Comment by felsmann** [comment]
I am having the same issue but on a Mac 
When my phone's wifi is off and on LTE I can stream but if I'm on Wifi it won't stream, just get "camera not responding"

(I can see ffmpeg starting then stopping after a few seconds)

**Comment by pokono** [comment]
+1
