### ISSUE TITLE
Homebridge detect camera, but "House" app no....

### ISSUE THREAD

**Issue by gparga** [KhaosT/homebridge-camera-ffmpeg#89]
Hi, have a little problem here:
Installed a camera at Homebridge:

[37m[5/24/2017, 7:10:46 PM][39m Main Room is running on port 55658.
stdout
19:10:46
no did or loc found!

But "House" app, no find this accessory, I tried:
Reset Docker (Installed at Synology NAS)
Reset Router
Reset Camera
Reset my brain....

Any trick or help with this?¿

Many, many Thanks!

**Comment by theo-69** [comment]
you have to add the camera via homekit

**Comment by gparga** [comment]
MY HOUSE = HOMEKIT :-)

**Comment by theo-69** [comment]
yep but press the plus like you would like to add a new bridge, you will than see your camera ;-)

**Comment by eggyacid** [comment]
same issue, it's not seeing the camera even after adding the Plus

**Comment by xdenneboom** [comment]
I'm having the same issue. I've tested the RTSP feed via VLC and I get the feed. The raspberry output is saying the camera is running on port x and it is initialized. Once I add homebridge and all plugins from scratch to the iOS Home app, all plugins but the camera are added. I've also tried disabling all other plugins. 

I've also tried playing with the resolution, fps, and other peoples solutions of adding stuff before the -re -i in source. Nothing really changed. 

here's my config
`{
	"bridge": {
		"name": "Homebridge",
		"username": "DE:22:3D:EE:CC:33",
		"port": 51826,
		"pin": "000-11-333"
	},
	"description": "Hoi :)",

	"platforms": [
		{
			"platform": "Camera-ffmpeg",
			"cameras": [{
				"name": "leylacam",
				"videoConfig": {
					"source": "-re -i rtsp://admin:ajax@192.168.178.24:10554/tcp/av0_0",
					"maxStreams": 2,
					"maxWidth": 1024,
					"maxHeight": 1024,
					"maxFPS": 25
				}
			}]
		}
	]
}`
