### ISSUE TITLE
big delay in stream

### ISSUE THREAD

**Issue by theo-69** [KhaosT/homebridge-camera-ffmpeg#92]
Hi my stream real slow and with a big delay (30sec) anything I can do?

**Comment by NorthernMan54** [comment]
Have you looked at the wiki for someone with a similar setup to yours?

**Comment by theo-69** [comment]
yes used the same (Xiaomi Fang) and if i compare the rtsp and its 20 sec behind and stops a lot.

**Comment by NorthernMan54** [comment]
Where are you running homebridge?  Raspberry pi?   If you it isn't fast enough, with using a special version of ffmpeg, that supports hardware acceleration.  Search on google for the omx version of ffmpeg complied for your rpi
