### ISSUE TITLE
Live stream 

### ISSUE THREAD

**Issue by fabvis** [KhaosT/homebridge-camera-ffmpeg#93]
hi

i have a homebridge fresh install on raspberry pi3.
everything work fine, except live streaming in home.app.

stillImage is ok in home.app, refresh every 10 sec.
live feed is ok in browser, no delay, good quality.
but this live feed won't load in home.app, and i don't know why !!!
(no error in homebridge journal)

any idea ?

my ffmpeg command

`ffserver -f /etc/ffserver.conf & ffmpeg -r 10 -s 1280x720 -f video4linux2 -i /dev/video0 http://localhost:8090/feed1.ffm
`

my ffmpegserver config

`#RTSPPort 5554
RtspPort 5554
HttpPort 8090
HttpBindAddress 0.0.0.0
MaxClients 10
MaxBandwidth 10000000
NoDaemon
<Feed feed1.ffm>
File /tmp/feed1.ffm
FileMaxSize 800M
</Feed>
<Stream test.mjpg>
Feed feed1.ffm
Format mpjpeg
VideoFrameRate 10
VideoSize 1280x720
VideoQMin 1
VideoQMax 2
VideoBitRate 400000
NoAudio
Strict -1
</Stream>
`

and my homebridge-camera-ffmpeg config

` "platform": "Camera-ffmpeg",
                "name": "Webcam",
                "cameras": [{
                        "name": "WebcamChambre",
                        "videoConfig": {
                        "source": "-re -i http://picam3.local:8090/test.mjpg",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "vcodec": "h264_omx"
                        }
                }]`

**Comment by noaht8um** [comment]
I'm having the exact same issue with my setup.

I used homebridge on my RPi and it wouldn't work, but I could get it working on my macOS homebridge installation.

Anyone else have any ideas? I'd like to run the stream and homebridge all on the RPi.

**Comment by fabvis** [comment]
Try to add your homebridge user to video group

**Comment by noaht8um** [comment]
@fabvis Do you mean the linux group "video."

I'll give that a shot, but it might be irrelevant in my case because I'm using the RPi Camera (the ribbon one)

**Comment by fabvis** [comment]
I use the pi camera too.
When you install Homebridge, if you want to launch it at boot, you must create an homebridge user, and this user don't have access to linux group "video"

**Comment by noaht8um** [comment]
Right now, I haven't set up any launch scripts–I wanted to get the configuration working first–so I'm just using the "pi" user which is in the "video" group.

**Comment by fabvis** [comment]
Ok.
Can i see your ffmpeg part in config.json ?

**Comment by noaht8um** [comment]
Sure thing

/etc/ffserver.conf

```
HTTPPort 8090
HttpBindAddress 0.0.0.0
MaxClients 10
MaxBandwidth 1000000

<Feed feed1.ffm>
File /tmp/feed1.ffm
FileMaxSize 10M
</Feed>

<Stream test.mjpg>
Feed feed1.ffm
#Format mpjpeg
Format h264
VideoSize 1280x720
VideoFrameRate 30
VideoBitRate 400000
VideoQMin 1
VideoQMax 2
NoAudio
Strict -1
</Stream>
```

**Comment by noaht8um** [comment]
And this is the script I run to get the video streaming to ffserver:

`raspivid -t 0 -w 1280 -h 720 -fps 30 -o - | ffmpeg -i - http://localhost:8090/feed1.ffm`

**Comment by fabvis** [comment]
try this in homebridge config.json  

`"source": "-re -r 6 -s 1920x1080 -f video4linux2 -i /dev/video0",`

**Comment by fabvis** [comment]
Install the video for Linux 2 driver with "sudo modprobe bcm2835-v4l2". After this, you should have a device called /dev/video0. Add the line "bcm2835-v4l2" with "sudo nano /etc/modules". This makes sure the driver is loaded when you reboot.

**Comment by noaht8um** [comment]
Ah, you have the v4l2 driver which gives you the /dev/video0. I don't have that. Instead, I'm piping raspivid into ffmpeg for streaming.

I can try to get that setup, but I wanted to do it this way because I compiled ffmpeg with omx support.

**Comment by noaht8um** [comment]
Whoops, you just said that haha.

I'll give it a shot.

**Comment by fabvis** [comment]
for me is the best way i've found for quality & low delay

**Comment by fabvis** [comment]
delay = -0.5 sec

**Comment by noaht8um** [comment]
So I tried adding that to my config, and it's still not working. I deleted the raspberry pi camera device and the bridge and re-added it, but no luck.

Here's my entire (sanitized) config

```
{
	"bridge": {
		"name": "Camera Bridge",
		"username": "XX:XX:XX:XX:XX:XX",
		"port": 51826,
		"pin": "XXX-XX-XXX"
	},

	"platforms": [{
		"platform": "Camera-ffmpeg",
		"cameras": [{
			"name": "raspicam",
			"videoConfig": {
				"source": "-re -r 6 -s 1920x1080 -f video4linux2 -i /dev/video0",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 720,
				"maxFPS": 30,
				"vcodec": "h264_omx"
			}
		}]
	}]
}
```

I tried it with and without the "vcodec": "h264_omx" line, but it didn't seem to make a difference.

When I clicked the stream in the Home app, I saw activity in the homebridge console, but it just kept spinning.

**Comment by fabvis** [comment]
tested now with a new rpi3 & pi cam v2

• update & upgrade your pi 
• install node 7,  avahi&co, and homebridge (see homebridge wiki)
• configure homebridge for start on boot with systemd (see wiki)

• install ffmpeg 
```
a. Download this package: sudo wget goo.gl/gMGA81 -O ffmpeg.deb
b. Install this package: sudo dpkg -i ffmpeg.deb
```
(much faster as other method)

• add your homebridge user to video group
`sudo usermod -aG video _youruser_`
homebridge user are created when you configure start on boot with systemd

• Install the video for Linux 2 driver with "sudo modprobe bcm2835-v4l2". After this, you should have a device called /dev/video0. Add the line "bcm2835-v4l2" with "sudo nano /etc/modules". This makes sure the driver is loaded when you reboot.

• edit your config.json
```
"source": "-re -r 6 -s 1920x1080 -f video4linux2 -i /dev/video0",
"stillImageSource": "-s 1920x1080 -f video4linux2 -i /dev/video0",
```

• reboot pi, and add your accessorie to home.app 

for me, still image & live stream are ok, no delay & good quality 

good luck

**Comment by ooii** [comment]
Hi,

I have 4 cameras and I'm not able to have video stream from any of them, only still images.
One of them is the K002 we can see [here](https://www.ispyconnect.com/man.aspx?n=keekoon). 
Using this url `http://192.168.1.147/videostream.asf?user=[user]&pwd=[pass]&resolution=1280x720` or this one `rtsp://192.168.1.147/rtsp_live0` in either `VLC` or `mplayer` works fine but not in `homebridge`.
Since my `homebridge` is running on an `HP N54L microserver` under `ubuntu`, I can do all what you have said before but is it really mandatory to do it with a `ffserver` etc?
Thanks guys.

**Comment by swdabing** [comment]
Segmentation fault
ffmpeg error ，how to solve

**Comment by CMaxim77** [comment]
I have a Kuna brand exterior light that has a camera built in, would this work for that device or is there another setup that I can do? Thanks in advance!
