### ISSUE TITLE
Multiple Cams not working

### ISSUE THREAD

**Issue by derkopp** [KhaosT/homebridge-camera-ffmpeg#94]
Hi,
I am trying to use multiple cams:
{
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "Terrasse",
      "videoConfig": {
        "source": "-re -rtsp_transport tcp -i rtsp://192.168.2.105:554/onvif2",
        "stillImageSource": "-i http://192.168.2.206/test.php?id=2",
        "maxStreams": 1,
        "maxWidth": 320,
        "maxHeight": 180,
        "maxFPS": 15
      }
    },{
      "name": "Weg zum Haus",
      "videoConfig": {
        "source": "-re -rtsp_transport tcp -i rtsp://192.168.2.102:554/onvif2",
        "stillImageSource": "-i http://192.168.2.206/test.php?id=1",
        "maxStreams": 1,
        "maxWidth": 320,
        "maxHeight": 180,
        "maxFPS": 15
      }
    }
  ]
}

but unfortunately, only one camera shows up in Home app.

Homebridge identifies two cams at startup (based on the port information), but with the same name:

[2017-06-17 13:47:03] Initializing Camera-ffmpeg platform...
[2017-06-17 13:47:04] Weg zum Haus is running on port 38133.
[2017-06-17 13:47:04] Weg zum Haus is running on port 40937.

**Comment by theo-69** [comment]
hi @derkopp  did you find a solution?

**Comment by DMBlakeley** [comment]
I have experienced the same problem with 2 Belkin NetcamHD cameras.  One streams just fine and is the same camera that is assigned to 2 different ports.  The second camera does not receive a port assignment.

**Comment by sjthespian** [comment]
As a workaround, I have found that if I add the cameras one at a time then add them to the Home app in IOS they work. However, they still all show up in the logs with whatever the last name is in the config file.
