### ISSUE TITLE
not seeing device in Add Accessory

### ISSUE THREAD

**Issue by eggyacid** [KhaosT/homebridge-camera-ffmpeg#95]
I have homebridge running and working.
i've downloaded and installed ffmpeg but it does not show additional device when i go in to add accessory.  After searching online, its suppose to show me the device to add but that doesn't show.

any ideas?  i have ffmpeg installed and running on Pi3

**Comment by Anuj79** [comment]
try deleting the files from persist folder.. that worked for me.

**Comment by xdenneboom** [comment]
hi, I also have this same problem. I just deleted everything in the persist folder, didn't seem to help. Any other plugin I disable / enable does seem to affect what I get back in the Home app. In terminal, I do see the camera plugin being initialised and running on a port.

**Comment by leroyrichjr** [comment]
I had to reboot my phone before it would show up in the Add Accessory screen, but it's happened more than once and that fixes it each time.
