### ISSUE TITLE
camera-ffmpeg-omx

### ISSUE THREAD

**Issue by alexsalex** [KhaosT/homebridge-camera-ffmpeg#96]
I use RPi0w... So, Raspbian. In raspbian backports right now is available ffmpeg:
`ffmpeg/jessie-backports 7:3.2.5-1~bpo8+1 armhf [upgradable from: 3.1.4-1]`
So, it not working with 3.2.5... How to make it works with this ver?

**Comment by iJaffa** [comment]
The omx compatible version which @legotheboss compiled works for me:

https://github.com/legotheboss/YouTube-files/raw/master/ffmpeg_3.1.4-1_armhf.deb

_Install via_
```
wget https://github.com/legotheboss/YouTube-files/raw/master/ffmpeg_3.1.4-1_armhf.deb
sudo dpkg -i ffmpeg_3.1.4-1_armhf.deb
```

I haven't come across a newer compiled version which has the omx plugin already installed, and I don't want to waste half an hour compiling it myself.

**Comment by alexsalex** [comment]
I'm not sure what you understand me. This topic about ffmpeg 3.2.5 from Debian backports. 3.1.4 works for me too.

**Comment by iJaffa** [comment]
ffmpeg 3.2.5 in Debian backports doesn't contain the omx plugin so it won't work with hardware encoding/deciding on the Raspberry Pi.

If you want this version, you'll need to build it from source yourself, but there are no new features you'd benefit from on the Raspberry Pi so I wouldn't bother.

**Comment by moritzmhmk** [comment]
you can use the [capabilities of the v4l2 driver](https://gist.github.com/moritzmhmk/48e5ed9c4baa5557422f16983900ca95) instead of `h264_omx`
