### ISSUE TITLE
stream problem  , need help

### ISSUE THREAD

**Issue by kendai1019** [KhaosT/homebridge-camera-ffmpeg#98]
HI Sirs,

	I got problem need help , my camera is XiaoYi camera(already hacked , enable RTSP) 
	
	I use Iphone & Android device ( VLC APP) RTSP streaming work ok ,
	
	when i use homebridge(Apple Home kit ) , I can see the camera in my Home APP 
	
	but streaming is not work , when i click the camera in Home App , it show 
	
	live steaming( but only one sec , then screen be stuck ) , i back to Home App index page ,
	
	and repect click the camera , it show live steaming( but only one sec , then screen be stuck )
	
	i use raspberry pi 3 , use this plugn ffmepg(sudo wget goo.gl/gMGA81 -O ffmpeg.deb)  , 
	
	somebody help me , sorry my english is bad > <

	below is my config , other queson ,  "stillImageSource" << How do I set it up at my camera ?
	
	thanks for your read.
{
"platform": "Camera-ffmpeg-omx",
"cameras": [
{
"name": "Camera Name",
"videoConfig": {
"source": "-re -i rtsp://192.168.0.124:554/ch0_0.h264",
"stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
"maxStreams": 2,
"maxWidth": 1280,
"maxHeight": 720,
"maxFPS": 30
}
}
]
}

**Comment by maragelis** [comment]
you will need to bring down the width height to 640x480,

**Comment by kendai1019** [comment]
Thx, but still have some problems!

**Comment by maragelis** [comment]
I have also changed the camera stream settings to 640*480. you will have to use ssh and tenet into the camera. If you are using fang-hack there is documentation on how to do this. This makes using the camera acceptable in homekit

**Comment by StefanMeGit** [comment]
#112 

got here the same problem! 

U mean it should be work when i go down with the source resolution?

**Comment by deanlyoung** [comment]
@maragelis can you link to the documentation?

**Comment by StefanMeGit** [comment]
@deanlyoung http://bobbyromeo.com/technology/xiaomi-smart-1080p-wifi-ip-camera-rtsp-streaming-hack/#resolution

I tried so many things now... the ONLY solution who worked for me is:

```
Homebridge config.json:
  "platform": "Camera-ffmpeg-omx",
  "cameras": [
    {
      "name": "Camera Name",
      "videoConfig": {
        "source": "-rtsp_transport http -re -i rtsp://192.168.1.161/unicast",
        "stillImageSource": "-i rtsp://192.168.1.161/unicast -vframes 1 -r 1",
        "maxStreams": 2,
        "maxWidth": 1280,
        "maxHeight": 720,
        "maxFPS":10
      }
    }
  ]
}
```

Camera settings 20-rtsp-server:

```
start()
{
  LOG=/dev/null
  echo "Starting RTSP server..."
  snx_rtsp_server -W 1280 -H 720 -Q 10 -F 10 -a >$LOG 2>&1 &
  echo "$!" > "$PIDFILE"
}
```

Even if i change ANYTHING here it doesnt work proper! Specialy if i add -b 2048 or 4096 or... stream doesnt work anymore. Has anyone an idea?

**Comment by niccolospa** [comment]
I'm having the exact same issue, someone sorted this out?

**Comment by iCarl** [comment]
@StefanMeGit I've been trying editing 20-rtsp-server in VI over ssh, is there another way to edit the file?
It says NOK as soon as I try to enable RTSP again.
