### ISSUE TITLE
How to set a camera using H.265 encoding.

### ISSUE THREAD

**Issue by olliwang** [KhaosT/homebridge-camera-ffmpeg#99]
Hi, I was trying to display a Hikvision camera with H.265 encoding.

I've installed `ffmpeg` by `homebrew` as follow:

    brew install ffmpeg --with-x265

And here's my configuration.

    "platforms": [
      {
        "platform": "Camera-ffmpeg",
        "cameras": [
          {
            "name": "Gate Camera",
            "videoConfig": {
              "source": "-re -i  rtsp://admin:password@192.168.1.2:554/Streaming/Channels/1",
              "maxStreams": 2,
              "maxWidth": 2560,
              "maxHeight": 1440,
              "maxFPS": 25,
              "vcodec": "libx265"
            }
          }
        ]
      }
    ]

Any idea? Thanks.

PS. The VLC media player can play the rtsp link correctly without any lag.

**Comment by aesterling** [comment]
@olliwang did you have any success with this? I would like to do the same. Thanks!

**Comment by KhaosT** [comment]
the `vcodec` still needs to be x264. That's for transcoding, not input format.
